### ISSUE TITLE
Adding resources for Jenkins in Devops

### ISSUE THREAD

**Issue by ARCHITABHATTAD** [EbookFoundation/free-programming-books#10031]
@eshellman can you assign me this issue under hacktoberfest 2023

**Comment by sohansai** [comment]
If you're familiar with Git, please feel free to submit a PR.

If not, provide details about the book, including its name, author, and a link to it.

Note that issues can't be assigned, but if you're ready, you can start contributing right away.

Also, make sure to read CONTRIBUTING.md before contributing.

**Comment by ngv-sama** [comment]
Hi! I am new to open source. Can someone please help me with what the issue is?
Thanks!

**Comment by AbdulSami455** [comment]
Assign this to me as I'm interested in DevOps and have knowledge of jenkins.
