### ISSUE TITLE
Redirecting to a non existing playlist

### ISSUE THREAD

**Issue by VerasNp** [EbookFoundation/free-programming-books#10067]
https://github.com/EbookFoundation/free-programming-books/blob/f87ef69f0c356f25ec6f9c6ebc64d7a3b678d341/courses/free-courses-pt_BR.md?plain=1#L116C21-L116C93

**Comment by ngv-sama** [comment]
Hi! I'm new to open source. Can you please explain what the issue is?
Thanks!

**Comment by rivailruiz** [comment]
Este curso não está em português.

**Comment by VerasNp** [comment]
Atualmente o link que se encontra no repo leva para uma playlist quebrada, a issue no caso era pra reaver novamente o link para o curso correto
