### ISSUE TITLE
Add Urdu Language in the list

### ISSUE THREAD

**Issue by AbdulRehmanGHub** [EbookFoundation/free-programming-books#10268]
As we all know that, Urdu is a famous and widely used language world wide. Please add the category of Urdu language as well in the Book, Courses, Interactive sessions and podcast etc. We will happy to contribute and share Urdu rescources. Thanks

**Comment by eshellman** [comment]
We currently have 15 resources listed as "hindi/urdu" in the Hindi list. The first step in adding a list for Urdu is to determine if these resources are more Urdu than Hindi, and move them into a new list. The ISO language code for Urdu is `ur`.

**Comment by sujal0320** [comment]
If no one else is working on this issue, I can take it

**Comment by eshellman** [comment]
completed
