### ISSUE TITLE
Css changes

### ISSUE THREAD

**Issue by saurabhprasadsah** [EbookFoundation/free-programming-books#10277]
What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

For resources
Description
Css

Why is this valuable (or not)?
Yes

How do we know it's really free?
Yes

For book lists, is it a book? For course lists, is it a course? etc.
Checklist:
 Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
 [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
 Include author(s) and platform where appropriate.
 Put lists in alphabetical order, correct spacing.
 Add needed indications (PDF, access notes, under construction).
 Used an informative name for this pull request.
Follow-up
Check the status of GitHub Actions and resolve any reported warnings!

**Comment by Rudy-Menekam** [comment]
Can i work on this issue?

**Comment by sohansai** [comment]
> What does this PR do? Add resource(s) | Remove resource(s) | Add info | Improve repo
> 
> For resources Description Css
> 
> Why is this valuable (or not)? Yes
> 
> How do we know it's really free? Yes
> 
> For book lists, is it a book? For course lists, is it a course? etc. Checklist: Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md). [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates. Include author(s) and platform where appropriate. Put lists in alphabetical order, correct spacing. Add needed indications (PDF, access notes, under construction). Used an informative name for this pull request. Follow-up Check the status of GitHub Actions and resolve any reported warnings!

Please avoid duplicating the pull request template; instead, use it to submit pull requests and open issues separately.

**Comment by sohansai** [comment]
> Can i work on this issue?

This isn't an issue. Feel free to contribute by following the guidelines in docs/CONTRIBUTING.md.

**Comment by saurabhprasadsah** [comment]
okay no issue.
