### ISSUE TITLE
[Add Course] No Such Good resource for KOTLIN Course in Bengali

### ISSUE THREAD

**Issue by subhadipbhowmik** [EbookFoundation/free-programming-books#10299]
### Lack of Quality Bengali Course for KOTLIN

There is no good resource available for learning Kotlin in Bengali. This is a problem because Kotlin is becoming increasingly popular in India and Bangladesh, and there is a growing demand for Android app developers in Bengali.

<img width="944" alt="KOTLIN_issue" src="https://github.com/EbookFoundation/free-programming-books/assets/57017965/6c0a9555-3155-412b-b7fd-e01b03013260">

### Proposed Solution:

I propose to add a new resource for a Kotlin course in Bengali to the list of resources. 

### The course covers the following topics:

1.Introduction to Kotlin
2. Kotlin syntax
3. Kotlin variables and data types
4.Kotlin functions
5. Kotlin object-oriented programming
6.Kotlin collections
7. Kotlin lambdas and higher-order functions
8. Kotlin Android development

The course is suitable for beginners and experienced programmers alike. It is a great way to learn Kotlin and start developing Android apps in Bengali.

### Benefits:

-   This course will make it easier for Bengali speakers to learn Kotlin.
-   This course will encourage more Bengali speakers to develop Android apps.
-   This course will help to grow the Kotlin community in India.

### Call to action:

I urge you to consider adding this new resource to the list of Kotlin resources. Thank you for your time and consideration.

**Comment by sohansai** [comment]
Your suggestion is noted

If you're familiar with Git, feel free to submit a pull request. Ensure it aligns with the CONTRIBUTING.md guidelines

If you're not familiar with Git, please specify the link(s) of the resources you plan to add
