### ISSUE TITLE
Code with Harry DSA whole notes

### ISSUE THREAD

**Issue by Aloneking789** [EbookFoundation/free-programming-books#10392]
Make sure some important points:
1)It's a single pdf
2)The official document available on Code with Harry website is incomplete
3)Just don't upload incomplete pdf available on any 3rd party website
4)You need merge all the pdf available after the videos
5)Also merge required data from Code with Harry site written by him which is only available online.

**Comment by Aloneking789** [comment]
![Screenshot_20231016-212312](https://github.com/EbookFoundation/free-programming-books/assets/116704975/452a5926-e439-432e-9b7b-40799261d5be)
Look at this image make sure that your pdf contain this . This is available after each video in the playlist .you need to upload this too either in form of img(clear images) or something else it's up to you

**Comment by aanyasinghdhaka** [comment]
I can work on this issue can u assign it to me i am new to open source

**Comment by sujal0320** [comment]
Has this issue already been assigned?
I can work on it

**Comment by smirti-barnwal** [comment]
Is this issue not assigned to anyone? 
I want to work on it

**Comment by Aloneking789** [comment]
Just make a valid pr for your request

**Comment by Aloneking789** [comment]
Just make a valid pr for your request
