### ISSUE TITLE
Required-new-Index-and-course

### ISSUE THREAD

**Issue by Ashu104** [EbookFoundation/free-programming-books#10519]
there isn't any index and course of Data Science for Hindi language. 

https://github.com/EbookFoundation/free-programming-books/blob/1144992db61655b6565ac17574e541d0871619b4/courses/free-courses-hi.md?plain=1#L22

**Comment by Ashu104** [comment]
hey @eshellman
this is a legit issue for  [free-programming-books/courses/free-courses-hi.md](https://github.com/EbookFoundation/free-programming-books/blob/1144992db61655b6565ac17574e541d0871619b4/courses/free-courses-hi.md) 
if so does for you. 
could I submit a pr for same?

**Comment by Ajay-singh1** [comment]
@Ashu104 Go for it.

**Comment by Ashu104** [comment]
> @Ashu104 Go for it.

sure, but let once confirm official.  i mean they actually want it or not!

**Comment by Ashu104** [comment]
@eshellman thanks for merging this pr.
