### ISSUE TITLE
Wrong alphabetical order in free-programming-books-bn.md

### ISSUE THREAD

**Issue by kn1-gh7** [EbookFoundation/free-programming-books#10557]
There is a wrong alphabetical order in free-programming-books-bn.md due to which linter test of PR #10556 is failing.

**Comment by honey-speaks-tech** [comment]
Yeah, this blocks PR [#10512](https://github.com/EbookFoundation/free-programming-books/pull/10512).
Probably many other PRs; seems like a show-stopper issue now.

Can someone help fixing this issue in high priority?

**Comment by kn1-gh7** [comment]
> Yeah, this blocks PR [#10512](https://github.com/EbookFoundation/free-programming-books/pull/10512). Probably many other PRs; seems like a show-stopper issue now.
> 
> Can someone help fixing this issue in high priority?

PR #10588 fixes this. It has been approved and is waiting for approval.

**Comment by eshellman** [comment]
I have merged #10558, and fixed the bangla list, which is now being linted. The build should be fixed.
