### ISSUE TITLE
DSA Guide Book

### ISSUE THREAD

**Issue by priyanka-deshmukh8** [EbookFoundation/free-programming-books#10584]
Practice Questions 🎯
Covered Concepts 💯
Videos and Notes ✅
Solutions 🔥
and much more...

**Comment by TJ7-droid** [comment]
I don't see any reference to page, which you have raised this Issue?

Can you elaborate on the same?

**Comment by priyanka-deshmukh8** [comment]
I have a DSA Guide book .can I upload that?

**Comment by sohansai** [comment]
You can upload the book if it follows the guidelines.

If you're familiar with Git, please submit a PR. If you're not familiar with Git, provide the links you're specifying, and make sure to read docs/CONTRIBUTING.md before contributing.
