### ISSUE TITLE
Feature-Request: Need a Button Which Closes/Redirects to main page after Subscribing the mail list

### ISSUE THREAD

**Issue by TJ7-droid** [EbookFoundation/free-programming-books#10589]
**Feature Request: Need a Button Which Closes/Redirects to main page after Subscribing the mail list**

**About Feature**: 

- When a user subscribes for the mail list, by entering input (Email ID, First Name, Last Name) and clicking on Subscribe Button
- He/she will be redirected to page asking for "I'm Not Robot" captcha and subscribe button
- once verification is done, with Successful Message, There is No back/redirection button for (https://ebookfoundation.org/)
- Adding a Back/Redirection Button could enhance the user experience.

**Existing Scenario:**

1. User Inputs the Subscribe Field

<img width="775" alt="image" src="https://github.com/EbookFoundation/free-programming-books/assets/58615108/46571197-59ac-4307-bfe4-fbae9a6b919e">

2. Redirected to Captcha Page

<img width="650" alt="image" src="https://github.com/EbookFoundation/free-programming-books/assets/58615108/6908a70c-3e0b-441d-8090-ea50116649a3">

After Verifying

<img width="650" alt="image" src="https://github.com/EbookFoundation/free-programming-books/assets/58615108/4b19f193-815b-4de6-81a9-0257437782b9">

There Is No Close/ Back to Page Button which  redirects back to  main page.

**Comment by anshul-kh** [comment]
Hi @TJ7-droid  ! I want to work on this issue .  Please assign this issue to me .

**Comment by Anushri-Rawat** [comment]
I can work on this. Please assign this issue to me

**Comment by TJ7-droid** [comment]
Hi @Anushri-Rawat,
I raised issue for feature request, I'm not repo maintainer

**Comment by eshellman** [comment]
sorry we don't have a repo for ebookfoundation.org
