### ISSUE TITLE
Adding aptitude book

### ISSUE THREAD

**Issue by SimranLahrani842** [EbookFoundation/free-programming-books#10650]
Adding link for quantitative book 
Top 100 tips
Which will help to ace the first round during interview process.

**Comment by sohansai** [comment]
To add the link for the quantitative book, if you're familiar with Git, please submit a PR. If you're not familiar with Git, provide the link you're specifying, and ensure you've read docs/CONTRIBUTING.md before contributing.

**Comment by git-create-devben** [comment]
I'll be happy to work on this can you assign me ?

**Comment by sohansai** [comment]
> I'll be happy to work on this can you assign me ?

If you have a link to a resource that should be added to the repo, there's no need to wait to be assigned!
For books make sure it's an authorized distribution.
For courses, make sure it's free and not time-limited.
