### ISSUE TITLE
Adding a Python Book

### ISSUE THREAD

**Issue by AnshMeshram** [EbookFoundation/free-programming-books#10681]
I want to add Learn Python Hard Way is a fully python oriented books for beginner

**Comment by AnshMeshram** [comment]
please assign this to me

**Comment by sohansai** [comment]
If you want to add books to the repo, just check if it's authorized, ensure it's free for courses, and for books, submit a PR if you know Git, or share the link and read docs/CONTRIBUTING.md if you're new. No need to wait for assigned issues; start contributing now!

**Comment by eshellman** [comment]
maybe search the repo?
