### ISSUE TITLE
Adding a new Book

### ISSUE THREAD

**Issue by vandana3869** [EbookFoundation/free-programming-books#10692]
Adding new books 
1.Name : automate-the-boring-stuff-with-python by Al Sweigart
2. Name: WEB SECURITY FOR DEVELOPERS by Malcolm McDonald
3. Name: How Computers really work  by Matthew Justice

All by no starch press

**Comment by vandana3869** [comment]
@aminsaedi  can you please assign me this issue?

**Comment by sohansai** [comment]
If you want to add books to the repo, just check if it's authorized, ensure it's free for courses, and for books, submit a PR if you know Git, or share the link and read docs/CONTRIBUTING.md if you're new. No need to wait for assigned issues; start contributing now!

**Comment by eshellman** [comment]
search the repo first. we got al covered
