### ISSUE TITLE
Outdated links

### ISSUE THREAD

**Issue by prammmoe** [EbookFoundation/free-programming-books#10770]
Hi, i found an outdated link in courses/free-courses-id.md, specifically in 

> [Belajar TypeScript Untuk Pemula](https://www.youtube.com/playlist?list=PL-CtdCApEFH_LJt-fhYfMMgqxirSu6EKo) - Eko Kurniawan Khannedy, Programmer Zaman Now

**Comment by sohansai** [comment]
PR #10774 raised, thanks for reporting

**Comment by sohansai** [comment]
Closing this issue as the pull request is merged and the problem is fixed.
