### ISSUE TITLE
Feature : Bottom to Top button

### ISSUE THREAD

**Issue by VaibhavSharma24** [EbookFoundation/free-programming-books#10815]
I want to add a button which will revert back to the front screen by clicking on it. It will solve the problem of scrolling back to top too much and enhance the user experience.

**Comment by eshellman** [comment]
where is this button?

**Comment by prathameshpowar1910** [comment]
Could you assign this issue to me?

**Comment by VaibhavSharma24** [comment]
@prathameshpowar1910 I opened the issue to work on this but someone made the PR already for it brother !! They don't feel the need to discuss anything before making PR.

**Comment by prathameshpowar1910** [comment]
@VaibhavSharma24 That's all right. But yeah you're right people should discuss and be more collaborative especially while working on an open source project such as this.
