### ISSUE TITLE
I'd love to see more resources on Accessibility!

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#10820]
Here's what we have:

free-programming-books-ja.md:

* [iOS アクセシビリティ プログラミング ガイド](https://developer.apple.com/jp/accessibility/ios) - Apple Developer

free-courses-en.md: 
* [Developing for Web Accessibility](https://www.w3.org/WAI/tips/developing/) - World Wide Web Consortium Web Accessibility Initiative
* [How to Meet Web Content Accessibility Guidelines (Quick Reference)](https://www.w3.org/WAI/WCAG21/quickref/) - W3C Web Accessibility Initiative

free-programming-cheatsheets.md: 
* [Accessibility CheatSheet](https://learn-the-web.algonquindesign.ca/topics/accessibility-cheat-sheet/) - Algonquin Design (HTML)

so, no books, except for one in japanese. 2 courses, only english.

**Comment by meekhasaji** [comment]
Hi @eshellman 
I want to contribute a resource for accessibility.
Please find a PR request with a tutorial for accessibility below.
Link: https://github.com/EbookFoundation/free-programming-books/pull/10875

Thanks 
Meekha
