### ISSUE TITLE
Fix broken links in README

### ISSUE THREAD

**Issue by mekapilgupta** [EbookFoundation/free-programming-books#10919]
The README file contains several links that are currently broken or outdated. This issue is tracking the broken links that need to be fixed or updated.
i checked below url and found many links on this page to be broken.
https://ebookfoundation.github.io/free-programming-books/more/free-programming-cheatsheets.html
Below is a list of all the broken links:

1. 404 Not Found - https://awagga.github.io/dyalog/vocDyalog APL - Vocabulary
2. 404 Not Found - https://www.docker.com/wp-content/uploads/2022/03/docker-cheat-sheet.pdf - Docker Cheat Sheet
3. Not found: The server name or address could not be resolved - https://swissarmydevops.com/containers/docker/docker-cli-cheat-sheet - Docker Cheat Sheet
4. 404 Not Found - https://helmcode.com/blog/docker-cheat-sheet - Docker Cheat Sheet ()
5. Not found: The date in the certificate is invalid or has expired - https://programmingwithmosh.com/wp-content/uploads/2020/09/Git-Cheat-Sheet.pdf - Git Cheat Sheet
6. Not found: The host name in the certificate is invalid or does not match - https://products.golangdojo.com/golang-cheat-sheet-by-golang-dojo - Go Dojo Cheatsheet
7. 404 Not Found - http://datacamp-community-prod.s3.amazonaws.com/21fdc814-3f08-4aa9-90fa-247eedefd655 - Jupyter Notebook Cheat sheet
8. Not found: The server name or address could not be resolved - https://www.vscheatsheet.com/ - VSCheatsheet
9. Not found: The date in the certificate is invalid or has expired - https://programmingwithmosh.com/wp-content/uploads/2019/07/Java-Cheat-Sheet.pdf - Java
10. 403 Forbidden - https://www.simonwenkel.com/publications/cheatsheets/pdf/cheatsheet_pytorch.pdf - PyTorch Framework Cheat Sheet
11. 404 Not Found - https://www.codecademy.com/learn/learn-python-3/modules/learn-python3-syntax/cheatsheet - Python Cheatsheet for beginners
12. Not found: An error occurred in the secure channel support - https://www.ocf.berkeley.edu/~janastas/docs/RStudioCheatSheet.pdf - Cheat Sheet for R and RStudio
13. 404 Not Found - https://www.woolseyworkshop.com/wp-content/uploads/WoolseyWorkshop_Cheatsheet_RaspberryPiBasics_v1.4.pdf - Raspberry Pi Basics cheatsheet

These links should be checked and either updated with working URLs or removed if the content is no longer available. Please go through the list and make the necessary changes.

Some things to try for fixing the links:

    Update the URLs if the content has moved to a new location
    Remove links if the content is no longer available
    Replace 404 links with working archived/cached versions if possible
    Replace broken GitHub raw content links with the repo-relative _relative_ equivalent

If any links cannot be fixed or found, they should be removed from the README. The goal is to have working links so the README content is useful for developers.

Let me know if you have any other questions!

**Comment by JayOaks** [comment]
Hi,
I'd like to work on this, please.

**Comment by Ajay-singh1** [comment]
@JayOaks I have assigned this issue to you.Feel free to Open a PR.

**Comment by JayOaks** [comment]
Thanks.

**Comment by mohdahsanrazakhan** [comment]
@mekapilgupta, I appreciate your effort in finding these broken links.
