### ISSUE TITLE
Free Web Developement course 

### ISSUE THREAD

**Issue by VaibhavSharma24** [EbookFoundation/free-programming-books#10916]
I want to add the resource of free web development course playlist by Thapa Technical it has more than 113,490 views and will be a good resource for someone to start web developement.

**Comment by sohansai** [comment]
You can add the resource if it follows the guidelines.

If you're familiar with Git, please submit a PR. If you're not familiar with Git, provide the links you're specifying, and make sure to read docs/CONTRIBUTING.md before contributing.
