### ISSUE TITLE
Why is Embedded Systems in Programming Language Index And Not Subject Index?

### ISSUE THREAD

**Issue by pegvin** [EbookFoundation/free-programming-books#10995]
Here: https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-langs.md#embedded-systems

Embedded Systems is not a language, it's a Subject/Topic/Field.

**Comment by A-4-Atom** [comment]
Hi, I'd like to fix it. Can you help me a little on how do I start to do that. Do I just fork the repo and make changes to the .md files? Or is there something else that needs to be done along with it?

**Comment by pegvin** [comment]
@A-4-Atom, You First Fork The Repository, Make Changes To The Neccessary Files, And Then On Your Fork's "Main Page" You will be asked to "Open Pull Request".

You Will Be Redirected To A New Page Where you can put necessary details, like What the Pull Request Does Etc.

**Comment by pegvin** [comment]
Closing The PR, Thanks @A-4-Atom.
