### ISSUE TITLE
The MoonMath Manual - zk SNARKS (zero-knowledge proofs)

### ISSUE THREAD

**Issue by LarryRuane** [EbookFoundation/free-programming-books#11039]
https://leastauthority.com/community-matters/moonmath-manual/

(The link is there to free PDF download, 229 pages)

I think this meets the requirements to be included in your list, although you have no ZK-proof category yet. The book does include programming, see Chapter 7.

I could make a PR if you'd like (I use git), but this is a bit far out so I thought I'd wait to see what opinions there might be.

**Comment by eshellman** [comment]
I'd put it in the cryptography section  in subjects
