### ISSUE TITLE
Spanish version? 

### ISSUE THREAD

**Issue by Asmodeusxxx85** [EbookFoundation/free-programming-books#11061]
If don’t exist I can help, because I know the Spanis is complicated

**Comment by eshellman** [comment]
We have spanish lists, is there something missing?

**Comment by 3R1Dev** [comment]
@Asmodeusxxx85 Tenemos las versiones en español bajo "en" en los títulos. En "books", "casts", y "courses" ya están establecidos. Pero puedes agregarles si falta algo.

Si tienes dudas puedes prenguntarme, si es todo voy a cerrar este tema.
