### ISSUE TITLE
Any books about solidity?

### ISSUE THREAD

**Issue by Niko030303** [EbookFoundation/free-programming-books#11069]

**Comment by SethFalco** [comment]
Hey hey!

You can use the search feature on the website or on GitHub to find the kind of books you want:

* https://ebookfoundation.github.io/free-programming-books-search/
* https://github.com/search?q=repo%3AEbookFoundation%2Ffree-programming-books+solidity&type=code

You can find Solidity books at the following:

* [Books in English](https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-langs.md#solidity)
* [Books in Indonesian](https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-id.md#solidity)

If you can identify other resources, you're welcome to share them in a separate issue or pull request and they can be included.
