### ISSUE TITLE
Playlist is not available

### ISSUE THREAD

**Issue by iamtonmoy0** [EbookFoundation/free-programming-books#11089]
[Python for Hackers FULL Course | Bug Bounty & Ethical Hacking](https://www.youtube.com/playlist?list=PLBfoYdk-WAlzfRFHRKAmA7Vw2svoGqfb5) - PhD Security

**Comment by LIGMATV** [comment]
You can add it as videocast on [/casts](https://github.com/EbookFoundation/free-programming-books/tree/main/casts)

**Comment by LIGMATV** [comment]
"The playlist does not exist."

**Comment by iamtonmoy0** [comment]
I have found the full video:
https://www.youtube.com/watch?v=XWuP5Yf5ILI&list=PLk2eI3QfoTTLuKecGzrcE2LrqUuNkRR_M&index=2&t=11s

**Comment by eshellman** [comment]
I think you want https://www.youtube.com/playlist?list=PLtZtNPs3fJyDUJttw2sJVU69IKfqY7XPn
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes
