### ISSUE TITLE
New Course Proposal

### ISSUE THREAD

**Issue by chr1st0scli** [EbookFoundation/free-programming-books#11102]
Hello.

I would like to request for the inclusion of the following course.

https://chr1st0scli.github.io/RainLisp/RainLisp/Docs/quick-start.html

It's a course about RainLisp, a LISP dialect which is very similar to Scheme. So, there might be some value to it about LISP and functional programming techniques in general.

Thank you.

**Comment by eshellman** [comment]
Looks more like a textbook for a course rather than a course by itself. It can be added in the lisp heading in the books list

**Comment by chr1st0scli** [comment]
> Looks more like a textbook for a course rather than a course by itself. It can be added in the lisp heading in the books list

Thank you!

**Comment by dana-66** [comment]
thank u ?
