### ISSUE TITLE
Inclusion of JavaScript Patterns by Lydia Halle and Andy Osmani

### ISSUE THREAD

**Issue by orinamio** [EbookFoundation/free-programming-books#11125]
Hi!

I'd like to add this JavaScript resource to the repo - [Patterns](https://www.patterns.dev/) by Lydia Hallie and Addy Osmani.

What is Patterns?

> Patterns.dev is a free online resource on design, rendering, and performance patterns for building powerful web apps with vanilla JavaScript or modern frameworks.

I personally find the resource useful for to identify solutions to commonly recurring problems in software design. It would be useful to have it in this repository [here](https://github.com/EbookFoundation/free-programming-books/blob/main/more/free-programming-interactive-tutorials-en.md#javascript). 

Let me know what you think [eshellman](https://github.com/eshellman). Thanks!

**Comment by eshellman** [comment]
could be a book if its free
