### ISSUE TITLE
geffp

### ISSUE THREAD

**Issue by Zerocoolocool** [EbookFoundation/free-programming-books#11130]
https://github.com/EbookFoundation/free-programming-books/blob/29ca065a066235583b9753bd7fa16a459d767ae3/casts/free-podcasts-screencasts-en.md?plain=1#L211

**Comment by Zerocoolocool** [comment]
Thanks for the book i will red it and use it thanks so much for anything you and ghithub will and can do for me to do what i do
________________________________

**Comment by CatBia** [comment]
Really cool Podcast! I'll add to my fav.

**Comment by Zerocoolocool** [comment]
Hello how are you?
