### ISSUE TITLE
Evidence-based Software Engineering

### ISSUE THREAD

**Issue by Derek-Jones** [EbookFoundation/free-programming-books#11146]
You need a section covering the engineering aspects of programming; in particular the evidence for the opinions that get bandied about.

A book to get the section started: [Evidence-based Software Engineering](http://knosof.co.uk/ESEUR/)

**Comment by Sevenns07** [comment]
What issue?

**Comment by eshellman** [comment]
That book would be good to add. I would put it in the "Software Architecture" category, which looks like a grab bag at the moment and we could consider splitting out a "software engineering" category.

Please us e this PR to add the book, splitting the section should be a separate category.

**Comment by mashazyu** [comment]
@eshellman 

Hello Eric,

I'd like to work on this issue. Could you please assign it to me?
