### ISSUE TITLE
How to know when something is free on google with pdf's.

### ISSUE THREAD

**Issue by M4ximumPizza** [EbookFoundation/free-programming-books#11220]
Hey,

So I was going to open a PR coming from this [commit](https://github.com/EbookFoundation/free-programming-books/compare/main...M4ximumPizza:free-programming-books:main) and these PDF's you can just find when you search the PDF form of it. Is this technically free or is it pirating the original authors books?  

- M4x

**Comment by eshellman** [comment]
these don't look like authorized distributions

**Comment by M4ximumPizza** [comment]
Alright thanks for you input.
