### ISSUE TITLE
Issue: Missing Favicon on the Website

### ISSUE THREAD

**Issue by nitesh2920** [EbookFoundation/free-programming-books#11337]
I noticed that the [website](https://ebookfoundation.github.io/free-programming-books-search/) currently does not have a favicon. A favicon is a small but important element that adds a more professional and polished look to the site. It also helps users quickly recognize the tab when multiple browser tabs are open.

I would like to suggest adding a favicon to the site.

If you're open to this improvement, I'd be happy to contribute by adding the favicon myself. Please let me know if you'd like me to proceed!

**Comment by eshellman** [comment]
I didn't realize you could do that. Use the EbookFoundation favicon

**Comment by nitesh2920** [comment]
@eshellman assign this to me I want to work on this

**Comment by sarah-abeer** [comment]
please assign me this issue

**Comment by MZ-AD** [comment]
You can assign me this issue

**Comment by aggavni4** [comment]
where is the front-end code for the website?

**Comment by eshellman** [comment]
[ebookfoundation.github.io](http://ebookfoundation.github.io/)

**Comment by Ayushgautam16** [comment]
please assign me this issue

**Comment by azamshaikh1103** [comment]
Hey @eshellman, Since the repo doesn’t have any assets folder or HTML files, what would be the best way to add a favicon? Should I create an assets folder or modify the markdown front matter?

**Comment by eshellman** [comment]
Ajay is trying it in #11603 Collaboration is highly encouraged here!

**Comment by Ajay-singh1** [comment]
@azamshaikh1103 Hey! You can check how to add a favicon from the minimal theme website here https://github.com/pages-themes/minimal.Also go through this PR #11603 maybe we can pair program:)

**Comment by azamshaikh1103** [comment]
> @azamshaikh1103 Hey! You can check how to add a favicon from the minimal theme website here https://github.com/pages-themes/minimal. Also go through this PR #11603 maybe we can pair program:)

Thanks for the response! I'll definitely check out the link and the PR to see how the minimal theme handles favicons. Pair programming sounds awesome—I'd love to collaborate on this! Let me dive into the resources, and I’ll reach out once I have a better understanding.

Looking forward to working together on this!

**Comment by azamshaikh1103** [comment]
![image](https://github.com/user-attachments/assets/82e4e417-dd92-4b72-a794-ab87bb7d1819)

@Ajay-singh1 Hey, I created new file head.html inside _includes folder and linked the favicon.ico
but I'm struggling to run this code locally
can u pls help me run this code locally?

**Comment by Ajay-singh1** [comment]
@azamshaikh1103 To run this locally you need to have jekyll installed on your local system and some gem files then you run the jekyll server and you are good to go.

**Comment by azamshaikh1103** [comment]
#11689 Mistakenly added the _static folder along with the Gemfile.

#11690 Added favicon.ico to the root folder. It's working, but the checks are failing - upload-artifact@v4

**Comment by Ajay-singh1** [comment]
@azamshaikh1103 You need to include and _include folder in the repository and create a file head.html then just link the favicon their.

**Comment by mi6paulino** [comment]
![IMG_9534](https://github.com/user-attachments/assets/0f742407-3753-43bb-8261-5821fe21ee0b)
![IMG_9533](https://github.com/user-attachments/assets/b49ddd13-631a-4fb1-9803-f639213dd47c)
