### ISSUE TITLE
URL change for French LaTeX documentation

### ISSUE THREAD

**Issue by babafou** [EbookFoundation/free-programming-books#11390]
Hi,

The URL used for the French LaTeX documentation Apprends LaTeX [https://tex.loria.fr/general/apprends-latex.pdf](url) is an older version on an unmaintained mirror.  The newest version is [http://www.babafou.eu.org/Apprends_LaTeX/Apprends_LaTeX.pdf](url) and should be used instead.

Thanks.

**Comment by Kiran-pande-30** [comment]
Hello @babafou may i know how to reproduce this issue.

**Comment by babafou** [comment]
There's nothing to reproduce, I'm not talking about a faulty program but a link to update.

**Comment by Abhayksharma75** [comment]
Hello @babafou @eshellman  , updated the link and created a pull request.

**Comment by babafou** [comment]
Abhay Sharma ***@***.***> écrit :
> Hello @babafou @eshellman  , updated the link and created a pull request.

Thanks.

**Comment by babafou** [comment]
Eric Hellman ***@***.***> écrit :
> Closed #11390 as completed.

Thanks.
