### ISSUE TITLE
Add 2 Free Programming Books and 2 Free Online Programming Courses 

### ISSUE THREAD

**Issue by VedasreeM** [EbookFoundation/free-programming-books#11399]
I'd like to suggest adding two free programming books and two free online programming courses to the repository.

1. Book: Eloquent JavaScript (3rd Edition)
Link: https://eloquentjavascript.net/
Description: Eloquent JavaScript is a highly respected book for learning JavaScript, both for beginners and advanced developers. The entire book is available online for free, and it covers topics such as basic programming concepts, control structures, and advanced JavaScript features.
Why it’s free: The book is published online by the author and accessible without any sign-ups or email registration.
2. Book: Python for Everybody (Exploring Data Using Python 3)
Link: https://py4e.com/book
Description: Python for Everybody is a book that introduces the Python programming language with a focus on data handling. It’s a great resource for beginners and includes exercises to practice your skills.
Why it’s free: The book is freely available on the official site of the author and can be accessed without any registration.
3. Course: Harvard's CS50 - Introduction to Computer Science
Link: https://cs50.harvard.edu/x/
Description: This is Harvard University's introduction to the intellectual enterprises of computer science and the art of programming. The course provides a thorough understanding of the basics of programming and computer science principles, accessible for free through edX.
Why it’s free: Harvard offers this course for free on edX, with the option to pay for a certificate if desired.
4. Course: The Odin Project - Full Stack JavaScript
Link: https://www.theodinproject.com/paths/full-stack-javascript
Description: The Odin Project is an open-source, full-stack curriculum that helps learners build strong web development skills, with an emphasis on JavaScript. It includes exercises and projects for hands-on learning.
Why it’s free: The entire curriculum is free, with no sign-up required, and the website encourages an open-source learning experience.

**Comment by eshellman** [comment]
I think we have all these - please check

**Comment by mutant138** [comment]
### Books and Courses

1.**"Dive Into Python 3" by Mark Pilgrim**

This book is a comprehensive guide to Python 3, targeting experienced programmers who want to learn Python quickly. It covers advanced topics like decorators, generators, and more.
[https://freecomputerbooks.com/Dive-Into-Python-3.html](url)

2.**"Programming Principles and Practice Using C++" by Bjarne Stroustrup**

This book is written by the creator of C++. It’s designed for beginners and covers both the fundamentals of programming and the principles of software development.
[https://www.codewithc.com/programming-principles-and-practice-using-c-pdf-bjarne-stroustrup/](url)

3.**edX: CS50’s Introduction to Artificial Intelligence with Python**

This course teaches the foundational concepts of AI, covering topics such as search algorithms, neural networks, and machine learning, using Python.
[https://www.edx.org/learn/artificial-intelligence/harvard-university-cs50-s-introduction-to-artificial-intelligence-with-python?index=product&queryID=0f6f2ad30f4423c1948a7ae635fcbe9f&position=1&linked_from=autocomplete&c=autocomplete](url)

4.**Udacity: Intro to HTML and CSS**

This free course is perfect for beginners looking to learn the basics of web development. It covers HTML and CSS to build stylish and responsive web pages.
[https://www.udacity.com/course/intro-to-html-and-css--ud001](url)

### Bonus :-
**"Namaste JavaScript"** is an excellent resource for anyone looking to deepen their understanding of JavaScript. 

[https://namastedev.com/learn/namaste-javascript](url)

**Comment by yaswika0311** [comment]
Hello!
I would like to contribute by adding two free programming books and two free online programming courses to our resources. Here are my suggestions:

Free Programming Books:
1. "The Art of Computer Programming" by Donald E. Knuth
Link: http://broiler.astrometry.net/~kilian/The_Art_of_Computer_Programming%20-%20Vol%201.pdf
A comprehensive series covering algorithms and programming techniques, is considered a classic in the field.
This greatly helps programmers as it has all the algorithms in one place. This is the link for Vol1, I can gather all other available volumes and add to the resources.

2. "Effective Modern C++" by Scott Meyers
Link: https://www.google.co.in/books/edition/Effective_Modern_C++/ZDhIBQAAQBAJ?hl=en&gbpv=1&kptab=getbook or I also have a google drive link for the pdf and here it is
Drive link: https://drive.google.com/file/d/1QXuMGPpVtW4Oug6tPYhfWrH6HVXbGIXY/view
A practical guide to C++11 and C++14, offering insights and best practices for writing efficient and maintainable code.
This is really a very good book to read.

Free Programming Courses:
1. Great Learning 
Link: https://www.mygreatlearning.com/coding/free-courses
Free coding courses covering popular languages like C, Python, PHP, Java and more. Students can learn the basics of coding, practice with algorithms, and earn certificates.

2. Khan Academy - Computer Programming
Platform: Khan Academy
Link: https://www.khanacademy.org/computing/computer-programming
A series of courses covering JavaScript, HTML/CSS, SQL, and other programming concepts with interactive coding challenges.

**Comment by eshellman** [comment]
@yaswika0311 Please don't recommend books that aren't free.

**Comment by eshellman** [comment]
Closing this issue because our workflow is to propose a pull request first. This forces the contributor to see if we already have the suggested books.
