### ISSUE TITLE
[Bangla] : Broken link 

### ISSUE THREAD

**Issue by sajjadrahman56** [EbookFoundation/free-programming-books#11498]
The link is not working : https://www.sattacademy.com/sql/sql-intro.php
Can I fix this one ?
![image](https://github.com/user-attachments/assets/7a1ca4be-f040-409f-b4e6-621ced5991b6)

**Comment by Malay207** [comment]
I would love to contribute to this issue for Hacktoberfest! Could you please assign it to me?
