### ISSUE TITLE
There are no resources to learn Neovim

### ISSUE THREAD

**Issue by Taussy10** [EbookFoundation/free-programming-books#11569]
As we know that Neovim speed up developer performance but here is no resources to learn Neovim

**Comment by dagenius007** [comment]
@eshellman I have some resource I can add for this. Can I be assigned to this and a push permission.

**Comment by Taussy10** [comment]
> @eshellman I have some resource I can add for this. Can I be assigned to this and a push permission.

Do it man

**Comment by dagenius007** [comment]
I need to access to make a PR.

**Comment by andrmavila2** [comment]
many changes
