### ISSUE TITLE
Missing the Nestjs Course

### ISSUE THREAD

**Issue by hn-agnihotri29** [EbookFoundation/free-programming-books#11630]
I would like to contribute a free course on NestJS to the repository. This course is not currently listed under the JavaScript section, and I believe it will be a valuable addition for those looking to learn NestJS.. I have 2 valuable resources related to Nest.js that will be beneficial for the repository.
 
Before proceeding with the PR, I aim to obtain approval to ensure that this resource fits well within the repository's guidelines.

**Comment by Ajay-singh1** [comment]
Go Ahead Buddy!
