### ISSUE TITLE
The React Tutorial is being redirected to a new website

### ISSUE THREAD

**Issue by YangKuang-Lin** [EbookFoundation/free-programming-books#11656]
I found that the link (https://reactjs.org/tutorial/tutorial.html) for the `React Tutorial` in `free-programming-books-langs.md` is being redirected to the new website (https://react.dev/learn/tutorial-tic-tac-toe).

Sould we use the new link (https://react.dev/learn) and rename the recourse to `Quick Start` or `React Quick Start`?

**Comment by eshellman** [comment]
yes
