### ISSUE TITLE
artifacts v3 deprecation

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#11749]
GitHub
Artifact actions v3 will be deprecated by December 5, 2024. You are receiving this email because you have GitHub Actions workflows using v3 of [actions/upload-artifact](https://app.github.media/e/er?s=88570519&lid=6648&elqTrackId=d2da2b8a2e2546f6bbbefc4362a25248&elq=039a852b648342b691f7685109b30416&elqaid=4245&elqat=1&elqak=8AF5A79567D1D842C6394C4E2A26BD2485A9F822DC0D1EAF1C396EB150F78C3C0ACE) or [actions/download-artifact](https://app.github.media/e/er?s=88570519&lid=6647&elqTrackId=a0c373a95cb941a69247c326aef08dfe&elq=039a852b648342b691f7685109b30416&elqaid=4245&elqat=1&elqak=8AF5A416F3461CA0C91DF8AF94CEC73EC20AF822DC0D1EAF1C396EB150F78C3C0ACE). After this date using v3 of these actions will result in a workflow failure. Artifacts within their retention period will remain accessible from the UI or REST API regardless of the version used to upload.

To raise awareness of the upcoming removal, we will temporarily fail jobs using v3 of actions/upload-artifact or actions/download-artifact. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:

November 14, 12pm - 1pm EST
November 21, 9am - 5pm EST
What you need to do
Update workflows to begin using v4 of the artifact actions as soon as possible. While v4 improves upload and download speeds by up to 98% and includes several new features, there are [key differences](https://app.github.media/e/er?s=88570519&lid=6646&elqTrackId=d75d31293f0e47148c8f2a339957fcaf&elq=039a852b648342b691f7685109b30416&elqaid=4245&elqat=1&elqak=8AF52EF15428B1DCF971E377BBEBF230341AF822DC0D1EAF1C396EB150F78C3C0ACE) from previous versions that may require updates to your workflows. Please see [the documentation](https://app.github.media/e/er?s=88570519&lid=6645&elqTrackId=53ce96ddadbb4fe1951a5a31db6a10b3&elq=039a852b648342b691f7685109b30416&elqaid=4245&elqat=1&elqak=8AF5B7CF2FDD10084FA269DD666DEC9DD40FF822DC0D1EAF1C396EB150F78C3C0ACE) in the project repositories for guidance on how to migrate your workflows.

**Comment by eshellman** [comment]
can we just change the version number?
https://github.com/EbookFoundation/free-programming-books/blob/fa55eb0e61535ae74dd9e1168701b4ba1a519073/.github/workflows/check-urls.yml#L107

**Comment by Thenlie** [comment]
I can test this out this week. We had some issues with v4 but hopefully they are resolved on the most recent version.

**Comment by Thenlie** [comment]
Opened a PR with the fix. This seems to work consistently in my testing. https://github.com/EbookFoundation/free-programming-books/pull/11754
