### ISSUE TITLE
To add Japanese Interactive Programming Resources

### ISSUE THREAD

**Issue by taiyoslime** [EbookFoundation/free-programming-books#1783]
### description

I would  add Japanese interactive-programming-resources.
[http://prog-8.com](http://prog-8.com)

But I don't sure where I add.
Where to add other spoken languages?

**Comment by vhf** [comment]
Hi, thanks!

Unfortunately I don't speak Japanese.

- Is this website completely free?
- Is it really interactive?

**Comment by onebree** [comment]
All that I can tell is that an account is required to access any content.

**Comment by taiyoslime** [comment]
> *Is this website completely free?*

Yes,it's completely free.

Lessons list:
- HTML&CSS ( Beginner / Advanced )
- JavaScript ( Beginner )
- jQuery ( Beginner ) 
- Ruby ( Beginner / Advanced )
- Ruby on Rails ( Beginner / Intermediate / Advanced )
- PHP ( Beginner ) 

> *Is it really interactive?*

Yes.
Here is a capture of the ruby on rails beginner lesson.
It's like a codeacademy.

<img width="1268" alt="ss 2016-01-16 7 11 32" src="https://cloud.githubusercontent.com/assets/11515982/12366786/b5809c28-bc20-11e5-8684-735720a51170.png">

Also it has slides to support learning.
<img width="1269" alt="ss 2016-01-16 7 07 35" src="https://cloud.githubusercontent.com/assets/11515982/12366848/28d0246e-bc21-11e5-80cc-f8f540326ee5.png">

**Comment by onebree** [comment]
It looks like a Japanese Codecademy, pretty much. I would approve it.

**Comment by vhf** [comment]
Yep, looks good, thanks!

**Comment by switchhax** [comment]
Is it clear where it should be added?

**Comment by johnaoss** [comment]
@switchhax Right now there's only [free-programming-interactive-tutorials-en.md](https://github.com/vhf/free-programming-books/blob/master/free-programming-interactive-tutorials-en.md). Any opinions on what should be done?

**Comment by switchhax** [comment]
Thats exactly my question. vhf has the word cause it´s his project. Maybe a new file, but for one link? I think this issue could be "spared" for when we have more links for this specific language file.

**Comment by vhf** [comment]
I don't really mind having a file with only one link.

**Comment by jarrydfillmore** [comment]
@vhf absolutely lol

**Comment by eshellman** [comment]
Picking this up... yes, please add  free-programming-interactive-tutorials-ja.md; it should be at least 6 links, no?

**Comment by charlottetan** [comment]
Suggestion: add Hacktoberfest label to this!

**Comment by eshellman** [comment]
anyone still interested? otherwise I'll close.

**Comment by eshellman** [comment]
feel free to reopen - willing to accept PRs.
