### ISSUE TITLE
Use a bot that monitors broken links

### ISSUE THREAD

**Issue by onebree** [EbookFoundation/free-programming-books#1849]
I just found this tool while browsing another "awesome" list. It can be used with Travis CI, which I believe this repo uses.

https://github.com/dkhamsing/awesome_bot

I know we currently use a script from @borgified, but I am not sure how frequently it runs. Maybe this could even be forked or modified to check for personal/affiliate links.

Pinging @vhf for thoughts

**Comment by vhf** [comment]
Interesting project, thanks @onebree. I'll set this up tomorrow on a branch and test it.

**Comment by borgified** [comment]
sorry i've been super busy w/ the new job so havent been able to contribute a whole lot lately. im running my url_checker atm and will post an update after it ends. not sure if we still need to run it or not (havent kept up to date with the latest with where we are towards automating the url checking)

**Comment by jarrydfillmore** [comment]
Nice!

**Comment by borgified** [comment]
i got some free time, im gonna set up a docker container, put the script in it and publish it on dockerhub so anyone can just launch and run and have all the dependencies already taken care of

**Comment by vhf** [comment]
That's awesome, thanks a lot @borgified !

**Comment by eshellman** [comment]
Anyone interested in running this regularly?

**Comment by vhf** [comment]
I wouldn't mind running it on my servers via a cronjob. How often though, any wish @eshellman ?

**Comment by eshellman** [comment]
once a month?

**Comment by borgified** [comment]
@eshellman from time to time (every other month these days), i come by here and run my script to check for bad links, i just found out that the project isnt under vhf anymore but my question is, do you want me to continue doing this?

what it entails:
1. i run the script
2. i copy the output and create an issue here
3. other volunteers can click on those links to verify if those urls are indeed bad (sometimes they are  are not up all the time or not fully globally accessible)
4. the same volunteers can create prs to correct the appropriate files and remove bad links

**Comment by vhf** [comment]
I forgot to report back. Setting this up was more troublesome than I thought because we'd need to create a github account and setup API keys for it to be able to come here to create an Issue.

**Comment by eshellman** [comment]
@borgified Yes, please! I'd be happy to add you as a team member if it would help.

**Comment by borgified** [comment]
sure ok (thanks @eshellman). actually in a previous iteration of the script i did manage to automate creating github issues based on my script output but that ended up spamming a bunch of contributors (example: https://github.com/EbookFoundation/free-programming-books/issues/733). i can give another go again and automate (this time being wiser about not spamming)

**Comment by kiquenet** [comment]
source code script?

**Comment by borgified** [comment]
@kiquenet here you go: https://github.com/borgified/url_checker

**Comment by eshellman** [comment]
One "link checker" issue is enough #2541
