### ISSUE TITLE
Mir Books available for free (Please check if availability is OK)

### ISSUE THREAD

**Issue by BrunoDG** [EbookFoundation/free-programming-books#2190]
So, I'm amused by this repo for almost a year and it's really helping me a lot to study! 

Since then, I was thinking over about the mathematics section and found a website with many awesome titles from the old Soviet Union.  My only doubt is: Since Mir has already closed, I don't know if their books are on Public domain, because if they aren't, this link can't be included on the section.

But otherwise, this is an awesome site with a quite complete list of titles published by Mir. I wonder if we could include this site on the list.

Here it goes: https://mirtitles.org/

**Comment by eshellman** [comment]
I asked a friend with public domain expertise about these books and he was not sure. They may be "Orphan Works". To add to the uncertainty, it's possible that Mir, which seems to be a continuing, if diminished, business, may not own the copyrights because that was disallowed in the Soviet era. In the gray zone, but possibly legal.

**Comment by eshellman** [comment]
I got some feedback from my contacts.
1. the books are in-copyright in the US.
2. it's VERY hard to determine who owns the copyright.

mirtitles is not a pirate site, it's a guerrilla digitization collective. But they link to Libgen, which is a pirate site, pretty much. They also deposit to Internet Archive, which is a legitimate source for f-p-b. The link is https://archive.org/details/@mirtitles

It's up to @vhf, of course.

**Comment by BrunoDG** [comment]
Oh. ok, thanks a lot for the feedback!

Now it' really up to @vhf, sure.

**Comment by vhf** [comment]
If we can get links to these books on the Internet Archive, I'd like them to be included here. If they are hosted somewhere else, either on mirtitles or linked from mirtitles, I'll err on the side of caution and would prefer not to include them here. 👍

**Comment by BrunoDG** [comment]
Sorry to return for this topic, but checking here, some of the books are actually on the Internet Archive, as this example: https://archive.org/details/SharyginProblemsInPlaneGeometryScienceForEveryone

So, it's a good thing to know. If wanted, I'll start digging over the Internet Archive to find all the books I can from mir titles. Is that ok?

**Comment by eshellman** [comment]
That would be super!

**Comment by BrunoDG** [comment]
All Right then! So, where can I post the links? Do I put 'em here at this post or do I need to send the links somewhere else?

**Comment by eshellman** [comment]
If you can make a PR, that would be best.

**Comment by eshellman** [comment]
Feel free to reopen but I'm closing this pending new activity
