### ISSUE TITLE
a d3 tutorial site has changed but that link is already old one.

### ISSUE THREAD

**Issue by 117028813** [EbookFoundation/free-programming-books#2319]
https://github.com/vhf/free-programming-books/blob/master/free-programming-books-zh.md#javascript

[D3.js 入门系列](http://www.ourd3js.com/wordpress/?cat=2)

**Comment by eshellman** [comment]
PRs always appreciated!

**Comment by charlottetan** [comment]
Suggestion: add Hacktoberfest label to this

**Comment by eshellman** [comment]
is this issue still relevant?

**Comment by 117028813** [comment]
no, this issue have already solved.
