### ISSUE TITLE
(japanese)日本語のlinux関連の文書

### ISSUE THREAD

**Issue by forregistrar** [EbookFoundation/free-programming-books#2325]
linux環境の管理に関する文書がないので、下記の文書をリストに加えてはどうでしょうか、特定のディストリビューションの文書を「linux」の項目に加えるのは議論のあるところだと思います。

linux標準教科書
http://www.lpi.or.jp/linuxtext/text.shtml (pdf, epub)

debian管理者ハンドブック
https://debian-handbook.info/browse/ja-JP/stable/ (html)
https://debian-handbook.info/get/ (pdf, epub, mobi)

debianリファレンス
https://www.debian.org/doc/manuals/debian-reference/index.ja.html (html)
https://packages.debian.org/ja/jessie/debian-reference-ja (ダウンロードしたdebファイルを解凍すると、epubファイルが入っています。gitレポジトリを探しましたが、epubファイルを直接ダウンロードできるようなリンクは見つかりませんでした。)

**Comment by eshellman** [comment]
These would be good additions. I suggest reading https://github.com/vhf/free-programming-books/blob/master/CONTRIBUTING.md and submitting a pull request.

**Comment by forregistrar** [comment]
Thank you for your replay!
I will try it.

**Comment by charlottetan** [comment]
Suggestion: add Hacktoberfest label to this

**Comment by eshellman** [comment]
Feel free to reopen if this is still relevant

**Comment by miaomiaopan** [comment]
mute the thread




------------------ 原始邮件 ------------------
发件人: "eshellman";<notifications@github.com>;
发送时间: 2018年1月29日(星期一) 上午10:00
收件人: "EbookFoundation/free-programming-books"<free-programming-books@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [EbookFoundation/free-programming-books] (japanese)日本語のlinux関連の文書 (#2325)




Closed #2325.
