### ISSUE TITLE
free-programming-books will change hands!

### ISSUE THREAD

**Issue by vhf** [EbookFoundation/free-programming-books#2349]
It's been three and a half years since I started the _free programming books_ project. It reached a level of popularity I never expected. It sees around 15,000 unique visitors per week, is still in the top 3 most starred repos on GitHub, etc.

Despite all the great contributions and help I received here from over 850 GitHub users, maintaining this repository takes more time than what I can currently allocate to it.

It got so popular people now think of it as a public service, letting it go to waste is unthinkable.

I approached the Free Ebook Foundation (@EbookFoundation) through its president and regular contributor here @eshellman. I will transfer this repository to the [Free Ebook Foundation GitHub organization](https://github.com/EbookFoundation) at the beginning of next month. This transfer will also create a redirect from the URL of this repo to its new URL in order not to break existing links to it.

I'm very excited about this, this project means a lot to me and the Free Ebook Foundation seems like the perfect organization to take care of it.

To all contributors to this project, thank you! 💯 ❤️

**Comment by eshellman** [comment]
Before approving this, the board of directors of the Free Ebook Foundation asked me to describe how we would manage this project moving forward. Here are the goals and principles I laid out:

### Goals

1. Don't break it.
2. Enlarge the maintainer community.
3. Evolve organically to increase impact.

### Guiding Principles

1. Use Github functionality wherever possible. 
2. Encourage positive, supportive discourse. 
3. No links to gray sites.
4. Always consult the users.

**Comment by eshellman** [comment]
Need to check if travis integration switches over without intervention. Travis access is enabled for https://github.com/EbookFoundation organization.

**Comment by vhf** [comment]
Amazing, it worked! :)

**Comment by vhf** [comment]
Travis seems to have automatically picked it up. 👍

**Comment by eshellman** [comment]
let's leave the issue open in case anyone wants to comment generally. Specific problems should go in separate issues.

**Comment by eshellman** [comment]
So it looks like Github can't complete its merge checks across the org change.
