### ISSUE TITLE
criteria for "in process" books

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#2357]
increasingly, there are suggestions to add unfinished or "in process" books to this list, for example #2252 

What criteria should be used for adding this sort of book?

**Comment by quobit** [comment]
Maybe adding it with a label after the link in the list? Sort of "draft", "in process", "stalled", "not finished yet", etc.

Criteria used for adding them could be:

* percentage of finished book (based on table of contents)
* if there's a public repo for the source, point at it, see if the commits have stalled or are alive (e.g. the book in #2252 has a repo here https://github.com/munificent/craftinginterpreters/graphs/contributors)
* contacting authors?

**Comment by eshellman** [comment]
maybe 75% for original, 50% for translations?

Maybe have a special list for in-process book repos, to help encourage participation?

Have asked @munificent for comment on twitter.

**Comment by polyzen** [comment]
> Maybe have a special list for in-process book repos, to help encourage participation?

Subsections seem appropriate.

**Comment by munificent** [comment]
I'm obviously biased, but I like the idea of listing books that are still underway. I would call them out in some way because people might be surprised if all the content isn't there yet.

There is a real risk of ending up listing books that are incomplete and abandoned. (I heard from O'Reilly that a surprisingly large fraction of technical books die before the author finishes them.)

**Comment by eshellman** [comment]
how about listing in-process books like this:

* 🚧 [Book Title](https://link-to-book.example.com)

At the end of a topic list (I think the linter will put emoji last alphabetically except for obscure characters).

And add guidance that incomplete books which haven't advanced in a year should be removed.

**Comment by eshellman** [comment]
"Crafting Interpreters" was merged with an emoji. Because of the way the linter want lists to be alphabetized, the listing was

* [Crafting Interpreters (:construction:)](http://www.craftinginterpreters.com) - Bob Nystrom (HTML)

Alternatives were:
* [Crafting Interpreters :construction:](http://www.craftinginterpreters.com) - Bob Nystrom (HTML)
* [Crafting Interpreters](http://www.craftinginterpreters.com) - Bob Nystrom (HTML) (:construction:)
* [Crafting Interpreters](http://www.craftinginterpreters.com) - Bob Nystrom (HTML) (:construction: *in process*)

etc.
Aesthetic review welcome.

**Comment by polyzen** [comment]
I prefer the latter option, append (🚧 in process), or just appending (🚧) if a legend is added:
`* Books labeled (🚧) are still in the process of being made.`

**Comment by eshellman** [comment]
This has been an open issue long enough. Let's go with this format:

* [Crafting Interpreters](http://www.craftinginterpreters.com) - Bob Nystrom (HTML) (:construction: *in process*)

Would appreciate a PR for CONTRIBUTING so we can close the issue.

**Comment by eshellman** [comment]
implemented.
