### ISSUE TITLE
Introdução a LISP

### ISSUE THREAD

**Issue by iahaelalmeida** [EbookFoundation/free-programming-books#2377]
* [Another book](http://www.dca.fee.unicamp.br/courses/EA072/lisp9596/Lisp9596.html)   ##(HTML)

**Comment by eshellman** [comment]
license indicates it is free http://www.dca.fee.unicamp.br/courses/EA072/lisp9596/license.html

Would welcome a PR!

**Comment by eshellman** [comment]
Thanks!
