### ISSUE TITLE
Let's start adding author names where appropriate

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#2383]
* many programming books have names that can be confused for similar books: e.g.  "introduction to Java". It's very helpful to browsers to see the author names
* The identity of books with translated titles may not be apparent
* People googling for books will more easily find our lists
* (perhaps most important) Authors who make their books available for free deserve recognition

If you'd like to assist in this effort: 
* submit PRs for manageable sections of the lists. (10 or so books at a time.)
* if there are a lot of authors, use "First Author et al."
* sometimes there's no useful author, don't sweat it.
* reviewing other contributors' PRs is almost as helpful to the admins as submitting new ones.

**Comment by tedyoung** [comment]
Would it be useful to add the year as well?

**Comment by eshellman** [comment]
A previous discussion #1926 (which I see @tedyoung has found) suggested that adding the year for older books would be a good idea.
