### ISSUE TITLE
Add traditional Chinese transliterations of the headings in -zh list

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#2384]
In PR #2074 it was proposed to add a zh_TW list. After discussion, it was proposed to add traditional headings in parens in the zh file where the traditional characters differ from simplified. This will make a combined list (resources in simplified and traditional characters) easier to maintain.

If users of the zh list agree, please submit a PR, if not, please let us know here.

谢谢 (謝謝)

**Comment by zhongjiajie** [comment]
I don't think is a good idea, it will make the ZH list duplicate. And most of the resources is in simplified chinese, you have to konw simplified chinese to read it.

**Comment by eshellman** [comment]
Without a PR or positive comment in 4 months, I'm closing this issue. Will reopen if there's more interest.
