### ISSUE TITLE
A github.io website

### ISSUE THREAD

**Issue by iamsubhranil** [EbookFoundation/free-programming-books#2479]
Hey, I've been thinking how about showcasing this awesome collection properly using a github.io website?

**Comment by eshellman** [comment]
Like this? https://ebookfoundation.github.io/free-programming-books/

Good idea. It's likely to surface other issues, submit a PR if you find any. (there's the books emoji, for one thing!)

**Comment by eshellman** [comment]
I also created https://github.com/EbookFoundation/ebookfoundation.github.io but have not done Jeckyl before; all help welcome.

**Comment by iamsubhranil** [comment]
Me neither. But we can try. Let's see.

**Comment by eshellman** [comment]
I suppose that to close this issue, we should add a link in the readme

**Comment by charlottetan** [comment]
Suggestion: add Hacktoberfest label to this
