### ISSUE TITLE
Book in the online course section

### ISSUE THREAD

**Issue by bharath-123** [EbookFoundation/free-programming-books#2482]
In the online course section, under the topic bash. There is book instead of a course. So It would be better to move the book to the programming books section .

**Comment by eshellman** [comment]
A PR would be welcomed. (and please give details along with an explanation of why you think the resource should be moved)

**Comment by bharath-123** [comment]
I made a  PR. Please check it :)

**Comment by charlottetan** [comment]
Suggestion: add Hacktoberfest label to this

**Comment by charlottetan** [comment]
Suggestion: add Hacktoberfest label to this

**Comment by eshellman** [comment]
addressed by #2493
