### ISSUE TITLE
Bootstrap links under HTML are poinitng to a login page

### ISSUE THREAD

**Issue by saurabh-pandey** [EbookFoundation/free-programming-books#2486]
Hi,
First of all thanks a lot for assembling such a great and expansive list. I was helped a lot from the links provided.
While going through some new topics I was exploring, I found that the Bootstrap links (both of them) under HTML were pointing to the same login page.
I have attempted a fix for them in my local branch and would raise a Pull Request asap.
Thanks,
Saurabh

**Comment by saurabh-pandey** [comment]
Hi,
Have raised a pull request (#2487). Can you please check and provide your suggestion(s) ?
Thanks,
Saurabh

**Comment by eshellman** [comment]
worth checking if we have any other links to this site.

**Comment by saurabh-pandey** [comment]
Sure. Will update if I find something. Thanks.
