### ISSUE TITLE
Apache中文文档更新

### ISSUE THREAD

**Issue by sxueck** [EbookFoundation/free-programming-books#2495]
你好，Apache HTTP Server version 2.4中文文档已更新，你的是2.2版本的
https://httpd.apache.org/docs/2.4/zh-cn/

**Comment by sxueck** [comment]
抱歉看错了，进去后还是英文文档

**Comment by eshellman** [comment]
please add it to the zh list. There's an index entry for HTTP, but no list yet!

**Comment by BinaryYS** [comment]
就看英文的吧

**Comment by eshellman** [comment]
@BinaryYS thanks for the assistance

**Comment by charlottetan** [comment]
Suggestion: add Hacktoberfest label to this
