### ISSUE TITLE
Why are there no BASIC/QBasic/QB64 books?

### ISSUE THREAD

**Issue by callowaysutton** [EbookFoundation/free-programming-books#2502]
There are many free eBooks available for how to learn BASIC/QBasic/QB64 and yet I see none here?
It's not as if Basic has become a slow language...
Here's a program I made in it: github.com/callowaysutton/Zinc
It operates a quickly as something programmed in C (of course it's not done yet :P )

**Comment by eshellman** [comment]
True, the English list has only 4 entries for Basic and 1 for Visual Basic.

As always, we welcome Pull Requests with additions/corrections!

https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md
