### ISSUE TITLE
help requested sorting zh

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#2503]
#2498 could use some help. volunteers would be appreciated. 

this is a common issue, and there are subtleties:

https://stackoverflow.com/questions/1097908/how-do-i-sort-unicode-strings-alphabetically-in-python

our linter uses some javascript to decide what is "alphabetical"

https://github.com/vhf/remark-lint-alphabetize-lists/blob/master/lib/alphabetical-list-items.js

**Comment by liluoao** [comment]
Thank you!

**Comment by eshellman** [comment]
If any zh-speaker can volunteer to help other zh-contributors with sorting issues, it would be a great help.

**Comment by zhongjiajie** [comment]
I can help sometime if you wish, but some `-zh` list sorted is odd for me. For example, some book's name in chinese start at `a` > `z` like [this](https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books-zh.md#项目相关), others `z` > `a` like [this](https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books-zh.md#python)

**Comment by zhongjiajie** [comment]
In my  latest comment, I don't see the link 
https://github.com/vhf/remark-lint-alphabetize-lists/blob/master/lib/alphabetical-list-items.js  
to decide what is "alphabetical". Now I kown how to do it, I will help chinese's contributor if them miss some sorted issue.

**Comment by eshellman** [comment]
stale
