### ISSUE TITLE
powershell book - bad link

### ISSUE THREAD

**Issue by shishini** [EbookFoundation/free-programming-books#2519]
the Mastering Powershell book link 
http://powershell.com/cs/login.aspx?ReturnUrl=/cs/blogs/ebook/default.aspx

now redirects to 
http://community.idera.com/powershell 

this might be the new link
http://community.idera.com/powershell/powertips/b/ebookv2#pi619PostSortOrder=Ascending

**Comment by eshellman** [comment]
The link should be removed. This is your chance to become a contributor by submitting a pull request!
