### ISSUE TITLE
Dead Link: Basic A beginner's guide to Gambas

### ISSUE THREAD

**Issue by drieslouw** [EbookFoundation/free-programming-books#2523]
### Basic

* [A beginner's guide to Gambas](http://beginnersguidetogambas.com)

Redirects to 'http://www1.beginnersguidetogambas.com/?kw=computer%20programming' which is a domain sale front for 'https://latonas.com/domains/marketplace/?domain=beginnersguidetogambas.com'

**Comment by eshellman** [comment]
Thanks, I'd appreciate a pull request. We welcome new contributors!
