### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by michaelstern336** [EbookFoundation/free-programming-books#2525]
https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books.md#javascript

**Comment by eshellman** [comment]
???

**Comment by michaelstern336** [comment]
Sorry

**Comment by michaelstern336** [comment]
sorry

**Comment by BrunoDamiao** [comment]
Em 05/09/17 10:01, michaelstern336  <notifications@github.com> escreveu: 
> 
> Sorry
>
