### ISSUE TITLE
nutz教程的书 应该出现在这里

### ISSUE THREAD

**Issue by HaimmingYu** [EbookFoundation/free-programming-books#2529]
nutz教程的书 应该出现在这里
https://github.com/wendal/nutz-book
http://nutzbook.wendal.net/

**Comment by eshellman** [comment]
Would welcome a PR!

**Comment by TonyYule** [comment]
This book is used for Nutz -- Web Framework(Mvc/Ioc/Aop/Dao/Json) for ALL Java developer 
https://github.com/nutzam/nutz
https://nutzam.com

**Comment by zhongjiajie** [comment]
@TonyYule, 维护者建议你在项目文件`free-programming-books-zh.md`的相应位置增加你的书，然后`pull requests`到项目中，这样他就能将这本书放进列表了

**Comment by TonyYule** [comment]
我有权限么

**Comment by zhongjiajie** [comment]
@TonyYule 你没有权限`直接push`到master中，但是任何人都可以提交`pull requests`。你要做的是将这个版本库`Fork`到你的Github中，然后`clone`到本地进行修改，`push`到你Github的远程库中，最后在你的库中点击`push requests`就可以了。
**要注意增加书目的顺序**，详情可以查看 https://github.com/EbookFoundation/free-programming-books/issues/2503

**Comment by charlottetan** [comment]
Suggestion: add Hacktoberfest label to this

**Comment by HaimmingYu** [comment]
fixed  [nutzbook](https://github.com/EbookFoundation/free-programming-books/pull/3063#issuecomment-441654319)

## What does this PR do?
Add Resource

## For resources
### Description 
Nutz -- Web Framework(Mvc/Ioc/Aop/Dao/Json) for ALL Java developer https://nutzam.com

### Why is this valuable (or not)
 Web Framework(Mvc/Ioc/Aop/Dao/Json) for ALL Java developer

### How do we know it's really free?
This work is licensed by using knowledge sharing signature - sharing the 4 international license agreement in the same way. Visit
 http://creativecommons.org/licenses/by-sa/4.0/

### For book lists, is it a book?
yes

### Checklist:
- [ ] Version v1.8-20161219
- [ ] The book's source code is hosted in [GitHub](https://github.com/wendal/nutz-book) and [open source China](http://git.oschina.net/wendal/nutz-book).
- [ ] The hosting address of the book is also in [GitHub](https://github.com/wendal/nutz-book) and [open source China](http://git.oschina.net/wendal/nutz-book).
- [ ] Wendal Chen write Fisrt Commit on Mar 9, 2015

**Comment by bluetata** [comment]
你提交的PR排序不对，被机器check住了，你提交的那两个链接互换下顺序应该就可以了
