### ISSUE TITLE
New Python book in pdf  (English and Dutch versions)

### ISSUE THREAD

**Issue by H3li0** [EbookFoundation/free-programming-books#2539]
Hello,

I would like to propose a link to a free pdf book about Python.

Here is the Title:
**The Coder's Apprentice**
_Learning Programming with Python 3_

Here is the link:
http://www.spronck.net/pythonbook/

Thank you.

**Comment by H3li0** [comment]
The book comes in English and Dutch versions.

**Comment by eshellman** [comment]
Outstanding! If you can, please send a PR. As always, check the CONTRIBUTING file for instructions.

**Comment by charlottetan** [comment]
Suggestion: add Hacktoberfest label to this
