### ISSUE TITLE
Broken links from linkchecker. Please help us fix these!

### ISSUE THREAD

**Issue by Devinsuit** [EbookFoundation/free-programming-books#2541]
@eshellman what do you think about https://github.com/dkhamsing/awesome_bot? For me, it looks pretty good. https://travis-ci.org/Devinsuit/free-programming-books/jobs/278984109

free-programming-books-pl.md
+ [ ] 500 Can't connect to stallman.helion.pl:80 http://stallman.helion.pl
+ [x] 500 read timeout http://www.ptm.org.pl/latex-ksiazka-kucharska

free-programming-books-cs.md

free-podcasts-screencasts-es.md

free-podcasts-screencasts-cs.md
+ [x] 500 Can't connect to java.cz:80 http://java.cz/article/czpodcast

free-programming-books-se.md

free-podcasts-screencasts-ru.md
+ [ ] 500 Can't connect to ruby.hasbrains.org:80 http://ruby.hasbrains.org
+ [ ] 500 Can't connect to rails.hasbrains.org:80 http://rails.hasbrains.org

free-programming-playgrounds.md
+ [ ] 522 Origin Connection Time-out http://code.runnable.com
+ [ ] 522 Origin Connection Time-out http://code.runnable.com

free-programming-books-fi.md

free-programming-books-mm.md

free-programming-books-az.md

free-programming-books-es.md
+ [ ] 404 Not Found http://www.colegiodrriodelaloza.edu.mx/informatica/Analisis%20Diseno%20e%20Implementacion%20de%20Algoritmos/17470106-BASES-de-DATOS-3-El-Modelo-Relacional-y-Algebra-Relacional.pdf

free-programming-books-id.md
+ [x] 403 Forbidden http://www.ilmuwebsite.com/ebook-php-free-download
+ [ ] 500 Can't connect to www.codingku.com:80 http://www.codingku.com/php/

free-programming-books-ar.md
+ [ ] 500 Can't connect to blog.algorithmers.com:80 http://blog.algorithmers.com/git/

free-programming-books-sk.md

free-courses-en.md
+ [x] 404 OK https://courses.platzi.com/courses/git-gitlab/
+ [ ] 404 Not Found https://www.learnhowtoprogram.com/java

free-programming-books-ja.md
+ [ ] 404 Not Found https://developer.apple.com/jp/devcenter/ios/library/documentation/OpenGLES_ProgrammingGuide.pdf
+ [ ] 404 Not Found http://www.oki-osk.jp/esc/groovy/
+ [ ] 404 Not Found http://www.fos.kuis.kyoto-u.ac.jp/~t-sekiym/classes/isle4/mltext/ocaml.html
+ [ ] 404 Not Found http://download.bnn.co.jp/download/beyond_interaction/BNN_BeyondInteraction.pdf

free-podcasts-screencasts-en.md
+ [ ] 302 Found http://www.tutsowl.com
+ [ ] 522 Origin Connection Time-out http://reactpodcast.com

free-programming-books-gr.md

free-programming-books-de.md

free-programming-books-tr.md

free-programming-books-ko.md
+ [ ] 500 Can't connect to www.openstatistics.net:80 http://www.openstatistics.net

free-programming-books-fa_IR.md

free-programming-books-zh.md
+ [ ] 302 Found http://neo4j.tw
+ [ ] 500 Can't connect to deerchao.net:80 http://deerchao.net/tutorials/regex/regex.htm
+ [ ] 404 Not Found https://github.com/Flowerowl/Big-Data-Resources
+ [ ] 500 Can't connect to deerchao.net:80 http://deerchao.net/tutorials/regex/regex.htm
+ [x] 500 Can't connect to gorevel.cn:80 http://gorevel.cn/docs/manual/index.html
+ [ ] 404 Not Found http://typeof.net/s/jsmech/
+ [ ] 404 Not Found http://learningcn.com/underscore/

free-programming-books-it.md

free-programming-books-fr.md
+ [x] 404 Not Found http://math.univ-lyon1.fr/irem/IMG/pdf/LatexPourProfMaths3.pdf

free-programming-books-hu.md
+ [ ] 404 Not Found http://blog.molnardenes.hu/python-programozas-1-alapfogalmak/

free-programming-interactive-tutorials-en.md

free-programming-books-pt_BR.md

free-programming-books.md
+ [ ] 500 Can't connect to gimp-savvy.com:80 http://gimp-savvy.com/BOOK/index.html
+ [ ] 404 Not Found http://webdocs.cs.ualberta.ca/~sutton/book/ebook/the-book.html
+ [ ] 404 Not Found http://www-stat.stanford.edu/~tibs/ElemStatLearn/
+ [ ] 404 Not Found http://www.math.cornell.edu/~bterrell/dn.pdf
+ [ ] 404 Not Found https://www.ansible.com/blog/free-ansible-book
+ [ ] 404 Not Found http://www.amibug.com/iamabug/p01.html
+ [ ] 404 Not Found https://courses.engr.illinois.edu/ece390/books/artofasm/artofasm.html
+ [ ] 404 Not Found http://www.ghielectronics.com/downloads/FEZ/Beginners%20guide%20to%20NETMF.pdf
+ [ ] 404 Not Found http://www-03.ibm.com/systems/z/education/skills_coursematerials.html#COBOL
+ [ ] 521 Origin Down http://rypress.com/tutorials/git
+ [x] 503 Service Unavailable http://go-book.appspot.com
+ [ ] 404 Not Found http://njbartlett.name/osgibook.html
+ [ ] 404 Not Found http://health.adelaide.edu.au/psychology/ccs/teaching/lsr
+ [ ] 404 Not Found https://consensys.github.io/developers/articles/101-noob-intro/

free-podcasts-screencasts-pt_BR.md

free-programming-books-pt_PT.md

javascript-frameworks-resources-pt_BR.md
+ [ ] 500 Can't connect to www.vedcasts.com.br:80 http://www.vedcasts.com.br/hibernando

free-podcasts-screencasts-se.md

free-programming-books-bg.md

free-programming-books-ro.md

free-programming-books-ua.md

problem-sets-competitive-programming.md

javascript-frameworks-resources.md

free-programming-books-ru.md

**Comment by eshellman** [comment]
@Devinsuit how do you suggest to run it? Would adding it to travis put error messages in unrelated PRs?

**Comment by eshellman** [comment]
time to run link check again?
