### ISSUE TITLE
Hijacked or "hijacked" domain

### ISSUE THREAD

**Issue by rautamiekka** [EbookFoundation/free-programming-books#2544]
http://www.brpreiss.com/books/opus6/ "`Data Structures and Algorithms with Object-Oriented Design Patterns in C#`" in the C# ebook section takes you to surveys and such; may be other unwanted results, I landed in a survey thing.

**Comment by eshellman** [comment]
See #2372, and #2348. If you could replace this with a wayback link, we'd really appreciate it. or remove it.

**Comment by rautamiekka** [comment]
https://github.com/EbookFoundation/free-programming-books/pull/2372 already has Wayback link. I guess I were lazy.
