### ISSUE TITLE
Implement awesome link

### ISSUE THREAD

**Issue by ShalokShalom** [EbookFoundation/free-programming-books#2549]
This here is an awesome link verifier: https://github.com/dkhamsing/awesome_bot

**Comment by zhongjiajie** [comment]
Wooh, this awesome.

**Comment by ShalokShalom** [comment]
And judicious sind always ;)

**Comment by eshellman** [comment]
please see the discussion in #2541 

my understanding is that wiring this into our travis tests would not be useful because with about 3600 links in the repo, there's always going to be at least one that fails.

**Comment by ShalokShalom** [comment]
So you are saying there are too much broken links, to make them visible? o.O

**Comment by eshellman** [comment]
44 urls not working out of 3600 is not so bad, I think. But if you test 1,000 sites, what are the chances that none of the thousand will be temporarily down? We should definitely run a link checker periodically, but not on every commit.

**Comment by ShalokShalom** [comment]
Yeah, that is fine. :)
