### ISSUE TITLE
Clean Code Developer: More professionalism in software development

### ISSUE THREAD

**Issue by Tardog** [EbookFoundation/free-programming-books#2562]
I believe the free guide for the Clean Code Developer initiative would make a great addition to the list:
https://www.gitbook.com/book/ccd_school/clean-code-developer-com/details

The main website of the initiative is in German: http://clean-code-developer.de

If there are no objections, I would like to submit a PR for this.

**Comment by eshellman** [comment]
The english translation looks unfinished to me. See the notations about "in-progress" works in CONTRIBUTING, if the translation is actively being worked on. The original German version looks acceptable.

**Comment by Tardog** [comment]
Thank you for taking the time to look into my proposal! Please see #2564 for the PR.
