### ISSUE TITLE
Suggestion: Add "Hacktoberfest" label to issues in repo

### ISSUE THREAD

**Issue by charlottetan** [EbookFoundation/free-programming-books#2590]
https://hacktoberfest.digitalocean.com/

Adding the label will help get more eyes on this project and this project is also a great candidate for people who are making their first pull request!

**Comment by eshellman** [comment]
good idea - added the label to our "add authors" issue. If @Devinsuit  (or anyone else!) runs the link checker again, that would be another issue the label could be applied to.

**Comment by eshellman** [comment]
Other suggestions for Hacktoberfest issues welcome!

**Comment by eshellman** [comment]
@charlottetan it's a big help to have more eyes on issues, thanks for taking a look!

**Comment by shabab477** [comment]
Thank you all the maintainers of this project for showing patience while participating in this event. Love you all <3
