### ISSUE TITLE
Please help us fix broken links!

### ISSUE THREAD

**Issue by Devinsuit** [EbookFoundation/free-programming-books#2602]
free-programming-books-pt_PT.md

free-programming-books-de.md

free-programming-books-cs.md

free-programming-books-ua.md

free-programming-books-se.md

free-programming-books-hu.md

free-programming-books-pt_BR.md
+ [x] 500 Can't connect to metamorphoselinux.net:80 http://metamorphoselinux.net/Shell_Script_do_Zero.pdf

free-programming-interactive-tutorials-en.md

free-podcasts-screencasts-es.md

free-podcasts-screencasts-cs.md

free-podcasts-screencasts-en.md

free-programming-books-ru.md

free-programming-books-bg.md

free-programming-books-sk.md

free-programming-books-pl.md

free-podcasts-screencasts-ru.md

free-programming-playgrounds.md
+ [x] 500 Can't connect to phpfiddle.org:80 http://phpfiddle.org

free-programming-books-it.md

free-podcasts-screencasts-se.md

free-programming-books-fi.md

free-courses-ru.md

free-programming-books-ro.md

free-programming-books-tr.md

problem-sets-competitive-programming.md
+ [ ] 500 Can't connect to acm.hdu.edu.cn:80 http://acm.hdu.edu.cn
+ [ ] 404 Not Found http://problembook.net/content/en/index.html

free-programming-books-fa_IR.md

free-programming-books-gr.md

free-programming-books-fr.md

javascript-frameworks-resources-pt_BR.md

free-programming-books.md
+ [x] 500 Can't connect to jeffe.cs.illinois.edu:80 http://jeffe.cs.illinois.edu/teaching/algorithms/
+ [x] 500 Can't connect to mfleck.cs.illinois.edu:80 http://mfleck.cs.illinois.edu/building-blocks/index.html
+ [ ] 500 Can't connect to blog.hit.edu.cn:80 http://blog.hit.edu.cn/jsx/upload/AT%EF%BC%86TAssemblyLanguage.pdf
+ [x] 500 Can't connect to www.slideshare.net:443 http://www.slideshare.net/olvemaudal/deep-c
+ [x] 503 Service Unavailable https://web.archive.org/web/20161220072449/http://www.brpreiss.com/books/opus6/
+ [ ] 521 Origin Down http://rypress.com/tutorials/git
+ [ ] 404 Not Found http://docs.spring.io/spring/docs/current/spring-framework-reference/pdf/spring-framework-reference.pdf
+ [ ] 404 Not Found http://health.adelaide.edu.au/psychology/ccs/teaching/lsr

free-programming-books-es.md
+ [ ] 404 Not Found http://library.originalhacker.org/biblioteca/articulo/ver/123

free-programming-books-az.md
+ [x] 502 Bad Gateway http://ilkaddimlar.com/ders/c-proqramlasdirma-dili
+ [x] 502 Bad Gateway http://ilkaddimlar.com/ders/css
+ [x] 502 Bad Gateway http://ilkaddimlar.com/ders/html
+ [x] 502 Bad Gateway http://ilkaddimlar.com/ders/javascript
+ [x] 502 Bad Gateway http://ilkaddimlar.com/ders/linux
+ [x] 502 Bad Gateway http://ilkaddimlar.com/ders/php

free-programming-books-ja.md
+ [ ] 404 Not Found https://developer.apple.com/jp/devcenter/ios/library/documentation/OpenGLES_ProgrammingGuide.pdf
+ [ ] 404 Not Found http://www.oki-osk.jp/esc/groovy/
+ [ ] 404 Not Found http://www.fos.kuis.kyoto-u.ac.jp/~t-sekiym/classes/isle4/mltext/ocaml.html
+ [ ] 404 Not Found http://download.bnn.co.jp/download/beyond_interaction/BNN_BeyondInteraction.pdf

free-programming-books-ko.md

free-podcasts-screencasts-pt_BR.md

javascript-frameworks-resources.md
+ [ ] 500 Can't connect to reactjs.net:80 http://reactjs.net/getting-started/aspnet5.html

free-programming-books-id.md
+ [ ] 403 Forbidden http://www.ilmuwebsite.com/ebook-php-free-download

free-courses-en.md

free-programming-books-ar.md

free-programming-books-mm.md

free-programming-books-zh.md
+ [ ] 302 Found http://neo4j.tw
+ [x] 502 Bad Gateway http://www.gruntjs.net
+ [ ] 500 Can't connect to deerchao.net:80 http://deerchao.net/tutorials/regex/regex.htm
+ [ ] 404 Not Found https://github.com/Flowerowl/Big-Data-Resources
+ [ ] 500 Can't connect to deerchao.net:80 http://deerchao.net/tutorials/regex/regex.htm
+ [ ] 500 Can't connect to local.joelonsoftware.com:80 http://local.joelonsoftware.com/wiki/Chinese_(Simplified)
+ [ ] 500 Can't connect to local.joelonsoftware.com:80 http://local.joelonsoftware.com/wiki/%E9%A6%96%E9%A0%81
+ [ ] 500 Status read failed: Connection reset by peer http://sewm.pku.edu.cn/src/paradise/reference/CMake%20Practice.pdf
+ [ ] 404 Not Found http://typeof.net/s/jsmech/
+ [ ] 404 Not Found http://learningcn.com/underscore/
+ [ ] 500 Status read failed: Connection reset by peer http://net.pku.edu.cn/~yhf/tutorial/perl/perl.html
+ [ ] 500 Can't connect to jwch.sdut.edu.cn:80 http://jwch.sdut.edu.cn/book/rst.html

**Comment by JacksonIsaac** [comment]
On it. Some links are working though. Will remove whichever are no longer available and update the ones which are relocated.
