### ISSUE TITLE
Functional C

### ISSUE THREAD

**Issue by ophey** [EbookFoundation/free-programming-books#2608]
Here is a link to an old book on functional programming 

https://research.utwente.nl/en/publications/functional-c

by Peter Hartelt

https://research.utwente.nl/files/5128727/book.pdf

**Comment by eshellman** [comment]
would be a good addition. may want to note year and authors

**Comment by ophey** [comment]
I cloned the repo and added the book to free-programming-books.md

Would I just push that on master for the pull request?

**Comment by eshellman** [comment]
give it a try
