### ISSUE TITLE
The New C Standard - An Economic and Cultural commentary

### ISSUE THREAD

**Issue by Derek-Jones** [EbookFoundation/free-programming-books#2622]
The title should be:

The New C Standard - An Economic and Cultural commentary
not
The New C Standard - An Annotated Reference

**Comment by eshellman** [comment]
A pull request would be appreciated!

**Comment by Derek-Jones** [comment]
Don't you want drive-by bug reports?  Or is your primary interest your fork count?

**Comment by eshellman** [comment]
Bug reports also appreciated. Thanks to an amazing community, issues get resolved one way or another.
