### ISSUE TITLE
Add Django Girls Tutorial translations to free-programming-books

### ISSUE THREAD

**Issue by miwojc** [EbookFoundation/free-programming-books#2626]
Add completed translations of "Django Girls Tutorial" to free-programming-books for related country file.
Link to website with translations: https://tutorial.djangogirls.org/
Available translations (some in beta):
🇺🇸 English
🇨🇿 Czech (beta)
🇩🇪 Deutsch (beta)
🇪🇸 Español (beta)
🇫🇷 Français
🇮🇹 Italian (beta)
🇭🇺 Magyar (beta)
🇵🇱 Polski
🇵🇹 Português-brasileiro (beta)
🇹🇷 Türkçe (beta)
🇷🇺 Русский (beta)
🇺🇦 Українська
🇨🇳 简体中文
🇰🇵/🇰🇷 한국어 (beta)
🇸🇰 Slovak (beta)

As always, please review the contributing and conduct guidelines for this repository.

**Comment by eshellman** [comment]
from #2625. for betas, please see note about "in-progress" works in CONTRIBUTING.
