### ISSUE TITLE
Hello! Can you help me update the documents in Spanish?

### ISSUE THREAD

**Issue by DpdC** [EbookFoundation/free-programming-books#2633]
I have updated the documents in Spanish. But I am not able to make a pull requests. 
Possibly doing something wrong. I am a beginner.

Can help me? Thank´s.  :+1:

**Comment by eshellman** [comment]
Maybe one of these will help: 
https://www.youtube.com/watch?v=0fKg7e37bQE
https://www.youtube.com/watch?v=G1I3HF4YWEw
https://guides.github.com/activities/hello-world/

Don't hesitate to ask questions; every contributor started with a first PR.

**Comment by polyzen** [comment]
https://help.github.com/articles/about-pull-requests/

**Comment by DpdC** [comment]
I had not made the fork in my 'profile' on github. That was all.
[- pull request #2635 -](https://github.com/EbookFoundation/free-programming-books/pull/2635 )
Now, I'm happy.. very happy.. :fire: :sob: :sob: :sunrise: :smile:  

Thank´s for the help.

- Dpdc, Regards.
