### ISSUE TITLE
Please adjust link to my Linear Algebra (help requested)

### ISSUE THREAD

**Issue by jimhefferon** [EbookFoundation/free-programming-books#2639]
I appreciate your work on open materials.  I see that you link to a version of my Linear Algebra.  That version is nearly a decade old now, and the newer versions have lots of corrections, improvements, added features, etc.  Could you please change the link

    Linear Algebra: An Introduction to Mathematical Discourse

to be something more like 

    Linear Algebra by Jim Hefferon

and direct it to the book's home page 

    http://joshua.smcvt.edu/linearalgebra

?  (You may also be interested in my Introduction to Proofs book at http://joshua.smcvt.edu/proofs.)

Thank you, Jim

**Comment by eshellman** [comment]
These look great! You're welcome to submit a PR; if not someone else from our amazing community will help out by making one.
