### ISSUE TITLE
Broken links (help requested)

### ISSUE THREAD

**Issue by Devinsuit** [EbookFoundation/free-programming-books#2650]
free-courses-en.md

free-programming-books-tr.md

free-programming-books-ua.md
+ [ ] 404 Not Found http://twbs.docs.org.ua

free-programming-books-fi.md

free-programming-books-nl.md

free-programming-books-az.md

free-programming-books-mm.md

free-programming-books-de.md

free-programming-books-ja.md
+ [ ] 404 Not Found http://lagendra.w3.kanazawa-u.ac.jp/ogurisu/manuals/awk/index.html
+ [ ] 404 Not Found http://home.soka.ac.jp/~unemi/LispProlog/
+ [ ] 403 Forbidden http://cdn8.atwikiimg.com/git_jp/pub/git-manual-jp/Documentation/user-manual.html
+ [ ] 403 Forbidden http://www38.atwiki.jp/aias-jsstyleguide2/
+ [ ] 500 Can't connect to net-newbie.com:80 http://net-newbie.com/support/pdf2/
+ [ ] 404 Not Found http://home.soka.ac.jp/~unemi/LispProlog/

free-podcasts-screencasts-en.md
+ [ ] 404 Not Found http://python.madewithopinion.com
+ [ ] 500 Can't connect to rubyshow.com:80 http://rubyshow.com

problem-sets-competitive-programming.md

free-programming-books-zh.md
+ [ ] 500 Can't connect to www.hubwiz.com:80 http://www.hubwiz.com
+ [ ] 500 Can't connect to www.kancloud.cn:80 http://www.kancloud.cn/kancloud/a-programmer-prepares
+ [ ] 500 Can't connect to www.kancloud.cn:80 http://www.kancloud.cn/kancloud/intro-to-prog/52592
+ [ ] 500 Can't connect to docs.huihoo.com:80 http://docs.huihoo.com/gnu/linux/gmake.html
+ [ ] 404 NOT FOUND https://web.archive.org/web/20170615232349/http://local.joelonsoftware.com/wiki/%E9
+ [ ] 500 Can't connect to docs.huihoo.com:80 http://docs.huihoo.com/gnu/linux/gmake.html
+ [ ] 500 Can't connect to jwch.sdut.edu.cn:80 http://jwch.sdut.edu.cn/book/rst.htm://web.archive.org/web/20170122080708/http://jwch.sdut.edu.cn/book/rst.html
+ [ ] 404 Not Found http://billie66.github.io/TLCL/book/zh
+ [ ] 500 Can't connect to man.chinaunix.net:80 http://man.chinaunix.net/newsoft/vi/doc/help.html

free-programming-books-pl.md

free-programming-books-bg.md

free-programming-books-pt_PT.md
+ [ ] 403 Forbidden http://www.dei.isep.ipp.pt/~pbsousa/aulas/ano_0/2006_07/c/Sebenta-cpp-03-2006.pdf

free-programming-books-sk.md

free-programming-books-cs.md

free-podcasts-screencasts-cs.md

free-courses-de.md

free-programming-interactive-tutorials-en.md
+ [ ] 500 Can't connect to www.tryclj.com:80 http://www.tryclj.com

javascript-frameworks-resources.md

free-programming-books-pt_BR.md
+ [ ] 500 Status read failed: Connection reset by peer http://www.jmonteiro.com/aprendaaprogramar/
+ [ ] 500 Can't connect to howtocode.com.br:80 http://howtocode.com.br/ebooks/ruby
+ [ ] 500 Can't connect to metamorphoselinux.net:80 http://metamorphoselinux.net/Shell_Script_do_Zero.pdf

free-programming-books-ar.md

javascript-frameworks-resources-pt_BR.md

free-programming-books-gr.md

free-programming-books-fr.md

free-programming-books-ko.md

free-programming-books-fa_IR.md

free-courses-ru.md

free-programming-playgrounds.md

free-podcasts-screencasts-ru.md

free-programming-books-ro.md

free-programming-books-id.md
+ [ ] 403 Forbidden http://www.ilmuwebsite.com/ebook-php-free-download

free-podcasts-screencasts-se.md

free-programming-books-se.md

free-programming-books-hu.md

free-podcasts-screencasts-es.md

free-podcasts-screencasts-pt_BR.md

free-programming-books-es.md
+ [x] 302 Moved Temporarily http://www.etnassoft.com/biblioteca/
+ [x] 302 Moved Temporarily http://www.etnassoft.com/biblioteca/guia-completa-de-css3/
+ [ ] 500 Can't connect to www.decom-uv.cl:80 http://www.decom-uv.cl/~roberto/apuntes/java/AprendiendoJava.pdf

free-programming-books-ru.md
+ [ ] 404 Not Found https://community.imgtec.com/downloads/digital-design-and-computer-architecture-russian-edition-second-edition

free-programming-books.md
+ [ ] 404 Not Found http://mirror.unicorncloud.org/savannah-nongnu//pgubook/ProgrammingGroundUp-1-0-booksize.pdf
+ [ ] 500 Can't connect to www.slideshare.net:443 http://www.slideshare.net/olvemaudal/deep-c
+ [ ] 404 Not Found http://underscore.io/books/advanced-scala/

free-programming-books-it.md
+ [ ] 500 Can't connect to www.perl.it:80 http://www.perl.it/documenti/articoli/mb_corso_perl/mb_corso_perl.pdf

**Comment by eshellman** [comment]
I think the -es broken links are fixed in #2635; it's just waiting for a few tweaks.

**Comment by DpdC** [comment]
free-programming-books-es.md

500 Can't connect to www.decom-uv.cl:80 [http://www.decom-uv.cl/~roberto/apuntes/java/AprendiendoJava.pdf](http://www.decom-uv.cl/~roberto/apuntes/java/AprendiendoJava.pdf) 
--------------
Not found and nor is a similar or related document found with it. :sweat: 

I m remove it. :blush:
