### ISSUE TITLE
New Python Book 

### ISSUE THREAD

**Issue by H3li0** [EbookFoundation/free-programming-books#2685]
Could someone please add this link?

http://books.goalkicker.com/PythonBook/

I am not familiar with GIT.

Thanks in advance,

**Comment by polyzen** [comment]
https://help.github.com/articles/editing-files-in-another-user-s-repository/

**Comment by gauravwfh** [comment]
Good resource.

**Comment by sstt011** [comment]
This link is already added. Someone please close
