### ISSUE TITLE
no bengali books found

### ISSUE THREAD

**Issue by sh1hab** [EbookFoundation/free-programming-books#2704]
there are  not any Bengali books here so i was just want to add one . here is [one ](https://downloadpdfbooks-free.blogspot.com/2017/04/download-computer-programming-book-pdf.html) it is absolutely  free . It is written on c programming language

**Comment by eshellman** [comment]
You are more than welcome to submit a PR starting a free-programming-books-bl.md page. However, the link you give would be characterized as a file-sharing site, and it's not clear that the site is authorized by the author or publisher. Put the book on internet archive if you believe redistribution is authorized.

**Comment by eshellman** [comment]
it appears to be really free - http://cpbook.subeen.com/p/blog-page.html and eligible to be hosted on internet archive.

**Comment by eshellman** [comment]
Thanks for #2705 and #2708
