### ISSUE TITLE
Join to translation English to Indonesian 

### ISSUE THREAD

**Issue by rabooe** [EbookFoundation/free-programming-books#2723]
hello Mr., I am a translator, I want to translate English into Indonesian, Because the majority of Indonesian people do not understand English

**Comment by eshellman** [comment]
we have a small number of indonesian books on free-programming-books-id.md and would welcome additions to that page that would help indonesian readers.

**Comment by rabooe** [comment]
Thank-you ser,  I will give my best

**Comment by ha-yi** [comment]
is it ok to add new link to any tutorial or books that use Indonesian languages?

**Comment by eshellman** [comment]
@ha-yi as long as they're free - see CONTRIBUTING.md

**Comment by ha-yi** [comment]
nice,,,
