### ISSUE TITLE
Policies

### ISSUE THREAD

**Issue by fosslinux** [EbookFoundation/free-programming-books#2756]
Thank you for this amazing project!

I have a few questions about general formatting that are **not** answered in CONTRIBUTING.md.

1. If it is a PDF, do we link directly to the PDF or to a website that has a link to the PDF? 
2. When there are multiple formats, but they are all available from the same website as the main one, do we just not provide a URL?
3. And what do we do when there are three or more formats (e.g. HTML, PDF and EPUB), and there are three different URL's, how do we indicate this?

Please could this be added to CONTRIBUTING. Thank you!

**Comment by sstt011** [comment]
Unfortunately I will not be able to respond over the next three days. I will reply as soon as I can.

**Comment by eshellman** [comment]
Good questions, they're touched on in the CONTRIBUTING, but it could be better. Please make a PR if you have suggestions.

1. If there's a web page specifically about the book, that has a link to the PDF, link to the page. if not, link to the pdf.
2. If there's a web page that links to multiple formats, link to that page.
3. [title](link1) - Author Name (format1) [(format2)](link2) [(format3)](link3)

**Comment by sstt011** [comment]
And another question:

4. Is it preferred to use the direct link (i.e. no 301 redirects) or the shorter link?

Thanks!

**Comment by eshellman** [comment]
we don't want link shortener links, or cloaked links, but redirects are ok if they make sense. Links that resolve to "file sharing sites" are not generally permitted.

**Comment by eshellman** [comment]
answers moved to Wiki
