### ISSUE TITLE
Add a qulity content

### ISSUE THREAD

**Issue by InCogNiTo124** [EbookFoundation/free-programming-books#2810]
I skimmed on a list of book on C and I realized a very good book is not on the list. The public url is: http://books.goalkicker.com/CBook/ it is the C Notes for Proffesionals, almost 400 pages of tips and tricks, all compiled from answers on StackOverflow. A great read, indeed, and it's published with Creative Commons license. I request an addition of the book.

**Comment by harrykar** [comment]
Actually exist -> [C Notes](https://goalkicker.com/CBook) (PDF) hence issue can be closed
