### ISSUE TITLE
Free Kindle books?

### ISSUE THREAD

**Issue by OgreZed** [EbookFoundation/free-programming-books#2921]
How about searches for free Kindle books on Amazon? For example:

- Python -- https://www.amazon.com/s?field-price=0-0&sort=review-rank&lo=digital-text&rh=n:6361574011,p_20:English&page=
- JavaScript -- https://www.amazon.com/s?field-price=0-0&sort=review-rank&lo=digital-text&rh=n:16977271011,p_20:English&page=
- Visual Basic -- https://www.amazon.com/s?field-price=0-0&sort=review-rank&lo=digital-text&rh=n:16977277011,p_20:English&page=

**Comment by moposx** [comment]
Hello bro, these links all have broken up, and are they free of charge indeed?

**Comment by eshellman** [comment]
@moposx do you mean the links are broken for you in China?

**Comment by OgreZed** [comment]
@moposx Not sure what you mean by broken up. They look fine to me? The "field-price=0-0" parameter in the URL is supposed to tell Amazon to only display items that are between $0 and $0.

**Comment by antonio-gil** [comment]
@eshellman , @OgreZed , @moposx , I can confirm that the links aren't broken. At least not in México.

**Comment by moposx** [comment]
@eshellman  Yes, no any matches are gotten as I access it in China. 
@OgreZed @antonio-gil I got this after several fruitless trials: 
![image](https://user-images.githubusercontent.com/15135544/44460835-2ba32f80-a641-11e8-8a0b-170be8d026de.png)
But with a US's proxy I can get those books shown on site page. Seems to be a regional restriction.
