### ISSUE TITLE
Link has gone :(

### ISSUE THREAD

**Issue by baegii** [EbookFoundation/free-programming-books#2945]
http://kr.discovermeteor.com/ has been dead website
which was korean meteor document

**Comment by eshellman** [comment]
could you submit a PR?

**Comment by borgified** [comment]
site's gone but maybe you can still get what you need from here: https://github.com/DiscoverMeteor/DiscoverMeteor_Kr

**Comment by baegii** [comment]
@borgified Oh thanks
@eshellman I don't have much time to PR sorry
