### ISSUE TITLE
"Programming in C" is broken

### ISSUE THREAD

**Issue by olaven** [EbookFoundation/free-programming-books#2947]
The link to "Programming in C" does not work. 
http://ee.hawaii.edu/content.php?pag=11

**Comment by olaven** [comment]
@eshellman I was not able to find the book.

**Comment by eshellman** [comment]
We'll need to remove it

**Comment by olaven** [comment]
Went to remove it, but the link lead me to a book now.

Closing as the issue is not relevant any more.

**Comment by eshellman** [comment]
Thanks for pursuing it!
