### ISSUE TITLE
(Java section) Object-Oriented vs. Functional Programming don't work

### ISSUE THREAD

**Issue by harrykar** [EbookFoundation/free-programming-books#2990]
For your information 
In Java section 
[Object-Oriented vs. Functional Programming](http://www.oreilly.com/programming/free/object-oriented-vs-functional-programming.cspl)'s  distribution seems not work i haven't yet received any mail with download link as they(oreilly) say

PS : 
You refer: _(email address requested, not required)_ That's not correct i had to provide my email address bot being able to press the download button and they 
"respond"  
Thank you.
Enjoy this free ebook from O’Reilly Media. Check your email for a link to download.

**Comment by harrykar** [comment]
I have found it here 
http://www.r-5.org/files/books/computers/languages/java/scala/Richard_Warburton-Object-Oriented_vs_Functional_Programming-EN.pdf

**Comment by eshellman** [comment]
If O'Reilly books require a working email, we may need to remove the listings.

**Comment by ShipsWithCannons** [comment]
The page currently 404's. So in this case, the link will have to be removed regardless.

**Comment by bluetata** [comment]
@harrykar posted a wrong link for the book, In our repo the book link is http://www.oreilly.com/programming/free/object-oriented-vs-functional-programming.csp   

**For** the book link in our repo. I provided my email address, then   

![image](https://user-images.githubusercontent.com/25427352/50872378-6b08c780-13fa-11e9-997c-ce2fa6388600.png)
![image](https://user-images.githubusercontent.com/25427352/50872384-70fea880-13fa-11e9-89b1-8f13f7955a88.png)

**BUT** I haven't also received any mail with download link - -! Does anyone else have the same problem as me?

**Comment by pritam-patil** [comment]
Hi guys, I've updated the .csp link from oreilly.com to a .pdf link where it's free and contains right content. Do review [this PR](https://github.com/EbookFoundation/free-programming-books/pull/3423).

And thank you for creating and maintaining this repo!
