### ISSUE TITLE
 Java: The Legend Past, Present, and Future

### ISSUE THREAD

**Issue by harrykar** [EbookFoundation/free-programming-books#2992]
As all the free oreilly books here i had just referred  that one also not works (no email with download link email me ever from oreily)

**Comment by harrykar** [comment]
found it here 
http://pepa.holla.cz/wp-content/uploads/2016/10/java-the-legend.pdf

**Comment by eshellman** [comment]
take a look at CONTRIBUTING.md

**Comment by ShipsWithCannons** [comment]
That link works, but it's likely an illegal mirror.

**Comment by eshellman** [comment]
should remove link
