### ISSUE TITLE
the black art of programming by mcilroy mark

### ISSUE THREAD

**Issue by harrykar** [EbookFoundation/free-programming-books#2993]
http://self.gutenberg.org/wplbn0002828847-the-black-art-of-programming-by-mcilroy-mark.aspx?

**Comment by harrykar** [comment]
That's 
A guide to computer programming. 
Covers the basic material from a Computer Science course.

where fit here ? I guess  Theoretical Computer Science section is not bad

**Comment by harrykar** [comment]
that seems to be the same with that one: 
http://self.gutenberg.org/eBooks/WPLBN0004102338-Introduction-to-Computer-Science-by-McIlroy-Mark.aspx?

> Description
> This book is an introduction to Computer Science and the craft of computer programming. It contains the basic information from a first-year Computer Science course.

Where in the catalog fit better?  maybe in Theoretical Computer Science section? the book is a practical one and language agnostic

**Comment by bluetata** [comment]
@harrykar I will put the book into Theoretical Computer Science section. If it's a mistake you can change it

**Comment by charlottetan** [comment]
this issue has already been fixed, should be closed
