### ISSUE TITLE
Concepts, Techniques, and Models of Computer Programming

### ISSUE THREAD

**Issue by harrykar** [EbookFoundation/free-programming-books#2994]
https://www.info.ucl.ac.be/~pvr/book.html

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.102.7366&rep=rep1&type=pdf

**Comment by harrykar** [comment]
Draft version
https://www.sics.se/~seif/DatalogiII/Book/datalogiII.pdf

**Comment by GintasS** [comment]
I'm going to take this one.

**Comment by GintasS** [comment]
#4144
