### ISSUE TITLE
 A New Kind of Science by Stephen Wolfram 

### ISSUE THREAD

**Issue by harrykar** [EbookFoundation/free-programming-books#2997]
(only online reading)
http://www.wolframscience.com/nks/

**Comment by bluetata** [comment]
The book [A New Kind of Science] is a duplicate with Cellular Automata section

**Comment by will168** [comment]
Please unsubscribe me from your mailing list.

Thanks,
William

**Comment by charlottetan** [comment]
already exists, this issue should be closed
