### ISSUE TITLE
The Scheme Programming Language  Fourth Edition

### ISSUE THREAD

**Issue by harrykar** [EbookFoundation/free-programming-books#3001]
(only online the free version)
https://www.scheme.com/tspl4/

**Comment by charlottetan** [comment]
Already exists https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books.md#scheme

**Comment by charlottetan** [comment]
Already exists - https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books.md#scheme

**Comment by eshellman** [comment]
Thanks, @charlottetan !
