### ISSUE TITLE
Anatomy of Programming Languages

### ISSUE THREAD

**Issue by harrykar** [EbookFoundation/free-programming-books#3006]
http://www.cs.utexas.edu/~wcook/anatomy/

**Comment by harrykar** [comment]
William Cook
UT Austin Computer Science

**Comment by eshellman** [comment]
Can we close the issue?

**Comment by harrykar** [comment]
Absolutely yes

**Comment by eshellman** [comment]
You should be able to close issues that you've opened.

**Comment by harrykar** [comment]
> You should be able to close issues that you've opened.

LOL i don't get it the first time sorry about that and thanks for the hint :+1:  little a little i start "take hand" on  how things work here
