### ISSUE TITLE
Java, Java, Java Object-Oriented Problem Solving by R. Morelli and R.Walde

### ISSUE THREAD

**Issue by harrykar** [EbookFoundation/free-programming-books#3011]
https://archive.org/details/JavaJavaJavaObject-orientedProblemSolving/page/n0

**Comment by harrykar** [comment]
why that link is not parsed correctly (mean  appear "strange" with makdown)?
[Java, Java, Java Object-Oriented Problem Solving] (https://archive.org/details/JavaJavaJavaObject-orientedProblemSolving/page/n0) - R. Morelli and R.Walde

**Comment by eshellman** [comment]
yes. sorry I missed that issue!

**Comment by harrykar** [comment]
I'm  correcting it in the next PR thanks
