### ISSUE TITLE
Web application hacking and penetration testing free book

### ISSUE THREAD

**Issue by Tlalanne** [EbookFoundation/free-programming-books#3016]
I noticed that there's not many books on hacking. especially web hacking and penetration testing. is it possible to have a link to a recommended beginner to expert copy?

**Comment by w0rmr1d3r** [comment]
Here you have a list of cybersec repos:
https://github.com/Hacker0x01/hacker101
https://github.com/jwasham/coding-interview-university#computer-security
https://github.com/enaqx/awesome-pentest
https://github.com/bcncybersecurity

More cool related repos:
https://github.com/fightforthefuture/idl-members
https://github.com/TheTorProject/gettorbrowser
https://github.com/pi-hole/pi-hole
https://github.com/mozilla/addon-wr
https://github.com/jarv/cmdchallenge
https://github.com/berzerk0/Probable-Wordlists

**Comment by harrykar** [comment]
@Tlalanne
For what you aspire you have to manage almost a bit google no?! :) 
Anyway take a look here to take a bird eye's view 
https://www.cyberdegrees.org/jobs/penetration-tester/
My recommendation is to search in Universities/Colleges sites and related courses for available texts  about that interdisciplinary specialty

**Comment by Tlalanne** [comment]
@harryKar I have, but GitHub have been super precise and helpful in that area. 
Thanks for your recommendation .
