### ISSUE TITLE
add PHPUnit Russian manual to free-programming-books-ru.md

### ISSUE THREAD

**Issue by fey** [EbookFoundation/free-programming-books#3020]
Hello, please add to
[free-programming-books-ru.md php section](https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books-ru.md#php)
https://phpunit.readthedocs.io/ru/latest/
 * [Руководство по PHPUnit на русском языке](https://phpunit.readthedocs.io/ru/latest/)

**Comment by jVirus** [comment]
As a native Russian language speaker, I must say that the provided materials are indeed legit and are directly related to the topic of the repository. @eshellman if you need any help with Russian language, please don't hesitate and just let me know 😉

**Comment by eshellman** [comment]
@jVirus Thanks, always appreciate expert opinion. Added PR requested label.

**Comment by fey** [comment]
Pull Request
https://github.com/EbookFoundation/free-programming-books/pull/3028

**Comment by eshellman** [comment]
PR merged!
