### ISSUE TITLE
Recommendations from contributors

### ISSUE THREAD

**Issue by alcole** [EbookFoundation/free-programming-books#3053]
I have been thinking about this repo and the wider project. It is easy to understand an analogue with a library or a bookstore. When I go to my local library I often look at the themed displays put together by the librarians and thought this could be something that could be added to this project in some way. There are a lot of resources on offer, so some context might help beginners (or could be interesting in its own right?). The contributors must be incentivised by passion and interest to be willing to contribute so may have some interesting background and insight to share. We could accept contributions from contributors (or even ‘big names’ or academics) where they recommend and describe their favourite resources listed in the repository. 
This could be by theme, eg beginner in Java / Mobile / web dev etc. or by contributor’s favourites.

**Comment by harrykar** [comment]
> I have been thinking about this repo and the wider project. It is easy to understand an analogue with a library or a bookstore. When I go to my local library I often look at the themed displays put together by the librarians and thought this could be something that could be added to this project in some way.
Hi @alcole i'm also new here. In (small) real libraries I really not notice themes but nevertheless your idea is a valid one and was my idea too and i try implement it(as a first try) [here](https://coderanch.com/wiki/660152/Find-Links-Free-Stuff#3062738)   
The main problem i experienced was the review of any text and the critical thinking --must not based in your actual knowledge but on that of the themed probable user that's a difficult task--.  on what category (theme) include a text.
Dunno exactly what the organization is here i meet only the good @eshellman maybe he can put light on that
I guess that work requires a set of people(contibutors) apart that have to do only that work (read texts and categorize-theme them properly  that as i mentioned is not a trivial work)
  
>There are a lot of resources on offer, so some context might help beginners (or could be interesting in its own right?). 
We agree and add not only beginners but help everyone find more easily what he search  

>The contributors must be incentivised by passion and interest to be willing to contribute so may have some interesting background and insight to share. We could accept contributions from contributors (or even ‘big names’ or academics) where they recommend and describe their favourite resources listed in the repository.

That's(about accademics) a good option another one would be e.g. follow a vote system in which contributors vote (like in [goodreads](https://www.goodreads.com/list/show/8379.Software_Craftsmanship)) on the texts they have read or studied or already start study 
However as i mentioned theming is a loose(mean not precise) at times subjective property and for that is a bit difficult
Another point is reviewers have to be people on the field mean CS CE(ngineering) etc
   
> This could be by theme, eg beginner in Java / Mobile / web dev etc. or by contributor’s favourites.

exactly
