### ISSUE TITLE
how can i dintinguish if a book distributed by an accredited institution (Uni) is suited to include in the list?

### ISSUE THREAD

**Issue by harrykar** [EbookFoundation/free-programming-books#3055]
Yesterday a friend of mine signaling me [a bunch of valuable texts](http://aleteya.cs.buap.mx/~jlavalle/papers/books_on_line/) distributed from a Mexican Uni [BENEMÉRITA UNIVERSIDAD AUTÓNOMA DE PUEBLA](http://aleteya.cs.buap.mx/) i see some texts are McGrawHill, Addison wesley, MIT press, Cambrige Uni press etc  I wonder if are they open or anyway suitable to include in list?

**Comment by harrykar** [comment]
Another one related question : in issue #2994 I used [citesheer](http://csxstatic.ist.psu.edu/home) engine to find the book it's ok?

**Comment by eshellman** [comment]
1. We do not include links to unauthorized or unlicensed distributions.
2. Citeseer is a great index to the computer science literature, but being indexed in citeseer is not determinative whether we would include something.

**Comment by harrykar** [comment]
> We do not include links to unauthorized or unlicensed distributions.
That's a nice statement but for us "common Joe's" what mean that? to whom we must give confidence? e.g. A Uni is an legal/authorized/licensed distribution? 

>     Citeseer is a great index to the computer science literature, but being indexed in citeseer is not determinative whether we would include something.

That's has to do with my question above: So in our specific use case(book) what we have to do?

**Comment by eshellman** [comment]
If there's a link from the author's academic homepage, that's a good indication that the distribution is authorized. Sometimes an academic will post a link on a page meant only for a class, not realizing its open to the world, so the fact that a link is on an academic site is also not determinative.

There are 3 links in #2994 so it's not clear what your question is about. In general, it's best to use a PR to propose a new link, so the context is clear - you might have additional links that support the new link, it's provenenance or licensing. If you use an issue, the connection to the commit gets lost and a year from now we might be scratching our heads about why a decision was made.

**Comment by harrykar** [comment]
> If there's a link from the author's academic homepage, that's a good indication that the distribution is authorized. 

Got it -> Author (the Knowledge's source) has the very precedence right? 

> Sometimes an academic will post a link on a page meant only for a class, not realizing its open to the world, so the fact that a link is on an academic site is also not determinative.

I doubt about an academic nowadays not be acknowledged is (s)he he open to world Vs to a class. And anyway i don't understand the author's  rationale behind "open only for a class" seems to me rather egoistic   
 
> There are 3 links in #2994 so it's not clear what your question is about. 

Indeed you open them ? Nevermind i repeat it here
the book at hand(propose to include in list) is: https://www.info.ucl.ac.be/~pvr/book.html
I found it in two different places and in two different editions 
1.(seems the final edition) http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.102.7366&rep=rep1&type=pdf
2. (first draft edition with fewer pages): https://www.sics.se/~seif/DatalogiII/Book/datalogiII.pdf
Can you decide if can be included in list and in case in what version?

>In general, it's best to use a PR to propose a new link, so the context is clear - you might have additional links that support the new link, it's provenenance or licensing. If you use an issue, the connection to the commit gets lost and a year from now we might be scratching our heads about why a decision was made.

Mmh as i understand from your words here take repos history one of the valuable(other than core content) of a repo right? 
I was convinced all in Github were connected  --> take history for all stuff wiki- issues-blog - whatever. Are you sure about ...the connection to the commit gets lost.." ? In my last commit i remember i put the "closes #issue" in commits message to close the issue automatically after your merge and worked. So issues are connected to commits(repo's history)  no?

**Comment by eshellman** [comment]
As to Van Roy & Haridi - the CiteSeer version is a cache from a site that has removed the original; neither van Roy or Haridi link to the pdf on their home pages, so it's not clear. I suggest you email the authors for clarification.

**Comment by harrykar** [comment]
For that text(IMO is really valuable) i take the hassle to do it ;) .
What about my other questions in PS?

**Comment by eshellman** [comment]
1. use the PR template
2. PR docs are in GH, not the git repo
3. Clearly written documentaion is always welcome. The trick is to keep it short enough so folks actually read it.

**Comment by harrykar** [comment]
> As to Van Roy & Haridi - the CiteSeer version is a cache from a site that has removed the original; neither van Roy or Haridi link to the pdf on their home pages, so it's not clear. 

How you you have discovered is in cache instead of  original and know the original is removed? 

>I suggest you email the authors for clarification.

For that text(IMO is really valuable) i take the hassle to do it ;) .
What about my other questions in PS?

**Comment by harrykar** [comment]
> use the PR template.

so ican use directly Github's  PR template without touching my local repo? so far i did a PR only as a change on my local repo 

>     PR docs are in GH, not the git repo

If you mean PR's history is recorded in Githubs repo and not in our local repo we agree;  you meant that? 

>     Clearly written documentaion is always welcome. The trick is to keep it short enough so folks actually read it.

About the trick I realized it in my first draft (have to finish it yet but dunno when) on Git's CLI isage in wiki

**Comment by eshellman** [comment]
http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.102.7366&rank=3&q=Peter%20Van%20Roy%20and%20Seif%20Haridi&osm=&ossid=

**Comment by harrykar** [comment]
Parsing that link all i can get is the text is somewhere in a DBMS and nothing else is that you mean cache? and from where citesheer get his content? i don't guess from illegal addresses or not?

**Comment by eshellman** [comment]
Citeseer is like Google - it's too big and indexes too many resources to be able to check the status of everything it finds.
