### ISSUE TITLE
Reminder on open resources found casually 

### ISSUE THREAD

**Issue by harrykar** [EbookFoundation/free-programming-books#3056]
https://openstax.org/subjects

**Comment by harrykar** [comment]
Draft version
https://www.sics.se/~seif/DatalogiII/Book/datalogiII.pdf

**Comment by eshellman** [comment]
openstax textbooks are generally excellent.

**Comment by harrykar** [comment]
> openstax textbooks are generally excellent.

good to know but there aren't CS texts maybe here we've to open another one broader book's category?

**Comment by eshellman** [comment]
There's a parallel repo for science books
https://github.com/EbookFoundation/free-science-books

**Comment by harrykar** [comment]
What a dumb am I? was "in house". Ok by the way can you delight me here how  is the organizzation of EbookFoundation - free-science-books - free-other - books etc?
I see only you here are a your initiative ? are you alone  ? what's your role (other than an integrator) etc

**Comment by eshellman** [comment]
https://ebookfoundation.org

**Comment by harrykar** [comment]
That one seems a promising source on open learning movement https://hewlett.org/strategy/open-educational-resources/ ; you know something about @eshellman ?

**Comment by eshellman** [comment]
Hewlett has been funding plenty of good work.

**Comment by harrykar** [comment]
[For the First Time in More Than 20 Years, Copyrighted Works Will Enter the Public Domain](https://www.smithsonianmag.com/arts-culture/first-time-20-years-copyrighted-works-enter-public-domain-180971016/?utm_source=quora&utm_medium=referral)

**Comment by harrykar** [comment]
[For the First Time in More Than 20 Years, Copyrighted Works Will Enter the Public Domain](https://www.smithsonianmag.com/arts-culture/first-time-20-years-copyrighted-works-enter-public-domain-180971016/?utm_source=quora&utm_medium=referral)
