### ISSUE TITLE
Just some thougths ...

### ISSUE THREAD

**Issue by harrykar** [EbookFoundation/free-programming-books#3061]
As i can understand so far here we've piled a collection  of  (elementary) categorized books on IT field and that's an awesome resource itself no doubt. So one who know what to do comes here access the book of interest and go ahead happy   

But what if we go in a higher abstraction mean consider the use case(i have meet some) of a person that pursue to follow a IT,CS,CE path and haven't the economic power to afford his/her studies(case of stop knowledge/growth cause economic issues)? In that frequent use case what we have to do? 

I guess  the very first step were to define directions required to cope with everyone of the aforementioned paths(as institutions do). Then  put some effort to categorize properly(into the aforementioned paths ) the already existed material other than find other new too ...

PS : that issue is somehow connected with #3053

**Comment by eshellman** [comment]
use #3053 for this discussion. Thanks.
