### ISSUE TITLE
“Linkers and Loaders” contains only dead links

### ISSUE THREAD

**Issue by dilyanpalauzov** [EbookFoundation/free-programming-books#3091]
Language Agnostic → Compiler Design → “Linkers and Loaders - John R. Levine” points to https://www.iecc.com/linker/ but the latter contains only dead links.

**Comment by eshellman** [comment]
Should be removed. Can you submit a PR?

**Comment by dilyanpalauzov** [comment]
No

**Comment by bluetata** [comment]
@dilyanpalauzov I think you should be use a **proxy** to visit the ebook link

![image](https://user-images.githubusercontent.com/25427352/50323594-5630c680-0515-11e9-8f1c-36089d8d664d.png)
![image](https://user-images.githubusercontent.com/25427352/50323605-5d57d480-0515-11e9-9709-8f4a227c29a4.png)
![image](https://user-images.githubusercontent.com/25427352/50323610-62b51f00-0515-11e9-8d74-06a1f98ee17b.png)

**Comment by bluetata** [comment]
@dilyanpalauzov I think you should be use a **proxy** to visit the ebook link

![image](https://user-images.githubusercontent.com/25427352/50323594-5630c680-0515-11e9-8f1c-36089d8d664d.png)
![image](https://user-images.githubusercontent.com/25427352/50323605-5d57d480-0515-11e9-9709-8f4a227c29a4.png)
![image](https://user-images.githubusercontent.com/25427352/50323610-62b51f00-0515-11e9-8d74-06a1f98ee17b.png)

Actually some ref links are dead link(tet, rtf file link), but the html link can be redirect to the site which  looks nomarl.

![image](https://user-images.githubusercontent.com/25427352/50324123-26cf8900-0518-11e9-884a-896e51236c62.png)

![image](https://user-images.githubusercontent.com/25427352/50323898-f63b1f80-0516-11e9-9a49-af6259e82b03.png)

**Comment by dilyanpalauzov** [comment]
Some links indeed work, but most of them are dead.  E.g. https://www.iecc.com/linker/linker01.html works and https://www.iecc.com/linker/linker02.html is invalid.  Under these circumstances referencing the source is not good — the user has to click a lot only to find out, that most of the information is missing.
