### ISSUE TITLE
The Road to Learn React [pt-br]

### ISSUE THREAD

**Issue by Rahmon** [EbookFoundation/free-programming-books#3110]
Hi.

There is a translate available for the book The Road to Learn React. So it would be cool if it was added to section React in pt-br page.

Link to the book: https://leanpub.com/the-road-to-learn-react-portuguese

**Comment by eshellman** [comment]
PR requested. An access note (see CONTRIBUTING) would be needed for this.

**Comment by bluetata** [comment]
You can open a PR to try to add the book to this repo.
