### ISSUE TITLE
A suggest to our lint

### ISSUE THREAD

**Issue by zhongjiajie** [EbookFoundation/free-programming-books#3115]
I just submit a [pr](https://github.com/EbookFoundation/free-programming-books/pull/3114) to this repo, I think we should add this rule to [our lint](https://github.com/vhf/free-programming-books-lint), but I am not a javascript programmer. So I add issue to seek someone who can do this

**Comment by zhongjiajie** [comment]
> The downside is people will abandon a PR because the linter fails. So yes, it's an improvement to remove the space, but it can be accomplished with a periodic cleanup PR such as the one I just merged.

so, you think the bot could fix minor errors in need, like [this iuuse](https://github.com/EbookFoundation/free-programming-books/issues/2672)?

**Comment by eshellman** [comment]
Yes!

**Comment by borgified** [comment]
@eshellman can you sign us up for github actions beta, there may be some automation there that could help us with this. https://github.com/features/actions

**Comment by eshellman** [comment]
done
