### ISSUE TITLE
Course / screencast question

### ISSUE THREAD

**Issue by MrS4w** [EbookFoundation/free-programming-books#3127]
Can I add links to courses/screencasts from platforms like Udemy since it is for free?

**Comment by eshellman** [comment]
I haven't looked at udemy specifically, but we have included one udemy course. 

If a registration is required for viewing, that should be noted in the listing.

**Comment by MrS4w** [comment]
Observed by something in parentheses or something similar or annotated in PR?

**Comment by eshellman** [comment]
take a look at CONTRIBUTING
