### ISSUE TITLE
Correct Spelling of HTML

### ISSUE THREAD

**Issue by verkiya** [EbookFoundation/free-programming-books#3129]
Kindly Correct Spelling of HTML on this page
https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books-ro.md

![image](https://user-images.githubusercontent.com/34170205/52334221-2dad4f00-2a25-11e9-9cef-3840cd909d28.png)

**Comment by eshellman** [comment]
PR definitely requested!

**Comment by Verkiya** [comment]
Thanks, @eshellman sir. Created a PR. 👍

**Comment by bluetata** [comment]
> 
> 
> Thanks, @eshellman sir. Created a PR. +1

@verkiya you can update your PR as [Review](https://github.com/EbookFoundation/free-programming-books/pull/3130#pullrequestreview-206217692)

**Comment by verkiya** [comment]
> @verkiya you can update your PR as [Review](https://github.com/EbookFoundation/free-programming-books/pull/3130#pullrequestreview-206217692)
Could you please check whether I did it correctly?

**Comment by bluetata** [comment]
> > @verkiya you can update your PR as [Review](https://github.com/EbookFoundation/free-programming-books/pull/3130#pullrequestreview-206217692)
> > @bluetata, please check whether I did it correctly?

thanks @verkiya ,I think now it is correct 👍
