### ISSUE TITLE
Broken Link: High Performance Python (PDF) link is broken

### ISSUE THREAD

**Issue by emres** [EbookFoundation/free-programming-books#3132]
High Performance Python (PDF) link is broken. The URL https://ianozsvald.com/HighPerformancePythonfromTrainingatEuroPython2011_v0.2.pdf returns `404` error.

**Comment by eshellman** [comment]
Another O'Reilly title going dark. PR requested.

**Comment by charlottetan** [comment]
seems like this has already been addressed, title no longer exists in code base, issue should be closed
