### ISSUE TITLE
The Current C Programming Language Standard – ISO/IEC 9899:2018 (C18)

### ISSUE THREAD

**Issue by kaleemullah360** [EbookFoundation/free-programming-books#3189]
**The Current C Programming Language Standard – ISO/IEC 9899:2018 (C18)**

[PDF link](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2310.pdf)

**Comment by eshellman** [comment]
good idea, but I wonder if there's a link that doesn't need changing after every revision.

**Comment by przemoc** [comment]
The link provided by OP is not a draft of the current C standard (C17/C18), but draft of the WIP version of future one (C2x). Well, it has diff marks, so it can be kind of used for C17/C18 too, but it would be rather inconvenient (and could confuse beginners).

---

C17/C18 has almost no language changes over C11 (sans obsoleted `ATOMIC_VAR_INIT` macro), but many improvements addressing several dozen DRs (e.g. [DR404][2] related to joke about atomic variables) as can be seen in [Clarification Request Summary for C11 Version 1.13][3], overviewed by Jens Gustedt's blog post titled [C17][4].

The most recent freely available draft of C17/C18 used to be [c17_updated_proposed_fdis.pdf][5], but it's no longer available directly and you need to use Wayback Machine to download [it][6]. Header of this document has N2176, and there is indeed N2176 mentioned in [WG14 Document Log][7], but it's a password protected PDF.

[2]: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2244.htm#dr_404
[3]: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2244.htm
[4]: https://gustedt.wordpress.com/2018/04/17/c17/
[5]: http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf
[6]: https://web.archive.org/web/20180118051003/http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf
[7]: http://www.open-std.org/jtc1/sc22/wg14/www/wg14_document_log.htm

**Comment by eshellman** [comment]
@przemoc what do recommend that we do?

**Comment by kaleemullah360** [comment]
If we remove word **n2310.pdf** from [URL](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2310.pdf), a [repository](http://www.open-std.org/jtc1/sc22/wg14/www/docs/) that contains more PDF is found. which means this link won't die, and would have future releases too. I guess.

Repository

[http://www.open-std.org/jtc1/sc22/wg14/www/docs/](http://www.open-std.org/jtc1/sc22/wg14/www/docs/)
[http://www.open-std.org/jtc1/sc22/wg14/www/](http://www.open-std.org/jtc1/sc22/wg14/www/)
[http://www.open-std.org/jtc1/sc22/wg14/](http://www.open-std.org/jtc1/sc22/wg14/)

**Comment by charlottetan** [comment]
seems like already addressed, should be closed

**Comment by TSlivede** [comment]
@przemoc 
[Your (non webarchive) link](http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf) for c17_updated_proposed_fdis.pdf almost works - just replace `www` with `www2` 🙂

This link does currently work:
http://www2.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf

**Comment by GintasS** [comment]
@eshellman @TSlivede this link does not work too.

**Comment by kaleemullah360** [comment]
@GintasS please use [this](https://web.archive.org/web/20181230041359if_/http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf) link

https://web.archive.org/web/20181230041359if_/http://www.open-std.org/jtc1/sc22/wg14/www/abq/c17_updated_proposed_fdis.pdf
