### ISSUE TITLE
Introduction to the COBOL language - No COBOL

### ISSUE THREAD

**Issue by NitroNils** [EbookFoundation/free-programming-books#3196]
Following the [Introduction to the COBOL Language](https://www.ibm.com/it-infrastructure/z/education#COBOL) does not lead to any obvious COBOL resources. I only see mainframe stuff (Firefox Lite on Android 6).

Did IBM move resource or did I miss somthing?

**Comment by cestith** [comment]
https://www.ibm.com/search?lang=en&cc=us&q=COBOL&tabType[0]=learning seems to find quite a few resources about COBOL for a start. I'm unsure which specifics resource or resources the PR was meant to surface. For that reason I'm not suggesting any particular edit to the PR and only hoping this URL is helpful in updating or correcting it.

**Comment by NitroNils** [comment]
Thank you, I don't know what I was missing — searching and your link gives plenty :)
