### ISSUE TITLE
Ссылка на книгу не работает. 

### ISSUE THREAD

**Issue by n37w1z** [EbookFoundation/free-programming-books#3220]
Особенности языка C. Учебное пособие - C. Шапошникова (PDF)
https://younglinux.info/%D1%81

**Comment by n37w1z** [comment]
ну то есть работает, но книги там нету =(

**Comment by eshellman** [comment]
I can't read the link

**Comment by n37w1z** [comment]
https://younglinux.info/c

**Comment by n37w1z** [comment]
ok, i got it, if you use this link https://younglinux.info/c, everything work fine, but I awlays redirect to this https://younglinux.info/%D1%81 ...
