### ISSUE TITLE
Failing links in free-programming-books.md HELP NEEDED!

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#3244]
Below is a list of failing links in free-programming-books.md
You can help improve this repo by resolving the problems.

A failing link may be a website or resource that has disappeared. You can submit a PR
+ removing the link (maybe the resource is obsolete.)
+ correcting the link (sometimes things move)
+ replacing the link (make sure the link is authorized, or the resource is open-licensed). Often a link to internet archive's wayback machine is useful.

Sometimes a link is only temporarily failing, or the site blocks link-checkers. If that's the case, leave a note on this issue.

In your PR, reference this issue.

Thanks for your help!

### Meta-Lists
+ [x] 404 Not Found http://codingus.blogspot.in [Codingus](http://codingus.blogspot.in)

#### Datamining
+ [ ] 503 Service Temporarily Unavailable http://schoolofdata.org/handbook/ [School of Data Handbook](http://schoolofdata.org/handbook/)

#### Machine Learning
+ [ ] 404 Not Found http://www.iro.umontreal.ca/~bengioy/papers/ftml_book.pdf [Learning Deep Architectures for AI](http://www.iro.umontreal.ca/~bengioy/papers/ftml_book.pdf) (PDF)

#### Mathematics
+ [ ] 500 Can't connect to www.ii.uib.no:80 (Connection timed out) http://www.ii.uib.no/~michal/und/i227/book/book.pdf [Mathematical Logic - an Introduction](http://www.ii.uib.no/~michal/und/i227/book/book.pdf) (PDF)

#### Parallel Programming
+ [ ] 404 Not Found https://us.fixstars.com/opencl/book/OpenCLProgrammingBook/contents/ [The OpenCL Programming Book](https://us.fixstars.com/opencl/book/OpenCLProgrammingBook/contents/)

#### Regular Expressions
+ [x] 404 Not Found http://regex.learncodethehardway.org/book/ [Learn Regex The Hard Way](http://regex.learncodethehardway.org/book/) - Zed. A. Shaw

#### Software Architecture
+ [ ] 404 Not Found http://www.computer.org/portal/web/swebok [Guide to the Software Engineering Body of Knowledge](http://www.computer.org/portal/web/swebok)

#### Theoretical Computer Science
+ [ ] 404 Not Found http://www.daimi.au.dk/~bra8130/Wiley_book/wiley.html [Semantics with Applications: A Formal Introduction](http://www.daimi.au.dk/~bra8130/Wiley_book/wiley.html) - Hanne Riis Nielson, Flemming Nielson

### Assembly Language
+ [ ] 500 Can't connect to mirror.unicorncloud.org:80 (Name or service not known) http://mirror.unicorncloud.org/savannah-nongnu//pgubook/ProgrammingGroundUp-1-0-booksize.pdf  [Programming from the Ground Up](http://mirror.unicorncloud.org/savannah-nongnu//pgubook/ProgrammingGroundUp-1-0-booksize.pdf) (PDF)
+ [ ] 403 Forbidden http://vendu.twodots.nl/wizardcode.html [Wizard Code](http://vendu.twodots.nl/wizardcode.html)

### C
+ [ ] 404 Not Found http://home.netcom.com/~tjensen/ptr/pointers.htm  [A Tutorial on Pointers and Arrays in C](http://home.netcom.com/~tjensen/ptr/pointers.htm) - Ted Jensen [(PDF, Zipped HTML)](http://pweb.netcom.com/~tjensen/ptr/cpoint.htm)
+ [ ] 404 Not Found http://pweb.netcom.com/~tjensen/ptr/cpoint.htm  [A Tutorial on Pointers and Arrays in C](http://home.netcom.com/~tjensen/ptr/pointers.htm) - Ted Jensen [(PDF, Zipped HTML)](http://pweb.netcom.com/~tjensen/ptr/cpoint.htm)

### Clojure
+ [ ] 500 Can't connect to daly.axiom-developer.org:80 (Connection timed out) http://daly.axiom-developer.org/clojure.pdf [Clojure in Small Pieces](http://daly.axiom-developer.org/clojure.pdf) - Rich Hickey (PDF)

### COBOL
+ [ ] 502 Bad Gateway http://yusman.staff.gunadarma.ac.id/Downloads/files/33460/COBOL_Programming_Fundamental.pdf [COBOL Programming Fundamental](http://yusman.staff.gunadarma.ac.id/Downloads/files/33460/COBOL_Programming_Fundamental.pdf) (PDF)

#### Phoenix
+ [ ] 500 Can't connect to elviovicosa.com:80 (Name or service not known) http://elviovicosa.com/books/versioned-apis-with-phoenix [Versioned APIs with Phoenix](http://elviovicosa.com/books/versioned-apis-with-phoenix) - Elvio Vicosa (PDF) *(account required)*

### F Sharp
+ [ ] 404 Not Found http://www.itu.dk/courses/BPRD/E2009/plcsd-1-2.pdf [Programming Language Concepts for Software Developers](http://www.itu.dk/courses/BPRD/E2009/plcsd-1-2.pdf) (PDF)

### HTML / CSS
+ [ ] 404 Not Found http://howtocodeinhtml.com [How to Code in HTML5 and CSS3](http://howtocodeinhtml.com)
+ [ ] 500 Can't connect to smacss.com:443 (LWP::Protocol::https::Socket: SSL connect attempt failed error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol) https://smacss.com [Scalable and Modular Architecture for CSS](https://smacss.com) - Jonathan Snook

### Icon
+ [ ] 404 Not Found http://www.cs.arizona.edu/icon/ibsale.htm [The Implementation of the Icon Programming Language](http://www.cs.arizona.edu/icon/ibsale.htm)

#### Angular.js
+ [ ] 500 Internal Server Error http://www.ng-newsletter.com/posts/angular-for-the-jquery-developer.html [Angular for the jQuery developer](http://www.ng-newsletter.com/posts/angular-for-the-jquery-developer.html)

### Maven
+ [ ] 403 Forbidden http://books.sonatype.com/m2eclipse-book/reference/ [Developing with Eclipse and Maven](http://books.sonatype.com/m2eclipse-book/reference/)

### Mercurial
+ [ ] 500 Can't connect to hginit.com:80 (No route to host) http://hginit.com [HGInit - Mercurial Tutorial by Joel Spolsky](http://hginit.com)

### Neo4J
+ [ ] 404 Not Found http://info.neotechnology.com/rs/neotechnology/images/GraphDatabases.pdf [Graph Databases](http://info.neotechnology.com/rs/neotechnology/images/GraphDatabases.pdf) (PDF)

### OpenMP
+ [ ] 500 Can't connect to bisqwit.iki.fi:80 (Connection timed out) http://bisqwit.iki.fi/story/howto/openmp/ [A Guide To OpenMP](http://bisqwit.iki.fi/story/howto/openmp/)

### Python
+ [ ] 500 Can't connect to python.net:80 (Connection refused) http://python.net/~goodger/projects/pycon/2007/idiomatic/handout.html [Code Like a Pythonista: Idiomatic Python](http://python.net/~goodger/projects/pycon/2007/idiomatic/handout.html)
+ [ ] 500 Status read failed: Connection reset by peer http://www.alan-g.me.uk [Learning to Program](http://www.alan-g.me.uk)
+ [ ] 403 Forbidden http://www.jython.org/jythonbook/en/1.0 [The Definitive Guide to Jython, Python for the Java Platform](http://www.jython.org/jythonbook/en/1.0) - Josh Juneau, Jim Baker, Victor Ng, Leo Soto, Frank Wierzbicki (2.5)
+ [ ] 500 Server closed connection without sending any data back http://mirnazim.org/writings/python-ecosystem-introduction/ [The Python Ecosystem: An Introduction](http://mirnazim.org/writings/python-ecosystem-introduction/)

#### Django
+ [ ] 500 Can't connect to www.effectivedjango.com:80 (Name or service not known) http://www.effectivedjango.com [Effective Django](http://www.effectivedjango.com) (1.5)

### Ruby
+ [ ] 500 Can't connect to www.learnruby.today:443 (timeout) https://www.learnruby.today [Learn Ruby First](https://www.learnruby.today) - Frederick John

#### Ruby on Rails
+ [ ] 500 Internal Server Error http://objectsonrails.com [Objects on Rails](http://objectsonrails.com)

### Swift
+ [ ] 404 Not Found https://itunes.apple.com/us/book/using-swift-cocoa-objective/id888894773?mt=11 [Using Swift with Cocoa and Objective-C](https://developer.apple.com/library/content//documentation/Swift/Conceptual/BuildingCocoaApps/index.html) (HTML) [(iBook)](https://itunes.apple.com/us/book/using-swift-cocoa-objective/id888894773?mt=11)

If you have comments about how these reports are presented, use issue #3233

**Comment by madebycollins** [comment]
Hello,

## The following services have now been restored:
- School of Data Handbook (http://schoolofdata.org/handbook/)
- Mathematical Logic - an Introduction (PDF) (http://www.ii.uib.no/~michal/und/i227/book/book.pdf)
- Clojure in Small Pieces (http://daly.axiom-developer.org/clojure.pdf)
- COBOL Programming Fundamental (PDF) (http://yusman.staff.gunadarma.ac.id/Downloads/files/33460/COBOL_Programming_Fundamental.pdf)
- A Guide To OpenMP (http://bisqwit.iki.fi/story/howto/openmp/)
- Learning to Program (http://www.alan-g.me.uk) ~ initially failed then loaded


## The following have moved:
- The OpenCL Programming Book (https://us.fixstars.com/opencl/book/OpenCLProgrammingBook/contents/) is now: https://us.fixstars.com/products/opencl/book/OpenCLProgrammingBook/contents/
- Learn Regex The Hard Way - Zed. A. Shaw( http://regex.learncodethehardway.org/book/)
is now https://learncodethehardway.org/regex/ (seems paid)

The rest are as you have said 💯

**Comment by charlottetan** [comment]
> ### Meta-Lists
> * [ ]  404 Not Found http://codingus.blogspot.in [Codingus](http://codingus.blogspot.in)

Permanently gone

> #### Datamining
> * [ ]  503 Service Temporarily Unavailable http://schoolofdata.org/handbook/ [School of Data Handbook](http://schoolofdata.org/handbook/)

Is working, redirects to https://schoolofdata.org/handbook/

> #### Machine Learning
> * [ ]  404 Not Found http://www.iro.umontreal.ca/~bengioy/papers/ftml_book.pdf [Learning Deep Architectures for AI](http://www.iro.umontreal.ca/~bengioy/papers/ftml_book.pdf) (PDF)

Already fixed, points to https://mila.quebec/wp-content/uploads/2019/08/TR1312.pdf

> #### Mathematics
> * [ ]  500 Can't connect to [www.ii.uib.no:80](http://www.ii.uib.no:80) (Connection timed out) http://www.ii.uib.no/~michal/und/i227/book/book.pdf [Mathematical Logic - an Introduction](http://www.ii.uib.no/~michal/und/i227/book/book.pdf) (PDF)

Link works

> #### Parallel Programming
> * [ ]  404 Not Found https://us.fixstars.com/opencl/book/OpenCLProgrammingBook/contents/ [The OpenCL Programming Book](https://us.fixstars.com/opencl/book/OpenCLProgrammingBook/contents/)

Already fixed, points to https://us.fixstars.com/products/opencl/book/OpenCLProgrammingBook/contents/

> #### Regular Expressions
> * [ ]  404 Not Found http://regex.learncodethehardway.org/book/ [Learn Regex The Hard Way](http://regex.learncodethehardway.org/book/) - Zed. A. Shaw

Appears to be no longer free like @madebycollins mentioned

> #### Software Architecture
> * [ ]  404 Not Found http://www.computer.org/portal/web/swebok [Guide to the Software Engineering Body of Knowledge](http://www.computer.org/portal/web/swebok)

Already removed

> #### Theoretical Computer Science
> * [ ]  404 Not Found http://www.daimi.au.dk/~bra8130/Wiley_book/wiley.html [Semantics with Applications: A Formal Introduction](http://www.daimi.au.dk/~bra8130/Wiley_book/wiley.html) - Hanne Riis Nielson, Flemming Nielson

Appears to be gone, copies exist online but unable to find a reliable source to link

Did not check the rest, submitted PR
