### ISSUE TITLE
Broken  pt_BR links HELP REQUESTED

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#3264]
Below is a list of failing links in our Portuguese lists
You can help improve this repo by resolving the problems.

A failing link may be a website or resource that has disappeared. You can submit a PR

+ removing the link (maybe the resource is obsolete.)
+ correcting the link (sometimes things move)
+ replacing the link (make sure the link is authorized, or the resource is open-licensed). Often a link to internet archive's wayback machine is useful.

Sometimes a link is only temporarily failing, or the site blocks link-checkers. If that's the case, leave a note on this issue.

In your PR, reference this issue.

Thanks for your help!

free-programming-books-pt_BR.md
+ [x] 404 Not Found http://ccsl.ime.usp.br/files/books/intro-java-cc.pdf
+ [x] 500 read timeout http://www.vedovelli.com.br/frontend/adicionar-bootstrap-e-font-awesome-no-projeto-criado-com-o-vue-cli/
+ [ ] 500 Can't connect to howtocode.com.br:80 (Name or service not known) http://howtocode.com.br/ebooks/ruby

**Comment by 4llan** [comment]
Didn't find any alternative to http://howtocode.com.br/ebooks/ruby. Sorry.

Contacted @vedovelli about the timeout in his site. If isn't a temporary issue, will add [Wayback Machine mirror](https://web.archive.org/web/20180613054310/http://www.vedovelli.com.br/frontend/adicionar-bootstrap-e-font-awesome-no-projeto-criado-com-o-vue-cli/) later
