### ISSUE TITLE
broken Farsi links HELP REQUESTED

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#3265]
Below is a list of failing links in our Farsi lists
You can help improve this repo by resolving the problems.

A failing link may be a website or resource that has disappeared. You can submit a PR

+ removing the link (maybe the resource is obsolete.)
+ correcting the link (sometimes things move)
+ replacing the link (make sure the link is authorized, or the resource is open-licensed). Often a link to internet archive's wayback machine is useful.

Sometimes a link is only temporarily failing, or the site blocks link-checkers. If that's the case, leave a note on this issue.

In your PR, reference this issue.

Thanks for your help!

free-programming-books-fa_IR.md
+ [ ] 500 Can't connect to agiledevelopment.ir:80 (Name or service not known) http://agiledevelopment.ir/ebook/
+ [ ] 500 Can't connect to docs.occc.ir:80 (Connection timed out) http://docs.occc.ir/books/Main%20Book-20110110_2.pdf
+ [ ] 500 Can't connect to linuxreview.ir:80 (Name or service not known) http://linuxreview.ir/archbook/ArchBook-2012-1.pdf

**Comment by spencer1573** [comment]
I'm going to look into this @eshellman

**Comment by spencer1573** [comment]
https://github.com/EbookFoundation/free-programming-books/pull/4067

**Comment by spencer1573** [comment]
new pull request for fixes here actually https://github.com/EbookFoundation/free-programming-books/pull/4129
