### ISSUE TITLE
Broken Chinese links - HELP REQUESTED

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#3267]
Below is a list of failing links in our Chinese lists
You can help improve this repo by resolving the problems.

A failing link may be a website or resource that has disappeared. You can submit a PR

+ removing the link (maybe the resource is obsolete.)
+ correcting the link (sometimes things move)
+ replacing the link (make sure the link is authorized, or the resource is open-licensed). Often a link to internet archive's wayback machine is useful.

Sometimes a link is only temporarily failing, or the site blocks link-checkers. If that's the case, leave a note on this issue.

In your PR, reference this issue.

Thanks for your help!

free-programming-books-zh.md
+ [ ] 404 Not Found https://softwaredownload.gitbooks.io/openwrt-fanqiang/content/
+ [ ] 404 Not Found https://code.csdn.net/CODE_Translation/spark_matei_phd
+ [ ] 500 Can't connect to man.chinaunix.net:80 (Name or service not known) http://man.chinaunix.net/linux/debian/reference/reference.zh-cn.html
+ [ ] 502 Bad Gateway http://wiki.ubuntu.org.cn/UbuntuManual
+ [ ] 500 Can't connect to web.archive.org:443 (timeout) https://web.archive.org/web/20170615232349/http://local.joelonsoftware.com/wiki/%E9
+ [ ] 500 Can't connect to stormzhang.com:80 (Connection refused) http://stormzhang.github.io/android/2014/07/07/learn-android-from-rookie/
sh: 1: Syntax error: ")" unexpected
+ [ ] 422 Unprocessable Entity https://wcc723.gitbooks.io/google_design_translate/content/style-icons.html)%EF
sh: 1: Syntax error: ")" unexpected
+ [ ] 400 Bad Request https://github.com/karlseguin/the-little-go-book)%E3
+ [ ] 403 Forbidden http://www.w3school.com.cn/html5/
+ [ ] 404 Not Found http://www.hawstein.com/posts/google-java-style.html
+ [ ] 500 Can't connect to wowubuntu.com:80 (Name or service not known) http://wowubuntu.com/markdown/basic.html
+ [ ] 500 Can't connect to wowubuntu.com:80 (Name or service not known) http://wowubuntu.com/markdown/
+ [ ] 500 Can't connect to old.sebug.net:80 (Connection timed out) http://old.sebug.net/paper/books/LearnPythonTheHardWay/
+ [ ] 404 Not Found http://wiki.ubuntu.org.cn/Shell%E7%BC%96%E7%A8%8B%E5%9F%BA%E7%A1%80
+ [ ] 500 Can't connect to man.chinaunix.net:80 (Name or service not known) http://man.chinaunix.net/newsoft/vi/doc/help.html

**Comment by 199911** [comment]
Checked all this link again:

## Links working now

502 Bad Gateway http://wiki.ubuntu.org.cn/UbuntuManual
404 Not Found http://wiki.ubuntu.org.cn/Shell%E7%BC%96%E7%A8%8B%E5%9F%BA%E7%A1%80

## Moved page

http://www.hawstein.com/posts/google-java-style.html become http://hawstein.com/2014/01/20/google-java-style/

**Comment by 199911** [comment]
422 Unprocessable Entity https://wcc723.gitbooks.io/google_design_translate/content/style-icons.html)%EF
sh: 1: Syntax error: ")" unexpected
The correct URL should be https://wcc723.gitbooks.io/google_design_translate/content/style-icons.html, which also work

**Comment by 199911** [comment]
400 Bad Request https://github.com/karlseguin/the-little-go-book)%E3
The correct url is https://github.com/karlseguin/the-little-go-book, which works

**Comment by 199911** [comment]
http://www.w3school.com.cn/html5/ should be https://www.w3school.com.cn/html5/index.asp,
which is also fixed in the list
