### ISSUE TITLE
Broken Russian links - HELP REQUESTED

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#3269]
Below is a list of failing links in our Russian lists
You can help improve this repo by resolving the problems.

A failing link may be a website or resource that has disappeared. You can submit a PR

+ removing the link (maybe the resource is obsolete.)
+ correcting the link (sometimes things move)
+ replacing the link (make sure the link is authorized, or the resource is open-licensed). Often a link to internet archive's wayback machine is useful.

Sometimes a link is only temporarily failing, or the site blocks link-checkers. If that's the case, leave a note on this issue.

In your PR, reference this issue.

Thanks for your help!

free-programming-books-ru.md
+ [ ] 404 Not Found https://ru.wikibooks.org/wiki/%D0
+ [ ] 404 Not Found https://younglinux.info/%D1
+ [ ] 404 Not Found https://ru.wikibooks.org/wiki/%D0
+ [ ] 404 Not Found http://ru.wikibooks.org/wiki/%D0
+ [ ] 404 Not Found https://ru.wikibooks.org/wiki/%D0
+ [ ] 500 Can't connect to railstutorial.ru:80 (Name or service not known) http://railstutorial.ru/chapters/4_0/beginning
+ [ ] 404 Not Found https://younglinux.info/linuxintro

**Comment by ex00** [comment]
Hi @eshellman 
I suppose all 404 errors for ru.wikibooks.org is problem checker tool, cause on
https://raw.githubusercontent.com/EbookFoundation/free-programming-books/master/free-programming-books-ru.md I don't see invalid links for this resource

```python
>>>target_url="https://raw.githubusercontent.com/EbookFoundation/free-programming-books/master/free-programming-books-ru.md"
>>>import requests
>>>data = requests.get(target_url).text
 >>>>>> urls = list(filter(lambda x: x.startswith("https://ru.wikibooks.org/"), data.replace("("," ").replace(")","").split(" ")))
# ['https://ru.wikibooks.org/wiki/Ассемблер_в_Linux_для_программистов_C', 'https://ru.wikibooks.org/wiki/Язык_Си_в_примерах', 'https://ru.wikibooks.org/wiki/Учебник_Python_2.6', 'https://ru.wikibooks.org/wiki/Ruby']
>>> for url in urls:
...     print("[{}]:{}, {}".format(url,requests.get(url).status_code, requests.get(url).url))
... 
[https://ru.wikibooks.org/wiki/Ассемблер_в_Linux_для_программистов_C]:200, https://ru.wikibooks.org/wiki/%D0%90%D1%81%D1%81%D0%B5%D0%BC%D0%B1%D0%BB%D0%B5%D1%80_%D0%B2_Linux_%D0%B4%D0%BB%D1%8F_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%81%D1%82%D0%BE%D0%B2_C
[https://ru.wikibooks.org/wiki/Язык_Си_в_примерах]:200, https://ru.wikibooks.org/wiki/%D0%AF%D0%B7%D1%8B%D0%BA_%D0%A1%D0%B8_%D0%B2_%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D0%B0%D1%85
[https://ru.wikibooks.org/wiki/Учебник_Python_2.6]:200, https://ru.wikibooks.org/wiki/%D0%A3%D1%87%D0%B5%D0%B1%D0%BD%D0%B8%D0%BA_Python_2.6
[https://ru.wikibooks.org/wiki/Ruby]:200, https://ru.wikibooks.org/wiki/Ruby

```
A we can see python code output all pages from wikibooks available.

Also I suppose that 
https://younglinux.info/%D1%81 moved to https://younglinux.info/c
https://younglinux.info/linuxintro moved to https://younglinux.info/linux

**Comment by eshellman** [comment]
looks like encoding problems to me. Unicode characters need to be % encoded in the url.
