### ISSUE TITLE
Broken Polish links - HELP REQUESTED

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#3270]
Below is a list of failing links in our Polish lists
You can help improve this repo by resolving the problems.

A failing link may be a website or resource that has disappeared. You can submit a PR

+ removing the link (maybe the resource is obsolete.)
+ correcting the link (sometimes things move)
+ replacing the link (make sure the link is authorized, or the resource is open-licensed). Often a link to internet archive's wayback machine is useful.

Sometimes a link is only temporarily failing, or the site blocks link-checkers. If that's the case, leave a note on this issue.

In your PR, reference this issue.

Thanks for your help!

free-programming-books-pl.md
+ [ ] 404 Not Found http://cyberpunk.e-spin.pl/86,36,5/KOD/KURSY-PROGRAMOWANIA/Kurs-CSS
+ [ ] 403 Forbidden http://ferrante.pl/books/html/
+ [ ] 404 Not Found http://cyberpunk.e-spin.pl/86,33,5/KOD/KURSY-PROGRAMOWANIA/Kurs-HTML
+ [ ] 404 Not Found http://cyberpunk.e-spin.pl/86,34,5/KOD/KURSY-PROGRAMOWANIA/Kurs-HTML5
+ [ ] 404 Not Found http://cyberpunk.e-spin.pl/86,35,5/KOD/KURSY-PROGRAMOWANIA/Kurs-XHTML
+ [ ] 403 Forbidden http://ferrante.pl/books/html/
+ [ ] 404 Not Found http://cyberpunk.e-spin.pl/86,44,5/KOD/KURSY-PROGRAMOWANIA/Kurs-JAVA
+ [ ] 404 Not Found http://cyberpunk.e-spin.pl/86,39,5/KOD/KURSY-PROGRAMOWANIA/Kurs-jQuery
+ [ ] 404 Not Found http://cyberpunk.e-spin.pl/86,38,5/KOD/KURSY-PROGRAMOWANIA/Kurs-MySQL
+ [ ] 404 Not Found http://zajacmarek.com/2014/10/kurs-perl-cz-1/
+ [ ] 404 Not Found http://cyberpunk.e-spin.pl/86,37,5/KOD/KURSY-PROGRAMOWANIA/Kurs-PHP-OOP

**Comment by hwilson2563** [comment]
I would love to help with this issue!

**Comment by eshellman** [comment]
go for it!
