### ISSUE TITLE
Broken Japanese links - HELP REQUESTED

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#3271]
Below is a list of failing links in our Japanese lists
You can help improve this repo by resolving the problems.

A failing link may be a website or resource that has disappeared. You can submit a PR

+ removing the link (maybe the resource is obsolete.)
+ correcting the link (sometimes things move)
+ replacing the link (make sure the link is authorized, or the resource is open-licensed). Often a link to internet archive's wayback machine is useful.

Sometimes a link is only temporarily failing, or the site blocks link-checkers. If that's the case, leave a note on this issue.

In your PR, reference this issue.

Thanks for your help!

free-programming-books-ja.md
+ [ ] 500 Can't connect to www.iim.ics.tut.ac.jp:80 (Name or service not known) http://www.iim.ics.tut.ac.jp/~sugaya/wiki/wiki/index.php?GTK%2FGNOME%A4%CB%A4%E8%A4%EBGUI%A5%D7%A5%ED%A5%B0%A5%E9%A5%DF%A5%F3%A5%B0#s8b2472b
+ [ ] 500 Can't connect to lagendra.w3.kanazawa-u.ac.jp:80 (Name or service not known) http://lagendra.w3.kanazawa-u.ac.jp/ogurisu/manuals/awk/index.html
+ [ ] 500 Can't connect to www-cms.phys.s.u-tokyo.ac.jp:80 (Name or service not known) http://www-cms.phys.s.u-tokyo.ac.jp/~naoki/CIPINTRO/
+ [ ] 500 Can't connect to episteme.wankuma.com:80 (Name or service not known) http://episteme.wankuma.com/stlprog/
+ [ ] 500 Can't connect to google-common-lisp-style-guide-ja.cddddr.org:80 (Name or service not known) http://google-common-lisp-style-guide-ja.cddddr.org
+ [ ] 404 Not Found http://home.soka.ac.jp/~unemi/LispProlog/
+ [ ] 403 Forbidden http://www.bookshelf.jp/texi/elisp-manual/21-2-8/jp/elisp.html
+ [ ] 404 Not Found http://hmdt.jp/tips/cocoa/index.html
+ [ ] 404 Not Found https://technet.microsoft.com/ja-jp/library/bb978525.aspx
+ [ ] 404 Not Found http://home.soka.ac.jp/~unemi/LispProlog/
+ [ ] 404 Not Found http://phpy.readthedocs.org/en/latest/
+ [ ] 404 Not Found http://psycho.edu.yamaguchi-u.ac.jp/?page_id=626

**Comment by dafujii** [comment]
- [x] **Fixed** https://github.com/EbookFoundation/free-programming-books/pull/3373/commits/0b2d50065c4eb356d38ba69c34cdc49677645a3a : 500 Can't connect to www.iim.ics.tut.ac.jp:80 (Name or service not known) http://www.iim.ics.tut.ac.jp/~sugaya/wiki/wiki/index.php?GTK%2FGNOME%A4%CB%A4%E8%A4%EBGUI%A5%D7%A5%ED%A5%B0%A5%E9%A5%DF%A5%F3%A5%B0#s8b2472b
- [ ] 500 Can't connect to lagendra.w3.kanazawa-u.ac.jp:80 (Name or service not known) http://lagendra.w3.kanazawa-u.ac.jp/ogurisu/manuals/awk/index.html
- [x] **Fixed** https://github.com/EbookFoundation/free-programming-books/pull/3373/commits/9c3854f42095493146730ba7e90d3be03d2249ce : 500 Can't connect to www-cms.phys.s.u-tokyo.ac.jp:80 (Name or service not known) http://www-cms.phys.s.u-tokyo.ac.jp/~naoki/CIPINTRO/
- [ ] 500 Can't connect to episteme.wankuma.com:80 (Name or service not known) http://episteme.wankuma.com/stlprog/
- [x] **Fixed** https://github.com/EbookFoundation/free-programming-books/pull/3373/commits/edad173dba7123575eeff3962fdf86cf70bd3052 : 500 Can't connect to google-common-lisp-style-guide-ja.cddddr.org:80 (Name or service not known) http://google-common-lisp-style-guide-ja.cddddr.org
- [ ] 404 Not Found http://home.soka.ac.jp/~unemi/LispProlog/
- [ ] 403 Forbidden http://www.bookshelf.jp/texi/elisp-manual/21-2-8/jp/elisp.html
- [ ] 404 Not Found http://hmdt.jp/tips/cocoa/index.html
- [ ] 404 Not Found https://technet.microsoft.com/ja-jp/library/bb978525.aspx
- [ ] 404 Not Found http://home.soka.ac.jp/~unemi/LispProlog/
- [ ] 404 Not Found http://phpy.readthedocs.org/en/latest/
- [ ] 404 Not Found http://psycho.edu.yamaguchi-u.ac.jp/?page_id=626

😯

**Comment by eshellman** [comment]
Thanks @dafujii

**Comment by dafujii** [comment]
- [x] Fixed https://github.com/EbookFoundation/free-programming-books/pull/3373/commits/0b2d50065c4eb356d38ba69c34cdc49677645a3a : 500 Can't connect to www.iim.ics.tut.ac.jp:80 (Name or service not known) http://www.iim.ics.tut.ac.jp/~sugaya/wiki/wiki/index.php?GTK%2FGNOME%A4%CB%A4%E8%A4%EBGUI%A5%D7%A5%ED%A5%B0%A5%E9%A5%DF%A5%F3%A5%B0#s8b2472b
- [x] **Fixed** https://github.com/EbookFoundation/free-programming-books/pull/3375/commits/b7264f9f11de797bc0fe179789c5477edd28eaae : 500 Can't connect to lagendra.w3.kanazawa-u.ac.jp:80 (Name or service not known) http://lagendra.w3.kanazawa-u.ac.jp/ogurisu/manuals/awk/index.html
- [x] Fixed https://github.com/EbookFoundation/free-programming-books/pull/3373/commits/9c3854f42095493146730ba7e90d3be03d2249ce : 500 Can't connect to www-cms.phys.s.u-tokyo.ac.jp:80 (Name or service not known) http://www-cms.phys.s.u-tokyo.ac.jp/~naoki/CIPINTRO/
- [x] **Fixed** https://github.com/EbookFoundation/free-programming-books/pull/3375/commits/c5b281cfc026dabc79e8da0b7cf5e103c4c03a7f : 500 Can't connect to episteme.wankuma.com:80 (Name or service not known) http://episteme.wankuma.com/stlprog/
- [x] Fixed https://github.com/EbookFoundation/free-programming-books/pull/3373/commits/edad173dba7123575eeff3962fdf86cf70bd3052 : 500 Can't connect to google-common-lisp-style-guide-ja.cddddr.org:80 (Name or service not known) http://google-common-lisp-style-guide-ja.cddddr.org
- [x] **Fixed** https://github.com/EbookFoundation/free-programming-books/pull/3375/commits/077819abc1bfb86004f7441e8d87a5de00942505 : 404 Not Found http://home.soka.ac.jp/~unemi/LispProlog/
- [x] **Fixed** https://github.com/EbookFoundation/free-programming-books/pull/3375/commits/15e02c30796a3b93f98352ed6a7b08aad1e6b487 : 403 Forbidden http://www.bookshelf.jp/texi/elisp-manual/21-2-8/jp/elisp.html
- [x] **Fixed** https://github.com/EbookFoundation/free-programming-books/pull/3375/commits/f61a2563fc5db42a03c6dde7c2a615844defd171 : 404 Not Found http://hmdt.jp/tips/cocoa/index.html
- [x] **Fixed** https://github.com/EbookFoundation/free-programming-books/pull/3375/commits/bdbe80718d17527c1b947a21cc8ae678685cc831 : 404 Not Found https://technet.microsoft.com/ja-jp/library/bb978525.aspx
- [x] **Fixed** https://github.com/EbookFoundation/free-programming-books/pull/3375/commits/077819abc1bfb86004f7441e8d87a5de00942505 : 404 Not Found http://home.soka.ac.jp/~unemi/LispProlog/
- [x] **Fixed** https://github.com/EbookFoundation/free-programming-books/pull/3375/commits/a1ddd80130ab231885dc4852b1abf6e9faeec3f1 : 404 Not Found http://phpy.readthedocs.org/en/latest/
- [x] **Fixed** https://github.com/EbookFoundation/free-programming-books/pull/3375/commits/706702e1c5b5f0e444df9c56a4c3c655050037aa : 404 Not Found http://psycho.edu.yamaguchi-u.ac.jp/?page_id=626

😚
