### ISSUE TITLE
Broken Korean links - HELP REQUESTED

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#3272]
Below is a list of failing links in our Korean lists
You can help improve this repo by resolving the problems.

A failing link may be a website or resource that has disappeared. You can submit a PR

+ removing the link (maybe the resource is obsolete.)
+ correcting the link (sometimes things move)
+ replacing the link (make sure the link is authorized, or the resource is open-licensed). Often a link to internet archive's wayback machine is useful.

Sometimes a link is only temporarily failing, or the site blocks link-checkers. If that's the case, leave a note on this issue.

In your PR, reference this issue.

Thanks for your help!

free-programming-books-ko.md
+ [ ] 404 Not Found http://l5.appkr.kr
+ [ ] 404 Not Found https://thebook.io/006855/

**Comment by thomasjeung** [comment]
https://thebook.io/006855/ which was for "모두의 파이썬: 20일 만에 배우는 프로그래밍 기초" has been revised and the new URL is https://thebook.io/007026/ "모두의 파이썬: 20일 만에 배우는 프로그래밍 기초(개정판)"

**Comment by thomasjeung** [comment]
Well, I created a PR from the forked git, I am fairly new so I am not sure if I did it correctly.

**Comment by eshellman** [comment]
fixed in #3309
