### ISSUE TITLE
Broken Ukrainian links - HELP REQUESTED

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#3275]
Below is a list of failing links in our Ukrainian lists
You can help improve this repo by resolving the problems.

A failing link may be a website or resource that has disappeared. You can submit a PR

+ removing the link (maybe the resource is obsolete.)
+ correcting the link (sometimes things move)
+ replacing the link (make sure the link is authorized, or the resource is open-licensed). Often a link to internet archive's wayback machine is useful.

Sometimes a link is only temporarily failing, or the site blocks link-checkers. If that's the case, leave a note on this issue.

In your PR, reference this issue.

Thanks for your help!

free-programming-books-ua.md
+ [ ] 404 Not Found https://uk.wikibooks.org/wiki/%D0

**Comment by MaximKazionov** [comment]
Hello, I can try to help you with this problem :)

**Comment by eshellman** [comment]
looks like it's just a url encoding issue
