### ISSUE TITLE
Broken French links - HELP REQUESTED

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#3276]
Below is a list of failing links in our French lists
You can help improve this repo by resolving the problems.

A failing link may be a website or resource that has disappeared. You can submit a PR

+ removing the link (maybe the resource is obsolete.)
+ correcting the link (sometimes things move)
+ replacing the link (make sure the link is authorized, or the resource is open-licensed). Often a link to internet archive's wayback machine is useful.

Sometimes a link is only temporarily failing, or the site blocks link-checkers. If that's the case, leave a note on this issue.

In your PR, reference this issue.

Thanks for your help!

free-programming-books-fr.md
+ [ ] 503 Service Unavailable http://fr.discovermeteor.com

**Comment by SomTambe** [comment]
The discovermeteor.com links for all language translations are down. Maybe we should remove the link. I will keep a watch on the site and since it is down for maintenance, I will add the link again when the site is completely functional. Should I put a PR for this?

**Comment by SomTambe** [comment]
Also, can I instead of removing the whole link, put a temporary wayback machine link?

**Comment by eshellman** [comment]
your help is much appreciated!
