### ISSUE TITLE
Unable to read 《Markdown 快速入门》

### ISSUE THREAD

**Issue by zjuncd** [EbookFoundation/free-programming-books#3327]
The link to 《Markdown 快速入门》 (http://wowubuntu.com/markdown/basic.html) is unavailable。
And 《Markdown 语法说明》 links to same domain, not work either

**Comment by zhongjiajie** [comment]
See also https://github.com/EbookFoundation/free-programming-books/issues/3267, there are many other broken links in `-zh` list
