### ISSUE TITLE
Syncfusion and export laws

### ISSUE THREAD

**Issue by dzmitry-lahoda** [EbookFoundation/free-programming-books#3368]
I propose any books with
```
Syncfusion is a United States company and is subject to US export laws. Consequently, due to your location, we may not allow access to any material on our site.
If you believe that this is inaccurate, please contact sales@syncfusion.com Thank you.
````

like 
https://www.syncfusion.com/ebooks/azure-functions-succinctly

to be tagged appropriately as risk of them potentially be non free.

Not sure about proper tag name so.

**Comment by eshellman** [comment]
Feedback from affected users on this issue would be appreciated.

**Comment by SethiPandi** [comment]
Please correct me if I'm wrong, but I think this issue might no longer be relevent today. Syncfusion requires the user to sign up before they can access the book.

They ask for full name, email address, phone number, and that the user verifies their email address.

There is no way to download the book without a working email address.

> We do not accept links to pages that require working email addresses to obtain books, but we welcome listings that request them.

Can this be closed?

**Comment by SethiPandi** [comment]
Ah! I'm so sorry, disregard my previous comment.
I immediately went to try and download the resource as I only read books offline.
Syncfusion resources are available to be read online without an account it seems! Just not to download!
