### ISSUE TITLE
HTTP Error 500 for a link

### ISSUE THREAD

**Issue by Khadiravana** [EbookFoundation/free-programming-books#3400]
A link to the Angular.js for "Angular for the jQuery developer" shows an HTTP Error 500.

The link is: https://www.ng-newsletter.com/posts/angular-for-the-jquery-developer.html

Please do the needful

**Comment by charlottetan** [comment]
This is probably a temporary issue that ng-newsletter.com needs to fix, but I found an alternate link for the post.
