### ISSUE TITLE
O'Reilly books problem

### ISSUE THREAD

**Issue by HankiDesign** [EbookFoundation/free-programming-books#3522]
I just noticed that the book [Apprenticeship Patterns: Guidance for the Aspiring Software Craftsman](http://chimera.labs.oreilly.com/books/1234000001813/index.html) is no longer available at its former location. I found the book [here](https://www.oreilly.com/library/view/apprenticeship-patterns/9780596806842/) and it's fully readable by clicking through the pages in the *Table of Contents*. 

However, I think it's a bit problematic how O'Reilly structures this free content. To continue from one page to another, the user needs to use the extremely small and easily missable arrow on the left or right (pictured) border of the page:

![Next arrow](https://user-images.githubusercontent.com/1816448/72653061-961ce400-3989-11ea-96a4-6e2fa5990010.png)

These arrows don't follow the user to the bottom of the page, so when they scroll down, they're greeted with the following AD:

![O'Reilly AD](https://user-images.githubusercontent.com/1816448/72653120-c3699200-3989-11ea-9402-051d8c926070.png)

My initial thought was that clearly this was just a sample chapter and now I need to subscribe to continue reading. But no, I can still go to the top of the page and click the small arrows or back to the table of contents and click the next chapter.

Now, my questions are:

1. Is it worth adding these books to the repo? Some books that I've already removed had the exact same page but clicking anything on the table of contents just showed a popup AD for the O'Reilly learning service. Who knows how long this will be available, as it doesn't even mention anywhere that it's free to read online.
2. If this is worth adding, should we have some guidance for such links that navigation is through the table of contents or something like that?

**Comment by eshellman** [comment]
If it's annoying, I wouldn't include it.
