### ISSUE TITLE
Site is difficult to follow for a newbie, especially for someone looking for resources other than books

### ISSUE THREAD

**Issue by natkuhn** [EbookFoundation/free-programming-books#3529]
Your site has wonderful resources, and I really appreciate everything that has gone into it. Unfortunately, I found the organization more difficult to follow than it needs to be. I did make one PR, but don't have time to make others, so I am leaving these suggestions, to use or ignore as you see fit.

1. It is not clear whether the site is for "books" or "resources". I vote for making it "resources." Then the sections would be Introduction, Books, Online Courses, Interactive Programming Resources, Problem Sets, Podcast - Screencast, Programming Playgrounds (though could that be combined with "Interactive Programming Resources"?)

1. At the very least, "View the English list" should say "View the English list **of books**".

1. The pages for "Online Courses", "Interactive Programming Resources", "Programming Playgrounds" are just labeled "Index" so it is impossible to know what you are looking at. They should be titled "Index of Programming Playgrounds", e.g.

1.  My PR was about online programming playgrounds, and @eshellman  raised the question of whether frameworks (React and Angular) should be listed separately, or under JavaScript as is done in books. I agree that it would be good to organize all the pages the same way, and it probably makes sense to list frameworks under languages. However, it would be good to indent the frameworks on the full list, rather than have them as [top-level entries the way they are here](https://ebookfoundation.github.io/free-programming-books/free-courses-en.html#angularjs). I understand that it may not be easy to do that in Jekyll. I see that the titles are `<h3>`s. Maybe the subsection titles could be `<h4>`s with some css to indent them. It would be OK to just indent the subheader, if it turns out not to be easy to indent lists under subheader.

Thanks for keeping up such a great resource, sorry I don't have time to do the PRs myself!

**Comment by Sant268** [comment]
https://pages.github.com/
Should we improvise this repo with a front-end Github Webpage? That would be more 'presentable' than a README.md

**Comment by eshellman** [comment]
you mean like https://ebookfoundation.github.io/free-programming-books/ ?

**Comment by Sant268** [comment]
Yeah, well:

The points mentioned above are for the README file, but I think that we should make the .io page a liitle more Navigate-friendly.
