### ISSUE TITLE
Missing books

### ISSUE THREAD

**Issue by leobetosouza** [EbookFoundation/free-programming-books#3569]
I see that some os the MagPi books aren't listed: [https://magpi.raspberrypi.org/books](https://magpi.raspberrypi.org/books)

**Comment by leobetosouza** [comment]
Two books from Al Sweigart are also missing:
https://inventwithscratch.com/book/
https://turtleappstore.com/book

**Comment by GintasS** [comment]
I will take it as well.

**Comment by GintasS** [comment]
I'm going to take this.

**Comment by GintasS** [comment]
#4150
