### ISSUE TITLE
Telegram Channels, Chats and Blogs

### ISSUE THREAD

**Issue by kirich1409** [EbookFoundation/free-programming-books#3592]
Many interesting materials are distributed by personal blogs, Telegram channels, and chats. I propose to add a new category of MDs for suck kind of resources

**Comment by kirich1409** [comment]
As an example from Android:
-  [Android Broadcast Telegram Channel](http://ttttt.me/android_broadcast)
-  [Android ResId](https://t.me/AndroidResId)
-  [Mobile Insights by AppTractor](http://ttttt.me/apptractor)

**Comment by eshellman** [comment]
It seems these resources are not viewable without a telegram account. So they can't be easily reviewed or link-checked. We discourage resources that require account sign-up. If we do Telegram, facebook and linkedin will follow.

Blogs have been suggested as a category before. The difficulty is figuring out criteria for which blogs to include or exclude, how to keep the list current (the average blog goes away or becomes stagnant in a year or two). Also, blogrolls that were once fun are now tedious.

I'll leave the issue open for a bit, though - our lists are community driven.
