### ISSUE TITLE
Road to React no longer free

### ISSUE THREAD

**Issue by alpal309** [EbookFoundation/free-programming-books#3600]
The link for road to react in the english list under javascript is broken and the book is not free anyways.

**Comment by SethiPandi** [comment]
Could this issue be closed?
I believe it should've been resolved in the PR merged above.

I wasn't aware of the [syntax](https://github.blog/2013-05-14-closing-issues-via-pull-requests/) for auto-closing an issue since I'm mostly a GitLab user, my fault.  
I'll be sure to do that in the future.
