### ISSUE TITLE
Add Georgian Online courses 

### ISSUE THREAD

**Issue by giorgiberia** [EbookFoundation/free-programming-books#3612]
Skills.ge

**Comment by eshellman** [comment]
gotta start somewhere, right?

**Comment by giorgiberia** [comment]
Yeap

**Comment by davorpa** [comment]
@eshellman @giorgiberia

this seems to bee a platform courses, it isn't?

How to contribute with PR to add it?

**Comment by eshellman** [comment]
site seems dead

**Comment by eshellman** [comment]
"Site administration is suspended. Last update: September 1, 2019"
