### ISSUE TITLE
链接失效：C++基础教程

### ISSUE THREAD

**Issue by zjuncd** [EbookFoundation/free-programming-books#3653]
链接：http://www.prglab.com/cms/ 
访问返回：

> Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /home/www/prglab.com/cms/framework/class.database.php:61 Stack trace: #0 /home/www/prglab.com/cms/framework/class.database.php(52): database->connect() #1 /home/www/prglab.com/cms/framework/initialize.php(32): database->database() #2 /home/www/prglab.com/cms/config.php(18): require_once('/home/www/prgla...') #3 /home/www/prglab.com/cms/index.php(29): require_once('/home/www/prgla...') #4 {main} thrown in /home/www/prglab.com/cms/framework/class.database.php on line 61

**Comment by eshellman** [comment]
It would be great if you check back on it in a couple days; if it continues to error we should remove it.

**Comment by zjuncd** [comment]
I tried again today. Same error. Maybe we should remove it.

**Comment by eshellman** [comment]
agreed

**Comment by GintasS** [comment]
I'm voting to close this because it has been fixed.
