### ISSUE TITLE
Free Udemy

### ISSUE THREAD

**Issue by slowkambo** [EbookFoundation/free-programming-books#3669]
Udemy is a payed source for the most part but also offers a lot of free stuff. 
  Not all good but should still definitely make the list.
  There's an outdated c++ (mostly c) intro class that's free that is definitely still worth the learning. 
  I did not see it in there but maybe I missed it

**Comment by eshellman** [comment]
we have 10 udemy listings in free-courses-en and 58 in free-courses-pt_BR
