### ISSUE TITLE
29 broken links

### ISSUE THREAD

**Issue by cktang88** [EbookFoundation/free-programming-books#3672]
I used https://github.com/tcort/markdown-link-check to scan the links on the English resources page, and found some dead links:

```
1843 links checked.

ERROR: 29 dead links found!
[✖] https://blogs.msdn.microsoft.com/mssmallbiz/2017/07/11/largest-free-microsoft-ebook-giveaway-im-giving-away-millions-of-free-microsoft-ebooks-again-including-windows-10-office-34
[✖] http://dces.essex.ac.uk/staff/rpoli/gp-field-guide/toc.html → Status: 404
[✖] http://www.cleveralgorithms.com/nature-inspired/ → Status: 404
[✖] http://csunplugged.org/books/ → Status: 404
[✖] http://www.ethoberon.ethz.ch/WirthPubl/CBEAll.pdf → Status: 0
[✖] http://people.cs.aau.dk/~csj/Thesis/ → Status: 0
[✖] http://schoolofdata.org/handbook/ → Status: 503
[✖] https://people.math.gatech.edu/~cain/winter99/complex.html → Status: 0
[✖] https://people.math.gatech.edu/~herod/Hspace/Hspace.html → Status: 0
[✖] https://people.math.gatech.edu/~cain/notes/calculus.html → Status: 0
[✖] http://scpd.stanford.edu/knuth/index.jsp → Status: 404
[✖] https://developer.android.com/guide → Status: 0
[✖] http://www.oualline.com/books.free/style/ → Status: 0
[✖] http://codebeerstartups.com/2012/12/a-complete-guide-for-learning-backbone-js/ → Status: 404
[✖] https://bulletproofmeteor.com → Status: 503
[✖] http://docs.kali.org → Status: 403
[✖] https://common-lisp-reserve.github.io/solid-design-principles-in-common-lisp/solid-design-principles-in-common-lisp.pdf → Status: 404
[✖] https://github.com/clojurians-org/lisp-ebook/blob/master/Successful%20Lisp%20How%20to%20Understand%20and%20Use%20Common%20Lisp%20-%20David%20B.%20Lamkins.pdf → Status: 451
[✖] http://www.wolfram.com/learningcenter/tutorialcollection/ → Status: 404
[✖] http://books.sonatype.com/m2eclipse-book/reference/ → Status: 403
[✖] http://downloads.mysql.com/docs/mysql-tutorial-excerpt-5.5-en.pdf → Status: 404
[✖] http://www.ravichaganti.com//blog/wp-content/uploads/2010/12/A%20layman's%20guide%20to%20PowerShell%202.0%20remoting-v2.pdf → Status: 404
[✖] https://www.gitbook.com/book/devopscollective/secrets-of-powershell-remoting/details → Status: 0
[✖] https://www.penflip.com/powershellorg/the-dsc-book → Status: 0
[✖] http://inventwithpython.com/chapters/ → Status: 404
[✖] http://books.aidanf.net/learn-swift → Status: 0
[✖] https://itunes.apple.com/us/book/using-swift-cocoa-objective/id888894773?mt=11 → Status: 500
[✖] http://www.invece.org/tclwise/index.html → Status: 404
[✖] https://makinggameswithtypescript.com → Status: 0

```

**Comment by borgified** [comment]
there are some false positives here. for example, https://people.math.gatech.edu/~cain/winter99/complex.html is actually a working link, it probably got flagged prob cuz of some webserver config issue.
https://developer.android.com/guide also seems to be working.

**Comment by l3g3ndf4i541** [comment]
@eshellman  I'd like to take this on. Please assign.

**Comment by eshellman** [comment]
I doubt @borgified would mind.

**Comment by charlottetan** [comment]
I've gone through the entire list of broken links here and fixed the ones that were broken, lots more were either already removed or actually working but did not pass the automated link check. Submitted a PR.

### Details:
#### Not broken:
[✖] https://blogs.msdn.microsoft.com/mssmallbiz/2017/07/11/largest-free-microsoft-ebook-giveaway-im-giving-away-millions-of-free-microsoft-ebooks-again-including-windows-10-office-34
[✖] http://people.cs.aau.dk/~csj/Thesis/ → Status: 0
[✖] http://schoolofdata.org/handbook/ → Status: 503
[✖] https://people.math.gatech.edu/~cain/winter99/complex.html → Status: 0
[✖] https://people.math.gatech.edu/~herod/Hspace/Hspace.html → Status: 0
[✖] https://people.math.gatech.edu/~cain/notes/calculus.html → Status: 0
[✖] https://developer.android.com/guide → Status: 0
[✖] http://www.oualline.com/books.free/style/ → Status: 0
[✖] http://docs.kali.org → Status: 403
[✖] https://itunes.apple.com/us/book/using-swift-cocoa-objective/id888894773?mt=11 → Status: 500

#### No longer in .md file:
[✖] http://dces.essex.ac.uk/staff/rpoli/gp-field-guide/toc.html → Status: 404
[✖] http://www.cleveralgorithms.com/nature-inspired/ → Status: 404
[✖] http://csunplugged.org/books/ → Status: 404
[✖] http://www.ethoberon.ethz.ch/WirthPubl/CBEAll.pdf → Status: 0
[✖] http://scpd.stanford.edu/knuth/index.jsp → Status: 404
[✖] http://codebeerstartups.com/2012/12/a-complete-guide-for-learning-backbone-js/ → Status: 404
[✖] https://bulletproofmeteor.com → Status: 503
[✖] https://common-lisp-reserve.github.io/solid-design-principles-in-common-lisp/solid-design-principles-in-common-lisp.pdf → Status: 404
[✖] https://github.com/clojurians-org/lisp-ebook/blob/master/Successful%20Lisp%20How%20to%20Understand%20and%20Use%20Common%20Lisp%20-%20David%20B.%20Lamkins.pdf → Status: 451
[✖] https://www.penflip.com/powershellorg/the-dsc-book → Status: 0
[✖] http://inventwithpython.com/chapters/ → Status: 404
[✖] http://books.aidanf.net/learn-swift → Status: 0
[✖] http://www.invece.org/tclwise/index.html → Status: 404
[✖] https://makinggameswithtypescript.com → Status: 0

#### Actually broken:
[✖] http://www.wolfram.com/learningcenter/tutorialcollection/ → Status: 404
[✖] http://books.sonatype.com/m2eclipse-book/reference/ → Status: 403
[✖] http://downloads.mysql.com/docs/mysql-tutorial-excerpt-5.5-en.pdf → Status: 404
[✖] http://www.ravichaganti.com//blog/wp-content/uploads/2010/12/A%20layman's%20guide%20to%20PowerShell%202.0%20remoting-v2.pdf → Status: 404
[✖] https://www.gitbook.com/book/devopscollective/secrets-of-powershell-remoting/details → Status: 0
