### ISSUE TITLE
Suggestion of adding Vulkan Tutorials at Graphics Programming

### ISSUE THREAD

**Issue by BrunoDG** [EbookFoundation/free-programming-books#3683]
There are some links that are aimed at graphics development, but using Vulkan instead of OpenGL. Although there are no Vulkan books here, I've found some that are free and even some projects that can help users on learning how to use Vulkan with C++ and Rust, and also how to use OpenGL with Rust as well:

https://vulkan-tutorial.com/Introduction - This is a tutorial that teaches how to use Vulkan, similar to the "Learn OpenGL" tutorial. This one covers C++ language

https://github.com/bwasty/vulkan-tutorial-rs - Also, he created another Vulkan tutorial for Rust...

https://github.com/Naitsirc98/Vulkan-Tutorial-Java - ...and for Java.

https://github.com/bwasty/learn-opengl-rs - And here we have the Learn OpenGL tutorial, covering Rust.

http://vulkano.rs/guide/introduction - And the Vulkano wrapper in Rust, that covers the Rust wrapper for Vulkan as well.

I hope those links cover some Graphics Programming development points that I hadn't seen on the list.

**Comment by eshellman** [comment]
vulkan-tutorial is bookish enough for this list. There;s even a pdf and an EPUB version!
The Rust version appears to be unfinished - see CONTRIBUTING for how to add an "in progress" notation. The Java version looks good too. The last link doesn't seem like a book, at first glance. And they have CC licenses!

When deciding where to put these links i.e. with graphic books or with language books, think about who will want to find these books, and where they would look for them- would it be someone looking for a Vulkan book, or someone looking for a graphics book using Rust? etc.

**Comment by BrunoDG** [comment]
All right then! 

Thanks for the info, I'll take a look on the contributing part.

**Comment by MaggieFero** [comment]
@BrunoDG Did you want to submit a PR for these? I don't want to snipe if you were planning to do it yourself, but I'd love to get these onto the list.

**Comment by BrunoDG** [comment]
Go ahead, NP! :)

**Comment by eshellman** [comment]
@MaggieFero if you have a PR, be sure to link it

**Comment by kadhirash** [comment]
@MaggieFero are you going to submit a PR? If not may I take over @eshellman ?

**Comment by MaggieFero** [comment]
I had an unexpected onslaught of work tasks right after I asked, fine by me
if you take it over. 😅 Thanks for checking!
