### ISSUE TITLE
科技向善，来自常熟农商银行程序员的呼救！

### ISSUE THREAD

**Issue by csrcbank** [EbookFoundation/free-programming-books#3709]
###          我们已有近百名程序员体检发现肺部结节，已有2位GG结节超过肺癌警戒线8毫米而住院手术治疗。
     
请大家关注我们。https://github.com/csrcbank/8mm

媒体采访请联系邮箱：csrcbank@yandex.com

抱歉有扰

**Comment by lzy1g1225** [comment]
你应该发到996.ICU项目里面
