### ISSUE TITLE
Which category does Data Science cheatsheets come under?

### ISSUE THREAD

**Issue by UjwalKandi** [EbookFoundation/free-programming-books#3712]
I have a link to this site where they have cheatsheets on R, Python and of other libraries that are used by Data Scientists. 

Should I add them to **_Misc_** or to **_Meta-Lists_**?

**Comment by UjwalKandi** [comment]
They also have a podcast on Data Science.

Can I add both these links in a single commit?

**Comment by eshellman** [comment]
we have one cheat-sheet site in the meta-list already, so I suppose that's where it should go.
The issues with these are likely to be different from the podcast link, so separate PRs are preferred.
