### ISSUE TITLE
Competitive Programming website suggestion

### ISSUE THREAD

**Issue by Tahanima** [EbookFoundation/free-programming-books#3719]
I want to add:

- [Toph](https://toph.co/)
- [URI Online Judge](https://www.urionlinejudge.com.br/judge/en/login)

under the **Competitive Programming** section of **problem-sets-competitive-programming.md** file

**Comment by eshellman** [comment]
make sure this is free

**Comment by Tahanima** [comment]
Yes, these sites are free. In fact, I've personally used them.
