### ISSUE TITLE
Suggestion on adding on age for the books

### ISSUE THREAD

**Issue by Fr3d-P** [EbookFoundation/free-programming-books#3771]
Hello,

I did search for a book for a specific language, and I found lots of them, but I had to visit each web site to verify that it wasn't informations from a too-old version...
I think it could be useful to add a possibility to mention the book's publication or modified date, then in the list it could be indicated, or even better the age of the book , calculated from current date...

**Comment by eshellman** [comment]
Fore older books, we encourage the addition of a date to the listing.
