### ISSUE TITLE
New References on free-courses-id.md

### ISSUE THREAD

**Issue by VicoSilalahi** [EbookFoundation/free-programming-books#3779]
C++
* [Belajar C++ - Object Oriented Programming Bahasa Indonesia (OOP)](https://www.youtube.com/playlist?list=PLZS-MHyEIRo7-RC_-hkL9gu0_ofABw862) - Kelas Terbuka
* [Belajar C++ Bahasa Indonesia (Dasar)](https://www.youtube.com/playlist?list=PLZS-MHyEIRo4Ze0bbGB1WKBSNMPzi-eWI) - Kelas Terbuka

I've tried doing PR but didn't know what to do after getting build fail, don't know what's Travis ci means.

**Comment by Tahanima** [comment]
Hi @VicoSilalahi 

The issues with your PR are:

- Incorrect number of blank lines between last section and next heading
- Incorrect number of blank lines between heading and section

in the **/home/travis/build/EbookFoundation/free-programming-books/free-courses-id.md** file

Please read the [Formatting](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#formatting) section of CONTRIBUTING.md file and fix your changes accordingly.

I hope this helps you resolve the issues. Good luck!

**Comment by VicoSilalahi** [comment]
Hi @Tahanima , thanks for your response, in my new PR, the build was successful, it was a new fork from the latest commit, i added the resources above as well as some more.

**Comment by eshellman** [comment]
Thanks for the help, @Tahanima

**Comment by Tahanima** [comment]
You're welcome @VicoSilalahi and @eshellman
