### ISSUE TITLE
Suggestion to add #hacktoberfest tag to make this repo eligible

### ISSUE THREAD

**Issue by Entropy4** [EbookFoundation/free-programming-books#3797]
Hi!
I just made a PR and went over to the Hacktoberfest site to confirm it, when I saw that they claimed this repo to be ineligible for the same. I am attaching herewith a screenshot showing the same. 

![screenshot](https://user-images.githubusercontent.com/52324356/95434040-66c26300-096e-11eb-927a-36196adfedf7.png)

@Moderators please consider adding the **hacktoberfest** tag to the repo to fix this issue.

Thanks again!
Entropy4

**Comment by eshellman** [comment]
done
