### ISSUE TITLE
Add Docker courses requested PR #3853

### ISSUE THREAD

**Issue by harekrishnarai** [EbookFoundation/free-programming-books#3856]
PR #3853 
### Docker

* [Docker By Automation Step By Step](https://www.youtube.com/playlist?list=PLhW3qG5bs-L99pQsZ74f-LC-tOEsBp2rK)
* [Docker Detailed Tutorial By IIEC Free Community](https://www.youtube.com/playlist?list=PLAi9X1uG6jZ30QGz7FZ55A27jPeY8EwkE)

**Comment by learn-everyday-with-me** [comment]
Can I do this.

**Comment by harekrishnarai** [comment]
> 
> 
> Can I do this.

yeah sure !

**Comment by learn-everyday-with-me** [comment]
You need to merge it.

**Comment by eshellman** [comment]
fix linter errors

**Comment by learn-everyday-with-me** [comment]
Fixed the errors.

**Comment by learn-everyday-with-me** [comment]
Can you please tell me what should I do to fix the error.

**Comment by learn-everyday-with-me** [comment]
Fixed the errors. Please check.

**Comment by kadhirash** [comment]
@eshellman This still seems to be open, want to assign me to this issue so I can take over?
