### ISSUE TITLE
Add Introduction to the computer science by edx OR udacity?

### ISSUE THREAD

**Issue by priyanshuSharma-WebDev** [EbookFoundation/free-programming-books#3878]
I have some courses link and they are free exclude certificate how do I contribute in your ripo?

**Comment by Swapnil123123** [comment]
By cloning the project, making additions to the files and raising PR

**Comment by maanpatel2492** [comment]
Tell me more about this issue so that I can contribute it.

**Comment by priyanshuSharma-WebDev** [comment]
edx offer Introduction to the computer Science course it is a 12 week long program organised by harvard university and very for those people who are new to computer science.

**Comment by AleenaAnnaRobin** [comment]
@eshellman  assign to me, please.
