### ISSUE TITLE
Deep Learning full courses and free projects

### ISSUE THREAD

**Issue by Satyam-kumar-yadav** [EbookFoundation/free-programming-books#4047]
I have some new deep learning courses including slides and video.

**Comment by yash37158** [comment]
hey @ericallam @emkay @radar @Andrea  this is my first time on open source contribution. can you please assign it to me , I would like to work on this issue ,

**Comment by eshellman** [comment]
we welcome contributions from anyone, but please read CONTRIBUTING.md guidelines!
