### ISSUE TITLE
separate page for cheatsheets?

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#4082]
We've now gotten a fair number of "cheatsheet" entries in the books list. I'd like to propose that we move these to a separate page.

Reasons:

1. Will be easier to find cheatsheets
2. Cheatsheets aren't books
3. Cheat sheets aren't so spoken-language specific.
4. The english-language books page is getting long.
5. Will encourage better cheatsheet coverage.

Against:

1. Scope creep.
2. People find language-specific cheatsheets as they look for books.

Comments and PRs welcome!

**Comment by AleenaAnnaRobin** [comment]
@eshellman  can you assign this for me?

**Comment by eshellman** [comment]
@AleenaAnnaRobin @yerenn22 has a start, but seems they need help

**Comment by kadhirash** [comment]
@eshellman May I start helping out @yerenn22 and @AleenaAnnaRobin on this?

**Comment by kadhirash** [comment]
@eshellman, The new page should be in the latest [PR](https://github.com/EbookFoundation/free-programming-books/pull/4087#issue-503468441) from @yerenn22 !

**Comment by eshellman** [comment]
We now have a cheat sheet page! Pleas help by moving links from cheatsheets!

**Comment by JiriJAdam** [comment]
Hello! Can I work on this?

**Comment by yerenn22** [comment]
> hello! can i work on this?

@JiriJAdam, hello! we have already transferred all of the links from books page to the new cheatsheets page

but you can add some new cheatsheets with good quality to [this](https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-cheatsheets.md) page

**Comment by JiriJAdam** [comment]
I can definitely do that!

**Comment by eshellman** [comment]
big success!
