### ISSUE TITLE
Need to add Google Codelabs

### ISSUE THREAD

**Issue by prateekcode** [EbookFoundation/free-programming-books#4238]
Google Codelabs helps you to build app/website/ml in a step by step by building small projects. It provides guided tutorials, hands-on coding experience. That the requirement of every new bie to hand-on coding experience. 
For the reference, I'm sharing the link of [Codelabs. ](https://codelabs.developers.google.com/)

**Comment by davorpa** [comment]
I think this should be closed 🤔.

It's solved in #4474 and #5183

**Comment by prateekcode** [comment]
Yes, I'm closing this issue now. Thanks :)
