### ISSUE TITLE
For New PR, check by Travis is failing due to previous lint error in the repo

### ISSUE THREAD

**Issue by codejayant** [EbookFoundation/free-programming-books#4254]
Check for any new PR is failing by Travis due to lint error in the existing repo.
Travis Link: https://travis-ci.com/github/EbookFoundation/free-programming-books/builds/190573756

**Comment by codejayant** [comment]
This PR fixes this issue: https://github.com/EbookFoundation/free-programming-books/pull/4253

**Comment by eshellman** [comment]
fixed
