### ISSUE TITLE
Script for checking for broken links

### ISSUE THREAD

**Issue by dbrn** [EbookFoundation/free-programming-books#4398]
Hello everybody!
I wrote a script in python 3 in the last two/three days that checks all the repo files for broken links and it works.
I'd love to share it with you and eventually turn it in some kind of Bot (Action?) to be automatically launched at given times of the week/day.
Sounds like something cool to me, and it takes away some of the burdens that come with the maintenance of such an amount of links.
What do you think about it?
Since I'm quite new to this, if someone is willing to guide me through the process, I'm excited to begin.

**Comment by eshellman** [comment]
we already have an action that checks links. from @borgified 
see #3233, #3679
