### ISSUE TITLE
Scalafiddle.io not working

### ISSUE THREAD

**Issue by pcbock** [EbookFoundation/free-programming-books#4438]
Scalafiddle.io on the free-programming-playgrounds page is not working.  The link is located here:

https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-playgrounds.md#scala

The link returns a 502 error.

**Comment by kadhirash** [comment]
https://github.com/scalafiddle

This looks to be the source code for that website, shows that there's a 502 error on the host side for me as well.

**Comment by charlottetan** [comment]
Reported issue on their repo

**Comment by borgified** [comment]
scalafiddle.io back to working
