### ISSUE TITLE
youtube playlist about CMake in english

### ISSUE THREAD

**Issue by x0rld** [EbookFoundation/free-programming-books#4520]
I'm not sure where I sould put it cause there isn't makefile courses and it's linked to C and C++
the [playlist](https://www.youtube.com/playlist?list=PLK6MXr8gasrGmIiSuVQXpfFuE1uPT615s) if you want take a look

**Comment by eshellman** [comment]
Shell?

**Comment by kadhirash** [comment]
I agree with @eshellman.  @x0rld, I think it could be under [Bash/Shell](https://github.com/EbookFoundation/free-programming-books/blob/master/free-courses-en.md#bash--shell) in the free-courses file, but after the playlist link you can specify that its (C/C++).

**Comment by x0rld** [comment]
thanks i will do that

**Comment by kadhirash** [comment]
Hey @x0rld, you mind if I add this to a PR?

**Comment by x0rld** [comment]
@kadhirash do it 👍
