### ISSUE TITLE
Attribute Contributors in LICENSE?

### ISSUE THREAD

**Issue by SethiPandi** [EbookFoundation/free-programming-books#4598]
**Disclaimer: I'm not a lawyer, everything here is just as far as I understand.**

I've noticed in the LICENSE file there is attribution to Victor Felder, and the Free Ebook Foundation, however there is no mention of other copyright holders.

As this repository doesn't have a [CLA (Contributor License Agreement)](https://en.wikipedia.org/wiki/Contributor_License_Agreement), all contributions made by individuals are under the copyright of those individuals, licensed to the Free Ebook Foundation under CC BY 4.0.

In other words, my understanding is that all copyright holders should be attributed, which includes all contributors as they are partial copyright holders of the content in the repository. Unless anyone disagrees, I think this repository should be treated the same way?

I've seen other repositories handle this by adding `and Contributors` to the end of the list of attributees with a link to their [insights](https://github.com/EbookFoundation/free-programming-books/graphs/contributors). 

For example:

```
It is attributed to Victor Felder, the Free Ebook Foundation, and free-programming-books contributors.
https://github.com/EbookFoundation/free-programming-books
```

> If a project was started by a single author who later incorporated contributions by other authors, the primary author does not own sole copyright. For projects with lots of small contributions by many people, it would be unfeasible to list all actual authors in the copyright notice. Instead, it is common to list the group of authors as the copyright owner(s), or to explicitly list the primary authors and note that additional authors exist:
> \- https://opensource.stackexchange.com/questions/5508/what-does-and-contributors-in-the-copyright-byline-imply

The following are some examples of large projects that include a mention to all contributors in the copyright.

**[Spring Projects](https://github.com/spring-projects/)**
> Copyright 2002-2019 **the original author or authors**.

**[RxJava](https://github.com/ReactiveX/RxJava)**
> Copyright (c) 2016-present, **RxJava Contributors**.

**[Mockito](https://github.com/mockito/mockito)**
> Copyright (c) 2007 **Mockito contributors**

**[JUnit](https://github.com/junit-team/junit5)**
> Copyright 2015-2020 **the original author or authors**.

**Comment by eshellman** [comment]
probably a good idea to add `and contributors`
