### ISSUE TITLE
volunteers needed to clean up the backlog

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#4853]
As Hacktoberfest nears its end, I can see that we're going to need help cleaning out the backlog. There are likely many moot PRs, others that just need a space added, and some where the proposed resource needs a bit of investigation. If you'd like to help leave a not here and I'll invite you to a slack channel or something like that where we can organize and discuss.

**Comment by SethiPandi** [comment]
> If you'd like to help leave a not here

Is that meant to say "note here"? If so, I wanted to help clean up after Hacktoberfest was over anyway, so I'd be down if it's not a bother.

---

> slack channel or something like that

By the wording, it sounds like the Slack channel doesn't exist yet? You can use whatever you feel is appropriate, but just wanted to put forward a suggestion. [Matrix](https://matrix.org/) might be a cool solution instead. It's free and open-source, end-to-end encrypted, and it's a standard, so people can use their preferred client to interact ie [Element](https://element.io/), [Thunderbird](https://www.thunderbird.net/en-US/), or [Fractal](https://wiki.gnome.org/Apps/Fractal) etc

**Comment by kadhirash** [comment]
Count me in!

**Comment by eshellman** [comment]
As a non-profit, Slack lets us have an upgraded slack for free. (just need to make a channel in the slack. And yes, @SethiPandi a NOTE. You're good at catching those! @kadhirash - excellent, I'll send invites.

**Comment by eshellman** [comment]
Invites sent. maybe @borgified, @charlottetan, @mcicolella, @MrS4w, @quobit would like to join the slack channel.

**Comment by quobit** [comment]
I'll try. Nowadays I'm short of time but I'll do my best. Anyway solving few PR are better than none. Send me an invite.

**Comment by borgified** [comment]
hi! thanks for including me. yes please inv me to the slack channel too. ty

**Comment by eshellman** [comment]
@quobit send me an email eric at ebookfoundation org

**Comment by kakashi215** [comment]
I'd also like to help up on this!!

**Comment by dev4s** [comment]
Well, I can help as well :)

**Comment by charlottetan** [comment]
Yay! I'll join but am not really a slack person. I'll pop in every so often!

**Comment by MrS4w** [comment]
You can count on me @eshellman 😄

**Comment by brunomguimaraes** [comment]
Count me on! @eshellman

**Comment by eshellman** [comment]
@dev4s @brunomguimaraes what would you like to work on? I'm not sure how familiar you are with F-P-B. Happy to suggest things based on your interests.

**Comment by brunomguimaraes** [comment]
@eshellman F-P-B was one of my main sources of knowledge back in the day and I just want to return the favor. 
I speak english and portuguese(PT-BR)

**Comment by eshellman** [comment]
@brunomguimaraes The pt-BR courses list is one of our biggest and has seen a lot of recent additions, including a number of pending. Right now the priority is to clear out the pending - often the new contributors don't know to look at the linter output or to fix conflicts - friendly comments are appreciated.

**Comment by dev4s** [comment]
@eshellman I speak English and Polish (my main language), so I can help with those PRs. I was using similar repos, like the [Awesome-awesomeness](https://github.com/bayandin/awesome-awesomeness) or [Awesome](https://github.com/sindresorhus/awesome). And as @brunomguimaraes I want to return some of the favor ;)

**Comment by eshellman** [comment]
Thanks @dev4s

**Comment by eshellman** [comment]
I see @brunomguimaraes has helped out on a number of PRs - Thanks!

**Comment by eshellman** [comment]
Thanks everyone!
