### ISSUE TITLE
Travis Issues

### ISSUE THREAD

**Issue by Umarovislam** [EbookFoundation/free-programming-books#4858]
Make sure that travis configs are correct and redeploy

**Comment by eshellman** [comment]
@Umarovislam I assume you're referring to the issues we've been having with Travis-CI occasionally failing to run the linter tests during Hacktoberfest. For you and anyone else have issues with the linter, the easiest way to get Travis-CI to run or to re-run is to close and reopen the PR.

One consequence of the volume and the missing Travis builds is that twice over the last week we've merged build-breaking commits, causing PRs to fail for no reason related to the PR. If you affected by on of these incidents, we tried to close and re-open affected PRs. If we've missed any of these, try closing and reopening your PR.

Volunteers have been helping to advise builds that have failed the linter. They're not perfect but in most cases you should take their advice!

**Comment by Umarovislam** [comment]
gotcha
