### ISSUE TITLE
Found some duplicate and redirecting Links

### ISSUE THREAD

**Issue by U-C-S** [EbookFoundation/free-programming-books#4892]
Example in Bash and C#:
<pre>
* [Bash Notes](https://goalkicker.com/BashBook) (PDF)
* [Bash Notes for Professionals](http://books.goalkicker.com/BashBook/) - Compiled from StackOverflow documentation (3.x) (PDF)
</pre>
<pre>
* [C# Notes](https://goalkicker.com/CSharpBook) (PDF)
* [C# Notes for Professionals](http://books.goalkicker.com/CSharpBook/) - Compiled from StackOverflow documentation (3.x)
</pre>

Here, books.goalkicker.com is re-directed to goalkicker.com

And

This books.goalkicker.com is used in few other places
<pre>
* [Git Notes](http://books.goalkicker.com/GitBook) (PDF)
</pre>
I suggest to go with the original: Goalkicker.com for all the redirects.

**Comment by eshellman** [comment]
yes please!
