### ISSUE TITLE
Books for Angular, Not AngularJS

### ISSUE THREAD

**Issue by U-C-S** [EbookFoundation/free-programming-books#4940]
While I was doing a PR (#4898), I found that there are only 2 books posted here for the latest Angular Framework that too in the AngularJS section.

Angular != AngularJS

- The AngularJS is old (2014-15), it's the version1.x
- When it reached v2, The developers of it decided to [rename](https://en.wikipedia.org/wiki/Angular_(web_framework)#Naming) it Angular. 
- So, Angular is the latest (Currently, latest release has a version of 10.x).

I suggest to either open a new section for Angular or differentiate the existing b/w AngularJS and Angular.
One book  I know for it is the official website [docs](https://angular.io/docs).

**Comment by SethiPandi** [comment]
I strongly agree with this, it's especially a problem when a resource is named at the source as AngularJS, but gets put in the repo as Angular.js which I've commented on in the past. It's unclear if Angular.js is even referring to Angular or AngularJS.

AngularJS is version 1, something which has been deprecated for a long time, and will no longer get updates after 2020.  
Angular is the current version of Angular, which most people learning about it probably only care for this one.

**Comment by eshellman** [comment]
Good idea to separate the two. When you do it, you might look through pending PRs so new items don't go in the wrong place.

**Comment by U-C-S** [comment]
While the above PR (#5124) only adds a couple of books in english, There are still others (free-courses and other languages) that might have this issue.

I think this Issue should stay open for a while

**Comment by eshellman** [comment]
thanks @U-C-S

**Comment by davorpa** [comment]
I'm currently reviewing this in other files

**Comment by eshellman** [comment]
reopen as an issue; not practical to use as a PR
