### ISSUE TITLE
Broken or Redirected Links in free-programming-books.md

### ISSUE THREAD

**Issue by kadhirash** [EbookFoundation/free-programming-books#5063]
A list of some of the broken or redirected links I came to find:

System Info:
 - macOS Catalina: Version 10.15.7
 - Tested on Brave, Firefox, and Chrome browsers

- School of Data Handbook (http://schoolofdata.org/handbook/) -> 503 error 
  - Broken
  - Found under Language Agnostic, Datamining
  - Works fine on Chrome for me, however. 

- Exploring CQRS and Event Sourcing (https://msdn.microsoft.com/en-us/library/jj554200.aspx) -> 403 error
  - Redirected to (https://docs.microsoft.com/en-us/previous-versions/msp-n-p/jj554200(v=pandp.10) which actually leads to a download page at https://www.microsoft.com/en-us/download/details.aspx?id=34774
  - Found under Language Agnostic, Software Architecture

- Java Programming (https://en.wikibooks.org/wiki/Java_Programming/) -> 404 error
  - Broken
  - The correct link should be: https://en.wikibooks.org/wiki/Java_Programming (no trailing slash at the end)
  - Found under Java

**Comment by eshellman** [comment]
school of data does a lot of "inspecting browser"!

**Comment by davorpa** [comment]
> school of data does a lot of "inspecting browser"!

Me too. Even cleaning cookies or IP change.

>   * Broken
>   * Found under Language Agnostic, Datamining
>   * Works fine on Chrome for me, however.
> * Exploring CQRS and Event Sourcing (https://msdn.microsoft.com/en-us/library/jj554200.aspx) -> 403 error
>   
>   * Redirected to (https://docs.microsoft.com/en-us/previous-versions/msp-n-p/jj554200(v=pandp.10) which actually leads to a download page at https://www.microsoft.com/en-us/download/details.aspx?id=34774
>   * Found under Language Agnostic, Software Architecture
> * Java Programming (https://en.wikibooks.org/wiki/Java_Programming/) -> 404 error

Its not mantained anymore. I think it could be fixed only removing redirection. Also, it has downloadable content like exercises too. Then, maybe better link to page instead download directly (it's more general)

BR

**Comment by eshellman** [comment]
thanks!
