### ISSUE TITLE
Broken or redirected links in free-courses-en.md

### ISSUE THREAD

**Issue by kadhirash** [EbookFoundation/free-programming-books#5112]
### C++
- Microsoft edX Courses:
  - Advanced C++ (https://www.edx.org/course/advanced-c-plus-plus-1)
  - Intermediate C++ (https://www.edx.org/course/intermediate-c-plus-plus-1)
  -  Introduction to C++ (https://www.edx.org/course/introduction-c-plus-plus-1) --> redirects to https://www.edx.org/course/introduction-to-c-3 but classes currently unavailable.

### Python
- Introduction to Python for Data Science (https://www.edx.org/course/introduction-python-data-science-microsoft-dat208x-3). --> Also another Microsoft course 

### Machine Learning
- Principles of Machine Learning By Microsoft (https://www.edx.org/course/principles-machine-learning-microsoft-dat203-2x-6)

### Mercurial
- Hg Init: a Mercurial Tutorial (http://hginit.com)

### Misc
- FindLectures.com (https://www.findlectures.com/?class1=Technology)

**Comment by computamike** [comment]
The loss of content is going to be continued issue - I wonder if there has been any thought around (where possible) mirroring this content on the Internet Archive?

We could have a spider vsit each link on the page, and if it gets a suitable response back, could flag that entry as being incomplete).  This would be very similar to a linter.  Something to visit each page, and visit each link in the page, and test each link that it is returning a 200.  We could schedule this as a GitHub Action, and create a ticket where appropriate.

**Comment by eshellman** [comment]
@computamike in fact we have a Github action that checks links on every changed page. it always passes because the links rarely fail fail because of the changed content. The other issue is that there's the false failure rate is significant.

The way the Github action works is suboptimal because it's a bit hard to find the links that are failing.

Improvements to the link checker action are very welcome!

With regard to archiving content listed in the repo, I'll talk to my friends at IA about doing some targeted archiving.

**Comment by davorpa** [comment]
> ### C++
> * Microsoft edX Courses:
>   
>   * Advanced C++ (https://www.edx.org/course/advanced-c-plus-plus-1)
>   * Intermediate C++ (https://www.edx.org/course/intermediate-c-plus-plus-1)
>   * Introduction to C++ (https://www.edx.org/course/introduction-c-plus-plus-1) --> redirects to https://www.edx.org/course/introduction-to-c-3 but classes currently unavailable.
>
> ### Python
> * Introduction to Python for Data Science (https://www.edx.org/course/introduction-python-data-science-microsoft-dat208x-3). --> Also another Microsoft course
>
> ### Machine Learning
> * Principles of Machine Learning By Microsoft (https://www.edx.org/course/principles-machine-learning-microsoft-dat203-2x-6)

All achieved / deprecated 🤔: https://www.edx.org/school/microsoft
No valid archive mirror 😣

> ### Mercurial
> * Hg Init: a Mercurial Tutorial (http://hginit.com)

Last mirror at 2018 Sept: https://web.archive.org/web/20180926172759/http://hginit.com/
Seems OK 🎉

> ### Misc
> * FindLectures.com (https://www.findlectures.com/?class1=Technology)

Last mirror at 2016 Dec: https://web.archive.org/web/20161219180842/https://www.findlectures.com/?class1=Technology
Only accesible first page 😣

**Comment by fake-rookie** [comment]
all `edx` link was wrong.

**Comment by eshellman** [comment]
agree

**Comment by davorpa** [comment]
Then... remove affected edx and add others as wayback machine?

**Comment by eshellman** [comment]
yes

**Comment by captn3m0** [comment]
Filing a PR for some fixes for hginit (there's a web archive link that needs replacing).

Anyone has suggestions on whether [HgInit](https://hginit.github.io/) classifies as a book or a course? It is currently repeated.

**Comment by davorpa** [comment]
> Filing a PR for some fixes for hginit (there's a web archive link that needs replacing).
> 
> Anyone has suggestions on whether [HgInit](https://hginit.github.io/) classifies as a book or a course? It is currently repeated.

You are right! I didn't realize about duplicated content 😳.

It's seems more like **book** than course due didn't it  doesn't depend on interactive content.
https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#genres

So **move from courses to books**. Remember also remove Mercurial section from courses TOC 😉.

Refer link to this issue on fix push/commit: `EbookFoundation/free-programming-books#5112` as I like did.

Thnx
