### ISSUE TITLE
CONTRIBUTING.md link for PRs is incorrect

### ISSUE THREAD

**Issue by ianchanning** [EbookFoundation/free-programming-books#5190]
The contributing link for PRs is broken it goes to https://github.com/CONTRIBUTING.md instead of https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md

You can see either my recent PR https://github.com/EbookFoundation/free-programming-books/pull/5189 or the previous one to that https://github.com/EbookFoundation/free-programming-books/pull/5188 they both have contributing links that go to the wrong place.

**Comment by eshellman** [comment]
I can't reproduce the problem, but I not that the CONTRIBUTING.md link on https://ebookfoundation.github.io/free-programming-books/ doesn't get rendered to HTML

**Comment by ianchanning** [comment]
As far as I can tell its because in the PR template it begins with a /

```
- [ ] Read our [contributing guidelines](/CONTRIBUTING.md)
```

**Comment by kadhirash** [comment]
Closing as the issue is resolved with PR #5226
