### ISSUE TITLE
2 incorrect links in the Competitive Programming section of Free Programming Books

### ISSUE THREAD

**Issue by TrevCan** [EbookFoundation/free-programming-books#5204]
As the title says, there are two 'broken' links in the **Competitive Programming** section of [free-programming-books.md](https://github.com/EbookFoundation/free-programming-books/blob/master/books/free-programming-books.md#competitive-programming)
**(1)** The first one is the [Competitive Programmer's Handbook](https://cses.fi/book.html) (https://cses.fi/book.html) - Antti Laaksonen (PDF). This links is incorrect because it redirects to another [webpage ](https://cses.fi/book/index.php)linking several lists of books. **The correct link is https://cses.fi/book/book.pdf**

**(2)** The second broken link is [Competitive Programming, 1st Edition (PDF)](https://cpbook.net/#CP1details) (https://cpbook.net/#CP1details) as it is not even a PDF file and I was not able to see the content at all, just a summary of each chapter/section. I do not know if there is a working link for this book.

**Comment by Fleefly20** [comment]
thanks
