### ISSUE TITLE
Additional Texbooks for Math Section

### ISSUE THREAD

**Issue by chir4gm** [EbookFoundation/free-programming-books#5206]
There are a few math textbooks indexed here (some of them are already in the list):
https://aimath.org/textbooks/approved-textbooks/

**Comment by prabhath75** [comment]
let me edit

**Comment by subhamgcon** [comment]
Is this issue still open?
Can i add any math book which will be help for engineering students?

**Comment by LuigiImVector** [comment]
> Can i add any math book which will be help for engineering students?

Yes, you can open an issue writing the name(s) of the book(s) you want to insert and then some staffer will insert them or you can directly create a pull request. Read [CONTRIBUTING.md](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md) for more information.

**Comment by LuigiImVector** [comment]
Solved in #5256
