### ISSUE TITLE
Broken link in free-programming-books-pt_BR.md

### ISSUE THREAD

**Issue by littlejuh** [EbookFoundation/free-programming-books#5229]
Hi everyone, I found an issue in Portuguese free books lis. 
The link to "Ruby on Rails - Desenv. Ágil para Web com Ruby on Rails - Caelum" in [Portuguese(Brazil)](free-programming-books-pt_BR.md)  are broken. I cannot find the originals.

Also thank you for maintaining this repo.

**Comment by davorpa** [comment]
#5231 should close this 🤔
