### ISSUE TITLE
Potentially broken links in free-programming-books.md

### ISSUE THREAD

**Issue by GintasS** [EbookFoundation/free-programming-books#5232]
I scanned the file via HTTP link checker and go this:

Error: https://github.com/practicingruby/rbp-book/tree/gh-pages/pdfs on line 2588 is unreachable.
Error: https://github.com/mdipierro/nlib on line 336 is unreachable.
Error: https://github.com/google/styleguide/blob/gh-pages/objcguide.md on line 2159 is unreachable.
Error: http://stephane.ducasse.free.fr/FreeBooks.html on line 254 is unreachable.
Error: http://stephane.ducasse.free.fr/FreeBooks/ on line 271 is unreachable.
Error: https://cloud4scieng.org/chapters/ on line 381 is unreachable.
Error: https://docs.blender.org/manual/en/latest on line 283 is unreachable.
Error: http://homepages.inf.ed.ac.uk/rbf/BOOKS/BANDB/bandb.htm on line 427 is unreachable.
Error: http://homepages.inf.ed.ac.uk/rbf/BOOKS/PHILLIPS/ on line 644 is unreachable.
Error: https://people.math.gatech.edu/~cain/winter99/complex.html on line 545 is unreachable.
Error: https://people.math.gatech.edu/~herod/Hspace/Hspace.html on line 570 is unreachable.
Error: https://people.math.gatech.edu/~cain/notes/calculus.html on line 576 is unreachable.
Error: http://home.iitk.ac.in/~arlal/book/la.pdf on line 567 is unreachable.
Error: http://web4.cs.ucl.ac.uk/staff/D.Barber/pmwiki/pmwiki.php?n=Brml.HomePage on line 491 is unreachable.
Error: https://intelligent-optimization.org/LIONbook/lionbook_3v0.pdf on line 519 is unreachable.
Error: https://mitpress.ublish.com/ereader/7093/?preview=#page/Cover on line 496 is unreachable.
Error: https://pi.math.cornell.edu/~hatcher/AT/ATpage.html on line 532 is unreachable.
Error: https://mitpress.ublish.com/ereader/77/?preview#page/Cover on line 542 is unreachable.
Error: https://ithemes.com/wp-content/uploads/downloads/2012/09/10-keys-to-great-landing-pages-eBook.pdf on line 606 is unreachable.
Error: https://www.math.ucdavis.edu/~linear/linear-guest.pdf on line 568 is unreachable.
Error: http://book.mixu.net/distsys/single-page.html on line 701 is unreachable.
Error: https://open.sap.com on line 689 is unreachable.
Error: https://open.hpi.de on line 688 is unreachable.
Error: http://pages.di.unipi.it/ricci/501302.pdf on line 711 is unreachable.
Error: http://pages.cs.wisc.edu/~remzi/OSTEP/ on line 745 is unreachable.
Error: https://us.fixstars.com/products/opencl/book/OpenCLProgrammingBook/contents/ on line 768 is unreachable.
Error: https://papl.cs.brown.edu/2019/ on line 892 is unreachable.
Error: https://pages.apigee.com/rs/apigee/images/api-design-ebook-2012-03.pdf on line 868 is unreachable.
Error: https://download.microsoft.com/download/0/F/B/0FBFAA46-2BFD-478F-8E56-7BF3C672DF9D/Introducing%20ASP.NET%20Web%20Pages%202.pdf on line 983 is unreachable.
Error: https://bash.cyberciti.biz/guide/Main_Page on line 1049 is unreachable.
Error: http://daly.axiom-developer.org/clojure.pdf on line 1188 is unreachable.
Error: https://ptolemy.berkeley.edu/books/leeseshia/releases/LeeSeshia_DigitalV2_2.pdf on line 1329 is unreachable.
Error: https://archive.org/details/JavaJavaJavaObject-orientedProblemSolving/page/n0 on line 1635 is unreachable.
Error: http://singlepageappbook.com on line 1743 is unreachable.
Error: https://singlepagebook.supportbee.com on line 1780 is unreachable.
Error: https://www.dashingd3js.com/table-of-contents on line 1794 is unreachable.
Error: https://www.math.ust.hk/~machas/scientific-computing.pdf on line 2065 is unreachable.
Error: https://www.cs.cornell.edu/courses/cs3110/2019sp/textbook/ on line 2169 is unreachable.
Error: http://phpsec.org/projects/guide/ on line 2239 is unreachable.
Error: http://www.obeythetestinggoat.com/pages/book.html on line 2450 is unreachable.
Error: http://www.burns-stat.com/pages/Tutor/R_inferno.pdf on line 2537 is unreachable.
Error: https://ruby-doc.org/docs/ruby-doc-bundle/UsersGuide/rg/index.html on line 2596 is unreachable.
Error: http://homepages.inf.ed.ac.uk/stg/NOTES/ on line 2810 is unreachable.
Error: https://www.red-gate.com/products/sql-development/sql-source-control/entrypage/sql-server-source-control-basics on line 2795 is unreachable.
Error: https://leanpub.com/thebigbookofpowershellerrorhandling on line 2320 is unreachable.
Error: https://en.wikibooks.org/wiki/Clipper_Tutorial%3A_a_Guide_to_Open_Source_Clipper(s on line 2963 is unreachable.
Error: https://homepages.uc.edu/~thomam/Intro_Unix_Text/TOC.html on line 2889 is unreachable.
Error: http://www-inst.eecs.berkeley.edu/~cs61b/fa14/book2/data-structures.pdf on line 339 is unreachable.
Error: http://ocw.mit.edu/courses/mathematics/18-05-introduction-to-probability-and-statistics-spring-2014/ on line 560 is unreachable.
Error: http://ocw.mit.edu/ans7870/resources/Strang/Edited/Calculus/Calculus.pdf on line 540 is unreachable.
Error: http://ocw.mit.edu/resources/res-6-004-principles-of-computer-system-design-an-introduction-spring-2009/online-textbook/part_ii_open_5_0.pdf on line 668 is unreachable.
Error: http://ocw.mit.edu on line 686 is unreachable.
Error: http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-02-introduction-to-eecs-ii-digital-communication-systems-fall-2012/readings/ on line 697 is unreachable.
Error: http://www.sp4comm.org on line 626 is unreachable.
Error: http://cs.gmu.edu/~sean/book/metaheuristics/ on line 555 is unreachable.
Error: http://people.math.umass.edu/~lavine/Book/book.html on line 562 is unreachable.
Error: http://cnx.org/contents/5e0744f9-9e79-4348-9237-ed012213a2d6%4040.9 on line 544 is unreachable.
Error: http://www.cse.buffalo.edu/~rapaport/Papers/phics.pdf on line 664 is unreachable.
Error: https://www.owasp.org/images/1/19/OTGv4.pdf on line 828 is unreachable.
Error: http://cyber.law.harvard.edu/wealth_of_networks/Main_Page on line 735 is unreachable.
Error: http://pages.tacc.utexas.edu/~eijkhout/istc/istc.html on line 763 is unreachable.
Error: http://www-inst.eecs.berkeley.edu/~cs61a/sp12/book/ on line 2447 is unreachable.
Error: http://www.cse.buffalo.edu/~shapiro/Commonlisp/ on line 2000 is unreachable.
Error: http://homepages.mcs.vuw.ac.nz/~tk/fps/fps-sans-escher.pdf on line 1291 is unreachable.
Error: https://itunes.apple.com/us/book/using-swift-cocoa-objective/id888894773?mt=11 on line 2828 is unreachable.
Error: http://use-the-index-luke.com on line 2769 is unreachable.
Error: http://blogs.msdn.com/b/microsoft_press/archive/2014/04/02/free-ebook-introducing-microsoft-sql-server-2014.aspx on line 2782 is unreachable.
Error: http://addyosmani.github.io/backbone-fundamentals/ on line 1781 is unreachable.
Error: http://effbot.org/librarybook/ on line 2457 is unreachable.
Error: http://www.cs.bu.edu/teaching/unix/reference/ on line 2891 is unreachable.
Error: http://www.linuxfromscratch.org/alfs/download.html on line 1958 is unreachable.
Error: http://www.linuxfromscratch.org/lfs/view/stable/ on line 1972 is unreachable.
Error: http://www.red-gate.com/products/sql-development/sql-prompt/entrypage/sql-query-optimizer-ebook3 on line 2779 is unreachable.
Error: http://www-01.ibm.com/support/docview.wss?uid=swg27036733 on line 1202 is unreachable.
Error: https://pages.apigee.com/oauth-big-picture-ebook.html on line 853 is unreachable.
Error: http://www.cs.berkeley.edu/~bh/ss-toc2.html on line 2705 is unreachable.
Error: http://python-ebook.blogspot.co.uk on line 2401 is unreachable.
Error: https://www.packtpub.com/free-ebooks/hands-cloud-administration-azure on line 384 is unreachable.
Error: https://www.packtpub.com/free-ebooks/artificial-intelligence-big-data on line 367 is unreachable.
Error: https://www.packtpub.com/free-ebooks/docker-cookbook-second-edition on line 436 is unreachable.
Error: https://usborne.com/browse-books/features/computer-and-coding-books/ on line 1009 is unreachable.
Error: https://www.packtpub.com/free-ebooks/full-stack-react-projects on line 1868 is unreachable.
Error: https://www.packtpub.com/free-ebooks/effective-devops-aws-second-edition on line 630 is unreachable.
Error: https://www.packtpub.com/free-ebooks/java-projects-second-edition on line 1640 is unreachable.
Error: https://www.packtpub.com/free-ebooks/industrial-cybersecurity on line 645 is unreachable.
Error: https://www.packtpub.com/free-ebooks/kubernetes-cookbook-second-edition on line 438 is unreachable.
Error: https://www.packtpub.com/free-ebooks/mastering-opencv-4-third-edition on line 430 is unreachable.
Error: https://www.packtpub.com/free-ebooks/big-data-analytics-hadoop-3 on line 1487 is unreachable.
Error: https://www.packtpub.com/free-ebooks/mastering-ros-robotics-programming-second-edition on line 655 is unreachable.
Error: https://www.packtpub.com/free-ebooks/serverless-design-patterns-and-best-practices on line 860 is unreachable.
Error: https://www.packtpub.com/free-ebooks/mastering-xamarin-ui-development-second-edition on line 1129 is unreachable.
Error: https://www.packtpub.com/free-ebooks/python-machine-learning-example on line 2437 is unreachable.
Error: https://www.packtpub.com/free-ebooks/building-applications-spring-5-and-vuejs-2 on line 1673 is unreachable.
Error: https://www.packtpub.com/free-ebooks/kali-linux-2018-assuring-security-penetration-testing-fourth-edition on line 1963 is unreachable.
Error: https://www.packtpub.com/free-ebooks/django-restful-web-services on line 2473 is unreachable.
Error: https://www.packtpub.com/free-ebooks/sql-server-2017-administrators-guide on line 2788 is unreachable.
Error: https://www.packtpub.com/free-ebooks/mastering-internet-things on line 1596 is unreachable.
Error: https://www.packtpub.com/free-ebooks/learn-python-programming-second-edition on line 2405 is unreachable.
Error: https://www.packtpub.com/free-ebooks/blockchain-example on line 616 is unreachable.
Error: https://www.packtpub.com/free-ebooks/expert-delphi on line 1275 is unreachable.
Error: https://www.packtpub.com/free-ebooks/software-architecture-spring-50 on line 1674 is unreachable.
Error: https://www.packtpub.com/free-ebooks/learn-powershell-core-60 on line 2311 is unreachable.
Error: https://www.packtpub.com/free-ebooks/splunk-7x-quick-start-guide on line 2760 is unreachable.

**Comment by eshellman** [comment]
I tried 3 of the links. one (a packt) book, was dead. We should probably remove the packt links. another - a gatech link, was https but should be http. The github objcguide like worked fine.

Are you looking at the link checker we run as a github action?

Bad links should be removed; it's tedious to check all of them, and we very much appreciate the PRs.

**Comment by GintasS** [comment]
> I tried 3 of the links. one (a packt) book, was dead. We should probably remove the packt links. another - a gatech link, was https but should be http. The github objcguide like worked fine.
> 
> Are you looking at the link checker we run as a github action?
> 
> Bad links should be removed; it's tedious to check all of them, and we very much appreciate the PRs.

I used local extension on my Visual Studio Code, well, I just thought pasting them here if someone want to help 👍

**Comment by eshellman** [comment]
5 days ago, the link-checking action found only 6 problems (I think it ignores some problems due to common false failure):   
1. [L0449]  http://people.cs.aau.dk/~csj/Thesis/ Net::ReadTimeout 
  2. [L0462] 503 http://schoolofdata.org/handbook/  
  3. [L0567] 404 http://home.iitk.ac.in/~arlal/book/la.pdf  
  4. [L0842] 403 https://msdn.microsoft.com/en-us/library/jj554200.aspx  
  5. [L1187] 404 http://daly.axiom-developer.org/clojure.pdf  
  6. [L2238] 404 http://phpsec.org/projects/guide/  

only #3 appears in your list!

**Comment by Astrodevil** [comment]
![scr](https://user-images.githubusercontent.com/73425223/104190565-4957d600-5442-11eb-8e01-f9bc4af9efc0.png)


- I clicked the link & i founds these links are not reachable,

- Specially related to this website https://www.packtpub.com

- Its not loading anyting.


Error: https://www.packtpub.com/free-ebooks/hands-cloud-administration-azure on line 384 is unreachable.
Error: https://www.packtpub.com/free-ebooks/artificial-intelligence-big-data on line 367 is unreachable.
Error: https://www.packtpub.com/free-ebooks/docker-cookbook-second-edition on line 436 is unreachable.
Error: https://www.packtpub.com/free-ebooks/full-stack-react-projects on line 1868 is unreachable.
Error: https://www.packtpub.com/free-ebooks/effective-devops-aws-second-edition on line 630 is unreachable.
Error: https://www.packtpub.com/free-ebooks/java-projects-second-edition on line 1640 is unreachable.
Error: https://www.packtpub.com/free-ebooks/industrial-cybersecurity on line 645 is unreachable.
Error: https://www.packtpub.com/free-ebooks/kubernetes-cookbook-second-edition on line 438 is unreachable.
Error: https://www.packtpub.com/free-ebooks/mastering-opencv-4-third-edition on line 430 is unreachable.
Error: https://www.packtpub.com/free-ebooks/big-data-analytics-hadoop-3 on line 1487 is unreachable.
Error: https://www.packtpub.com/free-ebooks/mastering-ros-robotics-programming-second-edition on line 655 is unreachable.
Error: https://www.packtpub.com/free-ebooks/serverless-design-patterns-and-best-practices on line 860 is unreachable.
Error: https://www.packtpub.com/free-ebooks/mastering-xamarin-ui-development-second-edition on line 1129 is unreachable.
Error: https://www.packtpub.com/free-ebooks/python-machine-learning-example on line 2437 is unreachable.
Error: https://www.packtpub.com/free-ebooks/building-applications-spring-5-and-vuejs-2 on line 1673 is unreachable.
Error: https://www.packtpub.com/free-ebooks/kali-linux-2018-assuring-security-penetration-testing-fourth-edition on line 1963 is unreachable.
Error: https://www.packtpub.com/free-ebooks/django-restful-web-services on line 2473 is unreachable.
Error: https://www.packtpub.com/free-ebooks/sql-server-2017-administrators-guide on line 2788 is unreachable.
Error: https://www.packtpub.com/free-ebooks/mastering-internet-things on line 1596 is unreachable.
Error: https://www.packtpub.com/free-ebooks/learn-python-programming-second-edition on line 2405 is unreachable.
Error: https://www.packtpub.com/free-ebooks/blockchain-example on line 616 is unreachable.
Error: https://www.packtpub.com/free-ebooks/expert-delphi on line 1275 is unreachable.
Error: https://www.packtpub.com/free-ebooks/software-architecture-spring-50 on line 1674 is unreachable.
Error: https://www.packtpub.com/free-ebooks/learn-powershell-core-60 on line 2311 is unreachable.
Error: https://www.packtpub.com/free-ebooks/splunk-7x-quick-start-guide on line 2760 is unreachable.

**Comment by eshellman** [comment]
yep, they're still dead. Time to delete these packtpub links.

**Comment by SethFalco** [comment]
Seems that some of them, probably all but didn't check each one, have just shifted from `/free-ebooks` to `/products`.

for example  
https://www.packtpub.com/free-ebooks/hands-cloud-administration-azure  
redirects to  
https://www.packtpub.com/free-ebooks/virtualization-and-cloud/hands-cloud-administration-azure/9781789134964  
which is no longer free and has been moved to  
https://www.packtpub.com/product/hands-on-cloud-administration-in-azure/9781789134964

They still aren't free, so should still be removed. Just wanted to note on this issue that the resources haven't been removed, but they were previously free resources that just had a price put on them.
