### ISSUE TITLE
Rename "Language Agnostic"?

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#5249]
Based on the categories in "Language Agnostic", I'm thinking it would be better to call it "By Topic" or "By Subject" and create "By Language" for the rest. This could be also be a useful way to split the too-long books list into two files.

Opinions/ Feedback?

**Comment by kadhirash** [comment]
I think renaming it to "By Topic" would be great based on what's currently there as it lists specific concepts such as "Algorithms and Data Structures" and "Cloud Computing"

**Comment by SethFalco** [comment]
Just to clarify, do you mean like?

* By Language
  * Java
  * Python 
  * ...
* By Topic
  * Cloud Computing
  * Kubernetes
  * ...

As the table of contents, and the body of the document reflecting this structure?

**Comment by eshellman** [comment]
Yes

**Comment by SethFalco** [comment]
I'd be a fan of this change then personally.
It seems like a more logical way to present the categories I think, and it'll be nice to have all the languages together rather than split only by a single non-language category.

**Comment by eshellman** [comment]
SICP is in "Theoretical Computer Science" - we have SEVEN versions. The new contributor perspective is really valuable; MAYbe MAY is a good time to do this.

**Comment by espertus** [comment]
My bad, I searched on the author name, not on the title. I would not have expected it under Theoretical Computer Science, but I have no excuse for not searching. 😳

For what little it's worth, I like the proposal to split up the list by language and by topic. I would want to know whether it's okay to put a given book into both lists.

**Comment by davorpa** [comment]
As a contributor I like @SethFalco suggestion

**Comment by rca1943** [comment]
Absolute newbie here: how about something similar such as "language independent"?
