### ISSUE TITLE
انت شخص رائح حقا تستحق قلب

### ISSUE THREAD

**Issue by doaashasho** [EbookFoundation/free-programming-books#5291]
❤
<a  href="https://www.aflam-4you.com">&nbsp;</a>

**Comment by SethFalco** [comment]
Translation: You are a really wonderful person, you deserve a heart 

Closing this since there isn't a clear request or scope of work associated with it.
Meanwhile, I'm sure all the contributors appreciate your compliment! \\(^-^)/
