### ISSUE TITLE
اعادة توجيه الروابط

### ISSUE THREAD

**Issue by doaashasho** [EbookFoundation/free-programming-books#5292]
الروابط المعطلة broken link ❤
<a  href="https://www.aflam-4you.com/2021/02/tawakkalna-apk.html">&nbsp;</a>

**Comment by doaashasho** [comment]
حل مشكلة broken link ❤
<a  href="https://www.aflam-4you.com/2021/02/tawakkalna-apk.html">&nbsp;</a>

**Comment by eshellman** [comment]
we run a link checker on every submission
