### ISSUE TITLE
ماهي هذه الكتب البرمجية

### ISSUE THREAD

**Issue by doaashasho** [EbookFoundation/free-programming-books#5293]
❤ ماهي الكتب لديك
<a  href="https://www.aflam-4you.com">&nbsp;</a>

**Comment by SethFalco** [comment]
Translation: What books do you have? 

---

This repository does not store books itself, but if you browse the repository you'll find links for many books.

Assuming Google Translate was correct, it seems you're familiar with Arabic, so you can visit the files which are `...-ar.md` which contain resources in Arabic.

See the following for books for example:
https://github.com/EbookFoundation/free-programming-books/blob/master/books/free-programming-books-ar.md

--- 

لا يقوم هذا المستودع بتخزين الكتب بنفسه ، ولكن إذا قمت بتصفح المستودع ، فستجد روابط للعديد من الكتب.

بافتراض صحة ترجمة Google ، يبدو أنك على دراية باللغة العربية ، لذا يمكنك زيارة الملفات `...- ar.md` التي تحتوي على موارد باللغة العربية.

انظر ما يلي للكتب على سبيل المثال:
https://github.com/EbookFoundation/free-programming-books/blob/master/books/free-programming-books-ar.md
