### ISSUE TITLE
Coding

### ISSUE THREAD

**Issue by ikergbaque** [EbookFoundation/free-programming-books#5295]

**Comment by SethFalco** [comment]
Closing this since there isn't a clear request or scope of work associated with it.
Feel free to open another issue if you're able to better describe a problem or request.

**Comment by eshellman** [comment]
definitely

**Comment by ikergbaque** [comment]
oh my bad. I'm new. I did not k ow how to save the post.
My apologies

**Comment by ikergbaque** [comment]
> Closing this since there isn't a clear request or scope of work associated with it.
> 
> Feel free to open another issue if you're able to better describe a problem or request.

oh my bad. I'm new. I did not know how to save the post. So "I put the name **coding**" . 
My apologies
