### ISSUE TITLE
An online Golang study lesson from Microsoft

### ISSUE THREAD

**Issue by zhoufoxcn** [EbookFoundation/free-programming-books#5325]
An online Golang study lesson from Microsoft,the url is:
[https://docs.microsoft.com/zh-cn/learn/paths/go-first-steps/](url)

**Comment by GintasS** [comment]
Where this should go? Tutorials, books? Since this an interactive one, so maybe a new file with **free-interactive-tutorials-zh-cn** ?

**Comment by eshellman** [comment]
I guess it would be better to start free-courses-zh_cn

**Comment by GintasS** [comment]
Ok then, maybe I have to time to add PR for this.

**Comment by GintasS** [comment]
Added this in PR: #5331.

**Comment by fake-rookie** [comment]
https://docs.microsoft.com/en-us/learn/paths/go-first-steps/

This is the `English` version.

**Comment by GintasS** [comment]
> https://docs.microsoft.com/en-us/learn/paths/go-first-steps/
> 
> This is the `English` version.

Will add this in the new PR.

**Comment by GintasS** [comment]
I'm voting to close this because it has been fixed.

**Comment by GintasS** [comment]
I'm voting to close this because it has been fixed.

**Comment by eshellman** [comment]
@GintasS if you title the PR "fixes #issuenum" the issue gets closed automatically when the PR is accepted.
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by GintasS** [comment]
Thanks, now I'll know!

**Comment by brian474** [comment]
肉肉肉肉
