### ISSUE TITLE
The .NET framework Issue

### ISSUE THREAD

**Issue by U-C-S** [EbookFoundation/free-programming-books#5326]
Currently, There are 2 different .NET frameworks in the .NET World
- .NET Framework (latest is called .NET Framework 4.8)
- .NET Core (latest is called .NET 5)

Both have differences and similarities between them.
**.NET framework** is older one here and Microsoft recommends to use **.NET core**, which is currently updated yearly
The Naming here often confuses a lot of people who wants to learn this stuff (including me previously)

Same issue applies to ASP.NET and ASP.NET Core

#### But, this Repository only hosts the sections - .NET Framework and ASP.NET, each respectively includes both of the resources

For Reference: 
- [.NET Core history - Wikipedia](https://en.wikipedia.org/wiki/.NET_Core#History)
- [ASP.NET Core Naming - Wikipedia](https://en.wikipedia.org/wiki/ASP.NET_Core#Naming)

## What Can be done
Add two new Sections:
- ASP.NET Core
- .NET Core / .NET

And Rearrange the books to them

**Comment by eshellman** [comment]
Good idea!

**Comment by davorpa** [comment]
I think this is already solved and merged by #5327 😉
