### ISSUE TITLE
book solidity thailand 

### ISSUE THREAD

**Issue by ez-kraivit** [EbookFoundation/free-programming-books#5357]
[solidity](https://github.com/Solidity-Thailand)

**Comment by eshellman** [comment]
not a book is it?

**Comment by ez-kraivit** [comment]
It is a documentation for solidity languages. I expect annotation information to be added.

**Comment by rutujak24** [comment]
I can add this. Please assign me this issue

**Comment by davorpa** [comment]
> I can add this. Please assign me this issue

@rutujak24 What about your assignement?

**Comment by LuigiImVector** [comment]
the project has not been updated since April 2021 and it isn't appropriate to be added, I think this issue can be closed
