### ISSUE TITLE
Broken link for C++ cheat sheet : https://www.hoomanb.com/cs/quickref/CppQuickRef.pdf

### ISSUE THREAD

**Issue by sjharb** [EbookFoundation/free-programming-books#5378]
The C++ cheat sheet PDF link is broken.

https://www.hoomanb.com/cs/quickref/CppQuickRef.pdf

**Comment by davorpa** [comment]
Can be solved changing to HTTP :wink: 

http://www.hoomanb.com/cs/quickref/CppQuickRef.pdf

**Comment by hartpoli** [comment]
> Can be solved changing to HTTP 😉
> 
> http://www.hoomanb.com/cs/quickref/CppQuickRef.pdf

----
Can it be opened?

**Comment by davorpa** [comment]
> > Can be solved changing to HTTP wink
> > http://www.hoomanb.com/cs/quickref/CppQuickRef.pdf
> 
> Can it be opened?

It's been solved actually at #5402

**Comment by davorpa** [comment]
Already fixed at #5440
