### ISSUE TITLE
Advanced Adobe XD for develpers

### ISSUE THREAD

**Issue by jayantbansal21** [EbookFoundation/free-programming-books#5379]
This course teaches about using photoshop, especially the skills that a develop should know, which sometimes comes really handy.

https://webdesign.tutsplus.com/courses/advanced-adobe-xd-for-everyone

**Comment by GintasS** [comment]
I'm taking this issue.

**Comment by SethFalco** [comment]
@GintasS Thanks for your contribution! 🎉 

Just a heads-up! If you wrote something like "Closes #5379" or "Fixes #5379" in the description or your PR, it would've closed this issue automatically.

**Comment by jayantbansal21** [comment]
> @GintasS Thanks for your contribution! 🎉
> 
> Just a heads-up! If you wrote something like "Closes #5379" or "Fixes #5379" in the description or your PR, it would've closed this issue automatically.

Ohh, I am new to open source contribution, thanks
