### ISSUE TITLE
Vim, A bite of Vim

### ISSUE THREAD

**Issue by cs102** [EbookFoundation/free-programming-books#5389]
FYI: The first book on the Vim category [A bite of Vim ](https://vim.swaroopch.com/) has a suspicious link with a possible virus on [Page 81, Link 16](https://github.com/cs102/pictures/blob/main/vim-suspicious.png), I added the link below if anyone wants to look at it in a Virtual Machine or a Safe Env. 

⚠️⚠️⚠️
[16] http://phraktured.net/vimmity-vim-vim.html
☠️☠️☠️

Thanks to everyone's hard work on this list.

**Comment by eshellman** [comment]
will check with  @swaroopch

**Comment by SethFalco** [comment]
Looks like back in 2008 it would've taken one to a page like this:
https://web.archive.org/web/20090208081230/http://phraktured.net/vimmity-vim-vim.html (2009 snapshot)

Unfortunately, today it redirects the user to a page with a tonne of requests that uBlock Origin blocks.

I could be wrong, but it looks to me like someone [domain sniped](https://en.wikipedia.org/wiki/Domain_drop_catching) and [parked](https://en.wikipedia.org/wiki/Domain_parking)  the domain to catch users who will inevitably end up on the page.

One of the requests appears to be from Google AdSense, so probably to monetize the domain by having unsuspecting visitors view ads.

**Comment by swaroopch** [comment]
Unfortunately, I have lost the original sources of the book, so unable to delete the link and regenerate the PDF. I could use the help if anybody can edit the PDF directly, which I can re-upload.

**Comment by SethFalco** [comment]
Once something has become a PDF, is there a reliable way to modify it without the source?

I did just try to import it to LibreOffice Draw 7.1.3, but unfortunately it breaks the formatting of the document. All monospace text gets wide, text spills off the page, and hyperlinks are removed so nothing is clickable anymore.

**Comment by eshellman** [comment]
Thanks for getting back to us. I'd be happy to help.  Let me take a look.

**Comment by eshellman** [comment]
I have swapped the hyperlink in the pdf with the wayback machine version. The new pdf is available at https://unglue.it/work/156169/ (hexedited the file, then opened and reexported with MacOS Preview)

**Comment by charlottetan** [comment]
The link appears to be fixed now - https://github.com/EbookFoundation/free-programming-books/blob/521f2e91d2ade5c7df20c361466988136411afb3/books/free-programming-books-langs.md#vim

A Byte of Vim links to http://www.swaroopch.com/notes/vim/

**Comment by davorpa** [comment]
> I have swapped the hyperlink in the pdf with the wayback machine version. The new pdf is available at https://unglue.it/work/156169/ (hexedited the file, then opened and reexported with MacOS Preview)

Not applied yet as mentioned by @charlottetan in https://github.com/EbookFoundation/free-programming-books/issues/5389#issuecomment-932841348

@swaroopch in which state is this at this moment? @eshellman what link we should use if remember something?

**Comment by eshellman** [comment]
Not sure if I understand the question, but closing to focus on things more actionable.
