### ISSUE TITLE
I would like to ask a question!

### ISSUE THREAD

**Issue by CarlosViniMSouza** [EbookFoundation/free-programming-books#5394]
**Good morning, I would like to know if I can place 2 books that are available on my Google Drive. I don't know of other ways to make them available for people to access.**
### Link to Data Science with R: https://drive.google.com/file/d/1F_Snn33O6FVf0uwN7Oyc6CmHQmdWJJ0a/view

*Waiting for a return 🖖👽*

**Comment by eshellman** [comment]
In general, we do not link to file sharing sites, including Google Drive. Distribution of the books you propose does not seem to be authoized by the creators.
