### ISSUE TITLE
link to 'The Art of Computer Programming - Donald Knuth (fascicles, mostly volume 4)' broken 

### ISSUE THREAD

**Issue by HadeidM** [EbookFoundation/free-programming-books#5401]
http://www.cs.utsa.edu/~wagner/knuth/ - here is the link that is broken.

**Comment by ankitcr7-afk** [comment]
Can i provide different domain for this book? If yes i would like to solve this issue

**Comment by eshellman** [comment]
based on https://cs.stanford.edu/~knuth/taocp.html I'd say this book is not free and should be removed from our list

**Comment by ankitcr7-afk** [comment]
> based on https://cs.stanford.edu/~knuth/taocp.html I'd say this book is not free and should be removed from our list

Yea exactly

**Comment by mmulahvictor** [comment]
@HadeidM here is the link of volume 4A https://ptgmedia.pearsoncmg.com/imprint_downloads/informit/bookreg/9780201038040/9780201038040_v4A_pages_i-16.pdf
Here is another link https://archive.org/details/B-001-001-251/page/n187/mode/2up

**Comment by rdmchr** [comment]
Would a temporary fix be, for this book at least, to add one of the links mentioned above? If so feel free to assign me to this issue and I'll open a pull request this weekend.
