### ISSUE TITLE
Fortran 95 links broken

### ISSUE THREAD

**Issue by ghost** [EbookFoundation/free-programming-books#5408]
1. http://people.cs.vt.edu/~asandu/Deposit/Fortran95_notes.pdf
2. https://www.mrao.cam.ac.uk/~rachael/compphys/SelfStudyF95.pdf

**Comment by silicon-wafer** [comment]
@eshellman
1. https://www.mjr19.org.uk/f1nn.pdf
2. https://www.archer.ac.uk/training/course-material/2014/08/F95_CCFE/Fortran95CourseNotes.pdf

**Comment by sloppyjuicy** [comment]
> 1. http://people.cs.vt.edu/~asandu/Deposit/Fortran95_notes.pdf
> 2. https://www.mrao.cam.ac.uk/~rachael/compphys/SelfStudyF95.pdf

**Comment by boosie74** [comment]
Thank you very much sir. I hope that help if not send a message and I'll help out . Will need help with a phone and laptop design. Also various other things I have ony agenda.

**Comment by GintasS** [comment]
@eshellman I wanted to work on this, but It's really not clear of what needs to be done, maybe you understand this?

**Comment by eshellman** [comment]
looks to me that the dead links should be removed
