### ISSUE TITLE
Pandas entry update on Books - English - Python?

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books#5431]
Hello contributors 👋

Is really needed have this entry with "in process" note? It always points to last version 😉.
https://github.com/EbookFoundation/free-programming-books/blob/62da834ed2d7601d50fe6e7f51b5db41568d1e0e/books/free-programming-books.md#L2570-L2581

I can contribute with this minor change. Or updating to add html links:

* Online: https://pandas.pydata.org/docs
* HTML: https://pandas.pydata.org/docs/pandas.zip
* PDF: https://pandas.pydata.org/docs/pandas.pdf (already added) 👆

How to proceed in this case?

**Comment by eshellman** [comment]
I'd change to online and remove the in process note
