### ISSUE TITLE
Addition of new framework Fastify JS under the Javascript

### ISSUE THREAD

**Issue by Hardikpoudel** [EbookFoundation/free-programming-books#5443]
Fastify, which is a open source node framework seems to be missing from your frameworks section in javascript, I think this needs to included as well

**Comment by eshellman** [comment]
If there are free books covering Fastify, add them. We try not to create a new section with only one book though.

**Comment by davorpa** [comment]
The only I could find until this moment is the official documentation:

https://www.fastify.io/docs/latest

Can it be valid as a book?

**Comment by eshellman** [comment]
yes
