### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by Aanchal116** [EbookFoundation/free-programming-books#5491]
The current UI seems to be very plain with no headers and footers. I would like to propose working on making the website more attractive.

**Comment by eshellman** [comment]
I assume you mean https://ebookfoundation.github.io/free-programming-books Very little has but done on the design/cosmetics, so there's plenty of room to improve. But can't change our markdown style. PRs welcome, incremental improvements are better than complete overhauls.

**Comment by Aanchal116** [comment]
Yes, you got it right. I'll see how I can maintain the current flow with the improvements. Thankyou.

**Comment by ShehanMaduwantha** [comment]
What if someone makes a nice frontend from these markdown files ?

**Comment by LuigiImVector** [comment]
maybe we can just use another theme, like cayman: https://luigiimvector.github.io/free-programming-books/ (branch [pages-test](https://github.com/LuigiImVector/free-programming-books/blob/pages-test/_config.yml))
