### ISSUE TITLE
Fortran books

### ISSUE THREAD

**Issue by Beliavsky** [EbookFoundation/free-programming-books#5492]
I suggest adding a link to the tutorials section of the Fortran Wiki http://fortranwiki.org/fortran/show/Tutorials and to 

Modern Fortran in Science and Technology by Jonas Lindemann and Ola Dahlblom
Introduction to Advanced Fortran
Introduction to Fortran
Modern Fortran Tutorial
Fortran Lecture notes from a class by Paul Tackley

which are linked there. Arguably the Fortran 77 book currently listed should be removed, since it is about an antiquated standard.

**Comment by eshellman** [comment]
our preferred way of dealing with books that may be out of date is to add the publication year.

**Comment by davorpa** [comment]
Working on it 🤗

**Comment by davorpa** [comment]
> - Modern Fortran in Science and Technology by Jonas Lindemann and Ola Dahlblom
> - Introduction to Advanced Fortran
> - Introduction to Fortran
> - Modern Fortran Tutorial
> - Fortran Lecture notes from a class by Paul Tackley

@eshellman should this also be added if already exist in the provided link?

**Comment by eshellman** [comment]
I checked one of these that seems like a set of powerpoint slides, so, not a book. others can be added if they look like they fit.
