### ISSUE TITLE
three-part Fortran cours, French

### ISSUE THREAD

**Issue by nbehrnd** [EbookFoundation/free-programming-books#5496]
For the French section of programming books about Fortran, I would like to suggest the addition of a three-part instruction.  All material, including supporting sample code, is compiled on [one page](http://www.idris.fr/formations/fortran/) in common by the Institut du développement et des ressources en informatique scientifique of the French CNRS.

* as an initiation: [Langage Fortran (Base)](http://www.idris.fr/media/formations/fortran/idris_fortran_base_cours.pdf) by Anne Fouilloux and Patrick Corde
* based on the former, an extension with focus on modern Fortran 90 including selected concepts up to Fortran 2003: [Langage Fortran (Avancé)](http://www.idris.fr/media/formations/fortran/idris_fortran_avance_cours.pdf) by Patrick Corde and Hervé Delouis
* a capstone class with focus on Fortran 2003 and Fortran 2008: [Langage Fortran (Expert)](http://www.idris.fr/media/formations/fortran/idris_fortran_expert_cours.pdf) by Patrick Corde and Hervé Delouis.

**Comment by davorpa** [comment]
It will be a pleasure work on it :hugs:

Let me see where is the listing of each one
