### ISSUE TITLE
Broken link for: Arduino Programming Notebook - Brian Evans

### ISSUE THREAD

**Issue by fearlessdots** [EbookFoundation/free-programming-books#5504]
Broken link is **http://www.lulu.com/shop/brian-evans/arduino-programming-notebook/ebook/product-18598708.html**. It is returning a 404 error. I tested using HTTPS, and it responded with the same error.

**Comment by davorpa** [comment]
Could be valid the wayback machine link?

https://web.archive.org/web/20200105102050/http://www.lulu.com/shop/brian-evans/arduino-programming-notebook/ebook/product-18598708.html

**Comment by davorpa** [comment]
Also unglued at https://unglue.it/work/152452/
