### ISSUE TITLE
Addition of GangOfFour primer book for Design Patterns

### ISSUE THREAD

**Issue by kd-labs** [EbookFoundation/free-programming-books#5515]
Hi Team

Creating this issue/suggestion if we could add the classic book on Design Patterns in this repo.

Thanks

**Comment by davorpa** [comment]
Hi @kd-labs 

Could you provide a link if its free redistributable? See our guidelines about what kind of resources we accept

/labelthis: PR requested, need more info

**Comment by charlottetan** [comment]
Found the book, while it is free, there is a suggested donation:
book landing page: https://leanpub.com/aprimerondesignpatterns/
reading the book: https://leanpub.com/aprimerondesignpatterns/read

**Comment by davorpa** [comment]
> Found the book, while it is free, there is a suggested donation:

Thanks @charlottetan :hugs: 

Then feel free one or the other :wink: to send a PR adding in the right listing

Remember include the PR with the right tag, something like: `Resolves #5515`

**Comment by charlottetan** [comment]
I've created a PR, although on closer inspection I am not 100% sure if this is the book that the issue author intended. The usual (very popular) [Gang of Four book](https://springframework.guru/gang-of-four-design-patterns/) isn't free, and I skimmed through the chapters of this primer book and it doesn't exactly match the Gang of Four's topics and/or book structure
