### ISSUE TITLE
Developing An Advanced Windows Phone 7.5 App That Connects To The Cloud

### ISSUE THREAD

**Issue by Akshar-Premnath** [EbookFoundation/free-programming-books#5518]
The link to "Developing An Advanced Windows Phone 7.5 App That Connects To The Cloud" under "Windows 8" in "free-programming-books/books/free-programming-books.md" doesn't include the book.

**Comment by davorpa** [comment]
I've just found an alternative

:book: https://social.technet.microsoft.com/wiki/contents/articles/11608.e-book-gallery-for-microsoft-technologies-en.aspx#DevelopinganAdvancedWindowsPhone7.5AppthatConnectstotheCloud

Following it, download link can be scraped from wayback machine:

:arrow_down:  https://web.archive.org/web/20150709045622/http://download.microsoft.com/download/C/4/6/C4635738-5E06-4DF7-904E-BDC22AED2E58/Developing%20an%20Advanced%20Windows%20Phone%207.5%20App%20that%20Connects%20to%20the%20Cloud.pdf

@eshellman I can't find the work, can be this unglued? Or above link is fine to improve repo?
