### ISSUE TITLE
proposal(lists): Merge Version Control Systems into same section

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books#5526]
I'm convinced that it would be a nice idea join all `Version Control Systems` into the same category. I mean: `Git`, `SVN`, `Mercurial`, `CVS`...

And if there are some resource treating Github, Gitlab, Bitbucket, Gitea, Gitpod... put it in a subsection something like `As a Service/Platform SaaS/PaaS`.

Also with views to cover some utility/GUI client resources about: Gitkraken, Github Desktop, SourceTree and so on.

This will give much more context than a merely listing grouped by tool/programming language.

Therefore, maybe it aims to improve :rocket::
- #5092 
- #5249

But there are some doubts how to change it :worried:

1. Under which section? The most will be `Language agnostic`/`by topic` (pending to abord #5249 ??? ), or as TOC first level...
2. Is needed preserve each heading: Git, SVN... ?
    This next heading snippet
    ```markdown
    ### <a name="git"></a><a name="svn"></a>... Version Control Systems
    ```
    could be used in some manner for backwards compatibility, but markdown TOC that GitHub provides automatically will be lost (is built using each `##`)

It's already applied in some listings.

Let me know your opinion/feedback :wink: :hugs:

**Comment by eshellman** [comment]
I guess it's time to roll out a proposal for a programming-lang/subject split

**Comment by davorpa** [comment]
It's already applied to courses-es

https://github.com/EbookFoundation/free-programming-books/blob/076fca27c3baceeb7187988c0b0def0da04e70d4/courses/free-courses-es.md#L1-L10

**Comment by davorpa** [comment]
Locked at this moment by #5563

**Comment by mihir1739** [comment]
How can I contribute to this issue..?

**Comment by davorpa** [comment]
Hey @eshellman. Can I abord this before Hacktoberfest starts?

Locales where already applied: Spanish and english

**Comment by eshellman** [comment]
"abord"?

**Comment by davorpa** [comment]
> abord

Sorry spanglish!! "tackle", "board in", "start with"

**Comment by eshellman** [comment]
go for it
