### ISSUE TITLE
Emacs reference / cheat sheet

### ISSUE THREAD

**Issue by ps173** [EbookFoundation/free-programming-books#5627]
Here is a great [emacs cheat sheet / reference card](https://www.gnu.org/software/emacs/refcards/pdf/refcard.pdf). 
I think this should be added to [IDE / Editor section](https://github.com/EbookFoundation/free-programming-books/blob/master/more/free-programming-cheatsheets.md#ide--editors) of cheat sheets. I suppose this is the official refcard by gnu so it should be free to use.

**Comment by AR10X** [comment]
@ps173 I added the resource. Here's the PR #5630.

**Comment by AR10X** [comment]
@ps173 hey, could you help me review this PR #5630
