### ISSUE TITLE
Add Algorithms book

### ISSUE THREAD

**Issue by sparsh9** [EbookFoundation/free-programming-books#5631]
I can add 2 books :
1. Algorithms 4th Edition by Robert Sedgewick, Kevin Wayne
2.  Algorithms in a Nutshell -(O'Reilly) George T. Heineman, Gary Pollice, Stanley Selkow-Algorithms in a Nutshell-O'Reilly Media (2016).pdf

**Comment by davorpa** [comment]
Thanks for yours suggestions but...

> 1. Algorithms 4th Edition by Robert Sedgewick, Kevin Wayne

Not free: https://algs4.cs.princeton.edu/home/


> 2\. Algorithms in a Nutshell -(O'Reilly) George T. Heineman, Gary Pollice, Stanley Selkow-Algorithms in a Nutshell-O'Reilly Media (2016).pdf

Not free: https://www.oreilly.com/library/view/algorithms-in-a/9781491912973/
