### ISSUE TITLE
Cracking the coding interview book

### ISSUE THREAD

**Issue by SahityaRoy** [EbookFoundation/free-programming-books#5637]
It's contain 150+ interview questions and solution it was a really awesome book

**Comment by davorpa** [comment]
Thanks for your suggestion but I think it's not free.

Proof: https://www.crackingthecodinginterview.com/

If you are sure that are free... provide right link

**Comment by SahityaRoy** [comment]
It's free i will provide you everything in free of cost in pdf format

**Comment by davorpa** [comment]
> It's free i will provide you everything in free of cost in pdf format

Then provide the URL of target link

**Comment by SahityaRoy** [comment]
@davorpa should i create a PR ???

**Comment by SahityaRoy** [comment]
Please assign me the task  in Hacktoberfest 2021 Label

**Comment by davorpa** [comment]
> @davorpa should i create a PR ???

No needed make issues if you have some experience contributing on FOOS: Read our [HOWTO](https://github.com/EbookFoundation/free-programming-books/blob/master/HOWTO.md)

> Please assign me the task in Hacktoberfest 2021 Label

Hacktoberfest tag is setted at repo level

**Comment by kinb98** [comment]
This book is not free.
You can get the pdf version of any paid resource(book or online course) on various websites or torrents, but that doesn't make the resouce free. That is just piracy.

The only resources which are free are those which can be downloaded or viewed on their official website without paying any money.

**Comment by davorpa** [comment]
@SahityaRoy I hope you have write permissions for use this book as it's how to redistribute it

![image](https://user-images.githubusercontent.com/3125580/135735335-59581d50-196f-4882-a058-e96e31689b90.png)

:information_source: Author site: https://www.gayle.com/books

Do you want more proofs?
