### ISSUE TITLE
Add HackThisSite in Capture the flag category.

### ISSUE THREAD

**Issue by AR10X** [EbookFoundation/free-programming-books#5642]
Add HackThisSite CTF website link in Capture the flag category in more/problem-sets-competitive-programming.md file and also correct the spelling of the 'address' in same category.

**Comment by davorpa** [comment]
Do you talk about https://ctf.hackthissite.org/ ?

**Comment by AR10X** [comment]
I made a PR #5643, though I added this URL https://www.hackthissite.org/
