### ISSUE TITLE
Add: DSA Course Playlist (in Hindi section)

### ISSUE THREAD

**Issue by icoderharshit** [EbookFoundation/free-programming-books#5671]
I want to add Data Structures & Algorithms course by 'Apni Kaksha' on YouTube in 'Hindi' section. Note: This is my first issue for HacktoberFest '21, I would be really if you assign me this issue and accept my PR for the same @eshellman

**Comment by davorpa** [comment]
Remember link PR with issue :wink: with something like `Resolves #prnumber` (replace `prnumber` by provided by github
