### ISSUE TITLE
Hands-On Machine Learning with Scikit-Learn and TensorFlow

### ISSUE THREAD

**Issue by ManviGoel26** [EbookFoundation/free-programming-books#5737]
A PDF for the book by O'Reilly for machine learning concepts and codes.
Please assign this to me.

**Comment by VDliveson** [comment]
I have the latest version available of book available with unedited & raw version .Kindly assign to me this issue

![image](https://user-images.githubusercontent.com/72307306/135714401-4e2f65c0-7ff7-4b13-8581-799291a17b35.png)

**Comment by charlottetan** [comment]
This book doesn't appear to be free?
https://www.amazon.com/Hands-Machine-Learning-Scikit-Learn-TensorFlow/dp/1492032646

**Comment by ManviGoel26** [comment]
This link provides a free pdf for the 2nd edition of the book.
https://www.knowledgeisle.com/wp-content/uploads/2019/12/2-Aur%C3%A9lien-G%C3%A9ron-Hands-On-Machine-Learning-with-Scikit-Learn-Keras-and-Tensorflow_-Concepts-Tools-and-Techniques-to-Build-Intelligent-Systems-O%E2%80%99Reilly-Media-2019.pdf

**Comment by charlottetan** [comment]
That doesn't appear to be a legal copy of the book unless I am missing something? The publisher's website does not link to that domain:
https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/

Please see [CONTRIBUTING](CONTRIBUTING.md) for more information about determining whether a book is free

**Comment by ManviGoel26** [comment]
Thanks for informing me. I  will close the issue.
