### ISSUE TITLE
Resources REST API

### ISSUE THREAD

**Issue by SidhaantThakker** [EbookFoundation/free-programming-books#5778]
I had an idea, we could take the entire database here and make an API that could serve the data based on certain requests. It can be used to get the data in a much more streamlined manner, as well as serve as a base for later creating a web app.
I can personally help with this as I work with the MERN stack, I could make the API using Node.js which could be easily integrated into future web apps.

**Comment by E-wave112** [comment]
@SidhaantThakker i would like to work on this with you, i also work with nodejs (i am more of a backend guy though)

**Comment by SidhaantThakker** [comment]
@E-wave112 Sure!
@davorpa If you like the idea we could have a discussion about it :)

**Comment by eshellman** [comment]
There is a team of 6 student Sees from Stevens Institute of Technology working on something like this. See https://github.com/EbookFoundation/capstone-projects/blob/master/fpb.md 

I'll point them at this issue. They may benefit from expertise of others!

**Comment by E-wave112** [comment]
Okay Eric,

Many thanks!

**Comment by LeoOuyang24** [comment]
Yeah sounds good

**Comment by actuallyyun** [comment]
Hey I have some experience building REST API with Python and Django. I would love to get involved if you guys need more help.

**Comment by sanjai0py** [comment]
is this issue still alive? if not i would love to work on it!

**Comment by eshellman** [comment]
Closing the issue, but check out https://github.com/EbookFoundation/free-programming-books-search
