### ISSUE TITLE
Add more resource in java

### ISSUE THREAD

**Issue by satyampgt4** [EbookFoundation/free-programming-books#5793]
add [Pepcoding](https://www.youtube.com/c/Pepcoding) as it has good quality content of ds and algorithm in java for free

I like to work on this under hacktoberfest 2021

**Comment by davorpa** [comment]
Not is necessary open issues if you are be able to send the PR 😉.

ℹ️ Remember link the request with something like `Resolves #NNNN`, where NNNN is the provided by GitHub when the PR is created.

**Comment by sid-khuntwal** [comment]
Can I do something in this repo? I am a beginner!

**Comment by davorpa** [comment]
> Can I do something in this repo? I am a beginner!

Welcome! Read CONTRIBUTING.MD and HOWTO.MD to know how to works this project
