### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by charlottetan** [EbookFoundation/free-programming-books#5803]
Request to rename `master` to `main` for cultural sensitivity and inclusivity:

https://github.com/github/renaming

https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main

**Comment by Kriti021999** [comment]
I would like to work on this issue.

**Comment by davorpa** [comment]
> I would like to work on this issue.

No masters, no slaves neither is the time. It's Hacktoberfest

/addthis: backlog

**Comment by eshellman** [comment]
We should do this after hacktoberfest as part of the general cleanup.

**Comment by codexmon** [comment]
only org owners or admin folks can change the name - "For organization owners, on the https://github.com/organizations/YOUR-ORGANIZATION/settings/repository-defaults page
For enterprise administrators, on the https://github.com/enterprises/YOUR-ENTERPRISE/settings/member_privileges page"

**Comment by eshellman** [comment]
master branch has been renamed to main.

**Comment by davorpa** [comment]
I review a bit and it left some rewording in files.

https://github.com/EbookFoundation/free-programming-books/blob/31fb2488b8223e76a5b73ba1e9daba1e83594e16/.github/PULL_REQUEST_TEMPLATE.md#L14
