### ISSUE TITLE
Add two english books under Algorithms & Data Structures and Competitive Programming subjects.

### ISSUE THREAD

**Issue by AR10X** [EbookFoundation/free-programming-books#5825]
Add two books, [Introduction to Algorithms, Third Edition](https://web.iiit.ac.in/~pratik.kamble/storage/Algorithms/Cormen_Algorithms_3rd.pdf) in Algorithms & Data Structures category and [Programming Challenges](http://acm.cs.buap.mx/downloads/Programming_Challenges.pdf) in Competitive Programming category in /books/free-programming-books-subjects.md file.

The above two books are considered the best books for competitive coding.
https://www.geeksforgeeks.org/5-best-books-for-competitive-programming/

**Comment by davorpa** [comment]
### :warning: NOT FREE

**Take care about DMCA**. That a link is public on the internet does not mean that its content is free. See [CONTRIBUTING guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#guidelines)
>  - we don't accept files hosted on google drive, dropbox, mega, scribd, issuu and other similar file upload platforms
>  - use the link with the most authoritative source (meaning the author's website is better than the editor's website, which is better than a third party website)
>    - no file hosting services (this includes (but is not limited to) Dropbox and Google Drive links)

We only accept contents with free licenses like CC (giving creator attributions).
