### ISSUE TITLE
Error in build 

### ISSUE THREAD

**Issue by Dicky1** [EbookFoundation/free-programming-books#5870]
hi guys i found an error when pushing repo and pull reques
![Screenshot_20211004_161038](https://user-images.githubusercontent.com/26633820/135825672-03468cbe-e7f9-48fe-9df8-15654dea7aeb.png)
t

**Comment by AR10X** [comment]
if you have committed to adding a resource, it must comply in alphabetical order in the list. Swap lines 23 & 24 in the file. This should work.

**Comment by davorpa** [comment]
@Dicky1, Welcome to the most common faults in this repo: resources alphabetization order, specially with non-latin listings.

Related with #5864
