### ISSUE TITLE
Add Algorithms and Data structures courses

### ISSUE THREAD

**Issue by AR10X** [EbookFoundation/free-programming-books#5872]
I would like to add two English Algorithms and Data Structures courses [Data Structures and Algorithms for Beginners](https://www.youtube.com/watch?v=BBpAmxU_NQo) by Programming with Mosh and [Data Structures and Algorithms](https://youtube.com/playlist?list=PLBZBJbE_rGRV8D7XZ08LK6z-4zPoWzu5H) by CS Dojo in free-programming-books/courses/free-courses-en.md file.

The above-given resources are Youtube videos so it's free to access.

**Comment by davorpa** [comment]
Not is necessary open issues if you are be able to send the PR 😉.

Remember link the request with something like `Resolves #NNNN`, where NNNN is the provided by GitHub when the PR is created
