### ISSUE TITLE
Improvement of the german (de) HOWTO file

### ISSUE THREAD

**Issue by FabianKielmann** [EbookFoundation/free-programming-books#5887]
Hey guys, I'd like contribute something for Hacktoberfest 2021.

As german is my mother tongue, I've noticed some issues with spelling, sentence construction and "formatting" in the german HOWTO file (HOWTO-de.md) and would like to improve it.

Please let me know If I should open a Pull Request :)

**Comment by FabianKielmann** [comment]
@davorpa I successfully created the pull request. Do you have to tag it with something special to make it count for hacktoberfest?

**Comment by davorpa** [comment]
> @davorpa I successfully created the pull request. Do you have to tag it with something special to make it count for hacktoberfest?

The repository is tagged as `hacktoberfest`, so you should be good. Obviously, the [**PR needs be accepted and merged** (see more rules)](https://hacktoberfest.digitalocean.com#rules)

**Comment by FabianKielmann** [comment]
@davorpa since you approved the changes in the pull request, can this issue be closed? Or will it auto close on a specific event?

**Comment by davorpa** [comment]
> @davorpa since you approved the changes in the pull request, can this issue be closed? Or will it auto close on a specific event?

It's already linked, since you uses `Resolves #5887` and then, it autoclose on merge. See [Github docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for more options.
