### ISSUE TITLE
Discussion about new subjects/sections. was: Airflow sub consideration

### ISSUE THREAD

**Issue by CakKhoiron** [EbookFoundation/free-programming-books#5896]
I want to add Airflow youtube tutorial in the [English free course list](https://github.com/EbookFoundation/free-programming-books/blob/master/courses/free-courses-en.md). Which one is best condition, should I add a new Sub in the list or will be better if add it under Python Sub?

**Comment by AR10X** [comment]
My opinion is that you should add a new sub as Workflow Management System/tools, although you use python to code, it belongs to a different software usage category 😄

**Comment by davorpa** [comment]
:information_source: It's usually not helpful to add a category for a single resource. :twisted_rightwards_arrows: Try to...
- ... find another category matching their topics.
- ... see if there are other books in our lists or third-party that would fit into your category (this fact contributes to consolitate it).

**Comment by eshellman** [comment]
Sections/Subjects are for the benefit of people looking for books and course. When adding a new language section or subject, try to think about how a non-expert user might search for the book or course. I'm guessing that a novice might not have heard of Airflow, and would look for a more general category.

**Comment by CakKhoiron** [comment]
PR Requested, please check and merge it
#7993
