### ISSUE TITLE
I have the original copy of the book named Automate The Boring Stuff in python

### ISSUE THREAD

**Issue by codewithpom** [EbookFoundation/free-programming-books#5959]
I want to know how can I contribute it.

**Comment by davorpa** [comment]
Read our maintenance documents that you can find in the repo root:
- [HOWTO.md](https://github.com/EbookFoundation/free-programming-books/blob/HEAD/HOWTO.md)
- [CONTRIBUTING.md](https://github.com/EbookFoundation/free-programming-books/blob/HEAD/CONTRIBUTING.md) guidelines.

Some warnings: 
- No attatchment accepted.
- No resources under copyright license. Only those such CC, MIT... and always mention involved authors.

If satisfy all those, the contribution has a warm welcome. Remember [link in the request body with something like `Resolves #NNNN`](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), where NNNN is provided by GitHub when the PR is created, :pray: thanks.

**Comment by codewithpom** [comment]
oh but I downloaded from some where else

**Comment by davorpa** [comment]
> Hi, there! It looks like that book is already included in the book section for English. You can find it [here](https://github.com/EbookFoundation/free-programming-books/blob/master/books/free-programming-books-langs.md#python).

Nice catch Amy. Thanks for your triage help.

https://github.com/EbookFoundation/free-programming-books/blob/f1dc9f15aa04ea7e1cd7f990cd9e1692af6e4dc3/books/free-programming-books-langs.md#L1784
