### ISSUE TITLE
Should this Markdownguide.org cheatsheet be included in markdown cheatsheets section

### ISSUE THREAD

**Issue by AR10X** [EbookFoundation/free-programming-books#5962]
Should this [Markdownguide.org cheatsheet](https://www.markdownguide.org/cheat-sheet/) be included in the markdown language cheatsheet section?

**Comment by davorpa** [comment]
> Should this [Markdownguide.org cheatsheet](https://www.markdownguide.org/cheat-sheet/) be included in the markdown language cheatsheet section?

Maybe, book don't


Remember [link in the request body with something like `Resolves #NNNN`](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), where NNNN is provided by GitHub when the PR is created, :pray: thanks.
