### ISSUE TITLE
Atomic Design Book

### ISSUE THREAD

**Issue by ramsesgarate** [EbookFoundation/free-programming-books#5978]
Hello, I would like to add Brad frost atomic design book, it has an online version that is totally free, the problem is that I do not know in which category it should go, I would like you to assign me this issue to add it, thank you.

**Comment by ramsesgarate** [comment]
Perfect, today I create that PR.

**Comment by davorpa** [comment]
It seems already listed

https://github.com/EbookFoundation/free-programming-books/blob/16df0aceb9b01dd18e3ee397ba93cb183dae8cc9/books/free-programming-books-langs.md#L877
