### ISSUE TITLE
proposal(docs): repository badges

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books#5983]
I've checked for all governance documents and the conclusion is we have the possibility to add:

- Awesome (already present)
- Contributor Covenant (as suggested at [www.contributor-covenant.org](https://www.contributor-covenant.org/#how-to-adopt-contributor-covenant))
- CC license (see [this gist](https://gist.github.com/qvil/5e3ed56c26d784e51424621119cc4028) for other designs)

An example, following other repositories, could be:

![image](https://user-images.githubusercontent.com/3125580/136253819-bf96c416-cc44-45bb-a599-812aff08b3e7.png)

Of course, this is a draft, not pushed into my fork yet. It can be placed at other part or files like CONTRIBUTING or HOWTO

If is taken as is, I'll also opt for remove it from 1st heading.

We reach an agreement among the entire community as to whether it is useful, its place and/or the order of the badges.

**Comment by LuigiImVector** [comment]
I think that's a good idea, maybe the Contributor Covenant badge could be placed in CONTRIBUTING.md

![image](https://user-images.githubusercontent.com/59611597/137194578-8155da58-1a4a-4df3-ad91-0c19807dff3c.png)

**Comment by davorpa** [comment]
More proposed badges at #6697
