### ISSUE TITLE
`MIT 6.S099: Artificial General Intelligence` url missmatch

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books#6003]
https://agi.mit.edu

This url points to obsolete SSL certificate
- if `http` is used... redirects to https://deeplearning.mit.edu/
- if an `https` exception is configured... to one of the instructors: https://lexfridman.com/

---
:question: Doubts:
1. I don't know how to resolve it. Also title doesn't match which it is redirected to
2. Lectures can be considered as a course or better as screencast?
3. What about instructors attribution?

_Originally posted by @davorpa in https://github.com/EbookFoundation/free-programming-books/pull/5987#discussion_r723706178_

**Comment by eshellman** [comment]
Maybe email the instructor?

**Comment by RuthlessRuler** [comment]
Last known saved copy w/o redirection can be found here: https://web.archive.org/web/20200415043122/https://agi.mit.edu/. There is also YT playlist: https://www.youtube.com/playlist?list=PL4jieTF-BpWoiVjta6VuRy5plFtDm9eRG.
