### ISSUE TITLE
Cilk 5.4.6 Reference Manual Removed From Original Source

### ISSUE THREAD

**Issue by whohet** [EbookFoundation/free-programming-books#6041]
URL : https://github.com/EbookFoundation/free-programming-books/blob/master/books/free-programming-books-langs.md#cilk
Issue : The url linked to this resource is no longer valid as the source has deleted the reosurce/resource is missing.
Suggested Fix : Changing the url to resource provided by Techinal University of Vienna (TUWEIN). URL : https://par.tuwien.ac.at/material/manual-5.4.6.pdf

**Comment by davorpa** [comment]
Helps to improve #5470 

https://github.com/EbookFoundation/free-programming-books/blob/579873607c27fef64b5af0e636a42cc64e1ba36b/books/free-programming-books-langs.md#L513

```markdown
* [Cilk 5.4.6 Reference Manual](https://par.tuwien.ac.at/material/manual-5.4.6.pdf) (PDF)
```

Or even better, use wayback machine to preserve authoring. The last available snapshot is: https://web.archive.org/web/20200930095608/http://supertech.lcs.mit.edu/cilk/manual-5.4.6.pdf

Using notes `*(:card_file_box: archived)*`
```markdown
* [Cilk 5.4.6 Reference Manual](https://web.archive.org/web/20200930095608/http://supertech.lcs.mit.edu/cilk/manual-5.4.6.pdf) (PDF) *(:card_file_box: archived)*
```

and/or mention MIT Supertech Cilk Project http://groups.csail.mit.edu/sct/wiki/index.php?title=The_Cilk_Project ???

```markdown
* [Cilk 5.4.6 Reference Manual](http://groups.csail.mit.edu/sct/wiki/index.php?title=The_Cilk_Project) (HTML, [PDF](https://web.archive.org/web/20200930095608/http://supertech.lcs.mit.edu/cilk/manual-5.4.6.pdf)) *(:card_file_box: archived)*
```

Remember [link in the request body with something like `Resolves #NNNN`](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), where NNNN is provided by GitHub when the PR is created, :pray: thanks.
