### ISSUE TITLE
逆引きSwift - FaBo(http://docs.fabo.io/swift/) is moved other site.

### ISSUE THREAD

**Issue by pond-e** [EbookFoundation/free-programming-books#6092]
In books/free-programming-books-ja.md
逆引きSwift - FaBo(http://docs.fabo.io/swift/) is moved other site.

**Comment by davorpa** [comment]
Remember [link in the request body with something like `Resolves #NNNN`](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), where NNNN is provided by GitHub when the PR is created, :pray: thanks.
