### ISSUE TITLE
Post-hacktoberfest chore: move docs to folders

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#6164]
Success: we have lots of translations.
Downside: they move the README far below the fold; filenames are difficult to scan.
Suggested solution: move the docs, other than README, to subfolders.

At the same time, maybe consolidate links to them. Does a visitor to an Arabic HOWTO really need the link to the Chinese HOWTO? These links are causing a lot of merge conflicts, too.

**Comment by davorpa** [comment]
Without want discriminate any language or country I opt to leave at least in root:
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- LICENSE

They are important in some GitHub parts. E.g. footer:
> (i) Remember, contributions to this repository should follow its `contributing guidelines` and `code of conduct`.

 I'm not be able to find if can be configured using some file in `.github` folder

**Comment by eshellman** [comment]
duplicate of #6590 addressed by #6614
