### ISSUE TITLE
proposal: "archived" resources

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#6301]
In #6281 @LuigiImVector implements a suggestion to mark items that have been changed to a wayback machine link to add an access note *(:card_file_box: archived)*  ~~(I think I saw this on another PR, too)~~ used by @davorpa in #6276 

I indtend to merge that PR in a few days, as I think this is a useful addition, but I wonder if this should be our standard practice, i.e. added to our documentation (#6282). Or do users/contribuotrs feel this clutters the UI or is difficult to implement, or could be improved?

Comments/suggestions welcomed!

**Comment by davorpa** [comment]
> (I think I saw this on another PR, too)

You are right. It's something liked in https://github.com/EbookFoundation/free-programming-books/pull/5464#issuecomment-891808804, PR where I use it as first time.

Here the repo search about it: https://github.com/EbookFoundation/free-programming-books/search?q=archive.org

I agree with it is a nice visual touch, and also maybe related with some historical resources we list.

Formats:
```markdown
01:   _(:card_file_box: archived)_
02:   *(:card_file_box: archived)*
```
 both format notes as italic
