### ISSUE TITLE
Update link to "Database Design - 2nd Edition" and other links coming from open.bccampus.ca

### ISSUE THREAD

**Issue by PC-DUSS** [EbookFoundation/free-programming-books#6302]
The download links for open.bccampus.ca are no longer valid. Valid links are found at opentextbc.ca/

For "Database Design - 2nd Edition" this links is here: https://opentextbc.ca/dbdesign01/

**Comment by davorpa** [comment]
Thanks!!!

Why change link if not broken?

https://github.com/EbookFoundation/free-programming-books/blob/198eb1d5513962192fee7989345c97fc5b4f9ad0/books/free-programming-books-subjects.md#L219

- Title: `Database Design – 2nd Edition`
- Authors: `Adrienne Watt, Nelson Eng @ Douglas College`
- Library entry: https://open.bccampus.ca/browse-our-collection/find-open-textbooks/?uuid=5b6f010a-0563-44d4-94c5-67caa515d2c5
- Resource home: https://opentextbc.ca/dbdesign01/
- Platform: `BCcampus Open Pressbooks`
