### ISSUE TITLE
URL changed for C for Python Programmers by Carl Burch

### ISSUE THREAD

**Issue by unemployedtechie** [EbookFoundation/free-programming-books#6500]
The following URL showing in the list has changed and needs to be updated.

Old URL: [http://www.toves.org/books/cpy/](http://www.toves.org/books/cpy/)
New URL: [http://www.cburch.com/books/cpy/index.html](http://www.cburch.com/books/cpy/index.html)

**Comment by Harshita-Kohli** [comment]
Ok. Thanks

**Comment by davorpa** [comment]
Improves #5470 

Remember [link in the request body with something like `Resolves #6500`](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), :pray: thanks.

**Comment by Harshita-Kohli** [comment]
yes yes sure. Will take care of this.
