### ISSUE TITLE
investigate techotopia/ebookfrenzy/linuxtopia ?

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#6517]
We currently have 1 listings from "techtopia" and "linuxtopia" These appear to be derivatives of the "Essentials" series published by ebookfrenzy, which lists the author as Neil Smyth. https://www.google.com/search?tbo=p&tbm=bks&q=inauthor:%22Neil+Smyth%22 https://www.ebookfrenzy.com/ 

Based on the number of titles listed by Mr. Smyth, I suspect little original effort goes into them.

The site and the books appear to be contruct for search engine placement, and I'll bet they're copied from other sources, and no attributions are given. Should they be removed?

**Comment by 2kindsofcs** [comment]
I found something like this: "https://www.linuxtopia.org/online_books/introduction_to_linux/index.html" 
The book("intorudction to linux) is originally authored by Machtelt Garrels. on the web page, it says "Machtelt Garrels" and also "Linuxtopia Edition Copyright © 2007 Neil Smyth" is found. it looks suspicious. 
![스크린샷 2021-10-30 오전 10 06 47](https://user-images.githubusercontent.com/42531877/139514883-842ded9a-3c01-4197-8db9-56b0ea1ec422.png)

**Comment by eshellman** [comment]
yes please
