### ISSUE TITLE
Is "Professional Assembly Language" really free?

### ISSUE THREAD

**Issue by cwfoo** [EbookFoundation/free-programming-books#6605]
*Professional Assembly Language* by Richard Blum was added in #84. Is it really a free book? If so, where is it mentioned?

https://github.com/EbookFoundation/free-programming-books/blob/d6633c1f42ea59d49761c533b4810693fa0ea8fc/books/free-programming-books-langs.md#L326

**Comment by davorpa** [comment]
Yes, you are right. Archived at #2603. Remove it.
