### ISSUE TITLE
Public (early) alpha of free-programming-books search

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#6643]
https://4dylanregan.github.io/myapp/

you can leave comments and suggestions here.

There's [a parser that converts the markdown to json,](https://github.com/Senior-Design-2021-Ebook-Team/markdown-parser)
and  [a react app](https://github.com/4dylanregan/myapp) that loads the json and searches it.

by @4dylanregan @nrfq @brogan20 @dpekata @LeoOuyang24 @pkelly10439594

**Comment by fake-rookie** [comment]
Thans for that first. 

A suggestion : maybe should open each link in a new frame(tab or window in browser). not in current frame. 
:)

**Comment by davorpa** [comment]
Nice!!!

**Comment by davorpa** [comment]
it would be great have `yml` format to address frontend using github pages

**Comment by davorpa** [comment]
My 2 cents to UI...

It would be great considere responsive design. 

![Screenshot_20211227-175831](https://user-images.githubusercontent.com/3125580/147493499-93e8b1d6-d7c6-43b9-8377-0ed77f628956.png)

Eg. above screenshot shows irregular gaps on breaking layout line when content is irregular

**Comment by AhmedElTabarani** [comment]
This link: https://4dylanregan.github.io/myapp/ show a blank page, there is no UI at all.
this is normal? or I use the link as API  or there something I miss?

**Comment by davorpa** [comment]
> This link: [4dylanregan.github.io/myapp](https://4dylanregan.github.io/myapp/) show a blank page, there is no UI at all. this is normal? or I use the link as API or there something I miss?

Project was transfered to the organization recently. Try with

https://ebookfoundation.github.io/free-programming-books-search/

**Comment by eshellman** [comment]
deployed
