### ISSUE TITLE
proposal: Mathematics for Computer Science Eric Lehman and Tom Leighton 2004

### ISSUE THREAD

**Issue by shruzki** [EbookFoundation/free-programming-books#6656]
https://www.cs.princeton.edu/courses/archive/spr10/cos433/mathcs.pdf

(Lecture Notes)

**Comment by eshellman** [comment]
Maybe this is a better viersion?:  https://courses.csail.mit.edu/6.042/spring18/mcs.pdf

**Comment by shruzki** [comment]
Yeah
