### ISSUE TITLE
Files name dispute

### ISSUE THREAD

**Issue by LuigiImVector** [EbookFoundation/free-programming-books#6693]
In many category files begin with "free-programming":
- `free-programming-books-en.md`
- `free-programming-cheatsheets.md`
- `free-programming-interactive-tutorials-en.md`
- `free-programming-playgrounds.md`

I propose then to rename the following files:
- `free-podcasts-screencasts-en.md` to `free-programming-podcasts-screencasts-en.md`
- `free-courses-en.md` to `free-programming-courses-en.md`
- `problem-sets-competitive-programming.md` to `free-problem-sets-competitive-programming.md` (for grammatical issues I don't think it's possible to write "free-programming" here, if not, write a comment)

What do you think?

**Comment by eshellman** [comment]
no tangible benefit; will break lots of links

**Comment by davorpa** [comment]
+1 with Eric

**Comment by CleanMachine1** [comment]
I agree, while the naming may be more helpful as to giving more information, the fact still remains that every link to the pages would become redundant.

**Comment by CleanMachine1** [comment]
One little extra note, whenever I am searching the repo for a book or guide, I have to shift through all of the directories and files, so making the files longer makes it just a little harder to find what I am looking for.

**Comment by LuigiImVector** [comment]
> One little extra note, whenever I am searching the repo for a book or guide, I have to shift through all of the directories and files, so making the files longer makes it just a little harder to find what I am looking for.

What if we shortened the file names instead?

**Comment by CleanMachine1** [comment]
Again, as mentioned the main downside is probably the links becoming invalid

**Comment by davorpa** [comment]
> What if we shortened the file names instead?

Better idea but this implies refactor too and there are more files in books and courses than in other categories. Also @brogan20 might tell us if there are some problems with parser too related with #6643

**Comment by LuigiImVector** [comment]
Too much work for too few benefits
