### ISSUE TITLE
Bad target url documenting `fpb-lint.yml` since CONTRIBUTINGs were moved to docs folder

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books#6721]
There are a bug present in all CONTRIBUTING files since were moved to `./docs/` folder pulled by #6614.

![image](https://user-images.githubusercontent.com/3125580/153770524-86f78d06-96a1-41f2-b203-b91457bf1380.png)

How to address this? The best way is always use a relative URL so patch the url markdown of each `fpb-lint.yml` reference with... 

```markdown
[`.github/workflows/fpb-lint.yml`](../.github/workflows/fpb-lint.yml)
```

I can't believe it how I didn't detect it in #6625 :worried:

_Originally posted by @davorpa in https://github.com/EbookFoundation/free-programming-books/pull/6719#discussion_r805399929_

### Notes

Start work after merge #6719

**Comment by RishiKumarRay** [comment]
@davorpa can i raise a PR fixing this?
