### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by AhmedElTabarani** [EbookFoundation/free-programming-books#6764]
- [ ] There is someone try to convert https://www.patterns.dev/ book into a series [here](https://www.youtube.com/playlist?list=PL0_C_32YKLpwykmU7t7bLZ7guRw1psa52), Can we add it to the Courses file? And what will be its index?
- [x] There is a translation of [The Next.js Handbook](https://flaviocopes.com/page/nextjs-handbook/) you can check it [here](https://blog.abdelhadi.org/learn-nextjs-in-arabic/), So can we add it in Books file?
- [ ] There is someone makes multi playlists for machine learning, (28 playlists), he converts the machine learning field into multi section each section is a playlist,  you can find them [here](https://www.youtube.com/c/HeshamAsem/playlists), (there are sections for machine learning basic, some python libs, Classification, NLP, Deep Learning,  and so on ...), so the same question 😅how can add them in the index table structure
- [x] Playlist of long lecture recordings for college or a place like an education center
- [ ] ACM training lectures
- [x] If the corresponding books are free and listed, the video playlists could be considered free courses.
- [x] There are people making a 7 to 10 hours video to explain something (combined course)
note: ok, but please note the length in the PR description.

**Comment by davorpa** [comment]
> * There is a translation of [The Next.js Handbook](https://flaviocopes.com/page/nextjs-handbook/) you can check it [here](https://blog.abdelhadi.org/learn-nextjs-in-arabic/), So can we add it in Books file?

If is a translation, needs attribution to both, the original author and who translate to arabic: `- Flavio Copes, عبدالهادي الأندلسي`

**Comment by eshellman** [comment]
1. we should add Learning Patterns to our English book list - there are design patterns books scattered around, the largest number in "Software Architecture".
2. the arabic playlist on Learning patterns is not quite a "course" yet. 
3. definite yes on the Next.js book
4. The Heshem Asem playlists  don't fit well into our structure, but deserve a listing. Maybe call the whole list of playlists a course. We can break our "use the title from the source" rule here and create a title for it.

**Comment by AhmedElTabarani** [comment]
@eshellman 

i will add this:

- Machine Learning:  from 1 to 13
- Deep Learning from 14 to 18
  - The playlist number 19 is a collection of 14, 15, 16, 17, 18
  So, we can add the playlist no. 19 instance of playlists from 14 to 18
- NLP: from 21 to 28

**Comment by AhmedElTabarani** [comment]
> 2. the arabic playlist on Learning patterns is not quite a "course" yet

Can i add it with "in progress" label

**Comment by AhmedElTabarani** [comment]
There are some playlists like [this](https://www.youtube.com/playlist?list=PLzCpl3aBwaY5nQxWH0HaNibR9UXKICWxz)
They are recordings of long lectures of one to two hours for each video, whether they are in college or a place like an educational center, can we put them? there are many playlists like this above for different topic.
@eshellman @davorpa

**Comment by davorpa** [comment]
> There are some playlists like [this](https://www.youtube.com/playlist?list=PLzCpl3aBwaY5nQxWH0HaNibR9UXKICWxz) They are recordings of long lectures of one to two hours for each video, whether they are in college or a place like an educational center, can we put them? there are many playlists like this above for different topic.

LGTM

**Comment by AhmedElTabarani** [comment]
Thanks 
can we put ACM training too?, see [this](https://www.youtube.com/playlist?list=PLPSFnlxEu99FcZdNGZ3dF2qCMvkd9whyN)

**Comment by AhmedElTabarani** [comment]
@davorpa  Hi there are huge courses coming now 😉

I have some questions here
- There are people making a 7 to 10 hours video to explain something (combined course)
- There is a course that explains Regex (independent of any language) in what category should I put it?
- There is a data science course, where should I put it?

**Comment by AhmedElTabarani** [comment]
> @davorpa, @eshellman Hi there are huge courses coming now 😉
> 
> I have some questions here
> 
> * course title like `Design Patterns in javascript`, `Design Patterns in PHP` should  I put them in their own language category `javascript`, `php`  or in `Software Architecture` category?
> * There are people making a 7 to 10 hours video to explain something (combined course)
> * There is a course that explains Regex (independent of any language) in what category should I put it?
> * There is a data science course, where should I put it?

**Comment by eshellman** [comment]
> @davorpa, @eshellman Hi there are huge courses coming now 😉
> 
> I have some questions here
> 
> * there is a Chanel that make a playlists to explain books like [Head First Object-Oriented Analysis and Design](https://www.youtube.com/watch?v=gfhzJxXcDpQ&list=PLWCr3KJclfzGkG7CXBmSdlIcIpjxo4FbF) and [Grokking Algorithms](https://www.youtube.com/watch?v=4HyjoHPRdJQ&list=PLWCr3KJclfzGV82gewnuAoKFBt_f9FvNa) where should I add them?

If the corresponding books are free and listed, the video playlists could be considered free  courses.

> * course title like `Design Patterns in javascript`, `Design Patterns in PHP` should  I put them in their own language category `javascript`, `php`  or in `Software Architecture` category?

Take title from the courses themselves. Do not try to translate titles yourself.

> * There are people making a 7 to 10 hours video to explain something (combined course)

ok, but please note the length in the PR description.

> * There is a course that explains Regex (independent of any language) in what category should I put it?

I think we have lists that use regex as a category.

> * There is a data science course, where should I put it?

either start a new category, or if its just one course, mayybe put it in a "general" or "miscelaneous" category

**Comment by AhmedElTabarani** [comment]
> If the corresponding books are free and listed, the video playlists could be considered free courses.

The books are not free, so I will delete the course from my pr #6964 

> Take title from the courses themselves. Do not try to translate titles yourself.
I didn't, this is the actual title, I put them in their language category

The rest of the things I will add in the next group of courses
