### ISSUE TITLE
Considere update CoC to 1.4 or 2.0

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books#6792]
Should we update CODE_OF_CONDUCT documents to a newer version ?

Maybe update to 1.4, or full upgrade to the most recent 2.0. If some translation doesn't exist we should contribute with the repo in charge of their maintenance (see #6791)

Let's talk!

**Comment by eshellman** [comment]
want to summarize the differences?

**Comment by davorpa** [comment]
> want to summarize the differences?

Of course.

Here the mapping:

| | version | document url |
| --- | --- | --- |
| Current version | 1.3.0 | https://www.contributor-covenant.org/version/1/3/0/code-of-conduct/ |
| Next minor | 1.4 | https://www.contributor-covenant.org/version/1/4/code_of_conduct/ |
| Full upgrade | 2.0 | https://www.contributor-covenant.org/version/2/0/code_of_conduct/ |

Currently document is the same of 1.3.0 less email part and the translations link we add some time ago.

Mainly...
 - In 1.4, sections was introduced to diferenciate parts. In the middle, some rewordings to be more neutral, I thought.
 - In 2.0, parts of Mozilla covenant guidelines was added.

Check following diffs to considere options

**Comment by LuigiImVector** [comment]
CoC  2.0 seems more professional.
Contributing directly to the main repository of Contributor Covenant I think it's a very nice idea, also to enhance the concept of collaboration between open source projects.
