### ISSUE TITLE
I wanna contribute Java Programming language in Bengali language

### ISSUE THREAD

**Issue by NeamulIslamFahim** [EbookFoundation/free-programming-books#6815]
I wanna contribute Java programming language in Bengali Language. As like other languages, the learners whose mother tongue is Bangla, also learning Java programming language. The resource of Bengali language is not much in Bengali Language. From that perspective, for the Bengali students, I wanna contribute my Java lecture from Basic to onwards.

Thank you

**Comment by davorpa** [comment]
Do you know how to make Pull Request? Both yes or not, I aim you to read our CONTRIBUTING guidelines and HOWTO to learn how to contribute in the repository.

If you want contribute in bangla resources, welcome. Search free resources in internet that satisfies the requirements and send the PR.

**Comment by NeamulIslamFahim** [comment]
Thanks. 
I will pull request and I have seen that Java content is already posted. So, I am  coming with HTML Bangla
