### ISSUE TITLE
link font increasing wrongly

### ISSUE THREAD

**Issue by mr-vaibh** [EbookFoundation/free-programming-books#6856]
just found out this minor issue. whenever hovering over this link, the font of text after the link is also getting increased.

the problem is with every link

probably missing a closing tag
https://ebookfoundation.github.io/free-programming-books/

![image](https://user-images.githubusercontent.com/52421094/170947309-aba467c0-cefa-4d7f-92b3-54f33f7dbc64.png)

**Comment by nbehrnd** [comment]
I actually welcome this as a nice feature to recognize the current selection in visual web browsers.  This is .true. especially in lists with entries close to each other where indentation does not change.  And as observed by you, this _assistance_ is present when selecting the natural languages, the programming languages, their individual entries etc.:

![font_change](https://user-images.githubusercontent.com/19709084/170954064-90ebcd2b-33ee-4168-ac85-a4552fb004cf.gif)

---

Depending on what type (and format) of information you intend to access, you may of course opt-in for light-weight text-based web browsers.  In case of [links2](https://en.wikipedia.org/wiki/Links_%28web_browser%29) (the developer's [source](http://links.twibright.com/)) started from and living in the terminal:

![example_links2](https://user-images.githubusercontent.com/19709084/170963732-3dbe16a9-937e-4c1d-8ee2-1671d65e3f40.gif)

(Launching `links2` in a pattern like `links2 -g www.example.org` offers an intermediate to the two above, `graphics mode`:)

![links2_g](https://user-images.githubusercontent.com/19709084/170964345-908b74db-0948-47f8-8a71-aeed29e0f7ce.png)

**Comment by eshellman** [comment]
the relevant css code is invoked in https://github.com/EbookFoundation/ebookfoundation.github.io/blob/master/_config.yml so maybe take it up with the developers of jekyll-theme-minimal

**Comment by nbehrnd** [comment]
Vaibhav Shukla ***@***.***> wrote:

> You'll see the other text around it pops up and gets displaced. 

Yes, if the label of the hyperlink is touched, its width and height
change (the weight increases) which affects all the text around.
Actually, in the lists with individual references to books and web
pages per programming language, the text not leading to the reference
page (like title/author of a book) equally inflates a little.  Similar
changes would happen if the font would change to /italics/ within the
same family of a proportional font (possibly more noticeable,
depending on the kerning).  But only in moments if the mouse is
nearby.

The perception if «annoyance» by this interactive character may vary.
Compared to other pages (like the pages of «learn language xyz» by
tutorialspoint.com), here, the page refrains from visual clutter and
appears to me much clearer, more focused.
