### ISSUE TITLE
Danish full ICU code is `da-dk` not `dk`

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books#6908]
Danish full ICU code is `da-dk`

https://www.localeplanet.com/icu/da-DK/index.html

so files should be renamed from `*-dk` to `*-da`

_Originally posted by @davorpa in https://github.com/EbookFoundation/free-programming-books-search/issues/29#issuecomment-1179764876_

**Comment by eshellman** [comment]
I'll do it
