### ISSUE TITLE
Remove no toplevel codecademy cheatsheets

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books#7049]
> need higher level link

No high level for each CodeCademy cheatsheet we have listed. Are structured in chapters and with a pdf each one. Entrypoint is always first chapter.

Better remove all of them in our listings?

_Originally posted by @davorpa and @eshellman in https://github.com/EbookFoundation/free-programming-books/pull/5696#discussion_r726499681_

**Comment by vipul-2003** [comment]
i am interested to work , but please explain in details , what exactly i have to do ?
@davorpa
