### ISSUE TITLE
feat: Create a workflow that label/unlabel issues on pin/unpin

### ISSUE THREAD

**Issue by davorpa** [EbookFoundation/free-programming-books#7055]
To enhace with #7053 stale labeling bypass, create a GitHub Actions workflow that automanage labels on pin/unpin issues.

When
- Pin an issue... add a label `📌 pinned`
- Unpin an issue... remove the label `📌 pinned`
- Optional: close a issue... remove the label `📌 pinned`

**Comment by mohitsaxenaknoldus** [comment]
Hey, can I work on this?

**Comment by eshellman** [comment]
two heads are better than one
