### ISSUE TITLE
written request to lower the hard deck, sir

### ISSUE THREAD

**Issue by breck7** [EbookFoundation/free-programming-books#7069]
feature suggestion: remove license, go public domain

> explain why you think it's a good idea.

essay: https://breckyunits.com/how-the-public-domain-can-win.html

hype video: https://pldb.com/posts/buildPublicDomain.html

**Comment by eshellman** [comment]
As a practical matter, removing the repo's license would require the consent of almost 2000 contributors.
Request denied.

**Comment by breck7** [comment]
> would require the consent of almost 2000 contributors.

On it.
