### ISSUE TITLE
Suggestion: add another playground for OCaml

### ISSUE THREAD

**Issue by JiaeK** [EbookFoundation/free-programming-books#7073]
[OCaml.org](https://ocaml.org/) has launched [a new playground](https://ocaml.org/play) for its newer version (version 3) website on April 29th, this year. And I’ve only found [the former one (Try OCaml)](https://try.ocamlpro.com/) on this repo. So it’d be great if we could add the new one, too. 

Likewise, I could open a PR for this. But for the PR, I have one question: should I add not only for [playground](https://github.com/EbookFoundation/free-programming-books/blob/5324b9e3cf886dc6e1add096f261754368515176/more/free-programming-playgrounds.md#ocaml) but also for [interactive tutorials](https://github.com/EbookFoundation/free-programming-books/blob/9bfd1914d5f31099563fc83acf8cc9d97a0a3ebc/more/free-programming-interactive-tutorials-en.md#ocaml), right?

**Comment by nbehrnd** [comment]
*Speculation:* Maybe this conveys the (potentially wrong) impression to the user the more frequently seen contributors of the project would be involved in the setup and maintenance of the software to run such a playground.  Thus, it might be more useful to indicate the existing of such sandboxes to get familiar with the languages -- either in the corresponding language, or as a separate category of the directories.  Examples of playground in addition to the one about ocaml you show could be

+ for [Python](https://lwebapp.com/en/python-playground)
+ for contemporary [Fortran](https://play.fortran-lang.org/)
+ for [Lua](https://www.lua.org/cgi-bin/demo)
+ for regular expressions [regex101.com](https://regex101.com/)
+ for [LaTeX](https://www.learnlatex.org/)
+ and multi-language playgrounds like the one by [tutorialspoint.com](https://www.tutorialspoint.com/codingground.htm), e.g. for and about [AWK](https://www.tutorialspoint.com/execute_awk_online.php)

with some preference to those obviously maintained closely by their community (like lua.org, fortran-lang.org).

**Comment by eshellman** [comment]
We try not to duplicate links. So pick one list - looks like a playground to me.
