### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Prashant-Bhapkar** [EbookFoundation/free-programming-books#7085]
[Docker Cheat Sheet (🇪🇸)](https://helmcode.com/blog/docker/docker_cheat_sheet) - Cristian Córdova, HelmCode (HTML)

The above link does not exist.
Request to change the link or to replace it with a new source.

**Comment by davorpa** [comment]
Address #6942  for 

https://github.com/EbookFoundation/free-programming-books/blob/4d678252fe8ba1929460ed1c67d7f84835aa0a99/more/free-programming-cheatsheets.md?plain=1#L96

**Comment by davorpa** [comment]
New url... https://helmcode.com/posts/docker-cheat-sheet

**Comment by GH05T-HUNTER5** [comment]
@Prashant-Bhapkar 
They will check and update it
wait

**Comment by davorpa** [comment]
Resolved by #7088
