### ISSUE TITLE
Add Django Cheat sheets

### ISSUE THREAD

**Issue by ayeshag7** [EbookFoundation/free-programming-books#7106]
Add Django cheat sheets. Here are some good ones I found:

A good overview:
https://dev.to/ericchapman/my-beloved-django-cheat-sheet-2056

About models and databases:
https://www.codecademy.com/learn/data-in-django/modules/django-models-and-databases/cheatsheet

**Comment by Rituraj-13** [comment]
Hey, I want to work on this, can you assign me for this?

**Comment by hitaarthh** [comment]
Hello Contributors, 

I have been learning django for a while now and therefore i feel i can potentially contribute to this issue.
