### ISSUE TITLE
菜鸟的成长手册

### ISSUE THREAD

**Issue by 3293172751** [EbookFoundation/free-programming-books#7109]
- 项目地址：https://github.com/3293172751/Block_Chain

- 类别：C++、CSS、Go、Java、JS、Python、书籍

- 项目标题：区块链以及Go语言的学习笔记和路线

- 项目描述：Block_Chain是区块链开发笔记和项目代码，包含区块链路线，Go语言学习路线，Go语言笔记，Go语言开发后端路线，密码学原理，fabric，hyperledger，docker容器技术，git，nginx，区块链原理，基本框架，IPFS技术，pbft共识算法，Go语言开发的项目，区块链的开发项目，redis技术（三主三重和主从扩容）和分布式算法，加密货币开发流程，将其上传到GitHub

- 亮点：内容精细，知识范围广，内容全，供大众学习（无论你是想从事区块链或者Go语言相关工作）
- 示例代码：（可选）
- 截图：（可选）gif/png/jpg
- 
![image](https://user-images.githubusercontent.com/86140903/192101763-d3ce42f2-7492-4e94-a4cc-34e6203d3528.png)
![image](https://sm.nsddd.top/184068388-3102d1c5-c5cd-4bc2-ac3f-476e3219ccf8.png?mail:3293172751@qq.com)
![image](https://user-images.githubusercontent.com/86140903/192101748-6179aef2-a3dc-4c01-886c-abc3a08a0d83.png)

- 后续更新计划：
  开发Linux内核，操作系统源码，以及区块链和fabric框架的解析

**Comment by eshellman** [comment]
doesn't look like a book
