### ISSUE TITLE
want to add some programming books.

### ISSUE THREAD

**Issue by Rahul-Bhati** [EbookFoundation/free-programming-books#7124]
One of them is BeginningNodejs , JavaScript Patterns - Stepanov , PHPOracleWeb etc.

**Comment by nbehrnd** [comment]
If you want to add a resource

+ identify the web address to access the material
+ check if the authors/the publishers permit a public share of the material
+ see how others prepared and submitted a pull request, and adopt this pattern
  for your contribution.  On the main page, a dedicated section «How to
  contribute» provides additional hints and examples to facilitate this.

**Comment by hitaarthh** [comment]
Can i take up this issue, can you assign this to me?

**Comment by ashuvsh** [comment]
Programming with java

**Comment by davorpa** [comment]
@nbehrnd told you all
