### ISSUE TITLE
YouTube  course in the Hindi language 

### ISSUE THREAD

**Issue by JayrajSingh65** [EbookFoundation/free-programming-books#7126]
Hey, 

- I want to add some YouTube channels that provide content related to programming languages in Hindi. 

- This course will be helpful for people who want to learn in  Hindi.

- I want to work on this issue.

**Comment by Atharv-Nalwade** [comment]
Really good thing that someone is listing sources to learn programming in Hindi language I do know such channels can you assign me this issue ?

**Comment by JayrajSingh65** [comment]
> Really good thing that someone is listing sources to learn programming in Hindi language I do know such channels can you assign me this issue ?

I am working on this issue, so you can go for other languages like Tamil or other native language .

**Comment by Atharv-Nalwade** [comment]
Ok
Just a doubt:
1. Will this issue be considered under hactoberfest 2022 ?

**Comment by JayrajSingh65** [comment]
> Ok
> Just a doubt:
> 1. Will this issue be considered under hactoberfest 2022 ?

Yes bro

**Comment by Atharv-Nalwade** [comment]
Ok I will do the issue but I will submit it when hacktoberfest starts accepting the PR's till that time I solve the issue
Kindly consider that

**Comment by JayrajSingh65** [comment]
> Ok I will do the issue but I will submit it when hacktoberfest starts accepting the PR's till that time I solve the issue
> Kindly consider that 

Ok 🙌

**Comment by JayrajSingh65** [comment]
> For youtube, we prefer "playlist" links and the name of the producer/creator. https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#platforms-and-access-notes

Ok I will consider this
