### ISSUE TITLE
Cheatsheet

### ISSUE THREAD

**Issue by Girlwithasmile** [EbookFoundation/free-programming-books#7127]
I am a hackthoberfest contributer and want to add some cheatsheets prepared by me.

**Comment by JayrajSingh65** [comment]
> I am a hackthoberfest contributer and want to add some cheatsheets prepared by me.

- Which topic cheat sheet you want to add?

**Comment by eshellman** [comment]
Note, we do not host books cheatsheets etc. If your sheets are published on a website (not a file-sharing site) you can add a link to it.
