### ISSUE TITLE
I want to add 'Atlassian-Git-Cheatsheet' 

### ISSUE THREAD

**Issue by keerthanasathya** [EbookFoundation/free-programming-books#7163]

**Comment by davorpa** [comment]
Could you provide the URL?

**Comment by keerthanasathya** [comment]
> Could you provide the URL?

file:///C:/Users/keers/Downloads/SWTM-2088_Atlassian-Git-Cheatsheet.pdf

**Comment by keerthanasathya** [comment]
> Could you provide the URL?

https://www.atlassian.com/git/tutorials/atlassian-git-cheatsheet

**Comment by keerthanasathya** [comment]
> Could you provide the URL?

I am not able to push origin in my forked repository, it says "It looks like you don't have write access to keerthanasathya/free-programming-books. If you should, please check with a repository administrator". Can you help me out with this sir?!

**Comment by keerthanasathya** [comment]
#7190

**Comment by Ashish-khanagwal** [comment]
hey, @keerthanasathya It seems, you're trying to push changes to the `main` branch. If this is the case try to change the branch by hitting the command `git checkout -b <your-branch-name>` and then push your changes.
