### ISSUE TITLE
I want to add WEB3 content

### ISSUE THREAD

**Issue by Prashant-Bhapkar** [EbookFoundation/free-programming-books#7172]
Looking forward to adding content related to web3 technology.

**Comment by davorpa** [comment]
Could you provide urls? Or.. are you be able to submit a PR

**Comment by Prashant-Bhapkar** [comment]
Check out:
Added Web Content and Update free-programming-cheatsheets.md #7186

Looking forward to merging this PR with label hactoberfest-accepted

**Comment by Junaid20001** [comment]
Hello sir can  you assign this issue to me
