### ISSUE TITLE
Want to add DevOps Resources

### ISSUE THREAD

**Issue by Ashish-khanagwal** [EbookFoundation/free-programming-books#7199]
I want to add a bunch of DevOps resources like podcasts, ebooks, and tutorials.

You can check out the ebook's link [here](https://www.pdfdrive.com/the-phoenix-project-a-novel-about-it-devops-and-helping-your-business-win-e177508710.html)

**Comment by davorpa** [comment]
Sorry but this book has copyright. We only accept free resources
