### ISSUE TITLE
I want to add some Kotlin and git resources.

### ISSUE THREAD

**Issue by Heismanish** [EbookFoundation/free-programming-books#7204]
I have a few amazing kotlin and git resources that I would like to add.
[A Kotlin book](https://www.pdfdrive.com/head-first-kotlin-e196919920.html)
[Kotlin course by Phillip Lackner](https://youtube.com/playlist?list=PLQkwcJG4YTCRSQikwhtoApYs9ij_Hc5Z9)
[Complete Git and Github tutorial](https://youtu.be/apGV9Kg7ics)

**Comment by strngpowty** [comment]
I would like to work on this issue, can you assign me ?

**Comment by harshdew02** [comment]
I would like to work on Git and the GitHub tutorial please assign me, also I can write this tutorial in Hindi...

**Comment by Heismanish** [comment]
These resources have been already added, so closing the issue.
