### ISSUE TITLE
I want to add a Telugu language blog

### ISSUE THREAD

**Issue by umadhatri** [EbookFoundation/free-programming-books#7211]
Hey everyone! I want to add a Telugu language blog about C. It is partially in telugu and partially in English. Can I add the blog to the list? If I can please let me know! Thank you and cheers!

**Comment by ojasaklechayt** [comment]
Hey!! In my opinion, I think you can add it in Telugu Section. It would be great.

**Comment by umadhatri** [comment]
> Hey!! In my opinion, I think you can add it in Telugu Section. It would be great.

Great! I'll add that blog

**Comment by davorpa** [comment]
As same reason that closes PR... Blogs are out of scope of this repo
