### ISSUE TITLE
I want to add websites which give best tutorials and materials for free

### ISSUE THREAD

**Issue by dp-lisin11** [EbookFoundation/free-programming-books#7225]
online platform is more precise and can help learn better so there should be learning websites for languages too

**Comment by akshaykhoje** [comment]
Please assign this issue to me. I'll be more than happy to give away all my resources to the community for learning purposes.

**Comment by davorpa** [comment]
Easy, if you want to add something... read first CONTRIBUTING carefully, then send a PR
