### ISSUE TITLE
I want to add more courses to free-courses-hi.md

### ISSUE THREAD

**Issue by kanikamalhans** [EbookFoundation/free-programming-books#7357]
I have many courses in DSA, Flutter, HTML CSS, etc to add in free-courses-hi for adding, Kindly assign me this issue.

**Comment by kanikamalhans** [comment]
I have more than 20 courses to be added

**Comment by Aarize29** [comment]
Please Merge My Pr 
#7386

**Comment by davorpa** [comment]
Resolved by #7359, Resolved by #7358
