### ISSUE TITLE
Added a source code analyzing GitHub repository in Chinese

### ISSUE THREAD

**Issue by liutng** [EbookFoundation/free-programming-books#7430]
Hi,
I'm so happy to make my first contribution to the open source community. For my first contribution, I added an online GitHub repository for Android source analysis in Chinese with Pull Request #7429. I would appreciate that if you could help me to review and merge it, which I would think may help other people in this community. I am looking forward to building this community together to make it more robust.

**Comment by davorpa** [comment]
Resolved by #7429
