### ISSUE TITLE
Add new bengali book on C++

### ISSUE THREAD

**Issue by metabiswadeep** [EbookFoundation/free-programming-books#7463]
Need to add new bengali books on C++ as none are listed.

**Comment by ayush0801** [comment]
#7462 I want to add a new C++ computer programming book in Bengali as there are none. There is one for C programming language but I wanted to add for C++. The author of the book is Mahmudul Hasan. 
[c_programming_bangla_book.pdf](https://github.com/EbookFoundation/free-programming-books/files/9704625/c_programming_bangla_book.pdf)

**Comment by Harsh0326** [comment]
Hey @davorpa can I add book .?

**Comment by ShuvamBag** [comment]
hello sir, I want to work on this issue.

**Comment by eshellman** [comment]
please remember we can't list books on "directory" or filesharing sites, as these are almost always unauthorized distributions
