### ISSUE TITLE
Add 'Algorithm Notes for Professional' Book PDF

### ISSUE THREAD

**Issue by keerthanasathya** [EbookFoundation/free-programming-books#7507]
This book provides a detailed explanation of algorithms from the start for beginners to understand in a better way.

**Comment by davorpa** [comment]
Are you talking about https://goalkicker.com/AlgorithmsBook/AlgorithmsNotesForProfessionals.pdf?

**Comment by keerthanasathya** [comment]
> Are you talking about https://goalkicker.com/AlgorithmsBook/AlgorithmsNotesForProfessionals.pdf? Go ahead then!

Yes sir!
