### ISSUE TITLE
Add 'Matlab Programming Fundamentals' PDF

### ISSUE THREAD

**Issue by keerthanasathya** [EbookFoundation/free-programming-books#7519]
This book provides a detailed explanation of matlab from the start for beginners to understand in a better way.

**Comment by Rohanfizz** [comment]
Can you please assign this issue to me :)

**Comment by keerthanasathya** [comment]
> Can you please assign this issue to me :)

You are not supposed to do that, this is my issue! I can report about this, this is against Hactoberfest guidelines.

**Comment by toukirkhan** [comment]
@eshellman how can you merge someone else's PR on someone else's repo isn't it against the hacktoberfest guidelines?

**Comment by Rohanfizz** [comment]
@keerthanasathya first of all, I'm sorry, I was unaware of how this repo worked. Issues are generally not raised by the ones who can fix that, When I saw that issue, there was no PR made to fix that. I thought this feature was requested by a moderator who I thought was you. Just advising you for the future, do PR as soon as you can in future as this might provoke others to fix the issue ASAP.

@toukirkhan you should read the repository contributing guidelines. You commented on bad language earlier which you should not.

**Comment by keerthanasathya** [comment]
> @keerthanasathya first of all, I'm sorry, I was unaware of how this repo worked. Issues are generally not raised by the ones who can fix that, When I saw that issue, there was no PR made to fix that. I thought this feature was requested by a moderator who I thought was you. Just advising you for the future, do PR as soon as you can in future as this might provoke others to fix the issue ASAP.
> 
> @toukirkhan you should read the repository contributing guidelines. You commented on bad language earlier which you should not.

But I just created the issue back then, how come it's late?! Not fair at all.

**Comment by Rohanfizz** [comment]
> > @keerthanasathya first of all, I'm sorry, I was unaware of how this repo worked. Issues are generally not raised by the ones who can fix that, When I saw that issue, there was no PR made to fix that. I thought this feature was requested by a moderator who I thought was you. Just advising you for the future, do PR as soon as you can in future as this might provoke others to fix the issue ASAP.
> > @toukirkhan you should read the repository contributing guidelines. You commented on bad language earlier which you should not.
> 
> But I just created the issue back then, how come it's late?! Not fair at all.

I think you are new to open source contribution.
Issues on github are never kept on waiting. If you know the fix, you do the fix.
Make a PR as soon as possible.

**Comment by keerthanasathya** [comment]
> > > @keerthanasathya first of all, I'm sorry, I was unaware of how this repo worked. Issues are generally not raised by the ones who can fix that, When I saw that issue, there was no PR made to fix that. I thought this feature was requested by a moderator who I thought was you. Just advising you for the future, do PR as soon as you can in future as this might provoke others to fix the issue ASAP.
> > > @toukirkhan you should read the repository contributing guidelines. You commented on bad language earlier which you should not.
> > 
> > 
> > But I just created the issue back then, how come it's late?! Not fair at all.
> 
> I think you are new to open source contribution. Issues on github are never kept on waiting. If you know the fix, you do the fix. Make a PR as soon as possible.

Anyways thanks Rohan for teaching me this!

**Comment by toukirkhan** [comment]
@Rohanfizz yes it's my bad that commented wrong at first place.

**Comment by Rohanfizz** [comment]
> > > > @keerthanasathya first of all, I'm sorry, I was unaware of how this repo worked. Issues are generally not raised by the ones who can fix that, When I saw that issue, there was no PR made to fix that. I thought this feature was requested by a moderator who I thought was you. Just advising you for the future, do PR as soon as you can in future as this might provoke others to fix the issue ASAP.
> > > > @toukirkhan you should read the repository contributing guidelines. You commented on bad language earlier which you should not.
> > > 
> > > 
> > > But I just created the issue back then, how come it's late?! Not fair at all.
> > 
> > 
> > I think you are new to open source contribution. Issues on github are never kept on waiting. If you know the fix, you do the fix. Make a PR as soon as possible.
> 
> Anyways thanks Rohan for teaching me this!

We all are here to learn and share :)
If you are starting out open source contribution through I can suggest you some good first-timer repos :)

**Comment by Rohanfizz** [comment]
> @Rohanfizz yes it's my bad that commented wrong at first place.

We cool brother 🤜🤛

**Comment by davorpa** [comment]
Please, stop discuss

@keerthanasathya Not is necessary open issues if you are be able to send the pull request (PR) :wink:. Anyway when will send, please link it writing in it description something like `Resolves NNN`, where NNN is the issue number.

**Comment by davorpa** [comment]
Anyway... resolved by #7528
