### ISSUE TITLE
Add DBMS Learning Resource

### ISSUE THREAD

**Issue by Geetanjaligupta123** [EbookFoundation/free-programming-books#7535]
I want to add DBMS Learning resources.

**Comment by Geetanjaligupta123** [comment]
I want to add DBMS Book and youtube best resources to learn DBMS in a better way for beginners.
Can you please assign this issue to me :)

**Comment by ys1113457623** [comment]
https://github.com/EbookFoundation/free-programming-books/pull/7566

**Few resources added**

**Comment by Pranathi-star** [comment]
I also want to add a DBMS learning resource. Please assign this issue to me

**Comment by davorpa** [comment]
Not is necessary open issues if you are be able to send the pull request (PR) :wink:.

Anyway, if you submit a PR, help us to autoclose this issue. How? Read this article about [how to linking a PR to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by BugsBunny-PG** [comment]
I want to  add some useful resources to learn  DBMS in practical way for beginners  please assign this issue to me

**Comment by kunna67** [comment]
Can you assign to me

**Comment by BugMasterArka** [comment]
Can I please get assigned to this issue?

**Comment by UdayHaldkar** [comment]
I want to add some DBMS notes for beginners to Advance.

**Comment by eshellman** [comment]
we have quite a few now
