### ISSUE TITLE
Add Dart Cheatsheet

### ISSUE THREAD

**Issue by Rituraj-13** [EbookFoundation/free-programming-books#7583]

**Comment by Rituraj-13** [comment]
Hey, I want to contribute on this. Can you please assign this to me?

**Comment by Rijudas149** [comment]
Hey, I can work on this topic. May I be assigned on this topic?

**Comment by davorpa** [comment]
Not is necessary open issues if you are be able to send the pull request (PR) :wink:.

Anyway, if you submit a PR, help us to autoclose this issue. How? Read this article about [how to linking a PR to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
