### ISSUE TITLE
Want to add NLP Course from Zero to Hero in Hindi/Urdu.

### ISSUE THREAD

**Issue by muhtalhakhan** [EbookFoundation/free-programming-books#7586]
Hey there,

I wanted to add a NLP course from zero to hero which is in hindi/urdu for which I couldn;t any course file to edit, can you add that course file so that I can edit and merge my PR with it after the creation.

Looking forward!

**Comment by davorpa** [comment]
Not is necessary open issues if you are be able to send the pull request (PR) :wink:.

Anyway, if you submit a PR, help us to autoclose this issue. How? Read this article about [how to linking a PR to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by muhtalhakhan** [comment]
cc: @davorpa

**Comment by davorpa** [comment]
Resolved by #7702
