### ISSUE TITLE
Want to add a beginner friendly DSA course in Hindi by Love Babbar.

### ISSUE THREAD

**Issue by Terra-01** [EbookFoundation/free-programming-books#7608]
### For Resources 
YouTube Playlist - https://youtube.com/playlist?list=PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA
### Description
This playlist has been curated for everyone regardless of the year, stream, branch etc. with 140 Lectures, 100 hours of Content, 250+ Questions, Handwritten Notes.... pretty much everything that is required to reach the advanced level in DSA!
### Why is this valuable (or not)?
It is extremely valuable as it helps candidates prepare for Software Engineering Interviews and also assists them to excel at DSA related coding problems.
### How do we know it's really free?
Love Babbar has created all videos for free on YouTube. In fact, the first video of this playlist explains about the "Free" series and to share it as much as possible.
### For book lists, is it a book? For course lists, is it a course? etc.
It is a course.
### Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.
> ## **Please consider it for HactoberFest.**
>> I want to contribute in this particular issue , i would be highly thankful if you will assign this to me.
>> Thanks

**Comment by Terra-01** [comment]
### **This is the video where he explains about the course:** https://youtu.be/9kQ1JUDleWg

**Comment by Terra-01** [comment]
###  **Made the Changes -** https://github.com/EbookFoundation/free-programming-books/pull/7610

**Comment by Terra-01** [comment]
### Please Review

**Comment by davorpa** [comment]
Resolved in #7295
