### ISSUE TITLE
Add 'Programming with MicroPython'

### ISSUE THREAD

**Issue by keerthanasathya** [EbookFoundation/free-programming-books#7642]

**Comment by parikhparth23** [comment]
Created a PR - https://github.com/EbookFoundation/free-programming-books/pull/7645

**Comment by parikhparth23** [comment]
@keerthanasathya you should have updated this thread before.
Mind deleting yours and going fwd plz comment in the ticket that you are working on it.

**Comment by parikhparth23** [comment]
@keerthanasathya both PRs are different

**Comment by davorpa** [comment]
This appears not to be an authorized distribution. Please see docs/CONTRIBUTING.md guidelines.
