### ISSUE TITLE
Linux Couse (Bengali)

### ISSUE THREAD

**Issue by Sabyasachi-Seal** [EbookFoundation/free-programming-books#7668]
Noticed that there was no Linux Book in Bengali. 
Want to add this Course to the list: https://youtube.com/playlist?list=PLMTKJq4uuKqXVg7S7XujEsONl9ZVT4X0p

**Comment by davorpa** [comment]
This is a video course. Put it in our `courses-bn.md` files

**Comment by Sabyasachi-Seal** [comment]
Got it 👍

**Comment by Sabyasachi-Seal** [comment]
PR: https://github.com/EbookFoundation/free-programming-books/pull/7674

**Comment by davorpa** [comment]
Not is necessary open issues if you are be able to send the pull request (PR) :wink:.

Anyway, if you submit a PR, help us to autoclose this issue. How? Read this article about [how to linking a PR to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by Sabyasachi-Seal** [comment]
Understood 👌. Will keep that in mind from the next time.
Thanks for letting me contribute :)
