### ISSUE TITLE
Need to have checklist for developers before making a accessible(for visually impaired persons) website

### ISSUE THREAD

**Issue by Hari70a** [EbookFoundation/free-programming-books#7676]
It would be helpful to have some to do checklist for accessibility before even starting the work

**Comment by shrn01** [comment]
Hey @Hari70a can you elaborate on the issue?

**Comment by Hari70a** [comment]
@shrn01 ,

It's similar to Todo list while doing the accessibility. I am not really sure, whether we need this.

Let me wait for @davorpa & @eshellman decision & assign it to me if it's needed.

**Comment by eshellman** [comment]
@Hari70a please elaborate on the issue

**Comment by Hari70a** [comment]
@eshellman ,
It's an accessibility checklist , that dev can use and mark it complete, once completed.

Not sure whether we need it.

Thank you

**Comment by eshellman** [comment]
we have a good entry in the HTML and CSS section of our cheatsheet list
