### ISSUE TITLE
Add SEO cheatsheet

### ISSUE THREAD

**Issue by Hari70a** [EbookFoundation/free-programming-books#7681]
Add SEO cheatsheet

**Comment by davorpa** [comment]
Not is necessary open issues if you are be able to send the pull request (PR) :wink:.

Anyway, if you submit a PR, help us to autoclose this issue. How? Read this article about [how to linking a PR to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by Darkdevip12** [comment]
Hello sir can you assign this issue to me?

**Comment by Hari70a** [comment]
@Darkdevip12 ,

Your PR seems to be duplicate, as I already have one in place.

https://github.com/EbookFoundation/free-programming-books/pull/7752

Could you please close yours.
