### ISSUE TITLE
Want to add DSA And Algo cheat sheet

### ISSUE THREAD

**Issue by rahulranjan74** [EbookFoundation/free-programming-books#7688]

**Comment by kishanshinde** [comment]
I can add dsa and  algo cheat sheet .. assign this issue to me .!
is .png fine or should it be .txt files

**Comment by Abinashbunty** [comment]
I think .txt files are fine. But maybe it is better to have .md files. Markdown files are quite easy to document and represent.

**Comment by rahulranjan74** [comment]
> I think .txt files are fine. But maybe it is better to have .md files. Markdown files are quite easy to document and represent.

can i upload then ??

**Comment by kishanshinde** [comment]
how is markdown file created ??

**Comment by Abinashbunty** [comment]
You can perhaps use [Stackedit](https://stackedit.io/) as an editor to write your markdown file.

And for markdown resources, you can follow: [JOHN GRUBER documentation](https://daringfireball.net/projects/markdown)

**Comment by rahulranjan74** [comment]
thanks !

**Comment by codurr1** [comment]
Please assign this to me

**Comment by Abinashbunty** [comment]
@codurr1 You can submit a PR. No need to assign.

**Comment by codurr1** [comment]
Just added a [PR](https://github.com/EbookFoundation/free-programming-books/pull/8760) please review

**Comment by eshellman** [comment]
we now have 4 DSA cheatsheets
