### ISSUE TITLE
Add DSA category in Course section of Tamil language.

### ISSUE THREAD

**Issue by yogan-gopi** [EbookFoundation/free-programming-books#7717]
There are no courses available on **DSA(Data Structures and Algorithms)** in **Tamil** language.

**Comment by davorpa** [comment]
Not is necessary open issues if you are be able to send the pull request (PR) :wink:.

Anyway, if you submit a PR, help us to autoclose this issue. How? Read this article about [how to linking a PR to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
