### ISSUE TITLE
[Fix] DevOps bootcamp

### ISSUE THREAD

**Issue by Sabyasachi-Seal** [EbookFoundation/free-programming-books#7720]
Devops Bootcamp by Kunal Kushwaha is added in the Hindi Courses section, but the course is in english.

![Screenshot_2022-10-06-23-48-50-21_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/36451386/194389349-42b4c074-87f8-4a11-b2c5-5449cdceaea8.jpg)

**Comment by RamitPahwa** [comment]
Hey, can I fix this ?

**Comment by Sabyasachi-Seal** [comment]
> Hey, can I fix this ?

Hey @RamitPahwa, 

Don't worry I'll handle this issue(once assigned). 

I'll also be checking some other couses under different sections if the same mistake was made.

**Comment by davorpa** [comment]
Not is necessary open issues if you are be able to send the pull request (PR) :wink:.

Anyway, if you submit a PR, help us to autoclose this issue. How? Read this article about [how to linking a PR to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
