### ISSUE TITLE
Add Kubernetes resource

### ISSUE THREAD

**Issue by VAIBHAVCES** [EbookFoundation/free-programming-books#7812]
VMWare vsphere is a very popular VMware product, and VMware provides a kubernetes guide to integrate them and use it practically.
Aim of this issue is too add free resource for it

**Comment by davorpa** [comment]
Not is necessary open issues if you are be able to send the pull request (PR) :wink:.

Anyway, if you submit a PR, help us to autoclose this issue. How? Read this article about [how to linking a PR to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
