### ISSUE TITLE
Add free java resource

### ISSUE THREAD

**Issue by VAIBHAVCES** [EbookFoundation/free-programming-books#7813]
Adding free and amazing java book complete reference

**Comment by davorpa** [comment]
Not is necessary open issues if you are be able to send the pull request (PR) :wink:.

Anyway, if you submit a PR, help us to autoclose this issue. How? Read this article about [how to linking a PR to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by Harsh0326** [comment]
Hey , can you assign this issue to me .

**Comment by Ishh91** [comment]
Add some Java books with all references

**Comment by lakshyabhasin509** [comment]
I have Ninth edition of the book as a pdf can i contribute

**Comment by Avishri99** [comment]
> Adding free and amazing java book complete reference

please assign it to me

**Comment by eshellman** [comment]
unfortunately no authorized distributions are available for that book
