### ISSUE TITLE
Want to Add a book ( Mathematics for Computer Science )

### ISSUE THREAD

**Issue by ducheharsh** [EbookFoundation/free-programming-books#7814]
It's an MIT OCW book by Eric Lehman and F. Thomson Leighton.

**Comment by shrn01** [comment]
Send out a PR if it's not already there.

**Comment by ducheharsh** [comment]
PR requested [ added a new section for 'mathematics for programming'.

**Comment by shrn01** [comment]
Please link the PR to the issue so that it will be auto closed once the PR is merged

**Comment by yrhemendra** [comment]
Sir Can i contribute to resolve the issue and give some feedback?

**Comment by shrn01** [comment]
@yrhemendra please feel free to raise a PR directly if you have any free resource in mind. No need for an issue

**Comment by yrhemendra** [comment]
Ok sir

**Comment by yrhemendra** [comment]
> @yrhemendra please feel free to raise a PR directly if you have any free resource in mind. No need for an issue

Ok sir

**Comment by codurr1** [comment]
Please assign this to me

**Comment by eshellman** [comment]
added in the subjects list under Mathematics For Computer Science
