### ISSUE TITLE
Add webpack beginner course

### ISSUE THREAD

**Issue by Hari70a** [EbookFoundation/free-programming-books#7972]
- Need to add a webpack beginner course

**Comment by BugsBunny-PG** [comment]
I want to add course to learn webpack in practical way for beginners please assign this issue to me.

**Comment by Hari70a** [comment]
I already have a PR in place which is linked with this issue. Kindly check it.

@BugsBunny-PG

**Comment by eshellman** [comment]
added webpack course in #9177
