### ISSUE TITLE
Add solidity courses

### ISSUE THREAD

**Issue by akp111** [EbookFoundation/free-programming-books#7987]
Add solidity courses that can be followed by begineers

**Comment by souravsasmal01** [comment]
Hello sir , can you assign this issue to me?

**Comment by souravsasmal01** [comment]
Hey there, can you assign this issue to me?

**Comment by psantosh16** [comment]
Hey ,
@akp111  
Can you assign this to me , I want to make some contributions in this issue.

**Comment by Sanhati** [comment]
@akp111 I would like to contribute, please do assign me this issue.

**Comment by souravsasmal01** [comment]
Hey ,
@akp111
Can you assign this to me , I want to make some contributions in this issue.

**Comment by getcoder-top** [comment]
Hiii apk111,
can you please assign this issue to me, i am currently working on blockchain can suggest some good books

**Comment by shrn01** [comment]
@akp111 Feel free to raise a PR for it. Link this issue so that it's autoclosed. In future feel free to raise a PR directly if you want to add a new resource. No need for an issue

**Comment by shrn01** [comment]
@psantosh16 @Sanhati @souravsasmal01 @getcoder-top hey please raise a PR directly if you have a free resource you want to share. No need for an issue for that. Ready [Contributing.md](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md) for more information

**Comment by akp111** [comment]
Hey @shrn01 
I have raised this PR
https://github.com/EbookFoundation/free-programming-books/pull/8091
