### ISSUE TITLE
Were do I place books about semaphores (Operating Systems)

### ISSUE THREAD

**Issue by raissonsouto** [EbookFoundation/free-programming-books#8021]
Hello, I'm willing to contributing to the repository adding a book about semaphores, however I didn't find where to place it. May you help me, please?

**Comment by shrn01** [comment]
Hey @raissonsouto, i think you can place the book in books/free-programming-books-subjects.md under operating-systems

**Comment by raissonsouto** [comment]
Ok, I will place it there, thanks!
