### ISSUE TITLE
Add Jest cheatsheet

### ISSUE THREAD

**Issue by Hari70a** [EbookFoundation/free-programming-books#8033]
- Add Jest cheatsheet

**Comment by astitva0011** [comment]
can i get the opportunity for resolving this issue?

**Comment by Hari70a** [comment]
@astitva0011 ,
I already raised a PR for this one. If you want, I can raise one more issue for you

**Comment by astitva0011** [comment]
It would be nice if you can do that

**Comment by Hari70a** [comment]
@astitva0011 ,

I already created this issue.
Please check this one https://github.com/EbookFoundation/free-programming-books/issues/8068

@davorpa / @eshellman / @LuigiImVector ,

Please assign the above issue to @astitva0011
