### ISSUE TITLE
Want to add OOPS concept book 

### ISSUE THREAD

**Issue by CodeXstalker** [EbookFoundation/free-programming-books#8051]
Hii @EbookFoundation,
There is missing OOP concept book in it this repo.

**Comment by CodeXstalker** [comment]
@EbookFoundation please assign this issue, I want to work on it.

**Comment by harshlancer** [comment]
I also want to help with this issue, please elaborate.

**Comment by astitva0011** [comment]
!assign

**Comment by sudips413** [comment]
assign me

**Comment by lakshmimaurya** [comment]
assign me

**Comment by somiyaAgarwal** [comment]
I want to work on this . Can you assign it to me??

**Comment by shrn01** [comment]
Hey @CodeXstalker Please feel free to raise a PR if you have a valuable resource which is free. No need to raise an issue for that. Please make sure you link the issue to the PR so that it will get auto closed once the PR is merged

**Comment by namitaarya** [comment]
Is this issue still open for contribution?

**Comment by shrn01** [comment]
Hey @namitaarya you do not need a issue to contribute. Feel free to raise a PR directly with the resources

**Comment by kanishkamalik09** [comment]
Please assign this issue to me

**Comment by eshellman** [comment]
proposed book did not appear to be free
