### ISSUE TITLE
Add a basic over view book of how programming languages work

### ISSUE THREAD

**Issue by mohan89en** [EbookFoundation/free-programming-books#8055]
Before entering into different programming languages people should understand how a language is structured and how to works at machine level

**Comment by mohan89en** [comment]
I can add some good books to help this, If you kindly accept.

**Comment by iamkunalkeshav** [comment]
can i add?

**Comment by shrn01** [comment]
Please feel free to raise a PR. Please link it to this issue so it is auto closed
