### ISSUE TITLE
Add react testing library cheatsheet

### ISSUE THREAD

**Issue by Hari70a** [EbookFoundation/free-programming-books#8068]
- Need to have RTL cheatsheet

**Comment by Hari70a** [comment]
@astitva0011
If you want, you can take this one

**Comment by iamkunalkeshav** [comment]
can i add ?

**Comment by Prachi257** [comment]
Can I add?

**Comment by astitva0011** [comment]
> @astitva0011 If you want, you can take this one

ok, thanks!

**Comment by shrn01** [comment]
Raising an issue is not required for contributions. Feel free to raise a PR directly with the resources you think are useful and are free

**Comment by Hari70a** [comment]
Closing as PR Got merged
