### ISSUE TITLE
Add 'DP Cheatsheet'

### ISSUE THREAD

**Issue by keerthanasathya** [EbookFoundation/free-programming-books#8077]

**Comment by Anuragwagh** [comment]
I will add the DP cheatsheet to the webpage and PDF format, which will be easy to access and read. Can I get this opportunity to contribute to this issue?

**Comment by keerthanasathya** [comment]
> I will add the DP cheatsheet to the webpage and PDF format, which will be easy to access and read. Can I get this opportunity to contribute to this issue?

I'm doing it!

**Comment by drashan14** [comment]
Hello Sir,
I would like to add DP CheatSheet for this issue.

**Comment by shrn01** [comment]
Closing this issue as PR is merged
