### ISSUE TITLE
Website Share Links

### ISSUE THREAD

**Issue by thomasthaddeus** [EbookFoundation/free-programming-books#8099]
Links not appearing on website. Attached links and photo of error occurring below

[Link:](https://ebookfoundation.github.io/free-programming-books/)
+ <https://ebookfoundation.github.io/free-programming-books/>

![GithubIssueFreeEBooks](https://user-images.githubusercontent.com/92204097/195198276-871d0eb3-8c6f-4db3-a869-0fbe4d1abe12.jpg)

**Comment by eshellman** [comment]
I'm confused. Is this fixed?

**Comment by thomasthaddeus** [comment]
Yes it is fixed. It looks like its not showing the links only on firefox. After this fix is applied it works on firefox, edge, and chrome.

![Link To Website](https://user-images.githubusercontent.com/92204097/195275072-a3350a17-4a12-4648-b2a7-7d1b1140deb7.jpg)
![Website](https://user-images.githubusercontent.com/92204097/195275041-e5f98047-2853-4e68-80c5-6edc4c888e6f.jpg)

Let me clarify. The links only disappear when on the website. So on the left is github readme and on the right is the 

![Side-By-Side](https://user-images.githubusercontent.com/92204097/195276315-6d4dbe38-b454-4feb-96f5-ac188bf30a33.jpg) of the two
