### ISSUE TITLE
Node.js Courses/Helping material in Urdu/Hindi (Hacktoberfest-22)

### ISSUE THREAD

**Issue by cchow33** [EbookFoundation/free-programming-books#8138]
I found a helpful Node.js course in Urdu/Hindi and I think we can add it to the existing list.

**Comment by shrn01** [comment]
Opening an issue is not needed for contributions. Please feel free to directly raise a PR with the resources you think are free and useful

**Comment by eshellman** [comment]
@cchow33's PR tried to merge hindi resourses into english file. Don't hesitate to check if the resources found their way to the hindi list, make a PR if not or ask to close this if so.
