### ISSUE TITLE
Adding free React course in Khmer (Cambodian) ខ្មែរ

### ISSUE THREAD

**Issue by cchow33** [EbookFoundation/free-programming-books#8150]
I noticed there aren't any React resources for Khmer speakers. I would like to add this free React tutorial to the list of resources.

**Comment by Nikhil562** [comment]
I would love to do that , can you please assign to me

**Comment by shrn01** [comment]
Opening an issue is not needed for contribution. Feel free to raise a PR with the resources

**Comment by eshellman** [comment]
add it to courses/free-courses-km.md
