### ISSUE TITLE
Add a chai cheatsheet

### ISSUE THREAD

**Issue by Hari70a** [EbookFoundation/free-programming-books#8157]
- Need to have a chai cheatsheet

**Comment by Hari70a** [comment]
@davorpa , @eshellman , @LuigiImVector ,

Please assign it to me

**Comment by muchristian** [comment]
Please assign it to me

**Comment by shrn01** [comment]
Please feel free to raise a PR. Link the issue so that it will be auto closed

**Comment by Hari70a** [comment]
> Please feel free to raise a PR. Link the issue so that it will be auto closed

I am trying to maintain some bucket for me. That's why raising an issue. 

And I purposefully didn't raise the PR immediately, because there will be conflicts with my another base MR https://github.com/EbookFoundation/free-programming-books/pull/8034, which got merged yesterday. Will do now

**Comment by Hari70a** [comment]
Closed as PR got merged
