### ISSUE TITLE
Add Data Analytics Cheat sheet

### ISSUE THREAD

**Issue by abhisek247767** [EbookFoundation/free-programming-books#8241]
Can you Give me the opportunity to add awesome python and Data Analytics Cheat sheet for the community.

**Comment by AS12-as** [comment]
please assign this to me @abhisek247767

**Comment by Zaid-Parkar** [comment]
I'll do this GitHub task for you.

**Comment by shrn01** [comment]
@abhisek247767 Feel free to raise a PR. Link this Issue so this is autoclosed

**Comment by ajs1220** [comment]
pr #8584
