### ISSUE TITLE
Add Software Construction Book

### ISSUE THREAD

**Issue by SarojWasti** [EbookFoundation/free-programming-books#8247]
I'm opening this issue to add a free book for software construction. [Here is the link to the book](https://www.pdfdrive.com/code-complete-a-practical-handbook-of-software-construction-d181977496.html):

Details:
Type: Book (pdf)
Pages: 914 (2nd ed.)
Author: Steve McConnell

**Comment by AS12-as** [comment]
Please assign this to me @SarojWasti
