### ISSUE TITLE
Competitive Programming

### ISSUE THREAD

**Issue by ashutosh-gupta2111** [EbookFoundation/free-programming-books#8288]
To add a Cheat Sheet of important Competitive Programming algorithms.

**Comment by ashutosh-gupta2111** [comment]
Please assign this issue to me.

**Comment by neeraj1766** [comment]
assign this to me please

**Comment by crescentpartha** [comment]
> assign this to me please

Create a direct **pull request**, @neeraj1766 @ashutosh-gupta2111
