### ISSUE TITLE
Add Few DevOps Courses

### ISSUE THREAD

**Issue by YashSalunke12** [EbookFoundation/free-programming-books#8440]
There are very few courses added in DevOps section, I want to add some more courses, Assign me for this!

**Comment by Zaid-Parkar** [comment]
I'll do this GitHub task for you.

**Comment by shrn01** [comment]
@YashSalunke12 Feel free to raise a PR. Link this issue so that it is autoclosed. In future if you want to add a new resource feel free to raise a PR directly.

**Comment by AshishSharma1203** [comment]
> @YashSalunke12 Feel free to raise a PR. Link this issue so that it is autoclosed. In future if you want to add a new resource feel free to raise a PR directly.

i have made the pull request regarding this. Can you please verify this and merge this .
