### ISSUE TITLE
Wanna add a coding interview book

### ISSUE THREAD

**Issue by jha-om** [EbookFoundation/free-programming-books#8441]
This is one of the most important book for coding interviews.
Please assign this issue to me, I will add the book quickly and help others finding this book easily on your website.

**Comment by Itashamodi** [comment]
please assign me the issue, I want to add some best coding books

**Comment by shrn01** [comment]
@jha-om Feel free to raise a PR for it. Link this issue so that it's autoclosed. In future feel free to raise a PR directly if you want to add a new resource. No need for an issue

**Comment by ashutosh-gupta2111** [comment]
please assign me the issue

**Comment by anshulkumar2311** [comment]
Please assign this issue to me. I will handle this issue

**Comment by aryabasu17** [comment]
I wanna add some interview books that i have it , I would like to work on this issue .

**Comment by Jaya-sys** [comment]
Please assign me this issue?
