### ISSUE TITLE
Add Programming books For Hackers

### ISSUE THREAD

**Issue by Itguyyyyyy** [EbookFoundation/free-programming-books#8447]
.

**Comment by 0fs3c** [comment]
Please assign this to me

**Comment by Zaid-Parkar** [comment]
I'll do this GitHub task for you.

**Comment by montu2003** [comment]
hello sir, can you assign this to me... i am a bug bounty(ethical hacker) hunter so I can do this task for you

**Comment by Itashamodi** [comment]
I am interested in doing this task, please assign me

**Comment by shrn01** [comment]
@Itguyyyyyy Feel free to raise a PR for it. Link this issue so that it's autoclosed. In future feel free to raise a PR directly if you want to add a new resource. No need for an issue

**Comment by kanishkamalik09** [comment]
Please assign this task to me

**Comment by eshellman** [comment]
severla books have been added
