### ISSUE TITLE
Java Bangla (বাংলা) tutorial for beginners

### ISSUE THREAD

**Issue by NeamulIslamFahim** [EbookFoundation/free-programming-books#8494]
Java Bangla (বাংলা) tutorial for beginners video contributed

**Comment by codingsagar** [comment]
Please assign this issue to me as soon as possible.

**Comment by NeamulIslamFahim** [comment]
How can I assign you?

**Comment by shrn01** [comment]
Hey @NeamulIslamFahim please feel free to raise a PR for it. Also link this issue so that it may be auto closed. In the future please feel free to raise a PR directly if you want to add a new resource. No need for an issue

**Comment by NeamulIslamFahim** [comment]
ok. Will you update the subject that I have contributed soon?

**Comment by codingsagar** [comment]
No thanks I will make a PR for other recourse. But they really merge our PR because I saw many pending PR'S which have to merged

**Comment by NeamulIslamFahim** [comment]
Won't my contribution be merged in the main branch?

**Comment by shrn01** [comment]
@NeamulIslamFahim the new contributions are directly committed to the main branch. so changes should be instantaneous

**Comment by shrn01** [comment]
Please close the issue if it is solved

**Comment by NeamulIslamFahim** [comment]
Thanks

**Comment by NeamulIslamFahim** [comment]
Why Java Bangla tutorial for Beginner is still not merged?
