### ISSUE TITLE
Add Graph Problems CheatSheet

### ISSUE THREAD

**Issue by ashutosh-gupta2111** [EbookFoundation/free-programming-books#8514]
Can Add Graph Problems CheatSheet?

**Comment by ashutosh-gupta2111** [comment]
Can you please assign me this issue?

**Comment by congo11** [comment]
[](url)
[javascript cheatsheat.txt](https://github.com/EbookFoundation/free-programming-books/files/9795564/javascript.cheatsheat.txt)

**Comment by codurr1** [comment]
Please assign this issue to me

**Comment by riddhitech** [comment]
Please assign me this issue.

**Comment by shrn01** [comment]
@ashutosh-gupta2111 @congo11 @codurr1 @riddhitech please feel free to raise a PR for the same adding the resources to proper file. No need to have an issue for that. Also read docs/CONTRIBUTING.md for more information about contributions
