### ISSUE TITLE
Add Qiskit textbook

### ISSUE THREAD

**Issue by Cipher-unhsiV** [EbookFoundation/free-programming-books#8633]
Can I get an opputunity to add this super-useful "Qiskit" textbook to the communnity!

**Comment by Abinashbunty** [comment]
You can directly submit a PR for the same. 👍🏻

**Comment by devmahfuj** [comment]
Hello Sir, Can you assign this issue to me?

**Comment by Cipher-unhsiV** [comment]
Already done @devmahfuj  bro :)
