### ISSUE TITLE
wanna add javascript notes in hindi

### ISSUE THREAD

**Issue by SuvratZZZ** [EbookFoundation/free-programming-books#8657]

**Comment by shrn01** [comment]
hey @SuvratZZZ please feel free to raise a PR for the same adding the resources to proper file. No need to have an issue for that. Also read docs/CONTRIBUTING.md for more information about contributions

**Comment by radar** [comment]
What list am I on that is making all these people tag me in these issues?

**Comment by eshellman** [comment]
added
