### ISSUE TITLE
Hacktoberfest contributions marked as excluded

### ISSUE THREAD

**Issue by miguelpalazzo** [EbookFoundation/free-programming-books#8671]
Maybe not a direct issue with the repository itself, just found out the hard way that PRs might be getting marked now as **Excluded** from the Hacktoberfest event.

![image](https://user-images.githubusercontent.com/50017/196687750-d69556b9-888e-4bbb-8bde-d48ca2fb2e65.png)

**Comment by eshellman** [comment]
I have created a support ticket with Hacktoberfest and they are reviewing the case. I doubt it will be a problem.

**Comment by miguelpalazzo** [comment]
> I have created a support ticket with Hacktoberfest and they are reviewing the case. I doubt it will be a problem.

So awesome! Thanks, @eshellman!

**Comment by RiyaBhaskar12** [comment]
Any updates on the same?

**Comment by eshellman** [comment]
Will post here with any updates. It's a weekend!

**Comment by pcodex** [comment]
@eshellman Looks like the repo is still excluded

**Comment by baciucristian** [comment]
Any updates? @eshellman

**Comment by baciucristian** [comment]
![image](https://user-images.githubusercontent.com/49842769/198389750-f4c67e49-ca76-4046-b80b-fb5cd4e26403.png)
It seems that is resolved now. Thank you! 😄

**Comment by miguelpalazzo** [comment]
Yes! It seems it's solved now. Thanks @eshellman for making it happen!

If more can please confirm, this issue can be safely closed.

**Comment by eshellman** [comment]
> Hi Eric Hellman,
> 
> Thank you for pointing this out. We have escalated this internally.
> 
> Sincerely,
> The Hacktoberfest Team

**Comment by shrn01** [comment]
@miguelpalazzo looks like it's in waiting state for everyone now. We can close this issue

**Comment by eshellman** [comment]
> Hi Eric Hellman,
> 
> We are happy to notify you that we have lifted the exclusion. We apologise if that caused any inconveniences and hope you had fun during Hacktoberfest.
> ​
> All the best!
> 
> Sincerely,
> The Hacktoberfest Team
