### ISSUE TITLE
Want to add a good Python Machine learning E-book

### ISSUE THREAD

**Issue by SurabhiSuresh22** [EbookFoundation/free-programming-books#8672]
I know a really good book that beginners can refer to learn machine learning with python. Please assign me this issue so that I shall add it.

**Comment by Shobhit1201** [comment]
I have an amazing beginner-friendly list of books since I am also learning right now, so please assign me this issue.

**Comment by nidhi-2619** [comment]
I have an amazing machine learning E-book for someone who is starting their journey in ML . Please assign this issue to me.

**Comment by nbehrnd** [comment]
If you identified a resource worth an addition to this compilation, do not rise
a blank issue.  Instead, either

a) if submitting an issue, include a link to the specific material. Or

b) file a pull request.  On the project's landing page you find a section «How
To Contribute»  with a link to a separate page; there, you find all the details
about the agreed format to prepare a PR.  In case your interest is ML, you
possibly acquired enough experience with git to use this option.

**Comment by shrn01** [comment]
@Shobhit1201 @nidhi-2619 Please feel free to raise a PR with the resource. No need to have an issue for it.
