### ISSUE TITLE
Wanna add Hindi github learning tutorials

### ISSUE THREAD

**Issue by Danish-Belal** [EbookFoundation/free-programming-books#8681]
I want to add Github learning tutorial in Hindi so that those Indian student who stuck cause of English they can also get good knowledge in Hindi . Thanks

**Comment by shrn01** [comment]
Hey @Danish-Belal, feel free to raise a PR for the same adding the resource to the proper file. Read docs/CONTRIBUTING.md for more information. Reply here if you have any issue

**Comment by Danish-Belal** [comment]
Please suggest me in which folder I should start adding YouTube  Hindi Tutorials , Should I make new one ?
