### ISSUE TITLE
Competitive Programming Cheat Sheet

### ISSUE THREAD

**Issue by codurr1** [EbookFoundation/free-programming-books#8758]
Best Curated Resource for Competitive Programming

**Comment by codurr1** [comment]
I have good resources to share

**Comment by Ujala-2110** [comment]
I have a good resource to share please assign me

**Comment by Mohit010rathore** [comment]
hey, I got one of the best Competitive Programming cheat sheets, for beginners who are just starting in it.

**Comment by riddhitech** [comment]
Please assign me this issue.

**Comment by shrn01** [comment]
Hey @Ujala-2110 @Mohit010rathore @riddhitech please feel free to raise a PR for the same adding the resources to the proper file. Read docs/CONTRIBUTING.md for more information regarding contributions

**Comment by SnehalSa** [comment]
Please assign me this issue.

**Comment by riddhitech** [comment]
Sir , please review the pr

**Comment by riddhitech** [comment]
Sir , please review the pr

**Comment by eshellman** [comment]
added (on the competeive programming list
