### ISSUE TITLE
Erro de digitação

### ISSUE THREAD

**Issue by GuilhermeSchwengber20** [EbookFoundation/free-programming-books#8769]
Estava lendo a documentação do projeto e encontrei uma palavra que possivelmente foi traduzida errada para minha lingua (pt-BR) a palavra é **Agnósticos** é encontrada duas vezes ou mais nesta pagina: https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-pt_BR.md#agn%C3%B3sticos
Acredito que a tradução correta seria **Diagnósticos**.

**Comment by loyannec** [comment]
Acredito que nesse contexto se trata de uma sessão de softwares independentes de plataforma que é executado em qualquer combinação de sistema operacional e arquitetura de processador subjacente. Tais apps às vezes são chamadas de plataforma cruzada.

**Comment by TysonOS** [comment]
A lista está dividida por linguagens de programação então acredito que o contexto da palavra agnóstico é para temas que não necessariamente estão ligados a alguma linguagem de programação, seria algo como Independente de Linguagem.
Na versão em inglês é usado o termo _Language Agnostic_.

**Comment by eshellman** [comment]
Thanks for clearing this up
