### ISSUE TITLE
Web Devopment Resources

### ISSUE THREAD

**Issue by KavyaSethia** [EbookFoundation/free-programming-books#8810]
I Want to add website development resources for beginners.

**Comment by riddhitech** [comment]
Please assign me this issue.

**Comment by yaksh1** [comment]
Please assign me this issue, I have some good resources as a web developer

**Comment by shrn01** [comment]
@KavyaSethia @riddhitech @yaksh1 please feel free to raise a PR for the same adding the resources to the proper file. Read docs/CONTRIBUTING.md for more information regarding contributions

**Comment by niket3342** [comment]
Hi, please assign me with this issue. I can add some good resources about web development compiled from linkedin and various other sources over the time.

**Comment by shrn01** [comment]
Hey @niket3342 feel free to raise a PR, no need to have an issue to track it

**Comment by aryabasu17** [comment]
Please assign me this issue , i want to provide some resources for beginners
