### ISSUE TITLE
HOWTO-ta.md

### ISSUE THREAD

**Issue by Madhesh-V** [EbookFoundation/free-programming-books#8816]
# HOW-TO பார்வையில்

<div align="right" markdown="1">

*[பிற மொழிகளில் இதைப் படியுங்கள்](README.md#translations)*

</div>

**``இலவச-நிரலாக்க-புத்தகங்களுக்கு'' வரவேற்கிறோம்!**

புதிய பங்களிப்பாளர்களை வரவேற்கிறோம்; அவர்கள் GitHub இல் முதன்முறையாக இழுக்கும் கோரிக்கையை (PR) செய்கிறார்கள். நீங்கள் அவர்களில் ஒருவராக இருந்தால், உங்களுக்கு உதவக்கூடிய சில ஆதாரங்கள் இங்கே உள்ளன:

* [கோரிக்கைகளை இழுப்பது பற்றி](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull -கோரிக்கைகள்) _(ஆங்கிலத்தில்)_
* [ஒரு இழுக்கும் கோரிக்கையை உருவாக்கு](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating- a -புல்-கோரிக்கை) _(ஆங்கிலத்தில்)_
* [GitHub Hello World](https://docs.github.com/en/get-started/quickstart/hello-world) _(ஆங்கிலத்தில்)_
* [YouTube - ஆரம்பநிலையாளர்களுக்கான GitHub டுடோரியல்](https://www.youtube.com/watch?v=0fKg7e37bQE) _(ஆங்கிலத்தில்)_
* [YouTube - எப்படி GitHub ரெப்போவை பிரித்து இழுக்கும் கோரிக்கையைச் சமர்ப்பிப்பது](https://www.youtube.com/watch?v=G1I3HF4YWEw) _(ஆங்கிலத்தில்)_
* [YouTube - Markdown Crash Course](https://www.youtube.com/watch?v=HUBNt18RFbo) _(ஆங்கிலத்தில்)_

கேள்விகளைக் கேட்கத் தயங்காதீர்கள்; ஒவ்வொரு பங்களிப்பாளரும் முதல் PR உடன் தொடங்கினார். எனவே... எங்கள் [பெரிய, வளர்ந்து வரும்](https://www.apiseven.com/en/contributor-graph?chart=contributorOverTime&repo=ebookfoundation/free-programming-books) சமூகத்தில் ஏன் சேரக்கூடாது.

<details align="center" markdown="1">
<summary>பயனர்களுக்கு எதிராக நேர வரைபடங்களைப் பார்க்க கிளிக் செய்யவும்..</summary>

[![EbookFoundation/free-programming-books's Contributor over time Graph](https://contributor-overtime-api.apiseven.com/contributors-svg?chart=contributorOverTime&repo=ebookfoundation/free-programming-books)](https://www.apiseven.com/en/contributor-graph?chart=contributorOverTime&repo=ebookfoundation/free-programming-books)

[![EbookFoundation/free-programming-books's Monthly Active Contributors graph](https://contributor-overtime-api.apiseven.com/contributors-svg?chart=contributorMonthlyActivity&repo=ebookfoundation/free-programming-books)](https://www.apiseven.com/en/contributor-graph?chart=contributorMonthlyActivity&repo=ebookfoundation/free-programming-books)

</விவரங்கள்>

நீங்கள் அனுபவமிக்க ஓப்பன் சோர்ஸ் பங்களிப்பாளராக இருந்தாலும், உங்களை உலுக்கிய பல விஷயங்கள் உள்ளன. உங்கள் PR ஐச் சமர்ப்பித்த பிறகு, ***GitHub Actions* ஒரு *Linter*ஐ இயக்கும், அடிக்கடி இடைவெளி அல்லது எழுத்துப்பிழையில் சிறிய சிக்கல்களைக் கண்டறியும்**. நீங்கள் பச்சை பொத்தானைப் பெற்றால், அனைத்தும் மதிப்பாய்வுக்குத் தயாராக உள்ளன; இல்லையெனில், லின்டர் விரும்பாத எதையும் கண்டுபிடிக்கத் தவறிவிட்டதா என்பதைச் சரிபார்ப்பிற்குக் கீழே உள்ள "விவரங்கள்" என்பதைக் கிளிக் செய்து, உங்கள் PR திறக்கப்பட்ட கிளையில் புதிய உறுதிமொழியைச் சேர்ப்பதன் மூலம் சிக்கலைச் சரிசெய்யவும்.

இறுதியாக, நீங்கள் சேர்க்க விரும்பும் ஆதாரமானது `இலவச-நிரலாக்க-புத்தகங்களுக்கு' பொருத்தமானதா என உங்களுக்குத் தெரியாவிட்டால், [பங்களிக்கை](CONTRIBUTING.md) *([மொழிபெயர்ப்புகள்](README.md#translations) இல் உள்ள வழிகாட்டுதல்களைப் படிக்கவும் ) மேலும் கிடைக்கும்)*.

**Comment by shrn01** [comment]
@Madhesh-V Please add the file in docs/ and link it in docs/README.md and raise a PR.
