### ISSUE TITLE
want to add new book for c language

### ISSUE THREAD

**Issue by avnishkt** [EbookFoundation/free-programming-books#8831]

**Comment by shrn01** [comment]
@avnishkt please feel free to raise a PR placing the resource in the proper file based on language and content. Read docs/CONTRIBUTING.md for more details

**Comment by Shinjan-saha** [comment]
please assign this to me i want to add a book on c language

**Comment by sadhvi1234** [comment]
Hi, can you please assign this to me ?
Thanks

**Comment by shivsaranyada** [comment]
Hi, can you please assign this to me ?

**Comment by shrn01** [comment]
@shivsaranyada please feel free to raise a PR
