### ISSUE TITLE
Database Management System Books

### ISSUE THREAD

**Issue by ablazecodes** [EbookFoundation/free-programming-books#8846]
I'd like to contribute books on DBMS, by highly acclaimed computer scientists
[Fundamentals of Database Systems Sixth Edition by Ramez A. Elmasri and ShamkantNavathe ](https://docs.ccsu.edu/curriculumsheets/ChadTest.pdf)

**Comment by shrn01** [comment]
@ablazecodes  Is this an authorized distribution? We only accept resources which are truly free for everyone to use

**Comment by ablazecodes** [comment]
Yes, I've removed the link whose authorization I was unsure about

**Comment by Gargi14** [comment]
Hi I would like to contribute books on DBMS Database System Concepts Seventh Edition by McGraw Hill Publication.Could you please assign me

**Comment by Gargi14** [comment]
[Database System Concept 7th Edition.pdf](https://github.com/EbookFoundation/free-programming-books/files/9900553/Database.System.Concept.7th.Edition.pdf)

DBMS Database System Concepts Seventh Edition by McGraw Hill Publication

**Comment by eshellman** [comment]
This appears not to be an authorized distribution. Please see docs/CONTRIBUTING.md guidelines.
