### ISSUE TITLE
MATLAB and Simulink Courses

### ISSUE THREAD

**Issue by Yadavbalbir** [EbookFoundation/free-programming-books#8848]
I want to add MATLAB and Simulink self-placed certified courses provided by mathworks.com

**Comment by shrn01** [comment]
Feel free to raise a PR with the resource if it is free for everyone and doesn't require a subscription or a fee

**Comment by Yadavbalbir** [comment]
Raised PR #8839 Pls merge

**Comment by eshellman** [comment]
added
