### ISSUE TITLE
Add DSA Hindi course

### ISSUE THREAD

**Issue by anishhh238** [EbookFoundation/free-programming-books#8879]
Adding the best DSA Hindi Course tht Help the beginner, mid-level students to learn Data Structure and Algorithm in easy, simple, efficient way

**Comment by anishhh238** [comment]
Assign me to add the DSA Hindi course links

**Comment by AshishSharma1203** [comment]
I would like to contribute regarding this issue

**Comment by developerSuranjan** [comment]
@anishhh238 Please assign this to me :) I eat DSA all the day

**Comment by shrn01** [comment]
@anishhh238 feel free to raise a PR. Please add `fixes #8879` to the description to close this issue automatically
