### ISSUE TITLE
Web development Resource 

### ISSUE THREAD

**Issue by abhishekpatelmc** [EbookFoundation/free-programming-books#8927]
- I want to include a course for web development

**Comment by Anshul-9923** [comment]
@abhishekpatelmc Please assign this issue to me.

**Comment by zaidali110** [comment]
hello sir can you assign this to me ?

**Comment by harshsingh-io** [comment]
i have the proper structured resource for web development. can you please assign me?

**Comment by ParthMadhvani2** [comment]
Hello, @abhishekpatelmc sir I have a well-structured resource for full-stack web development documentation.

**Comment by sadhvi1234** [comment]
Hello, can you assign this to me ?

**Comment by shivsaranyada** [comment]
i want to include a course for web development . please you can assign me.

**Comment by ivaibhavraheja** [comment]
i have a resource for learning web development, can you please assign it to me?

**Comment by bytesofbec** [comment]
Can please assign me this issue?

**Comment by abhishekpatelmc** [comment]
I am a contributor 
I don't have access to the repository

**Comment by shrn01** [comment]
Hey guys, if you do have any resource that is free for anyone to use, please feel free to raise a PR. No need to assign a issue for that. Hope this helps

**Comment by Vvpcse** [comment]
### Resource for learning **web development**: [https://www.youtube.com/c/Freecodecamp/search?query=web%20development](url)

**Comment by eshellman** [comment]
already added
