### ISSUE TITLE
Book for Data Structures and Algorithm 

### ISSUE THREAD

**Issue by abhishekpatelmc** [EbookFoundation/free-programming-books#8928]
- I want to add a book for Data Structure and Algorithm

**Comment by developerSuranjan** [comment]
@abhishekpatelmc Kindly assign this to me

**Comment by harshsingh-io** [comment]
@abhishekpatelmc assign me for this. i can give the best possible books for every kind of student from begginer to advance level with pdf too.

**Comment by chirag-cyber** [comment]
@abhishekpatelmc sir please assign this task to me. So that I can made my first pull request..

**Comment by ParthMadhvani2** [comment]
Hello, @abhishekpatelmc sir please assign this task to me, So that I can contribute all the required books.

**Comment by amananand0001** [comment]
hello, @abhishekpatelmc pls assign this task to me. 
I have 2 year experience of java.

**Comment by abhishekpatelmc** [comment]
I am not the project maintainer 
I am also a contributor to this repo

**Comment by SnehalSa** [comment]
Please assign me this issue.

**Comment by shrn01** [comment]
Hey @abhishekpatelmc feel free to raise a PR. We do not need an issue to add a resource to the repo. A PR can be raised directly
