### ISSUE TITLE
Book of Java in Hindi 

### ISSUE THREAD

**Issue by anishhh238** [EbookFoundation/free-programming-books#8961]
Adding Java programming language book in hindi

**Comment by bhaskaraj** [comment]
[Uploading Java in Hindi ( PDFDrive ).pdf…]()

**Comment by shrn01** [comment]
@anishhh238 Please feel free to raise a PR. We do not need to have an issue for contributing. Hope it helped

**Comment by eshellman** [comment]
pdfdrive links are not acceptable for this repo!
