### ISSUE TITLE
adding Link of java 

### ISSUE THREAD

**Issue by anishhh238** [EbookFoundation/free-programming-books#8963]
Adding Link of Java tutorial where u learn complete java in simple way..

**Comment by sahilihas** [comment]
https://www.udemy.com/topic/java/free/
you can try this

**Comment by harshsingh-io** [comment]
i can recommend **best possible solution and links according to level of students**. please assign me, i want to complete my hacktober pull request

**Comment by kgauravs192** [comment]
Hello sir, Can you assign this issue to me ?

**Comment by bytesofbec** [comment]
I can give the best java resources for learning, please assign me this issue

**Comment by shrn01** [comment]
Hey Guys. Feel free to raise a PR. You do not need to have an issue open for contributing. Hope it helps

**Comment by Vvpcse** [comment]
https://www.youtube.com/c/Freecodecamp/search?query=java

**Comment by Vvpcse** [comment]
### Learning **Path1** : [https://learn.microsoft.com/en-us/training/paths/az-400-get-started-devops-transformation-journey/](url)

### Learning **Path2** :  [https://learn.microsoft.com/en-us/training/paths/az-400-work-git-for-enterprise-devops/](url)

### Learning **Path3** :  [https://learn.microsoft.com/en-us/training/paths/az-400-implement-ci-azure-pipelines-github-actions/](url)

### Learning **Path4** : [https://learn.microsoft.com/en-us/training/paths/az-400-design-implement-release-strategy/](url)

### Learning **Path5** : [https://learn.microsoft.com/en-us/training/paths/az-400-implement-secure-continuous-deployment/](url)
