### ISSUE TITLE
Add Azure DevOps Courses and Documentation

### ISSUE THREAD

**Issue by sadhvi1234** [EbookFoundation/free-programming-books#8980]
Please provide relevant courses and documentation which are easily accessible online.

**Comment by bhavyasingh75** [comment]
on it.

**Comment by bhavyasingh75** [comment]
PR submitted.

**Comment by Vvpcse** [comment]
### Learning **Path1** : [https://learn.microsoft.com/en-us/training/paths/az-400-get-started-devops-transformation-journey/](https://github.com/EbookFoundation/free-programming-books/issues/url)

### Learning **Path2** : [https://learn.microsoft.com/en-us/training/paths/az-400-work-git-for-enterprise-devops/](https://github.com/EbookFoundation/free-programming-books/issues/url)

### Learning **Path3** : [https://learn.microsoft.com/en-us/training/paths/az-400-implement-ci-azure-pipelines-github-actions/](https://github.com/EbookFoundation/free-programming-books/issues/url)

### Learning **Path4** : [https://learn.microsoft.com/en-us/training/paths/az-400-design-implement-release-strategy/](https://github.com/EbookFoundation/free-programming-books/issues/url)

### Learning **Path5** : [https://learn.microsoft.com/en-us/training/paths/az-400-implement-secure-continuous-deployment/](https://github.com/EbookFoundation/free-programming-books/issues/url)

**Comment by Sohampatra1** [comment]
can you assign this issue to me
