### ISSUE TITLE
Add Git instructions for how to fork repo and create PR in Contributing.md file

### ISSUE THREAD

**Issue by actuallyyun** [EbookFoundation/free-programming-books#9026]
Hi, I think it would be a good idea to have clear and detailed instructions on how to use Git to contribute to this repo in the `Contributing.md` file. I could create a PR for this. Thank you!

**Comment by shrn01** [comment]
Hey @actuallyyun, We do have books in the repo that talk about how to use Git. Do we need to have it explicitly here?

**Comment by actuallyyun** [comment]
Hi @shrn01 Thanks for the replay.

As a newcomer who would like to contribute, my flow was: `README.ME` →` Contributing.md ` →`In a nutshell`→ _If you know Git, please Fork the repo and send Pull Requests (PR)._

I think it would be helpful to have a quick instruction on how to use Git to contribute here, for instance, the command for cloning the repo, command for pulling commits to one's local machine...
[An example ](https://github.com/facebook/jest/blob/main/CONTRIBUTING.md#workflow-and-pull-requests)I had in mind, if you go down to _Workflow and Pull Requests_ you could see a protect-specific instruction on how to contribute with Git. 

I learned that contributing resources doesn't require opening an issue. I think it would be beneficial to specify this in the file as well. As a matter of fact, most issues right now are regarding contributing resources. I think this could be reduced by having clear guidance in the file.

Please let me know what you think about it.

**Comment by Thenlie** [comment]
If this is something deemed worthwhile, I would be happy to make it! 

`Contributing.md` seems to make the most sense but a wiki or docs directory could also be created. [Here](https://gist.github.com/Thenlie/692c67a7da39b1e067cd4987a929a8ee) is a gist I made for another project as a rough idea. I think this is example goes into more detail than is needed here. Just a handful of links to the official GitHub docs on PRs, Forks and Issues should be enough.

Feel free to give me a ping with any follow up!

**Comment by eshellman** [comment]
we could add a link to your gist

**Comment by Thenlie** [comment]
> we could add a link to your gist

You are more than welcome to! Since it may not all apply to this repo, I would also be happy to make a new one.
