### ISSUE TITLE
Add a free full-stack programming course to free-courses-en.md  

### ISSUE THREAD

**Issue by actuallyyun** [EbookFoundation/free-programming-books#9027]
Hi I am learning with MigraCode Barcelona, and find its syllabus comprehensive, and interesting with loads of good exercises. It's entirely free and open to everyone. I would love to add this to `free-courses-en.md`  file. Thank you!

**Comment by shrn01** [comment]
Feel free to add it and raise a PR. No need to have an issue open to contribute to the repo. Hope it helps

**Comment by actuallyyun** [comment]
Hi @shrn01  I have created pull request  #9076 for this.

**Comment by eshellman** [comment]
added
