### ISSUE TITLE
Angular Testing Succinctly

### ISSUE THREAD

**Issue by ManviGoel26** [EbookFoundation/free-programming-books#9033]
**Angular Testing Succinctly**
 The book provides a quick introduction to different tools and approaches to testing Angular projects to make them higher quality from the start and easier to maintain down the road. Topics covered include lint checking, test-driven development, unit testing, and end-to-end testing.

Author: Joseph D. Booth
Format: HTML and PDF along with GitHub Repo link to code.
Website Link: https://www.syncfusion.com/succinctly-free-ebooks/angular-testing-succinctly

Please assign me this.

**Comment by shrn01** [comment]
Cool. Make sure to close the issue once the PR is submitted

**Comment by shrn01** [comment]
Book was added
