### ISSUE TITLE
Received mail from hacktoberfest issue solved 

### ISSUE THREAD

**Issue by Manish-Syal123** [EbookFoundation/free-programming-books#9042]
![emailhacktoberfest](https://user-images.githubusercontent.com/112818612/198707203-ef19af83-4620-4b2b-94b1-7bf68e0aa3ec.png)

**Comment by Manish-Syal123** [comment]
Even I also sent mail to then about this issue. Just now I received the mail from them.

**Comment by Manish-Syal123** [comment]
**The six days review period starts now.**
![Screenshot 2022-10-29 000929](https://user-images.githubusercontent.com/112818612/198708861-3eee92cb-aef8-4079-ab96-cf90e3104117.png)

**Comment by Manish-Syal123** [comment]
yes I know that the mail that I had written was not good, but still it works 😅

**Comment by shrn01** [comment]
Thank you @Manish-Syal123 for the information. Closing this issue as the problem was solved
