### ISSUE TITLE
Add some programming books for beginners 

### ISSUE THREAD

**Issue by AneezaSabirButt** [EbookFoundation/free-programming-books#9047]

**Comment by Vvpcse** [comment]
[Introduction to ‘C’ Language.pdf](https://github.com/EbookFoundation/free-programming-books/files/9892337/Introduction.to.C.Language.pdf)
[ada.pdf](https://github.com/EbookFoundation/free-programming-books/files/9892338/ada.pdf)

**Comment by Ubarrionuevo** [comment]
Hi ! , i want contribute in this usses , I ask permission to contribute

**Comment by amananand0001** [comment]
can you assign this issue to me

**Comment by khanyousufminhaj** [comment]
Please assign this issue to me as it will be a great start for me

**Comment by AneezaSabirButt** [comment]
> Please assign this issue to me as it will be a great start for me



> can you assign this issue to me

Sure

**Comment by 11nitis** [comment]
hey  @aneeza can you assign this task to me

**Comment by Sohampatra1** [comment]
can you assign this issue to me

**Comment by Ubarrionuevo** [comment]
Hey , i can helped

**Comment by akashdip2001** [comment]
HI , i want to join, I made a little Codind page Only for Kali Linux beginners, because it's very heard to learn Linux OS 1st time, So i can contribute little more.

**Comment by muhammadzubairmoosani** [comment]
Hey!, @AneezaSabirButt  Please can you assign it to me, I'll do it easily.

**Comment by j4sum** [comment]
Hi, I am a mod at women who code bookclub and would love to share some books.
