### ISSUE TITLE
Add SQL resources and books

### ISSUE THREAD

**Issue by Shreyan-12345** [EbookFoundation/free-programming-books#9048]

**Comment by flbjuniorx** [comment]
I'd be glad to help with this issue.

**Comment by Sohampatra1** [comment]
All You need is this book which I mentioned  below.(with Link)

SQL Cookbook by Anthony Molinaro-
https://b-ok.asia/book/11030721/8f8725

**Comment by Sohampatra1** [comment]
can you assign this issue to me?

**Comment by Niketdeshmukh** [comment]
can you assign this issue to me?

**Comment by Mirza-Hassan** [comment]
@Shreyan-12345 can you please assign it to me?
