### ISSUE TITLE
Add numpy and pandas cheatsheet

### ISSUE THREAD

**Issue by Shreyan-12345** [EbookFoundation/free-programming-books#9049]

**Comment by Vvpcse** [comment]
[https://www.kaggle.com/code/lavanyashukla01/pandas-numpy-python-cheatsheet](url)

**Comment by manny-uncharted** [comment]
I'll take this up

**Comment by manny-uncharted** [comment]
I've made a pull request can it get approved

**Comment by Sohampatra1** [comment]
can you assign this issue to me

**Comment by eshellman** [comment]
merged
