### ISSUE TITLE
Maximum of all subarrays of size k

### ISSUE THREAD

**Issue by amarjeet2003gupta** [EbookFoundation/free-programming-books#9060]
Given an array arr[] of size N and an integer K. Find the maximum for each and every contiguous subarray of size K.

Input : 
9 3
1 2 3 1 4 5 2 3 6

**Comment by amarjeet2003gupta** [comment]
Hello sir/ma'am,
I found this as an important DSA problem
Can you please assign this issue to me.

**Comment by Niketdeshmukh** [comment]
I can solve this problem, can you assign to me?

**Comment by Mirza-Hassan** [comment]
@amarjeet2003gupta I can solve this problem, can you please assign to me?

**Comment by shrn01** [comment]
Sorry, we do not support hosting these as of now. If you have any books or website articles which are free to use, please feel free to raise a PR with them. 

Closing this issue for now. please feel free to reply if you have any queries
