### ISSUE TITLE
Add free software design guide

### ISSUE THREAD

**Issue by pronoym99** [EbookFoundation/free-programming-books#9080]
The link to a free software guide by @arjancodes is accessible only via mail: [FREE GUIDE](https://www.arjancodes.com). This can be listed as stated in the first point of [In a nutshell](https://github.com/EbookFoundation/free-programming-books/blob/40d0e28b677fe2fdbd445dce40352bf5985a73cd/docs/CONTRIBUTING.md#in-a-nutshell) in the contributing guide.

**Comment by j4sum** [comment]
Could you please assign this issue to me. Thanks!

**Comment by pronoym99** [comment]
I do not have write access to this repo @j4sum, hence, I can't do that.

**Comment by eshellman** [comment]
we don't like books only by email
