### ISSUE TITLE
Formatting Issue with PR

### ISSUE THREAD

**Issue by CBID2** [EbookFoundation/free-programming-books#9202]
Hi there! :) I've been trying to add a resource to the  HTML & CSS section and the GitHub action keeps saying that formatting is wrong even though I followed the rules. I'm at a lost. Can you help me?
[My PR](https://github.com/EbookFoundation/free-programming-books/pull/9201#issue-1444917708)

**Comment by eshellman** [comment]
I have left a comment on the PR with the correct syntax; however we do not accept email address required cheatsheets.
