### ISSUE TITLE
<Category Request> Open Source

### ISSUE THREAD

**Issue by CBID2** [EbookFoundation/free-programming-books#9204]
Hi there! I was scrolling the 'O' section and thought it would be a good idea to add an Open Source section. It would be a great way for programmers of all levels to learn how to start their Open Source journey.

**Comment by yupendra2408** [comment]
It's nice bro start

**Comment by eshellman** [comment]
We have an "Open Source Ecosystem" section in books. Is there another list with resource we could group into a new section?

**Comment by CBID2** [comment]
Hmm..maybe something about Blogging?
