### ISSUE TITLE
Link isn't working. 

### ISSUE THREAD

**Issue by StarKnightt** [EbookFoundation/free-programming-books#9237]
![image](https://user-images.githubusercontent.com/92244026/208306229-7844a4ea-f80b-4ece-8799-c8057eb8d101.png)

https://ebookfoundation.github.io/free-programming-books-search/
The above link isn't working. 👆🏻👆🏻
![image](https://user-images.githubusercontent.com/92244026/208306388-5a1559ec-a979-4674-9bf5-85c2c6cf6ae1.png)
I'm just posting the problems here because I have no idea why it's not working and I want them to be fixed as soon as possible.
Thank you.

**Comment by eshellman** [comment]
I'm not able to reproduce the problem. Could you check if it persists in other browsers and in brave with all extensions turned off?

**Comment by StarKnightt** [comment]
> could you check in a network console to see what's being blocked, or perhaps try with curl?

My internet is flawless, and the link is now flawlessly working after restarting my laptop, so I guess there was a bug there. Keep going, by the way.
