### ISSUE TITLE
Build Your Own Redis with C/C++

### ISSUE THREAD

**Issue by mister-goo** [EbookFoundation/free-programming-books#9249]
The link is https://build-your-own.org/.

I'm not sure which subject it belongs. It fits into both networking and data structures, and the database subject doesn't seem to fit.

**Comment by eshellman** [comment]
existing entries for redis books are under NoSQL

**Comment by mister-goo** [comment]
> existing entries for redis books are under NoSQL

Hi. I doubt the NoSQL category fits since the book isn't about Redis, nor contains topics on NoSQL. May I suggest the C category instead? Since it's mostly about building things in plain C.

**Comment by eshellman** [comment]
makes sense.
