### ISSUE TITLE
Add a book

### ISSUE THREAD

**Issue by priyankarpal** [EbookFoundation/free-programming-books#9257]
Hey! Admin Add this Book **Java for Absolute Beginners Learn to Program the Fundamentals the Java 9+ Way**

This is the link    [Java for Absolute Beginners Learn to Program the Fundamentals the Java 9+ Way](https://www.pdfdrive.com/download.pdf?id=185771881&h=0db0f2eae168c600917807d193abdf4a&u=cache&ext=pdf) - Iuliana Cosmina (PDF)

**Comment by eshellman** [comment]
In general, we do not link to file sharing sites, or file hosting sites such as google docs. or dropbox.
