### ISSUE TITLE
How can i contribute multiple books from a site

### ISSUE THREAD

**Issue by John4650-hub** [EbookFoundation/free-programming-books#9276]
Hi, i have found this website called goalkicker which has alot of good programming books with notes  for professionals which are free. Am confused on how i should make this contribution because there  alot  of different books for different programming languages. Here is the link [goalkicker.com](https://goalkicker.com/)
Should i extract links to each and every book and then follow the contibutions guideline?

**Comment by eshellman** [comment]
please look at #4579
