### ISSUE TITLE
Book: Node.js Best Practices

### ISSUE THREAD

**Issue by jcubic** [EbookFoundation/free-programming-books#9327]
This is not a book on one particular subject I think that it will fit on the list:

https://github.com/goldbergyoni/nodebestpractices

It's also translated into various languages.

**Comment by JenIsCoding** [comment]
Hello everybody!
Is there someone working on this issue at the moment? 😊

**Comment by eshellman** [comment]
@JenIsCoding It's ok to just pick up an issue if you want to work on it - in this repo there's no need to ask.
