### ISSUE TITLE
【实用工具】ChatGPT注册登录流程图解

### ISSUE THREAD

**Issue by Pacdage** [EbookFoundation/free-programming-books#9332]
ChatGPT注册登录技巧：[快速注册登录ChatGPT](https://github.com/xiaoming2028/FreePAC/wiki/ChatGPT注册教程（完整指南）)

【教程分享】稳定安全又快速的科学上网指南：[科学上网方法推荐](https://github.com/xiaoming2028/FreePAC/wiki/2023-%E7%A8%B3%E5%AE%9A%E7%BF%BB%E5%A2%99%E6%9C%BA%E5%9C%BA%E6%8E%A8%E8%8D%90%E6%B5%8B%E8%AF%84%EF%BC%9AWgetCloud-%E6%80%8E%E4%B9%88%E6%A0%B7%EF%BC%8C%E5%80%BC%E5%BE%97%E5%85%A5%E6%89%8B%E5%90%97%EF%BC%9F)

**Comment by eshellman** [comment]
I think these resources are likley to be obsolete too soon to merit inclusion in our lists
