### ISSUE TITLE
Adding YouTube podcast

### ISSUE THREAD

**Issue by AhmedElTabarani** [EbookFoundation/free-programming-books#9337]
Can we add YouTube podcast in Podcast folders

Like this for example
https://youtube.com/playlist?list=PLTRDUPO2OmInoyjXpGCRIQ54SJCMihIsC

**Comment by eshellman** [comment]
sure, why not?

**Comment by AhmedElTabarani** [comment]
> sure, why not?

Just wanted to be sure, I'm going to make a pull request that includes all the Arabic tech podcasts right now
