### ISSUE TITLE
Bad url Java heb book

### ISSUE THREAD

**Issue by Shmuelmb** [EbookFoundation/free-programming-books#9338]
Hey!
The  link for Java book in Hebrew doesn't work
https://javabook.co.il/wordpress/?page_id=10
 Anyone know how to get pdf file of this book?

**Comment by JenIsCoding** [comment]
Unfortunately, I think that "The Israeli Guide To Java" is no longer available online. 😢 
If it's right, do you think that the book should be removed from the Hebrew list of programming books?

**Comment by Shmuelmb** [comment]
If this situation is unsolvable Its might be removed, in order to prevent confusion and frustration from happening

**Comment by eshellman** [comment]
can remove the listing
