### ISSUE TITLE
Link erróneo en curso "Programación en lenguaje Java (2015)" 

### ISSUE THREAD

**Issue by aguirreaxel** [EbookFoundation/free-programming-books#9345]
En la sección de cursos en españo el link que debería dirigir al curso "Programación en lenguaje Java (2015)" dirige a un curso de Ciencias psicosociales.
Esta es la sección:

https://github.com/EbookFoundation/free-programming-books/blob/main/courses/free-courses-es.md#programaci%C3%B3n

Este es el link al que dirige: https://ocw.unican.es/course/view.php?id=26

**Comment by JenIsCoding** [comment]
Hello, I fixed the issue. I hope I have done things right! 😺

**Comment by eshellman** [comment]
perfect
