### ISSUE TITLE
Please, add book "Python for OSINT. 21 day course for beginners"

### ISSUE THREAD

**Issue by cipher387** [EbookFoundation/free-programming-books#9362]
https://github.com/cipher387/python-for-OSINT-21-days (link to PDF in the repo)

**Comment by cipher387** [comment]
All correct. Thank you.

**Comment by JenIsCoding** [comment]
Perfect! 
I will add it as soon as I can 😃

**Comment by JenIsCoding** [comment]
Here I am!

Before making a pull request, I want to be sure that I have put in your right name 😺 
Below you can see a screenshot of the temporary changes I made on my [forked repo](https://github.com/JenIsCoding/free-programming-books/blob/main/courses/free-courses-en.md):

![osint_add](https://github.com/EbookFoundation/free-programming-books/assets/107807044/5947c833-6ecf-4af1-9d59-ac4e5b63757a)

Is everything fine or do you want to correct something? Maybe a capital C in the _cyb_detective_?

**Comment by JenIsCoding** [comment]
@eshellman 
Maybe, I don't know if it's correct!, is it better to add the link to the GitHub repo of the course in the [English course list](https://github.com/EbookFoundation/free-programming-books/blob/main/courses/free-courses-en.md) and the pdf in the [English book list](https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-en.md)?

**Comment by cipher387** [comment]
GitHub repo to English course list

**Comment by JenIsCoding** [comment]
Perfect. [These](https://github.com/JenIsCoding/free-programming-books/commit/084a54120691d2d8f50e1b422a58ee0a2888ae04) changes could be fine.
Let's see what @eshellman thinks! :)
