### ISSUE TITLE
Add Architecture of Open Source Applications (AOSA) Books

### ISSUE THREAD

**Issue by MuhammadSawalhy** [EbookFoundation/free-programming-books#9432]
There exists public free book series under the name "Architecture of Open Source Applications", I think it will be great if we add them to this repo. The official website for the books buys them but some of them such as "500 lines or less" are [open source](https://github.com/aosabook/500lines) and can be built as a pdf file from the source code.

**Comment by mjidelouss** [comment]
Good Idea

**Comment by MuhammadSawalhy** [comment]
PUMP
