### ISSUE TITLE
suggestion: Label for resources which are created or supported by the open-source community.

### ISSUE THREAD

**Issue by ghost** [EbookFoundation/free-programming-books#9433]
### Situation
Resources, like books are hosted on GitHub as a repository.  

### Aim
To give credit to the various contributors and to add an appropriate "author" for the book or resource.

### Suggestion
**Case 1: The community is the sole creator.**

There are cases where the community is developing a book or resource with various different authors for different chapters or even sections. In these cases, adding the author name becomes a tedious task as there is no clear author. For cases like this, I propose that we add a label stating that the work is created by the community.

For example, we may do something like:
* [An Awesome Community Driven Open-Source Book](Link To The Book) - *:people_holding_hands: created by community* (File Type 1, File Type 2...)

Real life examples where this is helpful:
* [The Architecture of Open Source Applications](https://aosabook.org/en/) - *:people_holding_hands: created by community* (HTML)
* [Node.JS Best Practices](https://github.com/goldbergyoni/nodebestpractices) - *:people_holding_hands: created by community* 

In the above two cases, a large community is creating the work.

**Case 2: The community is supporting the author(s).**

This is a common case now, where the authors are hosting their work on GitHub. For this situation, I propose adding the label after the author name.

For example:
* [An Awesome Book Supported By Community](Link To The Book) - Author Name, *:people_holding_hands: supported by community* (File Type 1, File Type 2...)

Real life examples where this is helpful:
* [Operating Systems: From 0 to 1](https://github.com/tuhdo/os01) - Tu, Ho Doang, *:people_holding_hands: supported by community* (PDF)

**Note:** I am not at all rigid in the ways I have suggested. More subtle ways would be more helpful. I request feedback from everybody.

**Comment by eshellman** [comment]
Case 1 - interesting suggestion. I worry about emojis in the creator field (note that our search box has to parse out creator names (free-programming-books-search). Take a look at #7034

Case 2 - this has been suggested before, but in practice it's too hard to maintain, verify, and avoid abuse
