### ISSUE TITLE
Broken links for Arabic Books

### ISSUE THREAD

**Issue by aminsys** [EbookFoundation/free-programming-books#9452]
Here is a list of the broken or inaccessible for the Arabic programming books where user gets messages such as "Page can not be found", "403 Forbidden", "ERR_SSL_PROTOCOL_ERROR", or "Connection timed out Error code 522":

- مدخل إلى الذكاء الاصطناعي وتعلم الآلة - Mohamed Lahlah‏ (PDF)
- سبيلك المختصر لتعلم لغة c#‎ - برمجة الواجهات - Khaled Al-Saadani‏ (PDF) 

- ~~تصميم قواعد البيانات - Adrienne Watt, Nelson Eng، ترجمة أيمن طارق وعلا عباس (PDF)~~ Working

- التحريك عبر CSS‏ - Donovan Hutchinson, Mohamed Beghat‏ (PDF)
- نحو فهم أعمق لتقنيات HTML5‏ - Mark Pilgrim, Abdullatif Eymash‏ (PDF)
- تفهيم الخوارزميات – الجزء الأول - جمال بن نوار (PDF)
- تفهيم الخوارزميات – الجزء الثاني - جمال بن نوار (PDF)
- أساسيات إطار العمل Vue.js - حسام برهان (PDF)
- الإدارة المتقدمة لجنو/لينكس - Remo Suppi Boldrito, Josep Jorba Esteve, Abdel Rahim Ghaleb‏ (PDF)
- دليل إدارة خواديم أوبنتو 14.04 - Ubuntu documentation team, Abdullatif Eymash‏ (PDF)
- الأبعاد الاستراتيجية للبرمجيات الحرة مفتوحة المصدر - فيجن للأنظمة المتقدمة (PDF)
- الحريات الرقمية - المفاهيم الرئيسية - محمد الطاهر (PDF)
- المصادر المفتوحة خيارات بلا حدود - محمد أنس طويلة (PDF)
- تعرف على البرمجيات الحرة - فهد السعيدي (PDF)
- نبذة عن رخص البرمجيات الحرة - جلال شفرور (PDF)
- المقدمة في تحليل وتصميم أنظمة - Ahmed Lexis
- أنظمة التشغيل للمبرمجين - Allen B. Downey ,ترجمة علا عباس (PDF)
- تعلم البرمجة بلغة PHP - Ahmed Abu Al-Saud , Abdul Latif Amish
- البرمجة بلغة بايثون
- راسبيري باي السهل - Abdullah Ali Abdullah (PDF)
- مقدمة في روبي - Ahmed Youssef (PDF)
- تعلم البرمجة مع القط سكراتش - نورا حاتم (PDF)
- تقنيات الاختراق المادي - Abdullah Ali Abdullah (PDF)
- دليل الأمان الرقمي
- تحسين محركات البحث SEO - دليل المبتدئين - The Google
- ملاحظات للعاملين بلغة SQL
- الدليل العملي إلى قواعد بيانات PostgreSQL‏ - Craig Kerstiens، مصطفى عطا العايش (PDF)

**Comment by ahmedhgabr** [comment]
I tried and crossed out the linkes that worked for me.  

- ~~مدخل إلى الذكاء الاصطناعي وتعلم الآلة~~- Mohamed Lahlah‏ (PDF)- 
- سبيلك المختصر لتعلم لغة c#‎ - برمجة الواجهات - Khaled Al-Saadani‏ (PDF)
- ~~تصميم قواعد البيانات - Adrienne Watt, Nelson Eng~~، ترجمة أيمن طارق وعلا عباس (PDF) Working
- ~~التحريك عبر CSS‏~~- Donovan Hutchinson, Mohamed Beghat‏ (PDF)
- ~~نحو فهم أعمق لتقنيات HTML5‏~~- Mark Pilgrim, Abdullatif Eymash‏ (PDF)
- تفهيم الخوارزميات – الجزء الأول - جمال بن نوار (PDF)
- تفهيم الخوارزميات – الجزء الثاني - جمال بن نوار (PDF)
- ~~أساسيات إطار العمل Vue.js~~ - حسام برهان (PDF)
- الإدارة المتقدمة لجنو/لينكس - Remo Suppi Boldrito, Josep Jorba Esteve, Abdel Rahim Ghaleb‏ (PDF)
- ~~دليل إدارة خواديم أوبنتو 14.04~~- Ubuntu documentation team, Abdullatif Eymash‏ (PDF)
- الأبعاد الاستراتيجية للبرمجيات الحرة مفتوحة المصدر - فيجن للأنظمة المتقدمة (PDF)
- الحريات الرقمية - المفاهيم الرئيسية - محمد الطاهر (PDF)
- المصادر المفتوحة خيارات بلا حدود - محمد أنس طويلة (PDF)
- تعرف على البرمجيات الحرة - فهد السعيدي (PDF)
- نبذة عن رخص البرمجيات الحرة - جلال شفرور (PDF)
- المقدمة في تحليل وتصميم أنظمة - Ahmed Lexis
- ~~أنظمة التشغيل للمبرمجين~~- Allen B. Downey ,ترجمة علا عباس (PDF)
- تعلم البرمجة بلغة PHP - Ahmed Abu Al-Saud , Abdul Latif Amish
- ~~البرمجة بلغة بايثون~~
- راسبيري باي السهل - Abdullah Ali Abdullah (PDF)
- مقدمة في روبي - Ahmed Youssef (PDF)
- تعلم البرمجة مع القط سكراتش - نورا حاتم (PDF)
- تقنيات الاختراق المادي - Abdullah Ali Abdullah (PDF)
- ~~دليل الأمان الرقمي~~
- تحسين محركات البحث SEO - دليل المبتدئين - The Google
- ملاحظات للعاملين بلغة SQL
- ~~الدليل العملي إلى قواعد بيانات PostgreSQL‏~~- Craig Kerstiens، مصطفى عطا العايش (PDF)
