### ISSUE TITLE
AWS For Beginners

### ISSUE THREAD

**Issue by jokoyoski** [EbookFoundation/free-programming-books#9455]
Link for AWS for starters

**Comment by sharma62** [comment]
can I resolve this issue? please Assign me ❤️

**Comment by eshellman** [comment]
note above says it was addressed

**Comment by DevanshKyada27** [comment]
Hey @eshellman want to work on it can you please assign me this issue.

**Comment by Ajay-singh1** [comment]
@jokoyoski Close this issue now!
