### ISSUE TITLE
Ruby on Rails courses

### ISSUE THREAD

**Issue by gorenbk** [EbookFoundation/free-programming-books#9486]
There are ruby courses, but no Ruby on Rails. Maybe also the interactive tutorials.

**Comment by eshellman** [comment]
Not sure what you mean:

Ruby
[Agile Development Using Ruby on Rails - Advanced](https://www.edx.org/course/agile-development-using-ruby-rails-uc-berkeleyx-cs169-2x#!)
[Agile Development Using Ruby on Rails - Basics](https://www.edx.org/course/agile-development-using-ruby-rails-uc-berkeleyx-cs169-1x#!)
[An Introduction to Ruby Programming Language](https://www.researchgate.net/publication/322222154_An_Introduction_to_Ruby_Programming_Language) - Ali Tourani (HTML, PDF)
[Full Stack Ruby on Rails](https://www.theodinproject.com/paths/full-stack-ruby-on-rails) - The Odin Project
[Learn how to program: Ruby](https://www.learnhowtoprogram.com/ruby) - Epicodus Inc.
[Learn Rails: Quickly Code, Style and Launch 4 Web Apps](https://www.udemy.com/course/learn-rails) - Adam Eubanks (Udemy)
[Learn Ruby](https://www.learnrubyonline.org/)
[RESTful API with Ruby On Rails 5](https://www.udemy.com/course/restful-api-with-ruby-on-rails-5/) - Udemy
[Ruby on Rails a Beginners Guide](https://www.udemy.com/course/ruby-on-rails-a-beginners-guide-free) - Stephen Chesnowitz (Udemy)
[Ruby Tutorial](https://www.w3resource.com/ruby/)

**Comment by gorenbk** [comment]
> Not sure what you mean
I meant a section for Rails courses

**Comment by eshellman** [comment]
I don't think there are so many Ruby courses that a Rails subsection is necessary. Someone would need to go through the courses to sift out the no-Rails Ruby courses; I wonder if there are any!
