### ISSUE TITLE
Python Books

### ISSUE THREAD

**Issue by PulsatingGenius** [EbookFoundation/free-programming-books#9522]
i have pdfs to some python books that are not added in this repo . following is the list of those books 

* Cracking codes with Python - Al Sweigart
* Learn Python visiually - Ivelin Demirov
* Real World Python - Lee Vaughan

**Comment by PulsatingGenius** [comment]
if we are not supposed to share any google drive links or dropbox then how am i supposed to share the pdf of the books

**Comment by eshellman** [comment]
If the books are free-licensed, then add them to internet archive. If not, we don't allow unauthorized distributions.

**Comment by policeakshithreddy** [comment]
Could you please assign this task to me? Thank you!

**Comment by ishaanv1206** [comment]
Can you please assign this task to me?

**Comment by sgindeed** [comment]
You can follow Python Programming by Charles Walker

**Comment by ishaanv1206** [comment]
Hiii ! could you please assign this task to me?

**Comment by imjhadhiraj** [comment]
Please assign me this issue...thank youuuu
