### ISSUE TITLE
Open University courses

### ISSUE THREAD

**Issue by eshellman** [EbookFoundation/free-programming-books#9530]
some great stuff here: https://www.open.edu/openlearn/digital

If you're looking for great content to add, go for it!

**Comment by rahul9852-dot** [comment]
@eshellman I have added all the content of the url which you have provided above for [Open University courses](#9530) 
I have created separate branch from main done all the necessary changes. Can i raised my MR by linking the above mention issues.

**Comment by Ajay-singh1** [comment]
Gotcha!
