### ISSUE TITLE
𝐁𝐔𝐆:𝐋𝐢𝐠𝐡𝐭 𝐚𝐧𝐝 𝐃𝐚𝐫𝐤 𝐦𝐨𝐝𝐞 𝐢𝐬 𝐧𝐨𝐭 𝐚𝐯𝐚𝐢𝐥𝐚𝐛𝐥𝐞 𝐢𝐧 𝐦𝐚𝐢𝐧 𝐩𝐚𝐠𝐞

### ISSUE THREAD

**Issue by SHARMA-1729** [EbookFoundation/free-programming-books#9559]
![Main page](https://github.com/EbookFoundation/free-programming-books/assets/129518514/4a84964b-a337-4324-9a2f-42c6c4da0217)

-->In main/home page light and dark mode is not available.
BUT
![second page](https://github.com/EbookFoundation/free-programming-books/assets/129518514/f3bfee1c-e469-4e79-ad4b-df0cee920acb)

-->In all other pages light and dark mode is available

-->𝐏𝐥𝐞𝐚𝐬𝐞 𝐚𝐬𝐬𝐢𝐠𝐧 𝐦𝐞 𝐭𝐡𝐢𝐬 𝐢𝐬𝐬𝐮𝐞!!!!

**Comment by sahilbhise09** [comment]
I hope you're doing well. I came across the issue also i have started working on it can you assign it to me to solve this issue

**Comment by SHARMA-1729** [comment]
because i found this issue so please assigned me this issue .

**Comment by SHARMA-1729** [comment]
@sahilbhise09 please work on other issue.

**Comment by shalabhtayal** [comment]
Hi Everyone,

I am new to open source. Does the mod assign this issue or anyone can solve it via pull request and ask for merge ? 

Thanks

@SHARMA-1729

**Comment by VinayakGaikwad101** [comment]
I want to work on this plz I'm new

**Comment by Kaustubh-2003** [comment]
hey think I can do it as I have done it before also in some of my projects.  So please assign it to me

**Comment by AkashMani1** [comment]
I also working on the same feature for one time I really do it So please assign this project to me. @AkashMani1

**Comment by SinghUjjwal12** [comment]
Hello sir, Can you please assign this issue to me.

**Comment by eshellman** [comment]
#9626
