### ISSUE TITLE
Linux Book

### ISSUE THREAD

**Issue by manishtambe** [EbookFoundation/free-programming-books#9590]
i have pdf of The Linux Programming Interface by Michael Kerrisk  which is not present in Linux book repository and i want to add this book as an Hacktoberfest contribution can i add this book ?

**Comment by shalabhtayal** [comment]
Hi Manish, 

You can share the pdf here.  You can share the link here (via your google docs or any other way)

**Comment by manishtambe** [comment]
I have added the book can you please check and merge my pull request.

**Comment by eshellman** [comment]
to link a PR, use it's number, for example #9208

**Comment by manishtambe** [comment]
ok got it ! i will take care of it from next time and if i have any book from authorized distribution i will add it.
