### ISSUE TITLE
There is no issue template for this repository

### ISSUE THREAD

**Issue by samithkavishke** [EbookFoundation/free-programming-books#9592]
## Details
To manage all the issues in same manner it is good to have a issue template

**Comment by AkashMani1** [comment]
yes, I can Do this. For these issues, I created a message box where user can put their issue in the message box and in the replay option we replay solution. So Please assign this project to me.

**Comment by eshellman** [comment]
How would an issue template have worked for this issue?

**Comment by AxaySharma** [comment]
Hi, I am adding issue templates to this repo.

**Comment by AxaySharma** [comment]
@eshellman  Added general Issue Templates and raised PR #9734 for the same. Kindly review it. Thanks!!

**Comment by eshellman** [comment]
I'm unconvinced. Have you looked through the actual  issues that have been filed in this repo???

**Comment by AxaySharma** [comment]
Hi @eshellman ! Appologies for overlooking the types of issues filed in this repo and Thank you for your prompt feedback. I've taken the time to review the types of issues that have been filed in this repository. Based on my observations, it appears that if we make an issue template then structure of issue submissions would almost resemble with 'pull request template'. What are your thoughts on the usefulness of an issue template in this context? Is it even required?  I look forward to hearing your perspective.
