### ISSUE TITLE
I want to add a free udemy course (NOT sponsored) that teaches fundamentals of Git and GitHub to new contributors.

### ISSUE THREAD

**Issue by VinayakGaikwad101** [EbookFoundation/free-programming-books#9615]
**Git: Become an Expert in Git & GitHub in 4 Hours**

**Comment by VinayakGaikwad101** [comment]
How to add this? Like a link?

**Comment by Parmesh119** [comment]
Hi, @VinayakGaikwad101 I am Parmesh B.
I hope you are fine.
Can you assign this issue to me?

**Comment by AkashMani1** [comment]
Hi , @AkashMani1 I would like to create a free Udemy course that teaches the fundamentals of Git and GitHub to new contributors. Can you assign this to me?

**Comment by Aryan182225** [comment]
I have understood your issue and i can contribute on it , I can add the Udemy Course in your website where you can contribute your fundamentals of Git and GitHub to the newcomers .

So please , assign me @Aryan182225 this project so that I contribute on it .

Anticipating for your positive response.

**Comment by any-mesh** [comment]
HI, @eshellman, I have raised a PR for adding a free udemy course "Git & GitHub Complete Guide".

**Comment by Atharva1723** [comment]
@eshellman Please can you assign this issue to me?

**Comment by Gauravpadam** [comment]
Here's the course link to all those who're wondering:
https://www.udemy.com/course/git-expert-4-hours/

**Comment by Krunal-375** [comment]
is this issue still open or closed?

**Comment by haxkd** [comment]
@eshellman  close this issue as completed with PR #10316

**Comment by Ajay-singh1** [comment]
@VinayakGaikwad101 You can close this issue now.
