### ISSUE TITLE
[FEAT] Blank section on the Home page 

### ISSUE THREAD

**Issue by prajapatdip** [EbookFoundation/free-programming-books#9692]
Image:
![Screenshot from 2023-10-02 12-31-13](https://github.com/EbookFoundation/free-programming-books/assets/104031556/ae7b9699-39ed-458b-9ec9-86c902172334)

Suggestion:
The blank section on the home page does'nt look good. We can add Trending books (Most used from the website) in that section.

**Comment by soumya-ranjan-pratap** [comment]
I want to work on this issue please assign it to me

**Comment by theayushkaul** [comment]
I can work on this issue.

**Comment by eshellman** [comment]
it's used for serach results. submit issues to https://github.com/EbookFoundation/free-programming-books-search/
