### ISSUE TITLE
want to add algorithm new handbook for professionals

### ISSUE THREAD

**Issue by devhimanshuu** [EbookFoundation/free-programming-books#9695]
* [Algorithm notesforprofessionals](https://goalkicker.com/AlgorithmsBook/) (PDF)

**Comment by soumya-ranjan-pratap** [comment]
Hi, Can I contribute to this issue ?

**Comment by khairnsaa** [comment]
i think you didn't need to be assigned if you want to add new book

related link:
https://github.com/EbookFoundation/free-programming-books/issues/9208

**Comment by soumya-ranjan-pratap** [comment]
Thank You @khairnsaa , What do I need to do

**Comment by AKay231** [comment]
### Probably the best book for beginners as well as professionals that you can refer.
[Introduction to algorithms by Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein (z-lib.org).pdf](https://github.com/EbookFoundation/free-programming-books/files/12782619/Introduction.to.algorithms.by.Thomas.H.Cormen.Charles.E.Leiserson.Ronald.L.Rivest.Clifford.Stein.z-lib.org.pdf)

**Comment by soumya-ranjan-pratap** [comment]
was it added by you @AKay231 or I can add this one

**Comment by eshellman** [comment]
see #6153
