### ISSUE TITLE
Adding  A free-programming-books For java 

### ISSUE THREAD

**Issue by Soyvor** [EbookFoundation/free-programming-books#9697]
- It will contain every detail of java that a user needs
- will have hyperlinks
- will be demonstrative 
- and easy to understand

label-hacktober fest 23

**Comment by KrishayNair** [comment]
Please assign me this issue @Soyvor . I can add a book of Java has all the information that the user needs.

**Comment by sanusisusi** [comment]
Java SE Fundamentals by ORACLE
Its a guide that's easy to understand
[JAVA SE 7    FUNDAMENTAL(volume1).pdf](https://github.com/EbookFoundation/free-programming-books/files/12781959/JAVA.SE.7.FUNDAMENTAL.volume1.pdf)

**Comment by CodeWithRishav** [comment]
please assign this task to me

**Comment by AKay231** [comment]
Here is a Helpful guide that one can refer to.
[JavaNotesForProfessionals.pdf](https://github.com/EbookFoundation/free-programming-books/files/12782580/JavaNotesForProfessionals.pdf)
