### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by siddakbagga13** [EbookFoundation/free-programming-books#9711]
Hey @ebookfoundation I would like to add contributing.md files so that the person making the pull and merge will get the steps easily and please add hacktoberfest tag with it.

**Comment by sohansai** [comment]
I noticed that there's already a `contributing.md` file in the repository, which is great for providing guidelines to contributors. 

You can refer to it here: [Contributing Guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).

Also, it's fantastic to see that the Hacktoberfest tag is already present. All the necessary steps seem to be outlined in the issue.

**Comment by eshellman** [comment]
we have docs/CONTRIBUTING.md
