### ISSUE TITLE
Overlay on CONTRIBUTING.md page

### ISSUE THREAD

**Issue by Ashu104** [EbookFoundation/free-programming-books#9736]
When accessing the **CONTRIBUTING** link from the homepage, the redirected page is marred by overlay issues that significantly compromise its professionalism.  These overlays obscure the main content, detracting from the user experience.

link to page - [ https://ebookfoundation.github.io/free-programming-books-search/?&sect=docs&file=CONTRIBUTING.md](url)

![Screenshot (20)](https://github.com/EbookFoundation/free-programming-books/assets/76779072/49a09f85-88f3-4cc6-a0f7-28d0cd2b983d)

**Comment by sohansai** [comment]
I have tested the link to the CONTRIBUTING page, and it appears to be working fine on my end without any overlay issues.

It's possible that the problem you're experiencing is related to your browser or some browser extension. 

I recommend trying the following steps to troubleshoot the issue:

1. Clear your browser cache and cookies.
2. Disable any browser extensions or add-ons that may be interfering with the page.
3. Try accessing the link in a different browser to see if the issue persists.

**Comment by eshellman** [comment]
works fine for me, too

**Comment by Ashu104** [comment]
I still have same issue, but  as you guys mentioned its system specific, and have no issue with #9736 .
yhh I'll try some other ways to fix it in my sys.  
and thanks btw.
