### ISSUE TITLE
Better looking Readme

### ISSUE THREAD

**Issue by Samir-Alam** [EbookFoundation/free-programming-books#9793]
I can improve the look of readme and make it more atteactive

**Comment by sohansai** [comment]
The readme file is already looking good and contains all the required information.

**Comment by hritikjena** [comment]
Is this Project participate in Hacktoberfest 2023??

**Comment by sohansai** [comment]
This place is not meant for asking questions. 

Yes, this project is participating in Hacktoberfest 2023. 

If you want more information, please check the project's [README](https://github.com/EbookFoundation/free-programming-books/blob/main/README.md) 

And if you want to contribute, refer to [CONTRIBUTING.md](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).

**Comment by eshellman** [comment]
thanks @sohansai
