### ISSUE TITLE
contributing page readme is showing free programming books tab

### ISSUE THREAD

**Issue by kpomal** [EbookFoundation/free-programming-books#9794]
The contributing page is showing free programming books tab hence it is difficult to read the page because of the contents in the previous page

**Comment by kpomal** [comment]
<img width="668" alt="image" src="https://github.com/EbookFoundation/free-programming-books/assets/73750160/c8f0b65f-4c11-4ea8-92d9-06dbb90e35aa">

**Comment by AnishTiwari16** [comment]
can u share the url of the route as it is working fine

**Comment by sohansai** [comment]
It is working fine on my end, and there may be a problem at your end or with your browser.

I recommend clearing your browser cache and trying again. 

I'm also attaching a screenshot for your reference to show that it's working well on my side.

![githubb](https://github.com/EbookFoundation/free-programming-books/assets/76840110/f6c21e98-64fc-45d3-bebe-2cd4bafc978d)

 Here's the URL: https://ebookfoundation.github.io/free-programming-books/docs/CONTRIBUTING.html

**Comment by kpomal** [comment]
there was a  problem while loading the contents of the page now it seems to be ok
