### ISSUE TITLE
Adding Hacktoberfest 2023 badge in Readme

### ISSUE THREAD

**Issue by isayakmondal** [EbookFoundation/free-programming-books#9839]

**Comment by sohansai** [comment]
The Hacktoberfest 2022 badge in the Readme links to pull requests from October 1 to October 31, 2022.

You want to add a Hacktoberfest 2023 badge, but it needs frequent updates. 

It's better to add it after Hacktoberfest 2023 ends to avoid daily updates.

**Comment by isayakmondal** [comment]
> The Hacktoberfest 2022 badge in the Readme links to pull requests from October 1 to October 31, 2022.
> 
> You want to add a Hacktoberfest 2023 badge, but it needs frequent updates. 
> 
> It's better to add it after Hacktoberfest 2023 ends to avoid daily updates.

I'm pretty sure the dynamic badges would fetch the number of PR automatically and doesn't have to be a manual chore.

**Comment by sohansai** [comment]
> > The Hacktoberfest 2022 badge in the Readme links to pull requests from October 1 to October 31, 2022.
> > You want to add a Hacktoberfest 2023 badge, but it needs frequent updates.
> > It's better to add it after Hacktoberfest 2023 ends to avoid daily updates.
> 
> I'm pretty sure the dynamic badges would fetch the number of PR automatically and doesn't have to be a manual chore.

I think it's better to wait until Hacktoberfest is over before putting the badge in the readme

Adding them now doesn't seem to help much, and this is just my opinion

Let's await comments or opinions from the collaborators

**Comment by isayakmondal** [comment]
> Adding them now doesn't seem to help much, and this is just my opinion

It might just be my opinion but adding a "Hacktoberfest 2023" badge in readme would server 2 purpose:

 1. It would indicate that the repo is a part of hacktoberfest (besides the github tags).
 2. It would also the show active number of PR's for this year's hacktoberfest.

But again, let's wait for the opinions of the collaborators.

**Comment by anshul-132002** [comment]
Hey ! i have added the Hacktoberfest 2023 badge in Readme.md file ,Please merge my pull request

**Comment by isayakmondal** [comment]
Hey @anshul-132002 if you look carefully #9841 already implements this

**Comment by eshellman** [comment]
the PR should remove the 2022 version. neither #9841 or #9842 do this. Extra credit for collaborations!
