### ISSUE TITLE
Add book: "Data structures using C" - Second Edition by Reema Thareja

### ISSUE THREAD

**Issue by AlefiyaAbbas** [EbookFoundation/free-programming-books#9853]
I found this book to be very helpful in my DSA journey. I can add this book to the [EbookFoundation](https://github.com/EbookFoundation).

Assign me this task.

**Comment by sohansai** [comment]
Provide a direct link to the book to confirm it's freely available and that it follows the guidelines for [contributions](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)

**Comment by AlefiyaAbbas** [comment]
The mentioned book can be found [here](https://aa.bbs.tr/lab/cen215-data-structures/Data-Structures-Using-C-2nd-edition.pdf).

**Comment by eshellman** [comment]
This appears not to be an authorized distribution. Please see docs/CONTRIBUTING.md guidelines.
