### ISSUE TITLE
How about we rewrite the website in Astro ?

### ISSUE THREAD

**Issue by RayyanNafees** [EbookFoundation/free-programming-books#9859]
Won't it be cooler and easier to maintain for opting in to [Astro](https://astro.build) which is the most popular framework known for its performance & architecture ?

## Advantages of using astro
- Easy to integrate Markdown content
- Astro 3.0's View Transitions
- a11y & Performance improvements
- Easy to integrate Node frameworks & packages from different ecosystems.

**Comment by eshellman** [comment]
no
