### ISSUE TITLE
Add Translation in Marathi for CODE_OF_CONDUCT,HOW_TO,CONTRIBUTING.md files in docs Folder

### ISSUE THREAD

**Issue by aneeshd27** [EbookFoundation/free-programming-books#9945]
Adding Translation of various Docs in Marathi would really help users who speak primarily speak Marathi as their first language

**Comment by sohansai** [comment]
Would you be interested in making a contribution by translating?

**Comment by Starkuser24** [comment]
I would like to try and add the Marathi translation for the required files

**Comment by aneeshd27** [comment]
I would like to add the Marathi Translation for the required files in the docs folder

**Comment by Neeraaaj** [comment]
added CODE_OF_CONDUCT-mr.md and CONTRIBUTING-mr.md

**Comment by Neeraaaj** [comment]
added HOW_TO-mr.md too

**Comment by aneeshd27** [comment]
Add CONTRIBUTING.md

**Comment by Neeraaaj** [comment]
added

**Comment by Starkuser24** [comment]
> Add CONTRIBUTING.md

Added
