### ISSUE TITLE
C Courses in Bangla are not good enough

### ISSUE THREAD

**Issue by subhadipbhowmik** [EbookFoundation/free-programming-books#9959]
The courses in C programming in Bangla is no sufficient. Only the Anisul Islam's Playlist is the beginner friendly and fully accomplished. I think there should add some more good courses to enhances the learning of C programmin gin Bangla. 

<img width="706" alt="c-programming-bangla-courses" src="https://github.com/EbookFoundation/free-programming-books/assets/57017965/8c5ed17a-edba-49df-94bc-b3d38f08a04e">

**Comment by bhorsujal** [comment]
There is a course on udemy for free called "C Programming in Bangla - from Zero to Hero" by Ministry of Codes(MoC), Prapty Rahman.
It is a completely free course.
Can I include that in the "free-courses-bn.md" file?

**Comment by sahalhes** [comment]
@subhadipbhowmik Hey I have added pdf of book c programming in bangla in the free-programming-books-bn.md
