### ISSUE TITLE
Request to Add a New Competetive Programming book

### ISSUE THREAD

**Issue by Manishak798** [EbookFoundation/free-programming-books#9978]
Subject: Request to Add a New Programming Book for Hacktoberfest 2023

Greetings,

I hope this message finds you well. I wanted to bring an exciting opportunity for this year's Hacktoberfest 2023 to your attention.

I've come across a fantastic programming book in PDF format that's available for free and has the potential to be incredibly helpful for programmers looking to solidify their understanding of programming concepts. I believe this resource would be a valuable addition to our Hacktoberfest project list.

To streamline the process, I'd like to request that this issue be assigned to me. I'm eager to take ownership of this task and ensure that the book gets added to our project repository for the community to benefit from.

I'm excited to contribute to Hacktoberfest 2023 and help fellow programmers improve their skills.

Thank you for your consideration, and I'm looking forward to your response.

Best regards,
Manisha Kundnani

**Comment by sohansai** [comment]
If you're familiar with Git, please feel free to submit a PR.

If not, provide details about the book, including its name, author, and a link to it.

Note that issues can't be assigned, but if you're ready, you can start contributing right away.

Also, make sure to read CONTRIBUTING.md before contributing.

**Comment by eshellman** [comment]
@sohansai thank you for your help - I'm sure that folks new to github really appreciate it!
