### ISSUE TITLE
Request to Automate Greeting Task - Hacktoberfest 2023

### ISSUE THREAD

**Issue by Manishak798** [EbookFoundation/free-programming-books#9979]
Subject: Request to Automate Greeting Task - Hacktoberfest 2023

Greetings,

I hope you're doing well. I have a proposal for an issue that could enhance our GitHub repository's responsiveness during Hacktoberfest 2023.

**Issue Description:**
I would like to suggest automating the greeting task by adding a `greetings.yml` file. With this automation, a GitHub bot will respond to new issues and pull requests with a warm greeting. This will not only increase responsiveness but also create a welcoming atmosphere for contributors.

**Benefits:**
- Enhances the user experience by providing instant acknowledgment and a friendly welcome to new contributors.
- Promotes community engagement and participation during Hacktoberfest.

**Assignment:**
I am eager to work on this issue and implement the proposed automation. I kindly request that you assign this issue to me as part of Hacktoberfest 2023. I believe it will be a fun and useful addition to our repository.

Please let me know if there are any specific guidelines or additional information I should consider while working on this issue.

Thank you for your consideration, and I'm excited to contribute to Hacktoberfest 2023.

Best regards,
Manisha Kundnani.

**Comment by sohansai** [comment]
Great idea!

Feel free to start working on the greeting task automation. 

But before you begin, wait for collaborator's response.

Once done, submit a pull request for review. If all is well, it will be merged.

**Comment by sohansai** [comment]
Great idea!

Feel free to start working on the greeting task automation.

But before you begin, wait for collaborator's response.

Once done, submit a pull request for review. If all is well, it will be merged.

Note that issues can't be assigned, but if you're ready, you can start contributing right away.

**Comment by bhorsujal** [comment]
I can work on this issue as well. 
I am aware of the basic working of github workflows

**Comment by eshellman** [comment]
we generate enough email as it is. won't do this. Thanks for the suggestion.

what would help a lot is a bot that adds a label to PRs labelled "waiting for changes" when a commit has been added by the submitter.
