### ISSUE TITLE
[ Doc: ] Adding Contributors section to the readme.md file.

### ISSUE THREAD

**Issue by mohitd404** [EbookFoundation/free-programming-books#9986]
Adding Contributors section to the readme.md file by limiting it to 100.

Example :- 
![2](https://github.com/EbookFoundation/free-programming-books/assets/146939900/7be55ae3-6e6b-433e-a4eb-549ba04163bc)

please assign this issue to me, Thank you !

**Comment by eshellman** [comment]
You'd be diminishing the contributions of 2,500 others!

**Comment by mcu13321** [comment]
我已经收到你的邮件了，我会尽快回复你的
